[tool.poetry]
name = "pythainav"
version = "0.1.1"
description = "a Python interface to pull thai mutual fund NAV"
authors = ["Nutchanon Ninyawee <me@nutchanon.org>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
requests-html = "^0.10.0"

[tool.poetry.dev-dependencies]
pytest = "^5.3"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
