# Generated by Django 2.2.5 on 2020-01-17 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('amazon_product', '0002_auto_20200117_1440'),
        ('marketplace', '0001_initial'),
        ('base_product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazonproduct',
            name='channel',
            field=models.ForeignKey(limit_choices_to={'domain__marketplace__unique_name__in': ['amazon_north_america', 'amazon_europe', 'amazon_far_east']}, on_delete=django.db.models.deletion.CASCADE, related_name='amazon_products', related_query_name='amazon_product', to='marketplace.Channel', verbose_name='Пользовательский канал продаж'),
        ),
        migrations.AddField(
            model_name='amazonproduct',
            name='extra_images',
            field=models.ManyToManyField(blank=True, related_name='amazonproduct_extras', related_query_name='amazonproduct_extra', to='base_product.ProductImage', verbose_name='Дополнительные изображения'),
        ),
        migrations.AddField(
            model_name='amazonproduct',
            name='main_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amazonproduct_main_images', related_query_name='amazonproduct_main_image', to='base_product.ProductImage', verbose_name='Главное изображение'),
        ),
        migrations.AddField(
            model_name='amazonproduct',
            name='product_id_code_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base_product.ProductCodeType', verbose_name='Тип кода товара'),
        ),
    ]
