# Generated by Django 2.2.5 on 2020-01-17 11:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ebay_listing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EbayBuyerOffer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('allowCounterOffer', models.BooleanField(default=False, editable=False, verbose_name='Контр-предложения разрешены')),
                ('message', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Сообщение покупателям')),
            ],
            options={
                'verbose_name': 'Предложение покупателям',
                'verbose_name_plural': 'Предложения покупателям',
            },
        ),
        migrations.CreateModel(
            name='EbayBuyerOfferDuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveIntegerField(verbose_name='Количество')),
                ('unit', models.CharField(choices=[('YEAR', 'Год'), ('MONTH', 'Месяц'), ('DAY', 'День'), ('HOUR', 'Час'), ('CALENDAR_DAY', 'Календарный день'), ('BUSINESS_DAY', 'Рабочий день'), ('MINUTE', 'Минута'), ('SECOND', 'Секунда'), ('MILLISECOND', 'Миллисекунда')], max_length=20, verbose_name='Единица измерения времени')),
            ],
            options={
                'verbose_name': 'Продолжительность действия предложения',
                'verbose_name_plural': 'Продолжительность действия предложения',
            },
        ),
        migrations.CreateModel(
            name='EbayBuyerOfferedItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('discountPercentage', models.FloatField(blank=True, null=True, verbose_name='Скидка в процентах')),
                ('quantity', models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество товаров, требуемое для скидки')),
            ],
            options={
                'verbose_name': 'Предлагаемый товар',
                'verbose_name_plural': 'Предлагаемые товары',
            },
        ),
        migrations.CreateModel(
            name='EbayBuyerOfferPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('RUB', 'Российский рубль'), ('USD', 'Доллар США'), ('EUR', 'Евро'), ('GBP', 'Фунт стерлингов'), ('JPY', 'Японская иена'), ('CNY', 'Китайский юань'), ('AUD', 'Австралийский доллар'), ('CAD', 'Канадский доллар')], max_length=20, verbose_name='Валюта')),
                ('value', models.FloatField(verbose_name='Значение цены')),
            ],
            options={
                'verbose_name': 'Цена для предложения покупателю',
                'verbose_name_plural': 'Цена для предложения покупателю',
            },
        ),
        migrations.CreateModel(
            name='EbayEligibleItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('active', models.BooleanField(blank=True, default=False, verbose_name='Интерес к товару активен')),
            ],
            options={
                'verbose_name': 'Товар, к которому проявили интерес',
                'verbose_name_plural': 'Товары, к которым проявили интерес',
            },
        ),
        migrations.CreateModel(
            name='EbayMessage',
            fields=[
                ('listingId', models.CharField(blank=True, max_length=30, null=True, verbose_name='ID листинга')),
                ('message_id', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='ID сообщения')),
                ('folder_id', models.CharField(max_length=2, verbose_name='ID папки')),
                ('sender', models.CharField(max_length=100, verbose_name='Имя отправителя')),
                ('recipient_id', models.CharField(max_length=30, verbose_name='ID получателя')),
                ('sender_id', models.CharField(blank=True, max_length=30, null=True, verbose_name='ID отправителя')),
                ('recipient', models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя отправителя')),
                ('replied', models.BooleanField(default=False, verbose_name='Отвечено')),
                ('read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('response_enabled', models.BooleanField(default=False, verbose_name='Ответ возможен')),
                ('response_url', models.URLField(blank=True, null=True, verbose_name='URL для ответа')),
                ('high_priority', models.BooleanField(default=False, verbose_name='Высокая приоритетность')),
                ('message_type', models.CharField(choices=[('All', 'All'), ('AskSellerQuestion', 'AskSellerQuestion'), ('ClassifiedsBestOffer', 'ClassifiedsBestOffer'), ('ClassifiedsContactSeller', 'ClassifiedsContactSeller'), ('ContactEbayMember', 'ContactEbayMember'), ('ContacteBayMemberViaAnonymousEmail', 'ContacteBayMemberViaAnonymousEmail'), ('ContacteBayMemberViaCommunityLink', 'ContacteBayMemberViaCommunityLink'), ('ContactMyBidder', 'ContactMyBidder'), ('ContactTransactionPartner', 'ContactTransactionPartner'), ('ResponseToASQQuestion', 'ResponseToASQQuestion'), ('ResponseToContacteBayMember', 'ResponseToContacteBayMember')], default='All', max_length=50, verbose_name='Тип сообщения')),
                ('subject', models.CharField(max_length=300, verbose_name='Тема сообщения')),
                ('content', models.TextField(verbose_name='Содержимое сообщения')),
                ('receive_date', models.DateTimeField(verbose_name='Дата и время получения сообщения')),
                ('expiration_date', models.DateTimeField(verbose_name='Дата и время автоудаления сообщения')),
                ('listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', related_query_name='message', to='ebay_listing.EbayListing', verbose_name='Листинг eBay')),
            ],
        ),
    ]
