
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-01-28T08:31:41+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "02282fa4c9d6975a4bd6062be3a581e6c75f285c",
 "version": "0.4.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
