[tool.poetry]
name = "actions_in_fly"
version = "0.2.1"
description = "Test several CI/CD mechanic"
authors = ["Anton Ilyushenkov <driverx_strogino@mail.ru>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/DriverX/actions_in_fly"
repository = "https://github.com/DriverX/actions_in_fly"
classifiers = [
    # 'Development Status :: 1 - Planning',
    # 'Development Status :: 2 - Pre-Alpha',
    'Development Status :: 3 - Alpha',
    # 'Development Status :: 4 - Beta',
    # 'Development Status :: 5 - Production/Stable',
    'Framework :: AsyncIO',
    'Intended Audience :: Developers',
    'Operating System :: POSIX :: Linux',
    'Programming Language :: Python :: 3.6',
    'Programming Language :: Python :: 3.7',
    'Programming Language :: Python :: 3.8',
    'Programming Language :: Python :: 3 :: Only',
    'Programming Language :: Python :: Implementation :: CPython',
]
packages = [
    {include = "actions_in_fly", from = "src"},
]

[tool.poetry.dependencies]
python = "^3.6"
attrs = ">=18.2.0, <20.0.0"
aiohttp = "^3.4.0"

[tool.poetry.dev-dependencies]
isort = {version="*", extras=["pyproject"]}
mypy = "*"
flake8 = "*"
pytest = "*"

[tool.poetry.scripts]
actions_in_fly = "actions_in_fly:main"

[tool.isort]
known_first_party = ["actions_in_fly"]
known_third_party = []
lines_after_imports = 2
multi_line_output = 5
skip = "__main__.py"
not_skip = "__init__.py"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
