[tool.poetry]
name = "simple_stat_learning"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.7"
numpy = "^1.18.1"
matplotlib = "^3.1.2"
seaborn = "^0.10.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
mypy = "^0.761"
sphinx = "^2.3.1"
statsmodels = "^0.11.0"
sphinx_rtd_theme = "^0.4.3"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
