# Generated by Django 2.2.5 on 2020-01-24 17:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_auto_20200117_1440'),
        ('etsy_account', '0002_etsyuseraccount_marketplace_user_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='EtsyShop',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('shop_id', models.CharField(max_length=30, unique=True, verbose_name='ID магазина Etsy')),
                ('title', models.CharField(max_length=300, verbose_name='Заголовок на главной странице магазина')),
                ('is_vacation', models.BooleanField(blank=True, default=False, verbose_name='Магазин временно не работает')),
                ('listing_active_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество активных листингов')),
                ('url', models.URLField(blank=True, null=True, verbose_name='URL магазина')),
                ('channel', models.OneToOneField(limit_choices_to={'domain__marketplace__unique_name': 'etsy'}, on_delete=django.db.models.deletion.CASCADE, related_name='shop', to='marketplace.Channel', verbose_name='Пользовательский канал продаж')),
            ],
            options={
                'verbose_name': 'Магазин Etsy',
                'verbose_name_plural': 'Магазины Etsy',
            },
        ),
        migrations.CreateModel(
            name='EtsyShopSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('shop_section_id', models.CharField(max_length=30, unique=True, verbose_name='ID секции магазина Etsy')),
                ('title', models.CharField(max_length=300, verbose_name='Заголовок секции магазина')),
                ('active_listing_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество активных листингов в секции')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', related_query_name='section', to='etsy_account.EtsyShop', verbose_name='Магазин Etsy')),
            ],
            options={
                'verbose_name': 'Секция магазина Etsy',
                'verbose_name_plural': 'Секции магазина Etsy',
            },
        ),
    ]
