[tool.poetry]
name = "fold-bdd"
version = "0.5.0"
readme="README.md"
repository = "https://github.com/mvcisback/fold-bdd"
description = "Library for folding (or reducing) over a Reduced Ordered Binary Decision Diagram."
authors = ["Marcell Vazquez-Chanlatte <mvc@linux.com>"]
license = "MIT"
packages = [
    { include = "fold_bdd" },
]

[tool.poetry.dependencies]
python = "^3.6"
dd = "^0.5.4"
attrs = "^19.3"
funcy = "^1.13"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
pytest-cov = "^2.7"
pytest-flake8 = "^1.0"
pytest-sugar = "^0.9.2"
pytest-xdist = "^1.29"
codecov = "^2.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
