[tool.poetry]
name = "edenpdf"
version = "1.0.2"
description = "ilovepdf.com python API library"

license = "GPL-3.0-only"

authors = [
    "Andrea Bruschi <moonx2006@gmail.com>",
    "Eden-Box <dev@edenbox.cf>"
]

readme = 'README.md'

repository = "https://github.com/AndyBTuttofare/pylovepdf"
homepage = "https://github.com/AndyBTuttofare/pylovepdf"

keywords = ['pdf', 'unlock', 'compress', 'manipulate', 'edit', 'protect', 'pdftojpg', 'jpgtopdf', 'pdfa']

classifiers = [
    'Development Status :: 5 - Production/Stable',
    'License :: OSI Approved :: GNU General Public License v3 (GPLv3)',
    'Programming Language :: Python :: 3.6',
    'Programming Language :: Python :: 3.7',
    'Topic :: Software Development :: Libraries :: Python Modules',
]

[tool.poetry.dependencies]
python = '^3.6.0'
requests = '^2.22.0'
urllib3 = '^1.25.0'
