[tool.poetry]
name = "escarpolette"
version = "0.3.0"
description = "Manage your musical playlist with your friends without starting a war."
license = "GPL-3.0"
authors = ["Alexandre Morignot <erdnaxeli@cervoi.se>"]
readme = "README.md"
homepage = "https://github.com/erdnaxeli/escarpolette"
repository = "https://github.com/erdnaxeli/escarpolette.git"

[tool.poetry.dependencies]
python = "^3.7"
sqlalchemy = "^1.2"
flask = "^1.0"
flask-sqlalchemy = "^2.3"
flask-cors = "^3.0"
youtube-dl = "*"
flask-restplus = "^0.12.1"
flask-migrate = "^2.5"
flask-login = "^0.4.1"
gevent = "^1.4"
click = "^7.0"

[tool.poetry.dev-dependencies]
pytest = "^4.1"
black = {version = "^18.3-alpha.0",allows-prereleases = true}
mypy = "^0.761"
radon = "^4.0"
pytest-mock = "^1.11"
pre-commit = "^1.20"

[tool.poetry.scripts]
escarpolette = "escarpolette:__main__"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
