
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-02-06T22:40:15+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "d53e785b2d6cdaabcafad8e1f78fc3be7da4f3bb",
 "version": "v1.3.0-beta"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
