# Generated by Django 2.2.5 on 2020-01-17 11:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplaceuseraccount',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_accounts', related_query_name='marketplace_account', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='domain',
            name='marketplace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', related_query_name='domain', to='marketplace.Marketplace', verbose_name='Маркетплейс'),
        ),
        migrations.AddField(
            model_name='channel',
            name='domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels', related_query_name='channel', to='marketplace.Domain', verbose_name='Домен'),
        ),
        migrations.AddField(
            model_name='channel',
            name='marketplace_user_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels', related_query_name='channel', to='marketplace.MarketplaceUserAccount', verbose_name='Маркетлейс аккаунт пользователя'),
        ),
        migrations.AddConstraint(
            model_name='channel',
            constraint=models.UniqueConstraint(fields=('marketplace_user_account', 'domain'), name='unique_domain'),
        ),
    ]
