[tool.poetry]
name = "typer-cli"
version = "0.0.1"
description = ""
authors = ["Sebastián Ramírez <tiangolo@gmail.com>"]
readme = 'README.md'

[tool.poetry.dependencies]
python = "^3.6"
importlib_metadata = "^1.5"

[tool.poetry.dev-dependencies]
pytest = "^3.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
