language: python
dist: xenial
cache: false
git:
  depth: false
addons:
  apt:
    packages:
      - gdb
env:
  global:
    - LD_PRELOAD=/lib/x86_64-linux-gnu/libSegFault.so
    - SEGFAULT_SIGNALS=all
    - PYTEST_ADDOPTS=--benchmark-disable
    - TWINE_USERNAME=ionel
matrix:
  include:
    - python: '3.8'
      env:
        - TOXENV=cythonize
      script:
        - |
          (
          set -eux
          tox -v
          git update-index --ignore-submodules --refresh
          if ! git diff-files --exit-code --ignore-submodules; then
            echo "C files are stale!"
            exit 1
          fi
          )
    - python: '3.8'
      env:
        - TOXENV=check
    - python: '3.8'
      env:
        - TOXENV=docs
{%- for env in tox_environments %}{{ '' }}
{%- if 'py37' in env or 'py27' in env %}{{ '' }}
    - os: osx
      language: generic
      env:
        - TOXENV={{ env|replace('py37', 'py3') }}
        - SETUPPY_CFLAGS=
{%- if "cython-nocov" in env %}{{ '' }}
        - WHEEL_PATH=.tox/dist
{%- endif %}
{%- endif %}{{ '' }}
    - env:
        - TOXENV={{ env }}{% if 'cover' in env %},codecov{% endif %}
{%- if 'pypy' not in env and 'nocov' in env %}{{ '' }}
        - WHEEL_MANYLINUX1=cp{{ env.split('-')[0][2:] }}
        - WHEEL_PATH=wheelhouse
{%- endif %}
{%- if env.startswith('pypy3') %}{{ '' }}
        - TOXPYTHON=pypy3
      python: 'pypy3'
{%- elif env.startswith('pypy') %}{{ '' }}
      python: 'pypy'
{%- else %}{{ '' }}
      python: '{{ '{0[2]}.{0[3]}'.format(env) }}'
{%- endif %}
{%- endfor %}{{ '' }}
before_install:
  - python --version
  - uname -a
  - lsb_release -a || true
  - sudo sysctl -w kernel.yama.ptrace_scope=0 || true
  - |
    if [[ $TRAVIS_OS_NAME == 'osx' ]]; then
      brew update-reset
      [[ $TOXENV =~ py3 ]] && brew upgrade python
      [[ $TOXENV =~ py2 ]] && brew install python@2
      export PATH="/usr/local/opt/python/libexec/bin:${PATH}"
    fi
install:
  - python -mpip install --progress-bar=off twine tox-wheel -rci/requirements.txt
  - virtualenv --version
  - easy_install --version
  - pip --version
  - tox --version
script:
  - |
    (
    set -eux
    if [[ -n ${WHEEL_MANYLINUX1:-} ]]; then
      docker run --rm --user $UID -itv $(pwd):/code ionelmc/manylinux $WHEEL_MANYLINUX1
      tox --installpkg $WHEEL_PATH/*.whl -v
    elif [[ -n ${WHEEL_PATH:-} ]]; then
      tox -v --wheel
    else
      tox -v
    fi
    if [[ -n ${WHEEL_PATH:-} ]]; then
      twine check $WHEEL_PATH/*.whl
      twine upload --repository-url https://test.pypi.org/legacy/ --skip-existing $WHEEL_PATH/*.whl
    fi
    )
after_failure:
  - more .tox/log/* | cat
  - more .tox/*/log/* | cat
notifications:
  email:
    on_success: never
    on_failure: always
