
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-01-27T10:51:32-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "6d8ee5016ea32e659fec973853b8fedb59dabd17",
 "version": "0.9.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
