name: Test, Build and Deploy

on: [push]

env:
  DOCKER_CLI_EXPERIMENTAL: enabled

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [2.7, 3.5, 3.6, 3.7]

    steps:
      - uses: actions/checkout@v1
      - name: Login to Docker Hub
        run: docker login --username "${DOCKER_USERNAME}" --password "${DOCKER_TOKEN}"
        env:
          DOCKER_USERNAME: mortenlj
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[ci]
      - name: Test with tox
        run: |
          tox
      - name: Build artifacts
        run: |
          python setup.py bdist_wheel sdist
      - name: Save coverage report
        uses: actions/upload-artifact@v1
        with:
          name: coverage-report-${{ matrix.python-version }}
          path: build/reports/coverage
  deploy:
    needs: build
    if: startsWith(github.event.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install publish
      - name: Publish version
        run: publish mortenlj dockerma
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
          GITHUB_TOKEN: ${{ secrets.PUSH_GITHUB_TOKEN }}
