# Generated by Django 2.2.5 on 2020-01-17 11:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0001_initial'),
        ('marketplace', '0002_auto_20200117_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseorder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_orders', related_query_name='base_order', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='marketplaceorder',
            name='channel',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_orders', related_query_name='marketplace_order', to='marketplace.Channel', verbose_name='Пользовательский канал продаж'),
        ),
    ]
