[build-system]
requires = ["flit_core >=2,<3"]
build-backend = "flit_core.buildapi"

[tool.flit.metadata]
module = "aiotmdb"
author = "Fabrizio Arzeni"
author-email = "fabrizio.arz@gmail.com"
classifiers = ["License :: OSI Approved :: MIT License"]
requires = [
    "aiohttp"
]

[tool.flit.metadata.requires-extra]
test = [
    "pytest >=2.7.3",
]
