# Generated by Django 2.2.5 on 2020-01-24 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ebay_account', '0003_auto_20200117_1440'),
    ]

    operations = [
        migrations.CreateModel(
            name='EbayAppRateLimits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apiContext', models.CharField(max_length=50, verbose_name='Тип API')),
                ('apiName', models.CharField(max_length=50, verbose_name='Название API')),
                ('apiVersion', models.CharField(blank=True, default='', max_length=10, verbose_name='Версия API')),
            ],
            options={
                'verbose_name': 'Ограничение на число запросов',
                'verbose_name_plural': 'Ограничение на число запросов',
            },
        ),
        migrations.AlterField(
            model_name='ebayratelimitsresource',
            name='rate_limits',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='ebay_account.EbayAppRateLimits'),
        ),
        migrations.DeleteModel(
            name='EbayUserRateLimits',
        ),
    ]
