[tool.poetry]
name = "edelweiss-data"
version = "0.2.1"
description = "Python client for EdelweissData"
authors = ["Edelweiss Connect <info@edelweissconnect.com>"]

[tool.poetry.dependencies]
python = "^3.6"
pandas = ">=0.23.0"
pyjwt = "^1.5.3"
requests = "^2.18.4"

[tool.poetry.dev-dependencies]
pytest = "^3.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
