---

- name: Configure GRUB
  collections: [ 'debops.debops' ]
  hosts: [ 'debops_service_grub' ]
  become: True

  environment: '{{ inventory__environment | d({})
                   | combine(inventory__group_environment | d({}))
                   | combine(inventory__host_environment  | d({})) }}'

  roles:

    - role: grub
      tags: [ 'role::grub', 'skip::grub' ]
