---

- name: Bootstrap Python environment
  collections: [ 'debops.debops' ]
  hosts: [ 'debops_all_hosts', 'debops_service_python' ]
  become: True
  gather_facts: False

  tasks:

    - import_role:
        name: 'python'
        tasks_from: 'main_raw'
      tags: [ 'role::python_raw', 'skip::python_raw' ]
