---

- name: Manage rsnapshot service
  collections: [ 'debops.debops' ]
  hosts: [ 'debops_service_rsnapshot' ]
  become: True

  environment: '{{ inventory__environment | d({})
                   | combine(inventory__group_environment | d({}))
                   | combine(inventory__host_environment  | d({})) }}'

  roles:

    - role: rsnapshot
      tags: [ 'role::rsnapshot', 'skip::rsnapshot' ]
