
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-01-21T23:27:50-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "e46f39e5dc16f983e10a5d5fbd300efaf701f4ed",
 "version": "0.0.9"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
