# Generated by Django 2.2.5 on 2020-01-17 11:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ebay_category', '0001_initial'),
        ('base_product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EbayListing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False)),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False)),
                ('status', model_utils.fields.StatusField(choices=[('draft', 'draft'), ('ready_to_publish', 'ready_to_publish'), ('published', 'published'), ('update_required', 'update_required')], default='draft', max_length=100, no_check_for_status=True)),
                ('published_at', model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', when={'published'})),
                ('listing_sku', models.CharField(max_length=255, verbose_name='SKU листинга')),
                ('groupListingId', models.CharField(blank=True, max_length=30, null=True, verbose_name='ID вариативного листинга')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование')),
                ('listing_description', models.TextField(blank=True, max_length=500000, null=True, verbose_name='Описание для листинга')),
                ('localizedFor', models.CharField(blank=True, choices=[('en_US', 'Английский (США)'), ('en_CA', 'Английский (Канада)'), ('en_GB', 'Английский (Великобритания)'), ('en_AU', 'Английский (Австралия)'), ('de_AT', 'Немецкий (Австрия)'), ('fr_BE', 'Французский (Бельгия)'), ('fr_FR', 'Французский (Франция)'), ('de_DE', 'Немецкий (Германия)'), ('it_IT', 'Итальянский (Италия)'), ('nl_BE', 'Голландский (Бельгия)'), ('nl_NL', 'Голландский (Нидерланды)'), ('es_ES', 'Испаский (Испания)'), ('de_CH', 'Немецкий (Швейцария)'), ('zh_TW', 'Китайский (Тайвань)'), ('zh_HK', 'Китайский (Гонконг)'), ('en_IE', 'Английский (Ирландия)'), ('en_PH', 'Английский (Филиппины)'), ('pl_PL', 'Польский (Польша)'), ('ru_RU', 'Русский (Россия)'), ('th_TH', 'Тайский (Тайланд)'), ('fr_CA', 'Французский (Канада)')], max_length=5, null=True, verbose_name='Локализация')),
                ('bestOfferEnabled', models.BooleanField(blank=True, default=False, verbose_name='BestOffer enabled')),
                ('base_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ebay_products', related_query_name='ebay_product', to='base_product.BaseProduct', verbose_name='Базовый товар')),
                ('category', models.ForeignKey(limit_choices_to={'is_leaf': True}, on_delete=django.db.models.deletion.CASCADE, related_name='ebay_products', related_query_name='ebay_product', to='ebay_category.EbayCategory', verbose_name='Категория товара eBay')),
            ],
            options={
                'verbose_name': 'Листинг',
                'verbose_name_plural': 'Листинги',
            },
        ),
        migrations.CreateModel(
            name='EbayProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(verbose_name='Цена')),
                ('currency', models.CharField(choices=[('RUB', 'Российский рубль'), ('USD', 'Доллар США'), ('EUR', 'Евро'), ('GBP', 'Фунт стерлингов'), ('JPY', 'Японская иена'), ('CNY', 'Китайский юань'), ('AUD', 'Австралийский доллар'), ('CAD', 'Канадский доллар')], max_length=20, verbose_name='Валюта')),
                ('converted_from_value', models.FloatField(blank=True, null=True, verbose_name='Исходная цена')),
                ('converted_from_currency', models.CharField(blank=True, choices=[('RUB', 'Российский рубль'), ('USD', 'Доллар США'), ('EUR', 'Евро'), ('GBP', 'Фунт стерлингов'), ('JPY', 'Японская иена'), ('CNY', 'Китайский юань'), ('AUD', 'Австралийский доллар'), ('CAD', 'Канадский доллар')], max_length=20, null=True, verbose_name='Исходная валюта')),
                ('sku', models.CharField(max_length=50, verbose_name='SKU')),
                ('description', models.TextField(max_length=500000, verbose_name='Описание продукта')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Количество')),
                ('product_id_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Код товара')),
                ('offerId', models.CharField(blank=True, max_length=50, null=True, verbose_name='ID оффера в системе eBay')),
                ('listingId', models.CharField(blank=True, max_length=50, null=True, verbose_name='ID листинга в системе eBay')),
                ('condition', models.CharField(choices=[('NEW', 'Новое'), ('LIKE_NEW', 'Как новое'), ('NEW_OTHER', 'Новое с особенностями упаковки'), ('NEW_WITH_DEFECTS', 'Новое с дефектами'), ('MANUFACTURER_REFURBISHED', 'Отремонтированное производителем'), ('SELLER_REFURBISHED', 'Отремонтированное продавцом'), ('USED_EXCELLENT', 'Подержанное, в отличном состоянии'), ('USED_VERY_GOOD', 'Подержанное, в очень хорошем состоянии'), ('USED_GOOD', 'Подержанное, в хорошем состоянии'), ('USED_ACCEPTABLE', 'Подержанное, в удовлетворительном состоянии'), ('FOR_PARTS_OR_NOT_WORKING', 'Неполноценно функционирующее')], default='NEW', max_length=30, verbose_name='Condition')),
                ('conditionDescription', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Condition description')),
                ('epid', models.CharField(blank=True, max_length=30, null=True, verbose_name='The eBay Product Identifier (ePID)')),
                ('format_type', models.CharField(blank=True, choices=[('FIXED_PRICE', 'Фиксированная цена')], default='FIXED_PRICE', max_length=20, verbose_name='Format type')),
                ('quantityLimitPerBuyer', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Ограничение числа товаров на один заказ')),
                ('is_removed', models.BooleanField(default=False, verbose_name='Удален')),
                ('extra_images', models.ManyToManyField(blank=True, related_name='ebayproduct_extras', related_query_name='ebayproduct_extra', to='base_product.ProductImage', verbose_name='Дополнительные изображения')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='ebay_listing.EbayListing')),
                ('main_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ebayproduct_main_images', related_query_name='ebayproduct_main_image', to='base_product.ProductImage', verbose_name='Главное изображение')),
                ('product_id_code_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base_product.ProductCodeType', verbose_name='Тип кода товара')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EbayProductCompatibility',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False)),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False)),
                ('status', model_utils.fields.StatusField(choices=[('draft', 'draft'), ('ready_to_publish', 'ready_to_publish'), ('published', 'published'), ('update_required', 'update_required')], default='draft', max_length=100, no_check_for_status=True)),
                ('published_at', model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', when={'published'})),
                ('notes', models.CharField(blank=True, max_length=500, null=True, verbose_name='Комментарии')),
                ('epid', models.CharField(blank=True, max_length=50, null=True, verbose_name='ePID транспорта')),
                ('ktype', models.CharField(blank=True, max_length=50, null=True, verbose_name='K Type Number транспорта')),
                ('listing', models.ForeignKey(limit_choices_to={'channel__domain__code__in': ['EBAY_MOTORS_US', 'EBAY_US', 'EBAY_CA', 'EBAY_GB', 'EBAY_DE', 'EBAY_AU', 'EBAY_FR', 'EBAY_IT', 'EBAY_ES']}, on_delete=django.db.models.deletion.CASCADE, related_name='compatibilities', related_query_name='compatibility', to='ebay_listing.EbayListing', verbose_name='Листинг')),
            ],
            options={
                'verbose_name': 'Совместимый с деталью транспорт',
                'verbose_name_plural': 'Совместимый с деталью транспорт',
            },
        ),
        migrations.CreateModel(
            name='EbayProductSpecification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=40, verbose_name='Name')),
                ('value', models.CharField(max_length=50, verbose_name='Value')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', related_query_name='specification', to='ebay_listing.EbayProduct')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EbayProductCompatibilityProperty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=40, verbose_name='Name')),
                ('value', models.CharField(max_length=50, verbose_name='Value')),
                ('compatibility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', related_query_name='property', to='ebay_listing.EbayProductCompatibility', verbose_name='Совместимый товар')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EbayProductAutoDeclinedPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('RUB', 'Российский рубль'), ('USD', 'Доллар США'), ('EUR', 'Евро'), ('GBP', 'Фунт стерлингов'), ('JPY', 'Японская иена'), ('CNY', 'Китайский юань'), ('AUD', 'Австралийский доллар'), ('CAD', 'Канадский доллар')], max_length=20, verbose_name='Валюта')),
                ('value', models.FloatField(verbose_name='Значение цены')),
                ('ebay_product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auto_declined_price', to='ebay_listing.EbayListing', verbose_name='Товар eBay')),
            ],
            options={
                'verbose_name': 'Порог цены для автоматического отклонения Best Offer',
                'verbose_name_plural': 'Порог цены для автоматического отклонения Best Offer',
            },
        ),
        migrations.CreateModel(
            name='EbayProductAutoAcceptPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('RUB', 'Российский рубль'), ('USD', 'Доллар США'), ('EUR', 'Евро'), ('GBP', 'Фунт стерлингов'), ('JPY', 'Японская иена'), ('CNY', 'Китайский юань'), ('AUD', 'Австралийский доллар'), ('CAD', 'Канадский доллар')], max_length=20, verbose_name='Валюта')),
                ('value', models.FloatField(verbose_name='Значение цены')),
                ('ebay_product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auto_accepted_price', to='ebay_listing.EbayListing', verbose_name='Товар eBay')),
            ],
            options={
                'verbose_name': 'Порог цены для автоматического принятия Best Offer',
                'verbose_name_plural': 'Порог цены для автоматического принятия Best Offer',
            },
        ),
        migrations.CreateModel(
            name='EbayListingAspect',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=40, verbose_name='Name')),
                ('value', models.CharField(max_length=50, verbose_name='Value')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aspects', related_query_name='aspect', to='ebay_listing.EbayListing', verbose_name='eBay listing')),
            ],
            options={
                'verbose_name': 'Аспект товара для eBay',
                'verbose_name_plural': 'Аспекты товара для eBay',
            },
        ),
    ]
