version: '3'
services:
   omegaml:
       build: .
       image: omegaml/omegaml:latest
       hostname: omegaml
       ports:
          - "8899:8888"
          - "5000:5000"
       links:
          - rabbitmq
          - mongodb
       working_dir: /app
       command: honcho start notebook restapi
       environment:
         - APP=omegaml
         - OMEGA_MONGO_URL=mongodb://mongodb/omega
         - OMEGA_BROKER=amqp://rabbitmq:5672//
         - OMEGA_FRAMEWORKS=scikit-learn,keras,tensorflow
         - JUPYTER_PASSWORD=sha1:24fa20fec60f:c7cd7e46afa507d484c59abeadbefa05022583b8
   worker:
       image: omegaml/omegaml:latest
       hostname: worker
       links:
          - rabbitmq
          - mongodb
       working_dir: /app
       command: honcho start worker
       environment:
         - OMEGA_MONGO_URL=mongodb://mongodb/omega
         - OMEGA_BROKER=amqp://rabbitmq:5672//
         - OMEGA_FRAMEWORKS=scikit-learn,keras,tensorflow
         - C_FORCE_ROOT=yes
   rabbitmq:
       image: rabbitmq:3.7.17
       hostname: rabbitmq
   mongodb:
       image: mongo:3.6.8-stretch
       hostname: mongodb
