[tool.poetry]
name = "phuzzymatcher"
version = "0.0.1"
description = "Features the combination of the fuzzywuzzy library and the spacy phrasematcher"
authors = ["Sebastian Menke <sebastian.menke@posteo.de>"]

packages = [{ include = "scripts" }]
include = ["README.md"]
exclude = ["notebooks","match_list"]

[tool.poetry.dependencies]
python = "^3.7"
spacy = "^2.2.3"
nltk = "^3.4.5"
fuzzywuzzy = "^0.17.0"

[tool.poetry.dev-dependencies]
pytest = "^3.7"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"




