# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'forms/centroid_plots_config.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CentroidPlotsConfigForm(object):
    def setupUi(self, CentroidPlotsConfigForm):
        CentroidPlotsConfigForm.setObjectName("CentroidPlotsConfigForm")
        CentroidPlotsConfigForm.resize(287, 451)
        self.gridLayout = QtWidgets.QGridLayout(CentroidPlotsConfigForm)
        self.gridLayout.setObjectName("gridLayout")
        self.xCentroidGroupBox = QtWidgets.QGroupBox(CentroidPlotsConfigForm)
        self.xCentroidGroupBox.setObjectName("xCentroidGroupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.xCentroidGroupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.autoscaleXLabel = QtWidgets.QLabel(self.xCentroidGroupBox)
        self.autoscaleXLabel.setObjectName("autoscaleXLabel")
        self.horizontalLayout_9.addWidget(self.autoscaleXLabel)
        self.autoscaleXComboBox = QtWidgets.QComboBox(self.xCentroidGroupBox)
        self.autoscaleXComboBox.setObjectName("autoscaleXComboBox")
        self.autoscaleXComboBox.addItem("")
        self.autoscaleXComboBox.addItem("")
        self.autoscaleXComboBox.addItem("")
        self.horizontalLayout_9.addWidget(self.autoscaleXComboBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.pixelAdditionXLabel = QtWidgets.QLabel(self.xCentroidGroupBox)
        self.pixelAdditionXLabel.setEnabled(False)
        self.pixelAdditionXLabel.setObjectName("pixelAdditionXLabel")
        self.horizontalLayout_8.addWidget(self.pixelAdditionXLabel)
        self.pixelAdditionXLineEdit = QtWidgets.QLineEdit(self.xCentroidGroupBox)
        self.pixelAdditionXLineEdit.setEnabled(False)
        self.pixelAdditionXLineEdit.setObjectName("pixelAdditionXLineEdit")
        self.horizontalLayout_8.addWidget(self.pixelAdditionXLineEdit)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.minXLimitLabel = QtWidgets.QLabel(self.xCentroidGroupBox)
        self.minXLimitLabel.setEnabled(False)
        self.minXLimitLabel.setObjectName("minXLimitLabel")
        self.horizontalLayout_5.addWidget(self.minXLimitLabel)
        self.minXLimitLineEdit = QtWidgets.QLineEdit(self.xCentroidGroupBox)
        self.minXLimitLineEdit.setEnabled(False)
        self.minXLimitLineEdit.setObjectName("minXLimitLineEdit")
        self.horizontalLayout_5.addWidget(self.minXLimitLineEdit)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.maxXLimitLabel = QtWidgets.QLabel(self.xCentroidGroupBox)
        self.maxXLimitLabel.setEnabled(False)
        self.maxXLimitLabel.setObjectName("maxXLimitLabel")
        self.horizontalLayout_4.addWidget(self.maxXLimitLabel)
        self.maxXLimitLineEdit = QtWidgets.QLineEdit(self.xCentroidGroupBox)
        self.maxXLimitLineEdit.setEnabled(False)
        self.maxXLimitLineEdit.setObjectName("maxXLimitLineEdit")
        self.horizontalLayout_4.addWidget(self.maxXLimitLineEdit)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.gridLayout.addWidget(self.xCentroidGroupBox, 0, 0, 1, 1)
        self.yCentroidGroupBox = QtWidgets.QGroupBox(CentroidPlotsConfigForm)
        self.yCentroidGroupBox.setObjectName("yCentroidGroupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.yCentroidGroupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.autoscaleYLabel = QtWidgets.QLabel(self.yCentroidGroupBox)
        self.autoscaleYLabel.setObjectName("autoscaleYLabel")
        self.horizontalLayout_3.addWidget(self.autoscaleYLabel)
        self.autoscaleYComboBox = QtWidgets.QComboBox(self.yCentroidGroupBox)
        self.autoscaleYComboBox.setObjectName("autoscaleYComboBox")
        self.autoscaleYComboBox.addItem("")
        self.autoscaleYComboBox.addItem("")
        self.autoscaleYComboBox.addItem("")
        self.horizontalLayout_3.addWidget(self.autoscaleYComboBox)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.pixelAdditionYLabel = QtWidgets.QLabel(self.yCentroidGroupBox)
        self.pixelAdditionYLabel.setEnabled(False)
        self.pixelAdditionYLabel.setObjectName("pixelAdditionYLabel")
        self.horizontalLayout_6.addWidget(self.pixelAdditionYLabel)
        self.pixelAdditionYLineEdit = QtWidgets.QLineEdit(self.yCentroidGroupBox)
        self.pixelAdditionYLineEdit.setEnabled(False)
        self.pixelAdditionYLineEdit.setObjectName("pixelAdditionYLineEdit")
        self.horizontalLayout_6.addWidget(self.pixelAdditionYLineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.minYLimitLabel = QtWidgets.QLabel(self.yCentroidGroupBox)
        self.minYLimitLabel.setEnabled(False)
        self.minYLimitLabel.setObjectName("minYLimitLabel")
        self.horizontalLayout_2.addWidget(self.minYLimitLabel)
        self.minYLimitLineEdit = QtWidgets.QLineEdit(self.yCentroidGroupBox)
        self.minYLimitLineEdit.setEnabled(False)
        self.minYLimitLineEdit.setObjectName("minYLimitLineEdit")
        self.horizontalLayout_2.addWidget(self.minYLimitLineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.maxYLimitLabel = QtWidgets.QLabel(self.yCentroidGroupBox)
        self.maxYLimitLabel.setEnabled(False)
        self.maxYLimitLabel.setObjectName("maxYLimitLabel")
        self.horizontalLayout.addWidget(self.maxYLimitLabel)
        self.maxYLimitLineEdit = QtWidgets.QLineEdit(self.yCentroidGroupBox)
        self.maxYLimitLineEdit.setEnabled(False)
        self.maxYLimitLineEdit.setObjectName("maxYLimitLineEdit")
        self.horizontalLayout.addWidget(self.maxYLimitLineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout.addWidget(self.yCentroidGroupBox, 1, 0, 1, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.numHistoBinsLabel = QtWidgets.QLabel(CentroidPlotsConfigForm)
        self.numHistoBinsLabel.setObjectName("numHistoBinsLabel")
        self.horizontalLayout_7.addWidget(self.numHistoBinsLabel)
        self.numHistoBinsLineEdit = QtWidgets.QLineEdit(CentroidPlotsConfigForm)
        self.numHistoBinsLineEdit.setObjectName("numHistoBinsLineEdit")
        self.horizontalLayout_7.addWidget(self.numHistoBinsLineEdit)
        self.gridLayout.addLayout(self.horizontalLayout_7, 2, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 3, 0, 1, 1)
        self.yCentroidGroupBox.raise_()
        self.xCentroidGroupBox.raise_()
        self.autoscaleXLabel.setBuddy(self.autoscaleXComboBox)
        self.pixelAdditionXLabel.setBuddy(self.pixelAdditionXLineEdit)
        self.minXLimitLabel.setBuddy(self.minXLimitLineEdit)
        self.maxXLimitLabel.setBuddy(self.maxXLimitLineEdit)
        self.autoscaleYLabel.setBuddy(self.autoscaleYComboBox)
        self.pixelAdditionYLabel.setBuddy(self.pixelAdditionYLineEdit)
        self.minYLimitLabel.setBuddy(self.minYLimitLineEdit)
        self.maxYLimitLabel.setBuddy(self.maxYLimitLineEdit)
        self.numHistoBinsLabel.setBuddy(self.numHistoBinsLineEdit)

        self.retranslateUi(CentroidPlotsConfigForm)
        self.autoscaleXComboBox.setCurrentIndex(2)
        self.autoscaleYComboBox.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(CentroidPlotsConfigForm)

    def retranslateUi(self, CentroidPlotsConfigForm):
        _translate = QtCore.QCoreApplication.translate
        CentroidPlotsConfigForm.setWindowTitle(_translate("CentroidPlotsConfigForm", "Form"))
        self.xCentroidGroupBox.setTitle(_translate("CentroidPlotsConfigForm", "X 1D"))
        self.autoscaleXLabel.setText(_translate("CentroidPlotsConfigForm", "Autoscale:"))
        self.autoscaleXComboBox.setItemText(0, _translate("CentroidPlotsConfigForm", "OFF"))
        self.autoscaleXComboBox.setItemText(1, _translate("CentroidPlotsConfigForm", "PARTIAL"))
        self.autoscaleXComboBox.setItemText(2, _translate("CentroidPlotsConfigForm", "ON"))
        self.pixelAdditionXLabel.setText(_translate("CentroidPlotsConfigForm", "Pixel Addition:"))
        self.pixelAdditionXLineEdit.setToolTip(_translate("CentroidPlotsConfigForm", "Valid Range: 1 to 10000 as an integer"))
        self.minXLimitLabel.setText(_translate("CentroidPlotsConfigForm", "Minimum:"))
        self.minXLimitLineEdit.setToolTip(_translate("CentroidPlotsConfigForm", "Valid Range: 0 to 1e9 as an integer"))
        self.maxXLimitLabel.setText(_translate("CentroidPlotsConfigForm", "Maximum:"))
        self.maxXLimitLineEdit.setToolTip(_translate("CentroidPlotsConfigForm", "Valid Range: 0 to 1e9 as an integer"))
        self.yCentroidGroupBox.setTitle(_translate("CentroidPlotsConfigForm", "Y 1D"))
        self.autoscaleYLabel.setText(_translate("CentroidPlotsConfigForm", "Autoscale:"))
        self.autoscaleYComboBox.setItemText(0, _translate("CentroidPlotsConfigForm", "OFF"))
        self.autoscaleYComboBox.setItemText(1, _translate("CentroidPlotsConfigForm", "PARTIAL"))
        self.autoscaleYComboBox.setItemText(2, _translate("CentroidPlotsConfigForm", "ON"))
        self.pixelAdditionYLabel.setText(_translate("CentroidPlotsConfigForm", "Pixel Addition:"))
        self.pixelAdditionYLineEdit.setToolTip(_translate("CentroidPlotsConfigForm", "Valid Range: 1 to 10000 as an integer"))
        self.minYLimitLabel.setText(_translate("CentroidPlotsConfigForm", "Minimum:"))
        self.minYLimitLineEdit.setToolTip(_translate("CentroidPlotsConfigForm", "Valid Range: 0 to 1e9 as an integer"))
        self.maxYLimitLabel.setText(_translate("CentroidPlotsConfigForm", "Maximum:"))
        self.maxYLimitLineEdit.setToolTip(_translate("CentroidPlotsConfigForm", "Valid Range: 0 to 1e9 as an integer"))
        self.numHistoBinsLabel.setText(_translate("CentroidPlotsConfigForm", "Num Histogram Bins:"))
        self.numHistoBinsLineEdit.setToolTip(_translate("CentroidPlotsConfigForm", "Valid Range: 1 to 1e9 as an integer"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CentroidPlotsConfigForm = QtWidgets.QWidget()
    ui = Ui_CentroidPlotsConfigForm()
    ui.setupUi(CentroidPlotsConfigForm)
    CentroidPlotsConfigForm.show()
    sys.exit(app.exec_())
