# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'forms/general_config.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GeneralConfigForm(object):
    def setupUi(self, GeneralConfigForm):
        GeneralConfigForm.setObjectName("GeneralConfigForm")
        GeneralConfigForm.resize(261, 430)
        GeneralConfigForm.setMinimumSize(QtCore.QSize(0, 430))
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(GeneralConfigForm)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.siteNameLabel = QtWidgets.QLabel(GeneralConfigForm)
        self.siteNameLabel.setObjectName("siteNameLabel")
        self.horizontalLayout.addWidget(self.siteNameLabel)
        self.siteNameLineEdit = QtWidgets.QLineEdit(GeneralConfigForm)
        self.siteNameLineEdit.setObjectName("siteNameLineEdit")
        self.horizontalLayout.addWidget(self.siteNameLineEdit)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.configVersionLabel = QtWidgets.QLabel(GeneralConfigForm)
        self.configVersionLabel.setObjectName("configVersionLabel")
        self.horizontalLayout_2.addWidget(self.configVersionLabel)
        self.configVersionLineEdit = QtWidgets.QLineEdit(GeneralConfigForm)
        self.configVersionLineEdit.setObjectName("configVersionLineEdit")
        self.horizontalLayout_2.addWidget(self.configVersionLineEdit)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.autorunCheckBox = QtWidgets.QCheckBox(GeneralConfigForm)
        self.autorunCheckBox.setObjectName("autorunCheckBox")
        self.verticalLayout_3.addWidget(self.autorunCheckBox)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.timezoneLabel = QtWidgets.QLabel(GeneralConfigForm)
        self.timezoneLabel.setObjectName("timezoneLabel")
        self.horizontalLayout_3.addWidget(self.timezoneLabel)
        self.timezoneComboBox = QtWidgets.QComboBox(GeneralConfigForm)
        self.timezoneComboBox.setObjectName("timezoneComboBox")
        self.horizontalLayout_3.addWidget(self.timezoneComboBox)
        self.horizontalLayout_3.setStretch(1, 1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.telemetryGroupBox = QtWidgets.QGroupBox(GeneralConfigForm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.telemetryGroupBox.sizePolicy().hasHeightForWidth())
        self.telemetryGroupBox.setSizePolicy(sizePolicy)
        self.telemetryGroupBox.setMinimumSize(QtCore.QSize(0, 200))
        self.telemetryGroupBox.setObjectName("telemetryGroupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.telemetryGroupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setSpacing(4)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(0, -1, -1, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.telemetryDirLabel = QtWidgets.QLabel(self.telemetryGroupBox)
        self.telemetryDirLabel.setObjectName("telemetryDirLabel")
        self.horizontalLayout_4.addWidget(self.telemetryDirLabel)
        self.telemetryDirPushButton = QtWidgets.QPushButton(self.telemetryGroupBox)
        self.telemetryDirPushButton.setObjectName("telemetryDirPushButton")
        self.horizontalLayout_4.addWidget(self.telemetryDirPushButton)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.clearTelemetryDirPushButton = QtWidgets.QPushButton(self.telemetryGroupBox)
        self.clearTelemetryDirPushButton.setObjectName("clearTelemetryDirPushButton")
        self.verticalLayout.addWidget(self.clearTelemetryDirPushButton)
        self.telemetryDirLineEdit = QtWidgets.QLineEdit(self.telemetryGroupBox)
        self.telemetryDirLineEdit.setEnabled(True)
        self.telemetryDirLineEdit.setReadOnly(True)
        self.telemetryDirLineEdit.setObjectName("telemetryDirLineEdit")
        self.verticalLayout.addWidget(self.telemetryDirLineEdit)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.removeDirectoryCheckBox = QtWidgets.QCheckBox(self.telemetryGroupBox)
        self.removeDirectoryCheckBox.setChecked(True)
        self.removeDirectoryCheckBox.setObjectName("removeDirectoryCheckBox")
        self.verticalLayout_2.addWidget(self.removeDirectoryCheckBox)
        self.removeFilesCheckBox = QtWidgets.QCheckBox(self.telemetryGroupBox)
        self.removeFilesCheckBox.setEnabled(False)
        self.removeFilesCheckBox.setChecked(True)
        self.removeFilesCheckBox.setObjectName("removeFilesCheckBox")
        self.verticalLayout_2.addWidget(self.removeFilesCheckBox)
        self.verticalLayout_3.addWidget(self.telemetryGroupBox)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.siteNameLabel.setBuddy(self.siteNameLineEdit)
        self.configVersionLabel.setBuddy(self.configVersionLineEdit)
        self.telemetryDirLabel.setBuddy(self.telemetryDirPushButton)

        self.retranslateUi(GeneralConfigForm)
        QtCore.QMetaObject.connectSlotsByName(GeneralConfigForm)
        GeneralConfigForm.setTabOrder(self.siteNameLineEdit, self.configVersionLineEdit)
        GeneralConfigForm.setTabOrder(self.configVersionLineEdit, self.autorunCheckBox)
        GeneralConfigForm.setTabOrder(self.autorunCheckBox, self.telemetryDirPushButton)
        GeneralConfigForm.setTabOrder(self.telemetryDirPushButton, self.clearTelemetryDirPushButton)
        GeneralConfigForm.setTabOrder(self.clearTelemetryDirPushButton, self.telemetryDirLineEdit)
        GeneralConfigForm.setTabOrder(self.telemetryDirLineEdit, self.removeDirectoryCheckBox)
        GeneralConfigForm.setTabOrder(self.removeDirectoryCheckBox, self.removeFilesCheckBox)

    def retranslateUi(self, GeneralConfigForm):
        _translate = QtCore.QCoreApplication.translate
        GeneralConfigForm.setWindowTitle(_translate("GeneralConfigForm", "Form"))
        self.siteNameLabel.setText(_translate("GeneralConfigForm", "Site Name:"))
        self.configVersionLabel.setText(_translate("GeneralConfigForm", "Config Version:"))
        self.autorunCheckBox.setToolTip(_translate("GeneralConfigForm", "Run program in ROI mode on launch. Only takes effect when launching program."))
        self.autorunCheckBox.setText(_translate("GeneralConfigForm", "Autorun"))
        self.timezoneLabel.setText(_translate("GeneralConfigForm", "Timezone:"))
        self.telemetryGroupBox.setTitle(_translate("GeneralConfigForm", "Telemetry"))
        self.telemetryDirLabel.setText(_translate("GeneralConfigForm", "Output Directory:"))
        self.telemetryDirPushButton.setText(_translate("GeneralConfigForm", "Select"))
        self.clearTelemetryDirPushButton.setText(_translate("GeneralConfigForm", "Clear"))
        self.removeDirectoryCheckBox.setText(_translate("GeneralConfigForm", "Remove Directory"))
        self.removeFilesCheckBox.setText(_translate("GeneralConfigForm", "Remove Files"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    GeneralConfigForm = QtWidgets.QWidget()
    ui = Ui_GeneralConfigForm()
    ui.setupUi(GeneralConfigForm)
    GeneralConfigForm.show()
    sys.exit(app.exec_())
