# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'forms/main_window.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1064, 765)
        MainWindow.setUnifiedTitleAndToolBarOnMac(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_5.setSpacing(1)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSpacing(1)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(1)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.cameraPlot = CameraPlotWidget(self.centralwidget)
        self.cameraPlot.setMinimumSize(QtCore.QSize(250, 200))
        self.cameraPlot.setObjectName("cameraPlot")
        self.verticalLayout_3.addWidget(self.cameraPlot)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.horizontalLayout_4.addLayout(self.verticalLayout_3)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.centroidXPlot = Centroid1dPlotWidget(self.centralwidget)
        self.centroidXPlot.setMinimumSize(QtCore.QSize(200, 150))
        self.centroidXPlot.setObjectName("centroidXPlot")
        self.verticalLayout_2.addWidget(self.centroidXPlot)
        self.centroidYPlot = Centroid1dPlotWidget(self.centralwidget)
        self.centroidYPlot.setMinimumSize(QtCore.QSize(200, 150))
        self.centroidYPlot.setObjectName("centroidYPlot")
        self.verticalLayout_2.addWidget(self.centroidYPlot)
        self.horizontalLayout_4.addLayout(self.verticalLayout_2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.scatterPlot = CentroidScatterPlotWidget(self.centralwidget)
        self.scatterPlot.setMinimumSize(QtCore.QSize(400, 300))
        self.scatterPlot.setObjectName("scatterPlot")
        self.verticalLayout_4.addWidget(self.scatterPlot)
        self.horizontalLayout_5.addLayout(self.verticalLayout_4)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.psd1dXPlot = Psd1dPlotWidget(self.centralwidget)
        self.psd1dXPlot.setMinimumSize(QtCore.QSize(250, 150))
        self.psd1dXPlot.setObjectName("psd1dXPlot")
        self.horizontalLayout_2.addWidget(self.psd1dXPlot)
        self.psd1dYPlot = Psd1dPlotWidget(self.centralwidget)
        self.psd1dYPlot.setMinimumSize(QtCore.QSize(250, 150))
        self.psd1dYPlot.setObjectName("psd1dYPlot")
        self.horizontalLayout_2.addWidget(self.psd1dYPlot)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.psdWaterfallXPlot = PsdWaterfallPlotWidget(self.centralwidget)
        self.psdWaterfallXPlot.setMinimumSize(QtCore.QSize(250, 250))
        self.psdWaterfallXPlot.setObjectName("psdWaterfallXPlot")
        self.horizontalLayout.addWidget(self.psdWaterfallXPlot)
        self.psdWaterfallYPlot = PsdWaterfallPlotWidget(self.centralwidget)
        self.psdWaterfallYPlot.setMinimumSize(QtCore.QSize(250, 250))
        self.psdWaterfallYPlot.setObjectName("psdWaterfallYPlot")
        self.horizontalLayout.addWidget(self.psdWaterfallYPlot)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.cameraControl = CameraControlWidget(self.centralwidget)
        self.cameraControl.setMinimumSize(QtCore.QSize(0, 0))
        self.cameraControl.setStyleSheet("")
        self.cameraControl.setObjectName("cameraControl")
        self.horizontalLayout_3.addWidget(self.cameraControl)
        self.cameraData = CameraDataWidget(self.centralwidget)
        self.cameraData.setMinimumSize(QtCore.QSize(100, 100))
        self.cameraData.setStyleSheet("")
        self.cameraData.setObjectName("cameraData")
        self.horizontalLayout_3.addWidget(self.cameraData)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1064, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuCamera = QtWidgets.QMenu(self.menubar)
        self.menuCamera.setObjectName("menuCamera")
        self.menuConfigure = QtWidgets.QMenu(self.menubar)
        self.menuConfigure.setObjectName("menuConfigure")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionDummy = QtWidgets.QAction(MainWindow)
        self.actionDummy.setObjectName("actionDummy")
        self.actionCameraConfig = QtWidgets.QAction(MainWindow)
        self.actionCameraConfig.setObjectName("actionCameraConfig")
        self.actionPlotsConfig = QtWidgets.QAction(MainWindow)
        self.actionPlotsConfig.setObjectName("actionPlotsConfig")
        self.actionDataConfig = QtWidgets.QAction(MainWindow)
        self.actionDataConfig.setObjectName("actionDataConfig")
        self.actionGeneralConfig = QtWidgets.QAction(MainWindow)
        self.actionGeneralConfig.setObjectName("actionGeneralConfig")
        self.actionSaveConfiguration = QtWidgets.QAction(MainWindow)
        self.actionSaveConfiguration.setObjectName("actionSaveConfiguration")
        self.actionWriteStandardConfig = QtWidgets.QAction(MainWindow)
        self.actionWriteStandardConfig.setCheckable(True)
        self.actionWriteStandardConfig.setChecked(True)
        self.actionWriteStandardConfig.setObjectName("actionWriteStandardConfig")
        self.actionWritePlotConfig = QtWidgets.QAction(MainWindow)
        self.actionWritePlotConfig.setCheckable(True)
        self.actionWritePlotConfig.setObjectName("actionWritePlotConfig")
        self.actionWriteEmptyConfig = QtWidgets.QAction(MainWindow)
        self.actionWriteEmptyConfig.setCheckable(True)
        self.actionWriteEmptyConfig.setObjectName("actionWriteEmptyConfig")
        self.actionOpenConfiguration = QtWidgets.QAction(MainWindow)
        self.actionOpenConfiguration.setObjectName("actionOpenConfiguration")
        self.actionCameraInfo = QtWidgets.QAction(MainWindow)
        self.actionCameraInfo.setEnabled(False)
        self.actionCameraInfo.setObjectName("actionCameraInfo")
        self.menuFile.addAction(self.actionOpenConfiguration)
        self.menuFile.addAction(self.actionSaveConfiguration)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionWritePlotConfig)
        self.menuFile.addAction(self.actionWriteEmptyConfig)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuHelp.addAction(self.actionAbout)
        self.menuHelp.addAction(self.actionCameraInfo)
        self.menuConfigure.addAction(self.actionCameraConfig)
        self.menuConfigure.addAction(self.actionPlotsConfig)
        self.menuConfigure.addAction(self.actionDataConfig)
        self.menuConfigure.addAction(self.actionGeneralConfig)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuCamera.menuAction())
        self.menubar.addAction(self.menuConfigure.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.menuCamera.setTitle(_translate("MainWindow", "Camera"))
        self.menuConfigure.setTitle(_translate("MainWindow", "Configure"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionExit.setToolTip(_translate("MainWindow", "Exit the Program"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionAbout.setShortcut(_translate("MainWindow", "Meta+Shift+A"))
        self.actionDummy.setText(_translate("MainWindow", "Dummy"))
        self.actionCameraConfig.setText(_translate("MainWindow", "Camera"))
        self.actionCameraConfig.setShortcut(_translate("MainWindow", "Meta+Shift+C"))
        self.actionPlotsConfig.setText(_translate("MainWindow", "Plots"))
        self.actionPlotsConfig.setShortcut(_translate("MainWindow", "Meta+Shift+P"))
        self.actionDataConfig.setText(_translate("MainWindow", "Data"))
        self.actionDataConfig.setShortcut(_translate("MainWindow", "Meta+Shift+D"))
        self.actionGeneralConfig.setText(_translate("MainWindow", "General"))
        self.actionGeneralConfig.setShortcut(_translate("MainWindow", "Meta+Shift+G"))
        self.actionSaveConfiguration.setText(_translate("MainWindow", "Save Configuration"))
        self.actionWriteStandardConfig.setText(_translate("MainWindow", "Write Standard Config"))
        self.actionWritePlotConfig.setText(_translate("MainWindow", "Write Plot Config"))
        self.actionWriteEmptyConfig.setText(_translate("MainWindow", "Write Empty Config"))
        self.actionOpenConfiguration.setText(_translate("MainWindow", "Open Configuration"))
        self.actionCameraInfo.setText(_translate("MainWindow", "Camera"))
        self.actionCameraInfo.setShortcut(_translate("MainWindow", "Meta+Shift+I"))
from spot_motion_monitor.views.camera_control_widget import CameraControlWidget
from spot_motion_monitor.views.camera_data_widget import CameraDataWidget
from spot_motion_monitor.views.camera_plot_widget import CameraPlotWidget
from spot_motion_monitor.views.centroid_1d_plot_widget import Centroid1dPlotWidget
from spot_motion_monitor.views.centroid_scatter_plot_widget import CentroidScatterPlotWidget
from spot_motion_monitor.views.psd_1d_plot_widget import Psd1dPlotWidget
from spot_motion_monitor.views.psd_waterfall_plot_widget import PsdWaterfallPlotWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
