# Generated by Django 2.0 on 2017-12-26 13:03

import django.contrib.postgres.fields.jsonb
import django.db.models.deletion
import django_intenum
import hearthstone.enums
from django.conf import settings
from django.db import migrations, models

import hearthsim.identity.accounts.models


class Migration(migrations.Migration):

	dependencies = [
		("accounts", "0001_initial"),
	]

	operations = [
		migrations.CreateModel(
			name="AccountActivity",
			fields=[
				("id", models.BigAutoField(primary_key=True, serialize=False)),
				("action", models.CharField(max_length=255)),
				("remote_ip", models.GenericIPAddressField(default="0.0.0.0")),
				("ip_country", models.CharField(blank=True, max_length=2)),
				("user_agent", models.TextField(blank=True)),
				("old_value", django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
				("new_value", django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
				("metadata", django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
				("created", models.DateTimeField(auto_now_add=True, db_index=True)),
			],
		),
		migrations.AlterField(
			model_name="user",
			name="last_name",
			field=models.CharField(blank=True, max_length=150, verbose_name="last name"),
		),
		migrations.AddField(
			model_name="accountactivity",
			name="user",
			field=models.ForeignKey(
				on_delete=django.db.models.deletion.CASCADE,
				related_name="account_activity",
				to=settings.AUTH_USER_MODEL
			),
		),
		migrations.AlterUniqueTogether(
			name="blizzardaccount",
			unique_together={("region", "account_lo"), ("account_hi", "account_lo")},
		),
	]
