[tool.poetry]
name = "keios-dynabuffers-atlas"
version = "0.4.0"
description = ""
authors = ["fridayy <benjamin.krenn@leftshift.one>"]

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]
pytest = "^3.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
