"""
Helper class that contains definitions for all emoji.

Names should be identical to those defined in Unicode, with the exceptions:
    * All names are in upper case
    * Names beginning 1st, 2nd, 3rd are replaced with FIRST, SECOND, THIRD
    * Special symbols &, # and * are replaced with AND, HASH and ASTERISK
"""

GRINNING_FACE = "😀" #grinning face
GRINNING_FACE_WITH_BIG_EYES = "😃" #grinning face with big eyes
GRINNING_FACE_WITH_SMILING_EYES = "😄" #grinning face with smiling eyes
BEAMING_FACE_WITH_SMILING_EYES = "😁" #beaming face with smiling eyes
GRINNING_SQUINTING_FACE = "😆" #grinning squinting face
GRINNING_FACE_WITH_SWEAT = "😅" #grinning face with sweat
ROLLING_ON_THE_FLOOR_LAUGHING = "🤣" #rolling on the floor laughing
FACE_WITH_TEARS_OF_JOY = "😂" #face with tears of joy
SLIGHTLY_SMILING_FACE = "🙂" #slightly smiling face
UPSIDE_DOWN_FACE = "🙃" #upside-down face
WINKING_FACE = "😉" #winking face
SMILING_FACE_WITH_SMILING_EYES = "😊" #smiling face with smiling eyes
SMILING_FACE_WITH_HALO = "😇" #smiling face with halo
SMILING_FACE_WITH_HEARTS = "🥰" #smiling face with hearts
SMILING_FACE_WITH_HEART_EYES = "😍" #smiling face with heart-eyes
STAR_STRUCK = "🤩" #star-struck
FACE_BLOWING_A_KISS = "😘" #face blowing a kiss
KISSING_FACE = "😗" #kissing face
SMILING_FACE = "☺" #smiling face
KISSING_FACE_WITH_CLOSED_EYES = "😚" #kissing face with closed eyes
KISSING_FACE_WITH_SMILING_EYES = "😙" #kissing face with smiling eyes
FACE_SAVORING_FOOD = "😋" #face savoring food
FACE_WITH_TONGUE = "😛" #face with tongue
WINKING_FACE_WITH_TONGUE = "😜" #winking face with tongue
ZANY_FACE = "🤪" #zany face
SQUINTING_FACE_WITH_TONGUE = "😝" #squinting face with tongue
MONEY_MOUTH_FACE = "🤑" #money-mouth face
HUGGING_FACE = "🤗" #hugging face
FACE_WITH_HAND_OVER_MOUTH = "🤭" #face with hand over mouth
SHUSHING_FACE = "🤫" #shushing face
THINKING_FACE = "🤔" #thinking face
ZIPPER_MOUTH_FACE = "🤐" #zipper-mouth face
FACE_WITH_RAISED_EYEBROW = "🤨" #face with raised eyebrow
NEUTRAL_FACE = "😐" #neutral face
EXPRESSIONLESS_FACE = "😑" #expressionless face
FACE_WITHOUT_MOUTH = "😶" #face without mouth
SMIRKING_FACE = "😏" #smirking face
UNAMUSED_FACE = "😒" #unamused face
FACE_WITH_ROLLING_EYES = "🙄" #face with rolling eyes
GRIMACING_FACE = "😬" #grimacing face
LYING_FACE = "🤥" #lying face
RELIEVED_FACE = "😌" #relieved face
PENSIVE_FACE = "😔" #pensive face
SLEEPY_FACE = "😪" #sleepy face
DROOLING_FACE = "🤤" #drooling face
SLEEPING_FACE = "😴" #sleeping face
FACE_WITH_MEDICAL_MASK = "😷" #face with medical mask
FACE_WITH_THERMOMETER = "🤒" #face with thermometer
FACE_WITH_HEAD_BANDAGE = "🤕" #face with head-bandage
NAUSEATED_FACE = "🤢" #nauseated face
FACE_VOMITING = "🤮" #face vomiting
SNEEZING_FACE = "🤧" #sneezing face
HOT_FACE = "🥵" #hot face
COLD_FACE = "🥶" #cold face
WOOZY_FACE = "🥴" #woozy face
DIZZY_FACE = "😵" #dizzy face
EXPLODING_HEAD = "🤯" #exploding head
COWBOY_HAT_FACE = "🤠" #cowboy hat face
PARTYING_FACE = "🥳" #partying face
SMILING_FACE_WITH_SUNGLASSES = "😎" #smiling face with sunglasses
NERD_FACE = "🤓" #nerd face
FACE_WITH_MONOCLE = "🧐" #face with monocle
CONFUSED_FACE = "😕" #confused face
WORRIED_FACE = "😟" #worried face
SLIGHTLY_FROWNING_FACE = "🙁" #slightly frowning face
FROWNING_FACE = "☹" #frowning face
FACE_WITH_OPEN_MOUTH = "😮" #face with open mouth
HUSHED_FACE = "😯" #hushed face
ASTONISHED_FACE = "😲" #astonished face
FLUSHED_FACE = "😳" #flushed face
PLEADING_FACE = "🥺" #pleading face
FROWNING_FACE_WITH_OPEN_MOUTH = "😦" #frowning face with open mouth
ANGUISHED_FACE = "😧" #anguished face
FEARFUL_FACE = "😨" #fearful face
ANXIOUS_FACE_WITH_SWEAT = "😰" #anxious face with sweat
SAD_BUT_RELIEVED_FACE = "😥" #sad but relieved face
CRYING_FACE = "😢" #crying face
LOUDLY_CRYING_FACE = "😭" #loudly crying face
FACE_SCREAMING_IN_FEAR = "😱" #face screaming in fear
CONFOUNDED_FACE = "😖" #confounded face
PERSEVERING_FACE = "😣" #persevering face
DISAPPOINTED_FACE = "😞" #disappointed face
DOWNCAST_FACE_WITH_SWEAT = "😓" #downcast face with sweat
WEARY_FACE = "😩" #weary face
TIRED_FACE = "😫" #tired face
YAWNING_FACE = "🥱" #⊛ yawning face
FACE_WITH_STEAM_FROM_NOSE = "😤" #face with steam from nose
POUTING_FACE = "😡" #pouting face
ANGRY_FACE = "😠" #angry face
FACE_WITH_SYMBOLS_ON_MOUTH = "🤬" #face with symbols on mouth
SMILING_FACE_WITH_HORNS = "😈" #smiling face with horns
ANGRY_FACE_WITH_HORNS = "👿" #angry face with horns
SKULL = "💀" #skull
SKULL_AND_CROSSBONES = "☠" #skull and crossbones
PILE_OF_POO = "💩" #pile of poo
CLOWN_FACE = "🤡" #clown face
OGRE = "👹" #ogre
GOBLIN = "👺" #goblin
GHOST = "👻" #ghost
ALIEN = "👽" #alien
ALIEN_MONSTER = "👾" #alien monster
ROBOT = "🤖" #robot
GRINNING_CAT = "😺" #grinning cat
GRINNING_CAT_WITH_SMILING_EYES = "😸" #grinning cat with smiling eyes
CAT_WITH_TEARS_OF_JOY = "😹" #cat with tears of joy
SMILING_CAT_WITH_HEART_EYES = "😻" #smiling cat with heart-eyes
CAT_WITH_WRY_SMILE = "😼" #cat with wry smile
KISSING_CAT = "😽" #kissing cat
WEARY_CAT = "🙀" #weary cat
CRYING_CAT = "😿" #crying cat
POUTING_CAT = "😾" #pouting cat
SEE_NO_EVIL_MONKEY = "🙈" #see-no-evil monkey
HEAR_NO_EVIL_MONKEY = "🙉" #hear-no-evil monkey
SPEAK_NO_EVIL_MONKEY = "🙊" #speak-no-evil monkey
KISS_MARK = "💋" #kiss mark
LOVE_LETTER = "💌" #love letter
HEART_WITH_ARROW = "💘" #heart with arrow
HEART_WITH_RIBBON = "💝" #heart with ribbon
SPARKLING_HEART = "💖" #sparkling heart
GROWING_HEART = "💗" #growing heart
BEATING_HEART = "💓" #beating heart
REVOLVING_HEARTS = "💞" #revolving hearts
TWO_HEARTS = "💕" #two hearts
HEART_DECORATION = "💟" #heart decoration
HEART_EXCLAMATION = "❣" #heart exclamation
BROKEN_HEART = "💔" #broken heart
RED_HEART = "❤" #red heart
ORANGE_HEART = "🧡" #orange heart
YELLOW_HEART = "💛" #yellow heart
GREEN_HEART = "💚" #green heart
BLUE_HEART = "💙" #blue heart
PURPLE_HEART = "💜" #purple heart
BROWN_HEART = "🤎" #⊛ brown heart
BLACK_HEART = "🖤" #black heart
WHITE_HEART = "🤍" #⊛ white heart
HUNDRED_POINTS = "💯" #hundred points
ANGER_SYMBOL = "💢" #anger symbol
COLLISION = "💥" #collision
DIZZY = "💫" #dizzy
SWEAT_DROPLETS = "💦" #sweat droplets
DASHING_AWAY = "💨" #dashing away
HOLE = "🕳" #hole
BOMB = "💣" #bomb
SPEECH_BALLOON = "💬" #speech balloon
EYE_IN_SPEECH_BUBBLE = "👁️‍🗨️" #eye in speech bubble
LEFT_SPEECH_BUBBLE = "🗨" #left speech bubble
RIGHT_ANGER_BUBBLE = "🗯" #right anger bubble
THOUGHT_BALLOON = "💭" #thought balloon
ZZZ = "💤" #zzz
WAVING_HAND = "👋" #waving hand
RAISED_BACK_OF_HAND = "🤚" #raised back of hand
HAND_WITH_FINGERS_SPLAYED = "🖐" #hand with fingers splayed
RAISED_HAND = "✋" #raised hand
VULCAN_SALUTE = "🖖" #vulcan salute
OK_HAND = "👌" #OK hand
PINCHING_HAND = "🤏" #⊛ pinching hand
VICTORY_HAND = "✌" #victory hand
CROSSED_FINGERS = "🤞" #crossed fingers
LOVE_YOU_GESTURE = "🤟" #love-you gesture
SIGN_OF_THE_HORNS = "🤘" #sign of the horns
CALL_ME_HAND = "🤙" #call me hand
BACKHAND_INDEX_POINTING_LEFT = "👈" #backhand index pointing left
BACKHAND_INDEX_POINTING_RIGHT = "👉" #backhand index pointing right
BACKHAND_INDEX_POINTING_UP = "👆" #backhand index pointing up
MIDDLE_FINGER = "🖕" #middle finger
BACKHAND_INDEX_POINTING_DOWN = "👇" #backhand index pointing down
INDEX_POINTING_UP = "☝" #index pointing up
THUMBS_UP = "👍" #thumbs up
THUMBS_DOWN = "👎" #thumbs down
RAISED_FIST = "✊" #raised fist
ONCOMING_FIST = "👊" #oncoming fist
LEFT_FACING_FIST = "🤛" #left-facing fist
RIGHT_FACING_FIST = "🤜" #right-facing fist
CLAPPING_HANDS = "👏" #clapping hands
RAISING_HANDS = "🙌" #raising hands
OPEN_HANDS = "👐" #open hands
PALMS_UP_TOGETHER = "🤲" #palms up together
HANDSHAKE = "🤝" #handshake
FOLDED_HANDS = "🙏" #folded hands
WRITING_HAND = "✍" #writing hand
NAIL_POLISH = "💅" #nail polish
SELFIE = "🤳" #selfie
FLEXED_BICEPS = "💪" #flexed biceps
MECHANICAL_ARM = "🦾" #⊛ mechanical arm
MECHANICAL_LEG = "🦿" #⊛ mechanical leg
LEG = "🦵" #leg
FOOT = "🦶" #foot
EAR = "👂" #ear
EAR_WITH_HEARING_AID = "🦻" #⊛ ear with hearing aid
NOSE = "👃" #nose
BRAIN = "🧠" #brain
TOOTH = "🦷" #tooth
BONE = "🦴" #bone
EYES = "👀" #eyes
EYE = "👁" #eye
TONGUE = "👅" #tongue
MOUTH = "👄" #mouth
BABY = "👶" #baby
CHILD = "🧒" #child
BOY = "👦" #boy
GIRL = "👧" #girl
PERSON = "🧑" #person
PERSON_BLOND_HAIR = "👱" #person: blond hair
MAN = "👨" #man
MAN_BEARD = "🧔" #man: beard
MAN_BLOND_HAIR = "👱‍♂️" #man: blond hair
MAN_RED_HAIR = "👨‍🦰" #man: red hair
MAN_CURLY_HAIR = "👨‍🦱" #man: curly hair
MAN_WHITE_HAIR = "👨‍🦳" #man: white hair
MAN_BALD = "👨‍🦲" #man: bald
WOMAN = "👩" #woman
WOMAN_BLOND_HAIR = "👱‍♀️" #woman: blond hair
WOMAN_RED_HAIR = "👩‍🦰" #woman: red hair
WOMAN_CURLY_HAIR = "👩‍🦱" #woman: curly hair
WOMAN_WHITE_HAIR = "👩‍🦳" #woman: white hair
WOMAN_BALD = "👩‍🦲" #woman: bald
OLDER_PERSON = "🧓" #older person
OLD_MAN = "👴" #old man
OLD_WOMAN = "👵" #old woman
PERSON_FROWNING = "🙍" #person frowning
MAN_FROWNING = "🙍‍♂️" #man frowning
WOMAN_FROWNING = "🙍‍♀️" #woman frowning
PERSON_POUTING = "🙎" #person pouting
MAN_POUTING = "🙎‍♂️" #man pouting
WOMAN_POUTING = "🙎‍♀️" #woman pouting
PERSON_GESTURING_NO = "🙅" #person gesturing NO
MAN_GESTURING_NO = "🙅‍♂️" #man gesturing NO
WOMAN_GESTURING_NO = "🙅‍♀️" #woman gesturing NO
PERSON_GESTURING_OK = "🙆" #person gesturing OK
MAN_GESTURING_OK = "🙆‍♂️" #man gesturing OK
WOMAN_GESTURING_OK = "🙆‍♀️" #woman gesturing OK
PERSON_TIPPING_HAND = "💁" #person tipping hand
MAN_TIPPING_HAND = "💁‍♂️" #man tipping hand
WOMAN_TIPPING_HAND = "💁‍♀️" #woman tipping hand
PERSON_RAISING_HAND = "🙋" #person raising hand
MAN_RAISING_HAND = "🙋‍♂️" #man raising hand
WOMAN_RAISING_HAND = "🙋‍♀️" #woman raising hand
DEAF_PERSON = "🧏" #⊛ deaf person
DEAF_MAN = "🧏‍♂️" #⊛ deaf man
DEAF_WOMAN = "🧏‍♀️" #⊛ deaf woman
PERSON_BOWING = "🙇" #person bowing
MAN_BOWING = "🙇‍♂️" #man bowing
WOMAN_BOWING = "🙇‍♀️" #woman bowing
PERSON_FACEPALMING = "🤦" #person facepalming
MAN_FACEPALMING = "🤦‍♂️" #man facepalming
WOMAN_FACEPALMING = "🤦‍♀️" #woman facepalming
PERSON_SHRUGGING = "🤷" #person shrugging
MAN_SHRUGGING = "🤷‍♂️" #man shrugging
WOMAN_SHRUGGING = "🤷‍♀️" #woman shrugging
MAN_HEALTH_WORKER = "👨‍⚕️" #man health worker
WOMAN_HEALTH_WORKER = "👩‍⚕️" #woman health worker
MAN_STUDENT = "👨‍🎓" #man student
WOMAN_STUDENT = "👩‍🎓" #woman student
MAN_TEACHER = "👨‍🏫" #man teacher
WOMAN_TEACHER = "👩‍🏫" #woman teacher
MAN_JUDGE = "👨‍⚖️" #man judge
WOMAN_JUDGE = "👩‍⚖️" #woman judge
MAN_FARMER = "👨‍🌾" #man farmer
WOMAN_FARMER = "👩‍🌾" #woman farmer
MAN_COOK = "👨‍🍳" #man cook
WOMAN_COOK = "👩‍🍳" #woman cook
MAN_MECHANIC = "👨‍🔧" #man mechanic
WOMAN_MECHANIC = "👩‍🔧" #woman mechanic
MAN_FACTORY_WORKER = "👨‍🏭" #man factory worker
WOMAN_FACTORY_WORKER = "👩‍🏭" #woman factory worker
MAN_OFFICE_WORKER = "👨‍💼" #man office worker
WOMAN_OFFICE_WORKER = "👩‍💼" #woman office worker
MAN_SCIENTIST = "👨‍🔬" #man scientist
WOMAN_SCIENTIST = "👩‍🔬" #woman scientist
MAN_TECHNOLOGIST = "👨‍💻" #man technologist
WOMAN_TECHNOLOGIST = "👩‍💻" #woman technologist
MAN_SINGER = "👨‍🎤" #man singer
WOMAN_SINGER = "👩‍🎤" #woman singer
MAN_ARTIST = "👨‍🎨" #man artist
WOMAN_ARTIST = "👩‍🎨" #woman artist
MAN_PILOT = "👨‍✈️" #man pilot
WOMAN_PILOT = "👩‍✈️" #woman pilot
MAN_ASTRONAUT = "👨‍🚀" #man astronaut
WOMAN_ASTRONAUT = "👩‍🚀" #woman astronaut
MAN_FIREFIGHTER = "👨‍🚒" #man firefighter
WOMAN_FIREFIGHTER = "👩‍🚒" #woman firefighter
POLICE_OFFICER = "👮" #police officer
MAN_POLICE_OFFICER = "👮‍♂️" #man police officer
WOMAN_POLICE_OFFICER = "👮‍♀️" #woman police officer
DETECTIVE = "🕵" #detective
MAN_DETECTIVE = "🕵️‍♂️" #man detective
WOMAN_DETECTIVE = "🕵️‍♀️" #woman detective
GUARD = "💂" #guard
MAN_GUARD = "💂‍♂️" #man guard
WOMAN_GUARD = "💂‍♀️" #woman guard
CONSTRUCTION_WORKER = "👷" #construction worker
MAN_CONSTRUCTION_WORKER = "👷‍♂️" #man construction worker
WOMAN_CONSTRUCTION_WORKER = "👷‍♀️" #woman construction worker
PRINCE = "🤴" #prince
PRINCESS = "👸" #princess
PERSON_WEARING_TURBAN = "👳" #person wearing turban
MAN_WEARING_TURBAN = "👳‍♂️" #man wearing turban
WOMAN_WEARING_TURBAN = "👳‍♀️" #woman wearing turban
MAN_WITH_CHINESE_CAP = "👲" #man with Chinese cap
WOMAN_WITH_HEADSCARF = "🧕" #woman with headscarf
MAN_IN_TUXEDO = "🤵" #man in tuxedo
BRIDE_WITH_VEIL = "👰" #bride with veil
PREGNANT_WOMAN = "🤰" #pregnant woman
BREAST_FEEDING = "🤱" #breast-feeding
BABY_ANGEL = "👼" #baby angel
SANTA_CLAUS = "🎅" #Santa Claus
MRS_CLAUS = "🤶" #Mrs. Claus
SUPERHERO = "🦸" #superhero
MAN_SUPERHERO = "🦸‍♂️" #man superhero
WOMAN_SUPERHERO = "🦸‍♀️" #woman superhero
SUPERVILLAIN = "🦹" #supervillain
MAN_SUPERVILLAIN = "🦹‍♂️" #man supervillain
WOMAN_SUPERVILLAIN = "🦹‍♀️" #woman supervillain
MAGE = "🧙" #mage
MAN_MAGE = "🧙‍♂️" #man mage
WOMAN_MAGE = "🧙‍♀️" #woman mage
FAIRY = "🧚" #fairy
MAN_FAIRY = "🧚‍♂️" #man fairy
WOMAN_FAIRY = "🧚‍♀️" #woman fairy
VAMPIRE = "🧛" #vampire
MAN_VAMPIRE = "🧛‍♂️" #man vampire
WOMAN_VAMPIRE = "🧛‍♀️" #woman vampire
MERPERSON = "🧜" #merperson
MERMAN = "🧜‍♂️" #merman
MERMAID = "🧜‍♀️" #mermaid
ELF = "🧝" #elf
MAN_ELF = "🧝‍♂️" #man elf
WOMAN_ELF = "🧝‍♀️" #woman elf
GENIE = "🧞" #genie
MAN_GENIE = "🧞‍♂️" #man genie
WOMAN_GENIE = "🧞‍♀️" #woman genie
ZOMBIE = "🧟" #zombie
MAN_ZOMBIE = "🧟‍♂️" #man zombie
WOMAN_ZOMBIE = "🧟‍♀️" #woman zombie
PERSON_GETTING_MASSAGE = "💆" #person getting massage
MAN_GETTING_MASSAGE = "💆‍♂️" #man getting massage
WOMAN_GETTING_MASSAGE = "💆‍♀️" #woman getting massage
PERSON_GETTING_HAIRCUT = "💇" #person getting haircut
MAN_GETTING_HAIRCUT = "💇‍♂️" #man getting haircut
WOMAN_GETTING_HAIRCUT = "💇‍♀️" #woman getting haircut
PERSON_WALKING = "🚶" #person walking
MAN_WALKING = "🚶‍♂️" #man walking
WOMAN_WALKING = "🚶‍♀️" #woman walking
PERSON_STANDING = "🧍" #⊛ person standing
MAN_STANDING = "🧍‍♂️" #⊛ man standing
WOMAN_STANDING = "🧍‍♀️" #⊛ woman standing
PERSON_KNEELING = "🧎" #⊛ person kneeling
MAN_KNEELING = "🧎‍♂️" #⊛ man kneeling
WOMAN_KNEELING = "🧎‍♀️" #⊛ woman kneeling
MAN_WITH_PROBING_CANE = "👨‍🦯" #⊛ man with probing cane
WOMAN_WITH_PROBING_CANE = "👩‍🦯" #⊛ woman with probing cane
MAN_IN_MOTORIZED_WHEELCHAIR = "👨‍🦼" #⊛ man in motorized wheelchair
WOMAN_IN_MOTORIZED_WHEELCHAIR = "👩‍🦼" #⊛ woman in motorized wheelchair
MAN_IN_MANUAL_WHEELCHAIR = "👨‍🦽" #⊛ man in manual wheelchair
WOMAN_IN_MANUAL_WHEELCHAIR = "👩‍🦽" #⊛ woman in manual wheelchair
PERSON_RUNNING = "🏃" #person running
MAN_RUNNING = "🏃‍♂️" #man running
WOMAN_RUNNING = "🏃‍♀️" #woman running
WOMAN_DANCING = "💃" #woman dancing
MAN_DANCING = "🕺" #man dancing
MAN_IN_SUIT_LEVITATING = "🕴" #man in suit levitating
PEOPLE_WITH_BUNNY_EARS = "👯" #people with bunny ears
MEN_WITH_BUNNY_EARS = "👯‍♂️" #men with bunny ears
WOMEN_WITH_BUNNY_EARS = "👯‍♀️" #women with bunny ears
PERSON_IN_STEAMY_ROOM = "🧖" #person in steamy room
MAN_IN_STEAMY_ROOM = "🧖‍♂️" #man in steamy room
WOMAN_IN_STEAMY_ROOM = "🧖‍♀️" #woman in steamy room
PERSON_CLIMBING = "🧗" #person climbing
MAN_CLIMBING = "🧗‍♂️" #man climbing
WOMAN_CLIMBING = "🧗‍♀️" #woman climbing
PERSON_FENCING = "🤺" #person fencing
HORSE_RACING = "🏇" #horse racing
SKIER = "⛷" #skier
SNOWBOARDER = "🏂" #snowboarder
PERSON_GOLFING = "🏌" #person golfing
MAN_GOLFING = "🏌️‍♂️" #man golfing
WOMAN_GOLFING = "🏌️‍♀️" #woman golfing
PERSON_SURFING = "🏄" #person surfing
MAN_SURFING = "🏄‍♂️" #man surfing
WOMAN_SURFING = "🏄‍♀️" #woman surfing
PERSON_ROWING_BOAT = "🚣" #person rowing boat
MAN_ROWING_BOAT = "🚣‍♂️" #man rowing boat
WOMAN_ROWING_BOAT = "🚣‍♀️" #woman rowing boat
PERSON_SWIMMING = "🏊" #person swimming
MAN_SWIMMING = "🏊‍♂️" #man swimming
WOMAN_SWIMMING = "🏊‍♀️" #woman swimming
PERSON_BOUNCING_BALL = "⛹" #person bouncing ball
MAN_BOUNCING_BALL = "⛹️‍♂️" #man bouncing ball
WOMAN_BOUNCING_BALL = "⛹️‍♀️" #woman bouncing ball
PERSON_LIFTING_WEIGHTS = "🏋" #person lifting weights
MAN_LIFTING_WEIGHTS = "🏋️‍♂️" #man lifting weights
WOMAN_LIFTING_WEIGHTS = "🏋️‍♀️" #woman lifting weights
PERSON_BIKING = "🚴" #person biking
MAN_BIKING = "🚴‍♂️" #man biking
WOMAN_BIKING = "🚴‍♀️" #woman biking
PERSON_MOUNTAIN_BIKING = "🚵" #person mountain biking
MAN_MOUNTAIN_BIKING = "🚵‍♂️" #man mountain biking
WOMAN_MOUNTAIN_BIKING = "🚵‍♀️" #woman mountain biking
PERSON_CARTWHEELING = "🤸" #person cartwheeling
MAN_CARTWHEELING = "🤸‍♂️" #man cartwheeling
WOMAN_CARTWHEELING = "🤸‍♀️" #woman cartwheeling
PEOPLE_WRESTLING = "🤼" #people wrestling
MEN_WRESTLING = "🤼‍♂️" #men wrestling
WOMEN_WRESTLING = "🤼‍♀️" #women wrestling
PERSON_PLAYING_WATER_POLO = "🤽" #person playing water polo
MAN_PLAYING_WATER_POLO = "🤽‍♂️" #man playing water polo
WOMAN_PLAYING_WATER_POLO = "🤽‍♀️" #woman playing water polo
PERSON_PLAYING_HANDBALL = "🤾" #person playing handball
MAN_PLAYING_HANDBALL = "🤾‍♂️" #man playing handball
WOMAN_PLAYING_HANDBALL = "🤾‍♀️" #woman playing handball
PERSON_JUGGLING = "🤹" #person juggling
MAN_JUGGLING = "🤹‍♂️" #man juggling
WOMAN_JUGGLING = "🤹‍♀️" #woman juggling
PERSON_IN_LOTUS_POSITION = "🧘" #person in lotus position
MAN_IN_LOTUS_POSITION = "🧘‍♂️" #man in lotus position
WOMAN_IN_LOTUS_POSITION = "🧘‍♀️" #woman in lotus position
PERSON_TAKING_BATH = "🛀" #person taking bath
PERSON_IN_BED = "🛌" #person in bed
PEOPLE_HOLDING_HANDS = "🧑‍🤝‍🧑" #⊛ people holding hands
WOMEN_HOLDING_HANDS = "👭" #women holding hands
WOMAN_AND_MAN_HOLDING_HANDS = "👫" #woman and man holding hands
MEN_HOLDING_HANDS = "👬" #men holding hands
KISS = "💏" #kiss
KISS_WOMAN_MAN = "👩‍❤️‍💋‍👨" #kiss: woman, man
KISS_MAN_MAN = "👨‍❤️‍💋‍👨" #kiss: man, man
KISS_WOMAN_WOMAN = "👩‍❤️‍💋‍👩" #kiss: woman, woman
COUPLE_WITH_HEART = "💑" #couple with heart
COUPLE_WITH_HEART_WOMAN_MAN = "👩‍❤️‍👨" #couple with heart: woman, man
COUPLE_WITH_HEART_MAN_MAN = "👨‍❤️‍👨" #couple with heart: man, man
COUPLE_WITH_HEART_WOMAN_WOMAN = "👩‍❤️‍👩" #couple with heart: woman, woman
FAMILY = "👪" #family
FAMILY_MAN_WOMAN_BOY = "👨‍👩‍👦" #family: man, woman, boy
FAMILY_MAN_WOMAN_GIRL = "👨‍👩‍👧" #family: man, woman, girl
FAMILY_MAN_WOMAN_GIRL_BOY = "👨‍👩‍👧‍👦" #family: man, woman, girl, boy
FAMILY_MAN_WOMAN_BOY_BOY = "👨‍👩‍👦‍👦" #family: man, woman, boy, boy
FAMILY_MAN_WOMAN_GIRL_GIRL = "👨‍👩‍👧‍👧" #family: man, woman, girl, girl
FAMILY_MAN_MAN_BOY = "👨‍👨‍👦" #family: man, man, boy
FAMILY_MAN_MAN_GIRL = "👨‍👨‍👧" #family: man, man, girl
FAMILY_MAN_MAN_GIRL_BOY = "👨‍👨‍👧‍👦" #family: man, man, girl, boy
FAMILY_MAN_MAN_BOY_BOY = "👨‍👨‍👦‍👦" #family: man, man, boy, boy
FAMILY_MAN_MAN_GIRL_GIRL = "👨‍👨‍👧‍👧" #family: man, man, girl, girl
FAMILY_WOMAN_WOMAN_BOY = "👩‍👩‍👦" #family: woman, woman, boy
FAMILY_WOMAN_WOMAN_GIRL = "👩‍👩‍👧" #family: woman, woman, girl
FAMILY_WOMAN_WOMAN_GIRL_BOY = "👩‍👩‍👧‍👦" #family: woman, woman, girl, boy
FAMILY_WOMAN_WOMAN_BOY_BOY = "👩‍👩‍👦‍👦" #family: woman, woman, boy, boy
FAMILY_WOMAN_WOMAN_GIRL_GIRL = "👩‍👩‍👧‍👧" #family: woman, woman, girl, girl
FAMILY_MAN_BOY = "👨‍👦" #family: man, boy
FAMILY_MAN_BOY_BOY = "👨‍👦‍👦" #family: man, boy, boy
FAMILY_MAN_GIRL = "👨‍👧" #family: man, girl
FAMILY_MAN_GIRL_BOY = "👨‍👧‍👦" #family: man, girl, boy
FAMILY_MAN_GIRL_GIRL = "👨‍👧‍👧" #family: man, girl, girl
FAMILY_WOMAN_BOY = "👩‍👦" #family: woman, boy
FAMILY_WOMAN_BOY_BOY = "👩‍👦‍👦" #family: woman, boy, boy
FAMILY_WOMAN_GIRL = "👩‍👧" #family: woman, girl
FAMILY_WOMAN_GIRL_BOY = "👩‍👧‍👦" #family: woman, girl, boy
FAMILY_WOMAN_GIRL_GIRL = "👩‍👧‍👧" #family: woman, girl, girl
SPEAKING_HEAD = "🗣" #speaking head
BUST_IN_SILHOUETTE = "👤" #bust in silhouette
BUSTS_IN_SILHOUETTE = "👥" #busts in silhouette
FOOTPRINTS = "👣" #footprints
RED_HAIR = "🦰" #red hair
CURLY_HAIR = "🦱" #curly hair
WHITE_HAIR = "🦳" #white hair
BALD = "🦲" #bald
MONKEY_FACE = "🐵" #monkey face
MONKEY = "🐒" #monkey
GORILLA = "🦍" #gorilla
ORANGUTAN = "🦧" #⊛ orangutan
DOG_FACE = "🐶" #dog face
DOG = "🐕" #dog
GUIDE_DOG = "🦮" #⊛ guide dog
SERVICE_DOG = "🐕‍🦺" #⊛ service dog
POODLE = "🐩" #poodle
WOLF = "🐺" #wolf
FOX = "🦊" #fox
RACCOON = "🦝" #raccoon
CAT_FACE = "🐱" #cat face
CAT = "🐈" #cat
LION = "🦁" #lion
TIGER_FACE = "🐯" #tiger face
TIGER = "🐅" #tiger
LEOPARD = "🐆" #leopard
HORSE_FACE = "🐴" #horse face
HORSE = "🐎" #horse
UNICORN = "🦄" #unicorn
ZEBRA = "🦓" #zebra
DEER = "🦌" #deer
COW_FACE = "🐮" #cow face
OX = "🐂" #ox
WATER_BUFFALO = "🐃" #water buffalo
COW = "🐄" #cow
PIG_FACE = "🐷" #pig face
PIG = "🐖" #pig
BOAR = "🐗" #boar
PIG_NOSE = "🐽" #pig nose
RAM = "🐏" #ram
EWE = "🐑" #ewe
GOAT = "🐐" #goat
CAMEL = "🐪" #camel
TWO_HUMP_CAMEL = "🐫" #two-hump camel
LLAMA = "🦙" #llama
GIRAFFE = "🦒" #giraffe
ELEPHANT = "🐘" #elephant
RHINOCEROS = "🦏" #rhinoceros
HIPPOPOTAMUS = "🦛" #hippopotamus
MOUSE_FACE = "🐭" #mouse face
MOUSE = "🐁" #mouse
RAT = "🐀" #rat
HAMSTER = "🐹" #hamster
RABBIT_FACE = "🐰" #rabbit face
RABBIT = "🐇" #rabbit
CHIPMUNK = "🐿" #chipmunk
HEDGEHOG = "🦔" #hedgehog
BAT = "🦇" #bat
BEAR = "🐻" #bear
KOALA = "🐨" #koala
PANDA = "🐼" #panda
SLOTH = "🦥" #⊛ sloth
OTTER = "🦦" #⊛ otter
SKUNK = "🦨" #⊛ skunk
KANGAROO = "🦘" #kangaroo
BADGER = "🦡" #badger
PAW_PRINTS = "🐾" #paw prints
TURKEY = "🦃" #turkey
CHICKEN = "🐔" #chicken
ROOSTER = "🐓" #rooster
HATCHING_CHICK = "🐣" #hatching chick
BABY_CHICK = "🐤" #baby chick
FRONT_FACING_BABY_CHICK = "🐥" #front-facing baby chick
BIRD = "🐦" #bird
PENGUIN = "🐧" #penguin
DOVE = "🕊" #dove
EAGLE = "🦅" #eagle
DUCK = "🦆" #duck
SWAN = "🦢" #swan
OWL = "🦉" #owl
FLAMINGO = "🦩" #⊛ flamingo
PEACOCK = "🦚" #peacock
PARROT = "🦜" #parrot
FROG = "🐸" #frog
CROCODILE = "🐊" #crocodile
TURTLE = "🐢" #turtle
LIZARD = "🦎" #lizard
SNAKE = "🐍" #snake
DRAGON_FACE = "🐲" #dragon face
DRAGON = "🐉" #dragon
SAUROPOD = "🦕" #sauropod
T_REX = "🦖" #T-Rex
SPOUTING_WHALE = "🐳" #spouting whale
WHALE = "🐋" #whale
DOLPHIN = "🐬" #dolphin
FISH = "🐟" #fish
TROPICAL_FISH = "🐠" #tropical fish
BLOWFISH = "🐡" #blowfish
SHARK = "🦈" #shark
OCTOPUS = "🐙" #octopus
SPIRAL_SHELL = "🐚" #spiral shell
SNAIL = "🐌" #snail
BUTTERFLY = "🦋" #butterfly
BUG = "🐛" #bug
ANT = "🐜" #ant
HONEYBEE = "🐝" #honeybee
LADY_BEETLE = "🐞" #lady beetle
CRICKET = "🦗" #cricket
SPIDER = "🕷" #spider
SPIDER_WEB = "🕸" #spider web
SCORPION = "🦂" #scorpion
MOSQUITO = "🦟" #mosquito
MICROBE = "🦠" #microbe
BOUQUET = "💐" #bouquet
CHERRY_BLOSSOM = "🌸" #cherry blossom
WHITE_FLOWER = "💮" #white flower
ROSETTE = "🏵" #rosette
ROSE = "🌹" #rose
WILTED_FLOWER = "🥀" #wilted flower
HIBISCUS = "🌺" #hibiscus
SUNFLOWER = "🌻" #sunflower
BLOSSOM = "🌼" #blossom
TULIP = "🌷" #tulip
SEEDLING = "🌱" #seedling
EVERGREEN_TREE = "🌲" #evergreen tree
DECIDUOUS_TREE = "🌳" #deciduous tree
PALM_TREE = "🌴" #palm tree
CACTUS = "🌵" #cactus
SHEAF_OF_RICE = "🌾" #sheaf of rice
HERB = "🌿" #herb
SHAMROCK = "☘" #shamrock
FOUR_LEAF_CLOVER = "🍀" #four leaf clover
MAPLE_LEAF = "🍁" #maple leaf
FALLEN_LEAF = "🍂" #fallen leaf
LEAF_FLUTTERING_IN_WIND = "🍃" #leaf fluttering in wind
GRAPES = "🍇" #grapes
MELON = "🍈" #melon
WATERMELON = "🍉" #watermelon
TANGERINE = "🍊" #tangerine
LEMON = "🍋" #lemon
BANANA = "🍌" #banana
PINEAPPLE = "🍍" #pineapple
MANGO = "🥭" #mango
RED_APPLE = "🍎" #red apple
GREEN_APPLE = "🍏" #green apple
PEAR = "🍐" #pear
PEACH = "🍑" #peach
CHERRIES = "🍒" #cherries
STRAWBERRY = "🍓" #strawberry
KIWI_FRUIT = "🥝" #kiwi fruit
TOMATO = "🍅" #tomato
COCONUT = "🥥" #coconut
AVOCADO = "🥑" #avocado
EGGPLANT = "🍆" #eggplant
POTATO = "🥔" #potato
CARROT = "🥕" #carrot
EAR_OF_CORN = "🌽" #ear of corn
HOT_PEPPER = "🌶" #hot pepper
CUCUMBER = "🥒" #cucumber
LEAFY_GREEN = "🥬" #leafy green
BROCCOLI = "🥦" #broccoli
GARLIC = "🧄" #⊛ garlic
ONION = "🧅" #⊛ onion
MUSHROOM = "🍄" #mushroom
PEANUTS = "🥜" #peanuts
CHESTNUT = "🌰" #chestnut
BREAD = "🍞" #bread
CROISSANT = "🥐" #croissant
BAGUETTE_BREAD = "🥖" #baguette bread
PRETZEL = "🥨" #pretzel
BAGEL = "🥯" #bagel
PANCAKES = "🥞" #pancakes
WAFFLE = "🧇" #⊛ waffle
CHEESE_WEDGE = "🧀" #cheese wedge
MEAT_ON_BONE = "🍖" #meat on bone
POULTRY_LEG = "🍗" #poultry leg
CUT_OF_MEAT = "🥩" #cut of meat
BACON = "🥓" #bacon
HAMBURGER = "🍔" #hamburger
FRENCH_FRIES = "🍟" #french fries
PIZZA = "🍕" #pizza
HOT_DOG = "🌭" #hot dog
SANDWICH = "🥪" #sandwich
TACO = "🌮" #taco
BURRITO = "🌯" #burrito
STUFFED_FLATBREAD = "🥙" #stuffed flatbread
FALAFEL = "🧆" #⊛ falafel
EGG = "🥚" #egg
COOKING = "🍳" #cooking
SHALLOW_PAN_OF_FOOD = "🥘" #shallow pan of food
POT_OF_FOOD = "🍲" #pot of food
BOWL_WITH_SPOON = "🥣" #bowl with spoon
GREEN_SALAD = "🥗" #green salad
POPCORN = "🍿" #popcorn
BUTTER = "🧈" #⊛ butter
SALT = "🧂" #salt
CANNED_FOOD = "🥫" #canned food
BENTO_BOX = "🍱" #bento box
RICE_CRACKER = "🍘" #rice cracker
RICE_BALL = "🍙" #rice ball
COOKED_RICE = "🍚" #cooked rice
CURRY_RICE = "🍛" #curry rice
STEAMING_BOWL = "🍜" #steaming bowl
SPAGHETTI = "🍝" #spaghetti
ROASTED_SWEET_POTATO = "🍠" #roasted sweet potato
ODEN = "🍢" #oden
SUSHI = "🍣" #sushi
FRIED_SHRIMP = "🍤" #fried shrimp
FISH_CAKE_WITH_SWIRL = "🍥" #fish cake with swirl
MOON_CAKE = "🥮" #moon cake
DANGO = "🍡" #dango
DUMPLING = "🥟" #dumpling
FORTUNE_COOKIE = "🥠" #fortune cookie
TAKEOUT_BOX = "🥡" #takeout box
CRAB = "🦀" #crab
LOBSTER = "🦞" #lobster
SHRIMP = "🦐" #shrimp
SQUID = "🦑" #squid
OYSTER = "🦪" #⊛ oyster
SOFT_ICE_CREAM = "🍦" #soft ice cream
SHAVED_ICE = "🍧" #shaved ice
ICE_CREAM = "🍨" #ice cream
DOUGHNUT = "🍩" #doughnut
COOKIE = "🍪" #cookie
BIRTHDAY_CAKE = "🎂" #birthday cake
SHORTCAKE = "🍰" #shortcake
CUPCAKE = "🧁" #cupcake
PIE = "🥧" #pie
CHOCOLATE_BAR = "🍫" #chocolate bar
CANDY = "🍬" #candy
LOLLIPOP = "🍭" #lollipop
CUSTARD = "🍮" #custard
HONEY_POT = "🍯" #honey pot
BABY_BOTTLE = "🍼" #baby bottle
GLASS_OF_MILK = "🥛" #glass of milk
HOT_BEVERAGE = "☕" #hot beverage
TEACUP_WITHOUT_HANDLE = "🍵" #teacup without handle
SAKE = "🍶" #sake
BOTTLE_WITH_POPPING_CORK = "🍾" #bottle with popping cork
WINE_GLASS = "🍷" #wine glass
COCKTAIL_GLASS = "🍸" #cocktail glass
TROPICAL_DRINK = "🍹" #tropical drink
BEER_MUG = "🍺" #beer mug
CLINKING_BEER_MUGS = "🍻" #clinking beer mugs
CLINKING_GLASSES = "🥂" #clinking glasses
TUMBLER_GLASS = "🥃" #tumbler glass
CUP_WITH_STRAW = "🥤" #cup with straw
BEVERAGE_BOX = "🧃" #⊛ beverage box
MATE = "🧉" #⊛ mate
ICE_CUBE = "🧊" #⊛ ice cube
CHOPSTICKS = "🥢" #chopsticks
FORK_AND_KNIFE_WITH_PLATE = "🍽" #fork and knife with plate
FORK_AND_KNIFE = "🍴" #fork and knife
SPOON = "🥄" #spoon
KITCHEN_KNIFE = "🔪" #kitchen knife
AMPHORA = "🏺" #amphora
GLOBE_SHOWING_EUROPE_AFRICA = "🌍" #globe showing Europe-Africa
GLOBE_SHOWING_AMERICAS = "🌎" #globe showing Americas
GLOBE_SHOWING_ASIA_AUSTRALIA = "🌏" #globe showing Asia-Australia
GLOBE_WITH_MERIDIANS = "🌐" #globe with meridians
WORLD_MAP = "🗺" #world map
MAP_OF_JAPAN = "🗾" #map of Japan
COMPASS = "🧭" #compass
SNOW_CAPPED_MOUNTAIN = "🏔" #snow-capped mountain
MOUNTAIN = "⛰" #mountain
VOLCANO = "🌋" #volcano
MOUNT_FUJI = "🗻" #mount fuji
CAMPING = "🏕" #camping
BEACH_WITH_UMBRELLA = "🏖" #beach with umbrella
DESERT = "🏜" #desert
DESERT_ISLAND = "🏝" #desert island
NATIONAL_PARK = "🏞" #national park
STADIUM = "🏟" #stadium
CLASSICAL_BUILDING = "🏛" #classical building
BUILDING_CONSTRUCTION = "🏗" #building construction
BRICK = "🧱" #brick
HOUSES = "🏘" #houses
DERELICT_HOUSE = "🏚" #derelict house
HOUSE = "🏠" #house
HOUSE_WITH_GARDEN = "🏡" #house with garden
OFFICE_BUILDING = "🏢" #office building
JAPANESE_POST_OFFICE = "🏣" #Japanese post office
POST_OFFICE = "🏤" #post office
HOSPITAL = "🏥" #hospital
BANK = "🏦" #bank
HOTEL = "🏨" #hotel
LOVE_HOTEL = "🏩" #love hotel
CONVENIENCE_STORE = "🏪" #convenience store
SCHOOL = "🏫" #school
DEPARTMENT_STORE = "🏬" #department store
FACTORY = "🏭" #factory
JAPANESE_CASTLE = "🏯" #Japanese castle
CASTLE = "🏰" #castle
WEDDING = "💒" #wedding
TOKYO_TOWER = "🗼" #Tokyo tower
STATUE_OF_LIBERTY = "🗽" #Statue of Liberty
CHURCH = "⛪" #church
MOSQUE = "🕌" #mosque
HINDU_TEMPLE = "🛕" #⊛ hindu temple
SYNAGOGUE = "🕍" #synagogue
SHINTO_SHRINE = "⛩" #shinto shrine
KAABA = "🕋" #kaaba
FOUNTAIN = "⛲" #fountain
TENT = "⛺" #tent
FOGGY = "🌁" #foggy
NIGHT_WITH_STARS = "🌃" #night with stars
CITYSCAPE = "🏙" #cityscape
SUNRISE_OVER_MOUNTAINS = "🌄" #sunrise over mountains
SUNRISE = "🌅" #sunrise
CITYSCAPE_AT_DUSK = "🌆" #cityscape at dusk
SUNSET = "🌇" #sunset
BRIDGE_AT_NIGHT = "🌉" #bridge at night
HOT_SPRINGS = "♨" #hot springs
CAROUSEL_HORSE = "🎠" #carousel horse
FERRIS_WHEEL = "🎡" #ferris wheel
ROLLER_COASTER = "🎢" #roller coaster
BARBER_POLE = "💈" #barber pole
CIRCUS_TENT = "🎪" #circus tent
LOCOMOTIVE = "🚂" #locomotive
RAILWAY_CAR = "🚃" #railway car
HIGH_SPEED_TRAIN = "🚄" #high-speed train
BULLET_TRAIN = "🚅" #bullet train
TRAIN = "🚆" #train
METRO = "🚇" #metro
LIGHT_RAIL = "🚈" #light rail
STATION = "🚉" #station
TRAM = "🚊" #tram
MONORAIL = "🚝" #monorail
MOUNTAIN_RAILWAY = "🚞" #mountain railway
TRAM_CAR = "🚋" #tram car
BUS = "🚌" #bus
ONCOMING_BUS = "🚍" #oncoming bus
TROLLEYBUS = "🚎" #trolleybus
MINIBUS = "🚐" #minibus
AMBULANCE = "🚑" #ambulance
FIRE_ENGINE = "🚒" #fire engine
POLICE_CAR = "🚓" #police car
ONCOMING_POLICE_CAR = "🚔" #oncoming police car
TAXI = "🚕" #taxi
ONCOMING_TAXI = "🚖" #oncoming taxi
AUTOMOBILE = "🚗" #automobile
ONCOMING_AUTOMOBILE = "🚘" #oncoming automobile
SPORT_UTILITY_VEHICLE = "🚙" #sport utility vehicle
DELIVERY_TRUCK = "🚚" #delivery truck
ARTICULATED_LORRY = "🚛" #articulated lorry
TRACTOR = "🚜" #tractor
RACING_CAR = "🏎" #racing car
MOTORCYCLE = "🏍" #motorcycle
MOTOR_SCOOTER = "🛵" #motor scooter
MANUAL_WHEELCHAIR = "🦽" #⊛ manual wheelchair
MOTORIZED_WHEELCHAIR = "🦼" #⊛ motorized wheelchair
AUTO_RICKSHAW = "🛺" #⊛ auto rickshaw
BICYCLE = "🚲" #bicycle
KICK_SCOOTER = "🛴" #kick scooter
SKATEBOARD = "🛹" #skateboard
BUS_STOP = "🚏" #bus stop
MOTORWAY = "🛣" #motorway
RAILWAY_TRACK = "🛤" #railway track
OIL_DRUM = "🛢" #oil drum
FUEL_PUMP = "⛽" #fuel pump
POLICE_CAR_LIGHT = "🚨" #police car light
HORIZONTAL_TRAFFIC_LIGHT = "🚥" #horizontal traffic light
VERTICAL_TRAFFIC_LIGHT = "🚦" #vertical traffic light
STOP_SIGN = "🛑" #stop sign
CONSTRUCTION = "🚧" #construction
ANCHOR = "⚓" #anchor
SAILBOAT = "⛵" #sailboat
CANOE = "🛶" #canoe
SPEEDBOAT = "🚤" #speedboat
PASSENGER_SHIP = "🛳" #passenger ship
FERRY = "⛴" #ferry
MOTOR_BOAT = "🛥" #motor boat
SHIP = "🚢" #ship
AIRPLANE = "✈" #airplane
SMALL_AIRPLANE = "🛩" #small airplane
AIRPLANE_DEPARTURE = "🛫" #airplane departure
AIRPLANE_ARRIVAL = "🛬" #airplane arrival
PARACHUTE = "🪂" #⊛ parachute
SEAT = "💺" #seat
HELICOPTER = "🚁" #helicopter
SUSPENSION_RAILWAY = "🚟" #suspension railway
MOUNTAIN_CABLEWAY = "🚠" #mountain cableway
AERIAL_TRAMWAY = "🚡" #aerial tramway
SATELLITE = "🛰" #satellite
ROCKET = "🚀" #rocket
FLYING_SAUCER = "🛸" #flying saucer
BELLHOP_BELL = "🛎" #bellhop bell
LUGGAGE = "🧳" #luggage
HOURGLASS_DONE = "⌛" #hourglass done
HOURGLASS_NOT_DONE = "⏳" #hourglass not done
WATCH = "⌚" #watch
ALARM_CLOCK = "⏰" #alarm clock
STOPWATCH = "⏱" #stopwatch
TIMER_CLOCK = "⏲" #timer clock
MANTELPIECE_CLOCK = "🕰" #mantelpiece clock
TWELVE_O_CLOCK = "🕛" #twelve o’clock
TWELVE_THIRTY = "🕧" #twelve-thirty
ONE_O_CLOCK = "🕐" #one o’clock
ONE_THIRTY = "🕜" #one-thirty
TWO_O_CLOCK = "🕑" #two o’clock
TWO_THIRTY = "🕝" #two-thirty
THREE_O_CLOCK = "🕒" #three o’clock
THREE_THIRTY = "🕞" #three-thirty
FOUR_O_CLOCK = "🕓" #four o’clock
FOUR_THIRTY = "🕟" #four-thirty
FIVE_O_CLOCK = "🕔" #five o’clock
FIVE_THIRTY = "🕠" #five-thirty
SIX_O_CLOCK = "🕕" #six o’clock
SIX_THIRTY = "🕡" #six-thirty
SEVEN_O_CLOCK = "🕖" #seven o’clock
SEVEN_THIRTY = "🕢" #seven-thirty
EIGHT_O_CLOCK = "🕗" #eight o’clock
EIGHT_THIRTY = "🕣" #eight-thirty
NINE_O_CLOCK = "🕘" #nine o’clock
NINE_THIRTY = "🕤" #nine-thirty
TEN_O_CLOCK = "🕙" #ten o’clock
TEN_THIRTY = "🕥" #ten-thirty
ELEVEN_O_CLOCK = "🕚" #eleven o’clock
ELEVEN_THIRTY = "🕦" #eleven-thirty
NEW_MOON = "🌑" #new moon
WAXING_CRESCENT_MOON = "🌒" #waxing crescent moon
FIRST_QUARTER_MOON = "🌓" #first quarter moon
WAXING_GIBBOUS_MOON = "🌔" #waxing gibbous moon
FULL_MOON = "🌕" #full moon
WANING_GIBBOUS_MOON = "🌖" #waning gibbous moon
LAST_QUARTER_MOON = "🌗" #last quarter moon
WANING_CRESCENT_MOON = "🌘" #waning crescent moon
CRESCENT_MOON = "🌙" #crescent moon
NEW_MOON_FACE = "🌚" #new moon face
FIRST_QUARTER_MOON_FACE = "🌛" #first quarter moon face
LAST_QUARTER_MOON_FACE = "🌜" #last quarter moon face
THERMOMETER = "🌡" #thermometer
SUN = "☀" #sun
FULL_MOON_FACE = "🌝" #full moon face
SUN_WITH_FACE = "🌞" #sun with face
RINGED_PLANET = "🪐" #⊛ ringed planet
STAR = "⭐" #star
GLOWING_STAR = "🌟" #glowing star
SHOOTING_STAR = "🌠" #shooting star
MILKY_WAY = "🌌" #milky way
CLOUD = "☁" #cloud
SUN_BEHIND_CLOUD = "⛅" #sun behind cloud
CLOUD_WITH_LIGHTNING_AND_RAIN = "⛈" #cloud with lightning and rain
SUN_BEHIND_SMALL_CLOUD = "🌤" #sun behind small cloud
SUN_BEHIND_LARGE_CLOUD = "🌥" #sun behind large cloud
SUN_BEHIND_RAIN_CLOUD = "🌦" #sun behind rain cloud
CLOUD_WITH_RAIN = "🌧" #cloud with rain
CLOUD_WITH_SNOW = "🌨" #cloud with snow
CLOUD_WITH_LIGHTNING = "🌩" #cloud with lightning
TORNADO = "🌪" #tornado
FOG = "🌫" #fog
WIND_FACE = "🌬" #wind face
CYCLONE = "🌀" #cyclone
RAINBOW = "🌈" #rainbow
CLOSED_UMBRELLA = "🌂" #closed umbrella
UMBRELLA = "☂" #umbrella
UMBRELLA_WITH_RAIN_DROPS = "☔" #umbrella with rain drops
UMBRELLA_ON_GROUND = "⛱" #umbrella on ground
HIGH_VOLTAGE = "⚡" #high voltage
SNOWFLAKE = "❄" #snowflake
SNOWMAN = "☃" #snowman
SNOWMAN_WITHOUT_SNOW = "⛄" #snowman without snow
COMET = "☄" #comet
FIRE = "🔥" #fire
DROPLET = "💧" #droplet
WATER_WAVE = "🌊" #water wave
JACK_O_LANTERN = "🎃" #jack-o-lantern
CHRISTMAS_TREE = "🎄" #Christmas tree
FIREWORKS = "🎆" #fireworks
SPARKLER = "🎇" #sparkler
FIRECRACKER = "🧨" #firecracker
SPARKLES = "✨" #sparkles
BALLOON = "🎈" #balloon
PARTY_POPPER = "🎉" #party popper
CONFETTI_BALL = "🎊" #confetti ball
TANABATA_TREE = "🎋" #tanabata tree
PINE_DECORATION = "🎍" #pine decoration
JAPANESE_DOLLS = "🎎" #Japanese dolls
CARP_STREAMER = "🎏" #carp streamer
WIND_CHIME = "🎐" #wind chime
MOON_VIEWING_CEREMONY = "🎑" #moon viewing ceremony
RED_ENVELOPE = "🧧" #red envelope
RIBBON = "🎀" #ribbon
WRAPPED_GIFT = "🎁" #wrapped gift
REMINDER_RIBBON = "🎗" #reminder ribbon
ADMISSION_TICKETS = "🎟" #admission tickets
TICKET = "🎫" #ticket
MILITARY_MEDAL = "🎖" #military medal
TROPHY = "🏆" #trophy
SPORTS_MEDAL = "🏅" #sports medal
FIRST_PLACE_MEDAL = "🥇" #1st place medal
SECOND_PLACE_MEDAL = "🥈" #2nd place medal
THIRD_PLACE_MEDAL = "🥉" #3rd place medal
SOCCER_BALL = "⚽" #soccer ball
BASEBALL = "⚾" #baseball
SOFTBALL = "🥎" #softball
BASKETBALL = "🏀" #basketball
VOLLEYBALL = "🏐" #volleyball
AMERICAN_FOOTBALL = "🏈" #american football
RUGBY_FOOTBALL = "🏉" #rugby football
TENNIS = "🎾" #tennis
FLYING_DISC = "🥏" #flying disc
BOWLING = "🎳" #bowling
CRICKET_GAME = "🏏" #cricket game
FIELD_HOCKEY = "🏑" #field hockey
ICE_HOCKEY = "🏒" #ice hockey
LACROSSE = "🥍" #lacrosse
PING_PONG = "🏓" #ping pong
BADMINTON = "🏸" #badminton
BOXING_GLOVE = "🥊" #boxing glove
MARTIAL_ARTS_UNIFORM = "🥋" #martial arts uniform
GOAL_NET = "🥅" #goal net
FLAG_IN_HOLE = "⛳" #flag in hole
ICE_SKATE = "⛸" #ice skate
FISHING_POLE = "🎣" #fishing pole
DIVING_MASK = "🤿" #⊛ diving mask
RUNNING_SHIRT = "🎽" #running shirt
SKIS = "🎿" #skis
SLED = "🛷" #sled
CURLING_STONE = "🥌" #curling stone
DIRECT_HIT = "🎯" #direct hit
YO_YO = "🪀" #⊛ yo-yo
KITE = "🪁" #⊛ kite
POOL_8_BALL = "🎱" #pool 8 ball
CRYSTAL_BALL = "🔮" #crystal ball
NAZAR_AMULET = "🧿" #nazar amulet
VIDEO_GAME = "🎮" #video game
JOYSTICK = "🕹" #joystick
SLOT_MACHINE = "🎰" #slot machine
GAME_DIE = "🎲" #game die
PUZZLE_PIECE = "🧩" #puzzle piece
TEDDY_BEAR = "🧸" #teddy bear
SPADE_SUIT = "♠" #spade suit
HEART_SUIT = "♥" #heart suit
DIAMOND_SUIT = "♦" #diamond suit
CLUB_SUIT = "♣" #club suit
CHESS_PAWN = "♟" #chess pawn
JOKER = "🃏" #joker
MAHJONG_RED_DRAGON = "🀄" #mahjong red dragon
FLOWER_PLAYING_CARDS = "🎴" #flower playing cards
PERFORMING_ARTS = "🎭" #performing arts
FRAMED_PICTURE = "🖼" #framed picture
ARTIST_PALETTE = "🎨" #artist palette
THREAD = "🧵" #thread
YARN = "🧶" #yarn
GLASSES = "👓" #glasses
SUNGLASSES = "🕶" #sunglasses
GOGGLES = "🥽" #goggles
LAB_COAT = "🥼" #lab coat
SAFETY_VEST = "🦺" #⊛ safety vest
NECKTIE = "👔" #necktie
T_SHIRT = "👕" #t-shirt
JEANS = "👖" #jeans
SCARF = "🧣" #scarf
GLOVES = "🧤" #gloves
COAT = "🧥" #coat
SOCKS = "🧦" #socks
DRESS = "👗" #dress
KIMONO = "👘" #kimono
SARI = "🥻" #⊛ sari
ONE_PIECE_SWIMSUIT = "🩱" #⊛ one-piece swimsuit
BRIEFS = "🩲" #⊛ briefs
SHORTS = "🩳" #⊛ shorts
BIKINI = "👙" #bikini
WOMAN_S_CLOTHES = "👚" #woman’s clothes
PURSE = "👛" #purse
HANDBAG = "👜" #handbag
CLUTCH_BAG = "👝" #clutch bag
SHOPPING_BAGS = "🛍" #shopping bags
BACKPACK = "🎒" #backpack
MAN_S_SHOE = "👞" #man’s shoe
RUNNING_SHOE = "👟" #running shoe
HIKING_BOOT = "🥾" #hiking boot
FLAT_SHOE = "🥿" #flat shoe
HIGH_HEELED_SHOE = "👠" #high-heeled shoe
WOMAN_S_SANDAL = "👡" #woman’s sandal
BALLET_SHOES = "🩰" #⊛ ballet shoes
WOMAN_S_BOOT = "👢" #woman’s boot
CROWN = "👑" #crown
WOMAN_S_HAT = "👒" #woman’s hat
TOP_HAT = "🎩" #top hat
GRADUATION_CAP = "🎓" #graduation cap
BILLED_CAP = "🧢" #billed cap
RESCUE_WORKER_S_HELMET = "⛑" #rescue worker’s helmet
PRAYER_BEADS = "📿" #prayer beads
LIPSTICK = "💄" #lipstick
RING = "💍" #ring
GEM_STONE = "💎" #gem stone
MUTED_SPEAKER = "🔇" #muted speaker
SPEAKER_LOW_VOLUME = "🔈" #speaker low volume
SPEAKER_MEDIUM_VOLUME = "🔉" #speaker medium volume
SPEAKER_HIGH_VOLUME = "🔊" #speaker high volume
LOUDSPEAKER = "📢" #loudspeaker
MEGAPHONE = "📣" #megaphone
POSTAL_HORN = "📯" #postal horn
BELL = "🔔" #bell
BELL_WITH_SLASH = "🔕" #bell with slash
MUSICAL_SCORE = "🎼" #musical score
MUSICAL_NOTE = "🎵" #musical note
MUSICAL_NOTES = "🎶" #musical notes
STUDIO_MICROPHONE = "🎙" #studio microphone
LEVEL_SLIDER = "🎚" #level slider
CONTROL_KNOBS = "🎛" #control knobs
MICROPHONE = "🎤" #microphone
HEADPHONE = "🎧" #headphone
RADIO = "📻" #radio
SAXOPHONE = "🎷" #saxophone
GUITAR = "🎸" #guitar
MUSICAL_KEYBOARD = "🎹" #musical keyboard
TRUMPET = "🎺" #trumpet
VIOLIN = "🎻" #violin
BANJO = "🪕" #⊛ banjo
DRUM = "🥁" #drum
MOBILE_PHONE = "📱" #mobile phone
MOBILE_PHONE_WITH_ARROW = "📲" #mobile phone with arrow
TELEPHONE = "☎" #telephone
TELEPHONE_RECEIVER = "📞" #telephone receiver
PAGER = "📟" #pager
FAX_MACHINE = "📠" #fax machine
BATTERY = "🔋" #battery
ELECTRIC_PLUG = "🔌" #electric plug
LAPTOP_COMPUTER = "💻" #laptop computer
DESKTOP_COMPUTER = "🖥" #desktop computer
PRINTER = "🖨" #printer
KEYBOARD = "⌨" #keyboard
COMPUTER_MOUSE = "🖱" #computer mouse
TRACKBALL = "🖲" #trackball
COMPUTER_DISK = "💽" #computer disk
FLOPPY_DISK = "💾" #floppy disk
OPTICAL_DISK = "💿" #optical disk
DVD = "📀" #dvd
ABACUS = "🧮" #abacus
MOVIE_CAMERA = "🎥" #movie camera
FILM_FRAMES = "🎞" #film frames
FILM_PROJECTOR = "📽" #film projector
CLAPPER_BOARD = "🎬" #clapper board
TELEVISION = "📺" #television
CAMERA = "📷" #camera
CAMERA_WITH_FLASH = "📸" #camera with flash
VIDEO_CAMERA = "📹" #video camera
VIDEOCASSETTE = "📼" #videocassette
MAGNIFYING_GLASS_TILTED_LEFT = "🔍" #magnifying glass tilted left
MAGNIFYING_GLASS_TILTED_RIGHT = "🔎" #magnifying glass tilted right
CANDLE = "🕯" #candle
LIGHT_BULB = "💡" #light bulb
FLASHLIGHT = "🔦" #flashlight
RED_PAPER_LANTERN = "🏮" #red paper lantern
DIYA_LAMP = "🪔" #⊛ diya lamp
NOTEBOOK_WITH_DECORATIVE_COVER = "📔" #notebook with decorative cover
CLOSED_BOOK = "📕" #closed book
OPEN_BOOK = "📖" #open book
GREEN_BOOK = "📗" #green book
BLUE_BOOK = "📘" #blue book
ORANGE_BOOK = "📙" #orange book
BOOKS = "📚" #books
NOTEBOOK = "📓" #notebook
LEDGER = "📒" #ledger
PAGE_WITH_CURL = "📃" #page with curl
SCROLL = "📜" #scroll
PAGE_FACING_UP = "📄" #page facing up
NEWSPAPER = "📰" #newspaper
ROLLED_UP_NEWSPAPER = "🗞" #rolled-up newspaper
BOOKMARK_TABS = "📑" #bookmark tabs
BOOKMARK = "🔖" #bookmark
LABEL = "🏷" #label
MONEY_BAG = "💰" #money bag
YEN_BANKNOTE = "💴" #yen banknote
DOLLAR_BANKNOTE = "💵" #dollar banknote
EURO_BANKNOTE = "💶" #euro banknote
POUND_BANKNOTE = "💷" #pound banknote
MONEY_WITH_WINGS = "💸" #money with wings
CREDIT_CARD = "💳" #credit card
RECEIPT = "🧾" #receipt
CHART_INCREASING_WITH_YEN = "💹" #chart increasing with yen
CURRENCY_EXCHANGE = "💱" #currency exchange
HEAVY_DOLLAR_SIGN = "💲" #heavy dollar sign
ENVELOPE = "✉" #envelope
E_MAIL = "📧" #e-mail
INCOMING_ENVELOPE = "📨" #incoming envelope
ENVELOPE_WITH_ARROW = "📩" #envelope with arrow
OUTBOX_TRAY = "📤" #outbox tray
INBOX_TRAY = "📥" #inbox tray
PACKAGE = "📦" #package
CLOSED_MAILBOX_WITH_RAISED_FLAG = "📫" #closed mailbox with raised flag
CLOSED_MAILBOX_WITH_LOWERED_FLAG = "📪" #closed mailbox with lowered flag
OPEN_MAILBOX_WITH_RAISED_FLAG = "📬" #open mailbox with raised flag
OPEN_MAILBOX_WITH_LOWERED_FLAG = "📭" #open mailbox with lowered flag
POSTBOX = "📮" #postbox
BALLOT_BOX_WITH_BALLOT = "🗳" #ballot box with ballot
PENCIL = "✏" #pencil
BLACK_NIB = "✒" #black nib
FOUNTAIN_PEN = "🖋" #fountain pen
PEN = "🖊" #pen
PAINTBRUSH = "🖌" #paintbrush
CRAYON = "🖍" #crayon
MEMO = "📝" #memo
BRIEFCASE = "💼" #briefcase
FILE_FOLDER = "📁" #file folder
OPEN_FILE_FOLDER = "📂" #open file folder
CARD_INDEX_DIVIDERS = "🗂" #card index dividers
CALENDAR = "📅" #calendar
TEAR_OFF_CALENDAR = "📆" #tear-off calendar
SPIRAL_NOTEPAD = "🗒" #spiral notepad
SPIRAL_CALENDAR = "🗓" #spiral calendar
CARD_INDEX = "📇" #card index
CHART_INCREASING = "📈" #chart increasing
CHART_DECREASING = "📉" #chart decreasing
BAR_CHART = "📊" #bar chart
CLIPBOARD = "📋" #clipboard
PUSHPIN = "📌" #pushpin
ROUND_PUSHPIN = "📍" #round pushpin
PAPERCLIP = "📎" #paperclip
LINKED_PAPERCLIPS = "🖇" #linked paperclips
STRAIGHT_RULER = "📏" #straight ruler
TRIANGULAR_RULER = "📐" #triangular ruler
SCISSORS = "✂" #scissors
CARD_FILE_BOX = "🗃" #card file box
FILE_CABINET = "🗄" #file cabinet
WASTEBASKET = "🗑" #wastebasket
LOCKED = "🔒" #locked
UNLOCKED = "🔓" #unlocked
LOCKED_WITH_PEN = "🔏" #locked with pen
LOCKED_WITH_KEY = "🔐" #locked with key
KEY = "🔑" #key
OLD_KEY = "🗝" #old key
HAMMER = "🔨" #hammer
AXE = "🪓" #⊛ axe
PICK = "⛏" #pick
HAMMER_AND_PICK = "⚒" #hammer and pick
HAMMER_AND_WRENCH = "🛠" #hammer and wrench
DAGGER = "🗡" #dagger
CROSSED_SWORDS = "⚔" #crossed swords
PISTOL = "🔫" #pistol
BOW_AND_ARROW = "🏹" #bow and arrow
SHIELD = "🛡" #shield
WRENCH = "🔧" #wrench
NUT_AND_BOLT = "🔩" #nut and bolt
GEAR = "⚙" #gear
CLAMP = "🗜" #clamp
BALANCE_SCALE = "⚖" #balance scale
PROBING_CANE = "🦯" #⊛ probing cane
LINK = "🔗" #link
CHAINS = "⛓" #chains
TOOLBOX = "🧰" #toolbox
MAGNET = "🧲" #magnet
ALEMBIC = "⚗" #alembic
TEST_TUBE = "🧪" #test tube
PETRI_DISH = "🧫" #petri dish
DNA = "🧬" #dna
MICROSCOPE = "🔬" #microscope
TELESCOPE = "🔭" #telescope
SATELLITE_ANTENNA = "📡" #satellite antenna
SYRINGE = "💉" #syringe
DROP_OF_BLOOD = "🩸" #⊛ drop of blood
PILL = "💊" #pill
ADHESIVE_BANDAGE = "🩹" #⊛ adhesive bandage
STETHOSCOPE = "🩺" #⊛ stethoscope
DOOR = "🚪" #door
BED = "🛏" #bed
COUCH_AND_LAMP = "🛋" #couch and lamp
CHAIR = "🪑" #⊛ chair
TOILET = "🚽" #toilet
SHOWER = "🚿" #shower
BATHTUB = "🛁" #bathtub
RAZOR = "🪒" #⊛ razor
LOTION_BOTTLE = "🧴" #lotion bottle
SAFETY_PIN = "🧷" #safety pin
BROOM = "🧹" #broom
BASKET = "🧺" #basket
ROLL_OF_PAPER = "🧻" #roll of paper
SOAP = "🧼" #soap
SPONGE = "🧽" #sponge
FIRE_EXTINGUISHER = "🧯" #fire extinguisher
SHOPPING_CART = "🛒" #shopping cart
CIGARETTE = "🚬" #cigarette
COFFIN = "⚰" #coffin
FUNERAL_URN = "⚱" #funeral urn
MOAI = "🗿" #moai
ATM_SIGN = "🏧" #ATM sign
LITTER_IN_BIN_SIGN = "🚮" #litter in bin sign
POTABLE_WATER = "🚰" #potable water
WHEELCHAIR_SYMBOL = "♿" #wheelchair symbol
MEN_S_ROOM = "🚹" #men’s room
WOMEN_S_ROOM = "🚺" #women’s room
RESTROOM = "🚻" #restroom
BABY_SYMBOL = "🚼" #baby symbol
WATER_CLOSET = "🚾" #water closet
PASSPORT_CONTROL = "🛂" #passport control
CUSTOMS = "🛃" #customs
BAGGAGE_CLAIM = "🛄" #baggage claim
LEFT_LUGGAGE = "🛅" #left luggage
WARNING = "⚠" #warning
CHILDREN_CROSSING = "🚸" #children crossing
NO_ENTRY = "⛔" #no entry
PROHIBITED = "🚫" #prohibited
NO_BICYCLES = "🚳" #no bicycles
NO_SMOKING = "🚭" #no smoking
NO_LITTERING = "🚯" #no littering
NON_POTABLE_WATER = "🚱" #non-potable water
NO_PEDESTRIANS = "🚷" #no pedestrians
NO_MOBILE_PHONES = "📵" #no mobile phones
NO_ONE_UNDER_EIGHTEEN = "🔞" #no one under eighteen
RADIOACTIVE = "☢" #radioactive
BIOHAZARD = "☣" #biohazard
UP_ARROW = "⬆" #up arrow
UP_RIGHT_ARROW = "↗" #up-right arrow
RIGHT_ARROW = "➡" #right arrow
DOWN_RIGHT_ARROW = "↘" #down-right arrow
DOWN_ARROW = "⬇" #down arrow
DOWN_LEFT_ARROW = "↙" #down-left arrow
LEFT_ARROW = "⬅" #left arrow
UP_LEFT_ARROW = "↖" #up-left arrow
UP_DOWN_ARROW = "↕" #up-down arrow
LEFT_RIGHT_ARROW = "↔" #left-right arrow
RIGHT_ARROW_CURVING_LEFT = "↩" #right arrow curving left
LEFT_ARROW_CURVING_RIGHT = "↪" #left arrow curving right
RIGHT_ARROW_CURVING_UP = "⤴" #right arrow curving up
RIGHT_ARROW_CURVING_DOWN = "⤵" #right arrow curving down
CLOCKWISE_VERTICAL_ARROWS = "🔃" #clockwise vertical arrows
COUNTERCLOCKWISE_ARROWS_BUTTON = "🔄" #counterclockwise arrows button
BACK_ARROW = "🔙" #BACK arrow
END_ARROW = "🔚" #END arrow
ON_ARROW = "🔛" #ON! arrow
SOON_ARROW = "🔜" #SOON arrow
TOP_ARROW = "🔝" #TOP arrow
PLACE_OF_WORSHIP = "🛐" #place of worship
ATOM_SYMBOL = "⚛" #atom symbol
OM = "🕉" #om
STAR_OF_DAVID = "✡" #star of David
WHEEL_OF_DHARMA = "☸" #wheel of dharma
YIN_YANG = "☯" #yin yang
LATIN_CROSS = "✝" #latin cross
ORTHODOX_CROSS = "☦" #orthodox cross
STAR_AND_CRESCENT = "☪" #star and crescent
PEACE_SYMBOL = "☮" #peace symbol
MENORAH = "🕎" #menorah
DOTTED_SIX_POINTED_STAR = "🔯" #dotted six-pointed star
ARIES = "♈" #Aries
TAURUS = "♉" #Taurus
GEMINI = "♊" #Gemini
CANCER = "♋" #Cancer
LEO = "♌" #Leo
VIRGO = "♍" #Virgo
LIBRA = "♎" #Libra
SCORPIO = "♏" #Scorpio
SAGITTARIUS = "♐" #Sagittarius
CAPRICORN = "♑" #Capricorn
AQUARIUS = "♒" #Aquarius
PISCES = "♓" #Pisces
OPHIUCHUS = "⛎" #Ophiuchus
SHUFFLE_TRACKS_BUTTON = "🔀" #shuffle tracks button
REPEAT_BUTTON = "🔁" #repeat button
REPEAT_SINGLE_BUTTON = "🔂" #repeat single button
PLAY_BUTTON = "▶" #play button
FAST_FORWARD_BUTTON = "⏩" #fast-forward button
NEXT_TRACK_BUTTON = "⏭" #next track button
PLAY_OR_PAUSE_BUTTON = "⏯" #play or pause button
REVERSE_BUTTON = "◀" #reverse button
FAST_REVERSE_BUTTON = "⏪" #fast reverse button
LAST_TRACK_BUTTON = "⏮" #last track button
UPWARDS_BUTTON = "🔼" #upwards button
FAST_UP_BUTTON = "⏫" #fast up button
DOWNWARDS_BUTTON = "🔽" #downwards button
FAST_DOWN_BUTTON = "⏬" #fast down button
PAUSE_BUTTON = "⏸" #pause button
STOP_BUTTON = "⏹" #stop button
RECORD_BUTTON = "⏺" #record button
EJECT_BUTTON = "⏏" #eject button
CINEMA = "🎦" #cinema
DIM_BUTTON = "🔅" #dim button
BRIGHT_BUTTON = "🔆" #bright button
ANTENNA_BARS = "📶" #antenna bars
VIBRATION_MODE = "📳" #vibration mode
MOBILE_PHONE_OFF = "📴" #mobile phone off
FEMALE_SIGN = "♀" #female sign
MALE_SIGN = "♂" #male sign
MEDICAL_SYMBOL = "⚕" #medical symbol
INFINITY = "♾" #infinity
RECYCLING_SYMBOL = "♻" #recycling symbol
FLEUR_DE_LIS = "⚜" #fleur-de-lis
TRIDENT_EMBLEM = "🔱" #trident emblem
NAME_BADGE = "📛" #name badge
JAPANESE_SYMBOL_FOR_BEGINNER = "🔰" #Japanese symbol for beginner
HOLLOW_RED_CIRCLE = "⭕" #hollow red circle
CHECK_MARK_BUTTON = "✅" #check mark button
CHECK_BOX_WITH_CHECK = "☑" #check box with check
CHECK_MARK = "✔" #check mark
MULTIPLICATION_SIGN = "✖" #multiplication sign
CROSS_MARK = "❌" #cross mark
CROSS_MARK_BUTTON = "❎" #cross mark button
PLUS_SIGN = "➕" #plus sign
MINUS_SIGN = "➖" #minus sign
DIVISION_SIGN = "➗" #division sign
CURLY_LOOP = "➰" #curly loop
DOUBLE_CURLY_LOOP = "➿" #double curly loop
PART_ALTERNATION_MARK = "〽" #part alternation mark
EIGHT_SPOKED_ASTERISK = "✳" #eight-spoked asterisk
EIGHT_POINTED_STAR = "✴" #eight-pointed star
SPARKLE = "❇" #sparkle
DOUBLE_EXCLAMATION_MARK = "‼" #double exclamation mark
EXCLAMATION_QUESTION_MARK = "⁉" #exclamation question mark
QUESTION_MARK = "❓" #question mark
WHITE_QUESTION_MARK = "❔" #white question mark
WHITE_EXCLAMATION_MARK = "❕" #white exclamation mark
EXCLAMATION_MARK = "❗" #exclamation mark
WAVY_DASH = "〰" #wavy dash
COPYRIGHT = "©" #copyright
REGISTERED = "®" #registered
TRADE_MARK = "™" #trade mark
KEYCAP_HASH = "#️⃣" #keycap: #
KEYCAP_ASTERISK = "*️⃣" #keycap: *
KEYCAP_0 = "0️⃣" #keycap: 0
KEYCAP_1 = "1️⃣" #keycap: 1
KEYCAP_2 = "2️⃣" #keycap: 2
KEYCAP_3 = "3️⃣" #keycap: 3
KEYCAP_4 = "4️⃣" #keycap: 4
KEYCAP_5 = "5️⃣" #keycap: 5
KEYCAP_6 = "6️⃣" #keycap: 6
KEYCAP_7 = "7️⃣" #keycap: 7
KEYCAP_8 = "8️⃣" #keycap: 8
KEYCAP_9 = "9️⃣" #keycap: 9
KEYCAP_10 = "🔟" #keycap: 10
INPUT_LATIN_UPPERCASE = "🔠" #input latin uppercase
INPUT_LATIN_LOWERCASE = "🔡" #input latin lowercase
INPUT_NUMBERS = "🔢" #input numbers
INPUT_SYMBOLS = "🔣" #input symbols
INPUT_LATIN_LETTERS = "🔤" #input latin letters
A_BUTTON_BLOOD_TYPE = "🅰" #A button (blood type)
AB_BUTTON_BLOOD_TYPE = "🆎" #AB button (blood type)
B_BUTTON_BLOOD_TYPE = "🅱" #B button (blood type)
CL_BUTTON = "🆑" #CL button
COOL_BUTTON = "🆒" #COOL button
FREE_BUTTON = "🆓" #FREE button
INFORMATION = "ℹ" #information
ID_BUTTON = "🆔" #ID button
CIRCLED_M = "Ⓜ" #circled M
NEW_BUTTON = "🆕" #NEW button
NG_BUTTON = "🆖" #NG button
O_BUTTON_BLOOD_TYPE = "🅾" #O button (blood type)
OK_BUTTON = "🆗" #OK button
P_BUTTON = "🅿" #P button
SOS_BUTTON = "🆘" #SOS button
UP_BUTTON = "🆙" #UP! button
VS_BUTTON = "🆚" #VS button
JAPANESE_HERE_BUTTON = "🈁" #Japanese “here” button
JAPANESE_SERVICE_CHARGE_BUTTON = "🈂" #Japanese “service charge” button
JAPANESE_MONTHLY_AMOUNT_BUTTON = "🈷" #Japanese “monthly amount” button
JAPANESE_NOT_FREE_OF_CHARGE_BUTTON = "🈶" #Japanese “not free of charge” button
JAPANESE_RESERVED_BUTTON = "🈯" #Japanese “reserved” button
JAPANESE_BARGAIN_BUTTON = "🉐" #Japanese “bargain” button
JAPANESE_DISCOUNT_BUTTON = "🈹" #Japanese “discount” button
JAPANESE_FREE_OF_CHARGE_BUTTON = "🈚" #Japanese “free of charge” button
JAPANESE_PROHIBITED_BUTTON = "🈲" #Japanese “prohibited” button
JAPANESE_ACCEPTABLE_BUTTON = "🉑" #Japanese “acceptable” button
JAPANESE_APPLICATION_BUTTON = "🈸" #Japanese “application” button
JAPANESE_PASSING_GRADE_BUTTON = "🈴" #Japanese “passing grade” button
JAPANESE_VACANCY_BUTTON = "🈳" #Japanese “vacancy” button
JAPANESE_CONGRATULATIONS_BUTTON = "㊗" #Japanese “congratulations” button
JAPANESE_SECRET_BUTTON = "㊙" #Japanese “secret” button
JAPANESE_OPEN_FOR_BUSINESS_BUTTON = "🈺" #Japanese “open for business” button
JAPANESE_NO_VACANCY_BUTTON = "🈵" #Japanese “no vacancy” button
RED_CIRCLE = "🔴" #red circle
ORANGE_CIRCLE = "🟠" #⊛ orange circle
YELLOW_CIRCLE = "🟡" #⊛ yellow circle
GREEN_CIRCLE = "🟢" #⊛ green circle
BLUE_CIRCLE = "🔵" #blue circle
PURPLE_CIRCLE = "🟣" #⊛ purple circle
BROWN_CIRCLE = "🟤" #⊛ brown circle
BLACK_CIRCLE = "⚫" #black circle
WHITE_CIRCLE = "⚪" #white circle
RED_SQUARE = "🟥" #⊛ red square
ORANGE_SQUARE = "🟧" #⊛ orange square
YELLOW_SQUARE = "🟨" #⊛ yellow square
GREEN_SQUARE = "🟩" #⊛ green square
BLUE_SQUARE = "🟦" #⊛ blue square
PURPLE_SQUARE = "🟪" #⊛ purple square
BROWN_SQUARE = "🟫" #⊛ brown square
BLACK_LARGE_SQUARE = "⬛" #black large square
WHITE_LARGE_SQUARE = "⬜" #white large square
BLACK_MEDIUM_SQUARE = "◼" #black medium square
WHITE_MEDIUM_SQUARE = "◻" #white medium square
BLACK_MEDIUM_SMALL_SQUARE = "◾" #black medium-small square
WHITE_MEDIUM_SMALL_SQUARE = "◽" #white medium-small square
BLACK_SMALL_SQUARE = "▪" #black small square
WHITE_SMALL_SQUARE = "▫" #white small square
LARGE_ORANGE_DIAMOND = "🔶" #large orange diamond
LARGE_BLUE_DIAMOND = "🔷" #large blue diamond
SMALL_ORANGE_DIAMOND = "🔸" #small orange diamond
SMALL_BLUE_DIAMOND = "🔹" #small blue diamond
RED_TRIANGLE_POINTED_UP = "🔺" #red triangle pointed up
RED_TRIANGLE_POINTED_DOWN = "🔻" #red triangle pointed down
DIAMOND_WITH_A_DOT = "💠" #diamond with a dot
RADIO_BUTTON = "🔘" #radio button
WHITE_SQUARE_BUTTON = "🔳" #white square button
BLACK_SQUARE_BUTTON = "🔲" #black square button
CHEQUERED_FLAG = "🏁" #chequered flag
TRIANGULAR_FLAG = "🚩" #triangular flag
CROSSED_FLAGS = "🎌" #crossed flags
BLACK_FLAG = "🏴" #black flag
WHITE_FLAG = "🏳" #white flag
RAINBOW_FLAG = "🏳️‍🌈" #rainbow flag
PIRATE_FLAG = "🏴‍☠️" #pirate flag
FLAG_ASCENSION_ISLAND = "🇦🇨" #flag: Ascension Island
FLAG_ANDORRA = "🇦🇩" #flag: Andorra
FLAG_UNITED_ARAB_EMIRATES = "🇦🇪" #flag: United Arab Emirates
FLAG_AFGHANISTAN = "🇦🇫" #flag: Afghanistan
FLAG_ANTIGUA_AND_BARBUDA = "🇦🇬" #flag: Antigua and Barbuda
FLAG_ANGUILLA = "🇦🇮" #flag: Anguilla
FLAG_ALBANIA = "🇦🇱" #flag: Albania
FLAG_ARMENIA = "🇦🇲" #flag: Armenia
FLAG_ANGOLA = "🇦🇴" #flag: Angola
FLAG_ANTARCTICA = "🇦🇶" #flag: Antarctica
FLAG_ARGENTINA = "🇦🇷" #flag: Argentina
FLAG_AMERICAN_SAMOA = "🇦🇸" #flag: American Samoa
FLAG_AUSTRIA = "🇦🇹" #flag: Austria
FLAG_AUSTRALIA = "🇦🇺" #flag: Australia
FLAG_ARUBA = "🇦🇼" #flag: Aruba
FLAG_ÅLAND_ISLANDS = "🇦🇽" #flag: Åland Islands
FLAG_AZERBAIJAN = "🇦🇿" #flag: Azerbaijan
FLAG_BOSNIA_AND_HERZEGOVINA = "🇧🇦" #flag: Bosnia and Herzegovina
FLAG_BARBADOS = "🇧🇧" #flag: Barbados
FLAG_BANGLADESH = "🇧🇩" #flag: Bangladesh
FLAG_BELGIUM = "🇧🇪" #flag: Belgium
FLAG_BURKINA_FASO = "🇧🇫" #flag: Burkina Faso
FLAG_BULGARIA = "🇧🇬" #flag: Bulgaria
FLAG_BAHRAIN = "🇧🇭" #flag: Bahrain
FLAG_BURUNDI = "🇧🇮" #flag: Burundi
FLAG_BENIN = "🇧🇯" #flag: Benin
FLAG_ST_BARTHÉLEMY = "🇧🇱" #flag: St. Barthélemy
FLAG_BERMUDA = "🇧🇲" #flag: Bermuda
FLAG_BRUNEI = "🇧🇳" #flag: Brunei
FLAG_BOLIVIA = "🇧🇴" #flag: Bolivia
FLAG_CARIBBEAN_NETHERLANDS = "🇧🇶" #flag: Caribbean Netherlands
FLAG_BRAZIL = "🇧🇷" #flag: Brazil
FLAG_BAHAMAS = "🇧🇸" #flag: Bahamas
FLAG_BHUTAN = "🇧🇹" #flag: Bhutan
FLAG_BOUVET_ISLAND = "🇧🇻" #flag: Bouvet Island
FLAG_BOTSWANA = "🇧🇼" #flag: Botswana
FLAG_BELARUS = "🇧🇾" #flag: Belarus
FLAG_BELIZE = "🇧🇿" #flag: Belize
FLAG_CANADA = "🇨🇦" #flag: Canada
FLAG_COCOS_KEELING_ISLANDS = "🇨🇨" #flag: Cocos (Keeling) Islands
FLAG_CONGO_KINSHASA = "🇨🇩" #flag: Congo - Kinshasa
FLAG_CENTRAL_AFRICAN_REPUBLIC = "🇨🇫" #flag: Central African Republic
FLAG_CONGO_BRAZZAVILLE = "🇨🇬" #flag: Congo - Brazzaville
FLAG_SWITZERLAND = "🇨🇭" #flag: Switzerland
FLAG_CÔTE_D_IVOIRE = "🇨🇮" #flag: Côte d’Ivoire
FLAG_COOK_ISLANDS = "🇨🇰" #flag: Cook Islands
FLAG_CHILE = "🇨🇱" #flag: Chile
FLAG_CAMEROON = "🇨🇲" #flag: Cameroon
FLAG_CHINA = "🇨🇳" #flag: China
FLAG_COLOMBIA = "🇨🇴" #flag: Colombia
FLAG_CLIPPERTON_ISLAND = "🇨🇵" #flag: Clipperton Island
FLAG_COSTA_RICA = "🇨🇷" #flag: Costa Rica
FLAG_CUBA = "🇨🇺" #flag: Cuba
FLAG_CAPE_VERDE = "🇨🇻" #flag: Cape Verde
FLAG_CURAÇAO = "🇨🇼" #flag: Curaçao
FLAG_CHRISTMAS_ISLAND = "🇨🇽" #flag: Christmas Island
FLAG_CYPRUS = "🇨🇾" #flag: Cyprus
FLAG_CZECHIA = "🇨🇿" #flag: Czechia
FLAG_GERMANY = "🇩🇪" #flag: Germany
FLAG_DIEGO_GARCIA = "🇩🇬" #flag: Diego Garcia
FLAG_DJIBOUTI = "🇩🇯" #flag: Djibouti
FLAG_DENMARK = "🇩🇰" #flag: Denmark
FLAG_DOMINICA = "🇩🇲" #flag: Dominica
FLAG_DOMINICAN_REPUBLIC = "🇩🇴" #flag: Dominican Republic
FLAG_ALGERIA = "🇩🇿" #flag: Algeria
FLAG_CEUTA_AND_MELILLA = "🇪🇦" #flag: Ceuta and Melilla
FLAG_ECUADOR = "🇪🇨" #flag: Ecuador
FLAG_ESTONIA = "🇪🇪" #flag: Estonia
FLAG_EGYPT = "🇪🇬" #flag: Egypt
FLAG_WESTERN_SAHARA = "🇪🇭" #flag: Western Sahara
FLAG_ERITREA = "🇪🇷" #flag: Eritrea
FLAG_SPAIN = "🇪🇸" #flag: Spain
FLAG_ETHIOPIA = "🇪🇹" #flag: Ethiopia
FLAG_EUROPEAN_UNION = "🇪🇺" #flag: European Union
FLAG_FINLAND = "🇫🇮" #flag: Finland
FLAG_FIJI = "🇫🇯" #flag: Fiji
FLAG_FALKLAND_ISLANDS = "🇫🇰" #flag: Falkland Islands
FLAG_MICRONESIA = "🇫🇲" #flag: Micronesia
FLAG_FAROE_ISLANDS = "🇫🇴" #flag: Faroe Islands
FLAG_FRANCE = "🇫🇷" #flag: France
FLAG_GABON = "🇬🇦" #flag: Gabon
FLAG_UNITED_KINGDOM = "🇬🇧" #flag: United Kingdom
FLAG_GRENADA = "🇬🇩" #flag: Grenada
FLAG_GEORGIA = "🇬🇪" #flag: Georgia
FLAG_FRENCH_GUIANA = "🇬🇫" #flag: French Guiana
FLAG_GUERNSEY = "🇬🇬" #flag: Guernsey
FLAG_GHANA = "🇬🇭" #flag: Ghana
FLAG_GIBRALTAR = "🇬🇮" #flag: Gibraltar
FLAG_GREENLAND = "🇬🇱" #flag: Greenland
FLAG_GAMBIA = "🇬🇲" #flag: Gambia
FLAG_GUINEA = "🇬🇳" #flag: Guinea
FLAG_GUADELOUPE = "🇬🇵" #flag: Guadeloupe
FLAG_EQUATORIAL_GUINEA = "🇬🇶" #flag: Equatorial Guinea
FLAG_GREECE = "🇬🇷" #flag: Greece
FLAG_SOUTH_GEORGIA_AND_SOUTH_SANDWICH_ISLANDS = "🇬🇸" #flag: South Georgia and South Sandwich Islands
FLAG_GUATEMALA = "🇬🇹" #flag: Guatemala
FLAG_GUAM = "🇬🇺" #flag: Guam
FLAG_GUINEA_BISSAU = "🇬🇼" #flag: Guinea-Bissau
FLAG_GUYANA = "🇬🇾" #flag: Guyana
FLAG_HONG_KONG_SAR_CHINA = "🇭🇰" #flag: Hong Kong SAR China
FLAG_HEARD_AND_MCDONALD_ISLANDS = "🇭🇲" #flag: Heard and McDonald Islands
FLAG_HONDURAS = "🇭🇳" #flag: Honduras
FLAG_CROATIA = "🇭🇷" #flag: Croatia
FLAG_HAITI = "🇭🇹" #flag: Haiti
FLAG_HUNGARY = "🇭🇺" #flag: Hungary
FLAG_CANARY_ISLANDS = "🇮🇨" #flag: Canary Islands
FLAG_INDONESIA = "🇮🇩" #flag: Indonesia
FLAG_IRELAND = "🇮🇪" #flag: Ireland
FLAG_ISRAEL = "🇮🇱" #flag: Israel
FLAG_ISLE_OF_MAN = "🇮🇲" #flag: Isle of Man
FLAG_INDIA = "🇮🇳" #flag: India
FLAG_BRITISH_INDIAN_OCEAN_TERRITORY = "🇮🇴" #flag: British Indian Ocean Territory
FLAG_IRAQ = "🇮🇶" #flag: Iraq
FLAG_IRAN = "🇮🇷" #flag: Iran
FLAG_ICELAND = "🇮🇸" #flag: Iceland
FLAG_ITALY = "🇮🇹" #flag: Italy
FLAG_JERSEY = "🇯🇪" #flag: Jersey
FLAG_JAMAICA = "🇯🇲" #flag: Jamaica
FLAG_JORDAN = "🇯🇴" #flag: Jordan
FLAG_JAPAN = "🇯🇵" #flag: Japan
FLAG_KENYA = "🇰🇪" #flag: Kenya
FLAG_KYRGYZSTAN = "🇰🇬" #flag: Kyrgyzstan
FLAG_CAMBODIA = "🇰🇭" #flag: Cambodia
FLAG_KIRIBATI = "🇰🇮" #flag: Kiribati
FLAG_COMOROS = "🇰🇲" #flag: Comoros
FLAG_ST_KITTS_AND_NEVIS = "🇰🇳" #flag: St. Kitts and Nevis
FLAG_NORTH_KOREA = "🇰🇵" #flag: North Korea
FLAG_SOUTH_KOREA = "🇰🇷" #flag: South Korea
FLAG_KUWAIT = "🇰🇼" #flag: Kuwait
FLAG_CAYMAN_ISLANDS = "🇰🇾" #flag: Cayman Islands
FLAG_KAZAKHSTAN = "🇰🇿" #flag: Kazakhstan
FLAG_LAOS = "🇱🇦" #flag: Laos
FLAG_LEBANON = "🇱🇧" #flag: Lebanon
FLAG_ST_LUCIA = "🇱🇨" #flag: St. Lucia
FLAG_LIECHTENSTEIN = "🇱🇮" #flag: Liechtenstein
FLAG_SRI_LANKA = "🇱🇰" #flag: Sri Lanka
FLAG_LIBERIA = "🇱🇷" #flag: Liberia
FLAG_LESOTHO = "🇱🇸" #flag: Lesotho
FLAG_LITHUANIA = "🇱🇹" #flag: Lithuania
FLAG_LUXEMBOURG = "🇱🇺" #flag: Luxembourg
FLAG_LATVIA = "🇱🇻" #flag: Latvia
FLAG_LIBYA = "🇱🇾" #flag: Libya
FLAG_MOROCCO = "🇲🇦" #flag: Morocco
FLAG_MONACO = "🇲🇨" #flag: Monaco
FLAG_MOLDOVA = "🇲🇩" #flag: Moldova
FLAG_MONTENEGRO = "🇲🇪" #flag: Montenegro
FLAG_ST_MARTIN = "🇲🇫" #flag: St. Martin
FLAG_MADAGASCAR = "🇲🇬" #flag: Madagascar
FLAG_MARSHALL_ISLANDS = "🇲🇭" #flag: Marshall Islands
FLAG_MACEDONIA = "🇲🇰" #flag: Macedonia
FLAG_MALI = "🇲🇱" #flag: Mali
FLAG_MYANMAR_BURMA = "🇲🇲" #flag: Myanmar (Burma)
FLAG_MONGOLIA = "🇲🇳" #flag: Mongolia
FLAG_MACAO_SAR_CHINA = "🇲🇴" #flag: Macao SAR China
FLAG_NORTHERN_MARIANA_ISLANDS = "🇲🇵" #flag: Northern Mariana Islands
FLAG_MARTINIQUE = "🇲🇶" #flag: Martinique
FLAG_MAURITANIA = "🇲🇷" #flag: Mauritania
FLAG_MONTSERRAT = "🇲🇸" #flag: Montserrat
FLAG_MALTA = "🇲🇹" #flag: Malta
FLAG_MAURITIUS = "🇲🇺" #flag: Mauritius
FLAG_MALDIVES = "🇲🇻" #flag: Maldives
FLAG_MALAWI = "🇲🇼" #flag: Malawi
FLAG_MEXICO = "🇲🇽" #flag: Mexico
FLAG_MALAYSIA = "🇲🇾" #flag: Malaysia
FLAG_MOZAMBIQUE = "🇲🇿" #flag: Mozambique
FLAG_NAMIBIA = "🇳🇦" #flag: Namibia
FLAG_NEW_CALEDONIA = "🇳🇨" #flag: New Caledonia
FLAG_NIGER = "🇳🇪" #flag: Niger
FLAG_NORFOLK_ISLAND = "🇳🇫" #flag: Norfolk Island
FLAG_NIGERIA = "🇳🇬" #flag: Nigeria
FLAG_NICARAGUA = "🇳🇮" #flag: Nicaragua
FLAG_NETHERLANDS = "🇳🇱" #flag: Netherlands
FLAG_NORWAY = "🇳🇴" #flag: Norway
FLAG_NEPAL = "🇳🇵" #flag: Nepal
FLAG_NAURU = "🇳🇷" #flag: Nauru
FLAG_NIUE = "🇳🇺" #flag: Niue
FLAG_NEW_ZEALAND = "🇳🇿" #flag: New Zealand
FLAG_OMAN = "🇴🇲" #flag: Oman
FLAG_PANAMA = "🇵🇦" #flag: Panama
FLAG_PERU = "🇵🇪" #flag: Peru
FLAG_FRENCH_POLYNESIA = "🇵🇫" #flag: French Polynesia
FLAG_PAPUA_NEW_GUINEA = "🇵🇬" #flag: Papua New Guinea
FLAG_PHILIPPINES = "🇵🇭" #flag: Philippines
FLAG_PAKISTAN = "🇵🇰" #flag: Pakistan
FLAG_POLAND = "🇵🇱" #flag: Poland
FLAG_ST_PIERRE_AND_MIQUELON = "🇵🇲" #flag: St. Pierre and Miquelon
FLAG_PITCAIRN_ISLANDS = "🇵🇳" #flag: Pitcairn Islands
FLAG_PUERTO_RICO = "🇵🇷" #flag: Puerto Rico
FLAG_PALESTINIAN_TERRITORIES = "🇵🇸" #flag: Palestinian Territories
FLAG_PORTUGAL = "🇵🇹" #flag: Portugal
FLAG_PALAU = "🇵🇼" #flag: Palau
FLAG_PARAGUAY = "🇵🇾" #flag: Paraguay
FLAG_QATAR = "🇶🇦" #flag: Qatar
FLAG_RÉUNION = "🇷🇪" #flag: Réunion
FLAG_ROMANIA = "🇷🇴" #flag: Romania
FLAG_SERBIA = "🇷🇸" #flag: Serbia
FLAG_RUSSIA = "🇷🇺" #flag: Russia
FLAG_RWANDA = "🇷🇼" #flag: Rwanda
FLAG_SAUDI_ARABIA = "🇸🇦" #flag: Saudi Arabia
FLAG_SOLOMON_ISLANDS = "🇸🇧" #flag: Solomon Islands
FLAG_SEYCHELLES = "🇸🇨" #flag: Seychelles
FLAG_SUDAN = "🇸🇩" #flag: Sudan
FLAG_SWEDEN = "🇸🇪" #flag: Sweden
FLAG_SINGAPORE = "🇸🇬" #flag: Singapore
FLAG_ST_HELENA = "🇸🇭" #flag: St. Helena
FLAG_SLOVENIA = "🇸🇮" #flag: Slovenia
FLAG_SVALBARD_AND_JAN_MAYEN = "🇸🇯" #flag: Svalbard and Jan Mayen
FLAG_SLOVAKIA = "🇸🇰" #flag: Slovakia
FLAG_SIERRA_LEONE = "🇸🇱" #flag: Sierra Leone
FLAG_SAN_MARINO = "🇸🇲" #flag: San Marino
FLAG_SENEGAL = "🇸🇳" #flag: Senegal
FLAG_SOMALIA = "🇸🇴" #flag: Somalia
FLAG_SURINAME = "🇸🇷" #flag: Suriname
FLAG_SOUTH_SUDAN = "🇸🇸" #flag: South Sudan
FLAG_SÃO_TOMÉ_AND_PRÍNCIPE = "🇸🇹" #flag: São Tomé and Príncipe
FLAG_EL_SALVADOR = "🇸🇻" #flag: El Salvador
FLAG_SINT_MAARTEN = "🇸🇽" #flag: Sint Maarten
FLAG_SYRIA = "🇸🇾" #flag: Syria
FLAG_ESWATINI = "🇸🇿" #flag: Eswatini
FLAG_TRISTAN_DA_CUNHA = "🇹🇦" #flag: Tristan da Cunha
FLAG_TURKS_AND_CAICOS_ISLANDS = "🇹🇨" #flag: Turks and Caicos Islands
FLAG_CHAD = "🇹🇩" #flag: Chad
FLAG_FRENCH_SOUTHERN_TERRITORIES = "🇹🇫" #flag: French Southern Territories
FLAG_TOGO = "🇹🇬" #flag: Togo
FLAG_THAILAND = "🇹🇭" #flag: Thailand
FLAG_TAJIKISTAN = "🇹🇯" #flag: Tajikistan
FLAG_TOKELAU = "🇹🇰" #flag: Tokelau
FLAG_TIMOR_LESTE = "🇹🇱" #flag: Timor-Leste
FLAG_TURKMENISTAN = "🇹🇲" #flag: Turkmenistan
FLAG_TUNISIA = "🇹🇳" #flag: Tunisia
FLAG_TONGA = "🇹🇴" #flag: Tonga
FLAG_TURKEY = "🇹🇷" #flag: Turkey
FLAG_TRINIDAD_AND_TOBAGO = "🇹🇹" #flag: Trinidad and Tobago
FLAG_TUVALU = "🇹🇻" #flag: Tuvalu
FLAG_TAIWAN = "🇹🇼" #flag: Taiwan
FLAG_TANZANIA = "🇹🇿" #flag: Tanzania
FLAG_UKRAINE = "🇺🇦" #flag: Ukraine
FLAG_UGANDA = "🇺🇬" #flag: Uganda
FLAG_U_S_OUTLYING_ISLANDS = "🇺🇲" #flag: U.S. Outlying Islands
FLAG_UNITED_NATIONS = "🇺🇳" #flag: United Nations
FLAG_UNITED_STATES = "🇺🇸" #flag: United States
FLAG_URUGUAY = "🇺🇾" #flag: Uruguay
FLAG_UZBEKISTAN = "🇺🇿" #flag: Uzbekistan
FLAG_VATICAN_CITY = "🇻🇦" #flag: Vatican City
FLAG_ST_VINCENT_AND_GRENADINES = "🇻🇨" #flag: St. Vincent and Grenadines
FLAG_VENEZUELA = "🇻🇪" #flag: Venezuela
FLAG_BRITISH_VIRGIN_ISLANDS = "🇻🇬" #flag: British Virgin Islands
FLAG_U_S_VIRGIN_ISLANDS = "🇻🇮" #flag: U.S. Virgin Islands
FLAG_VIETNAM = "🇻🇳" #flag: Vietnam
FLAG_VANUATU = "🇻🇺" #flag: Vanuatu
FLAG_WALLIS_AND_FUTUNA = "🇼🇫" #flag: Wallis and Futuna
FLAG_SAMOA = "🇼🇸" #flag: Samoa
FLAG_KOSOVO = "🇽🇰" #flag: Kosovo
FLAG_YEMEN = "🇾🇪" #flag: Yemen
FLAG_MAYOTTE = "🇾🇹" #flag: Mayotte
FLAG_SOUTH_AFRICA = "🇿🇦" #flag: South Africa
FLAG_ZAMBIA = "🇿🇲" #flag: Zambia
FLAG_ZIMBABWE = "🇿🇼" #flag: Zimbabwe
FLAG_ENGLAND = "🏴󠁧󠁢󠁥󠁮󠁧󠁿" #flag: England
FLAG_SCOTLAND = "🏴󠁧󠁢󠁳󠁣󠁴󠁿" #flag: Scotland
FLAG_WALES = "🏴󠁧󠁢󠁷󠁬󠁳󠁿" #flag: Wales
