# Generated by Django 2.2.5 on 2020-01-28 09:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('marketplace', '0002_auto_20200117_1440'),
    ]

    operations = [
        migrations.CreateModel(
            name='EtsyCategoryTree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_tree_version', models.CharField(blank=True, max_length=10, null=True, verbose_name='Версия дерева категорий')),
                ('domain', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='marketplace.Domain', verbose_name='Домен маркетплейса')),
            ],
            options={
                'verbose_name': 'Дерево категорий для Etsy',
                'verbose_name_plural': 'Деревья категорий для Etsy',
            },
        ),
        migrations.CreateModel(
            name='EtsyCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('category_id', models.CharField(max_length=15, verbose_name='ID категории')),
                ('parent_id', models.CharField(max_length=15, verbose_name='ID родительской категории или 0')),
                ('level', models.PositiveSmallIntegerField(verbose_name='Уровень вложенности категории')),
                ('name', models.CharField(max_length=100, verbose_name='Название категории')),
                ('name_path', models.CharField(blank=True, default='', max_length=500, verbose_name='Путь к категории')),
                ('id_path', models.CharField(blank=True, default='', max_length=300, verbose_name='ID пути к категории')),
                ('is_leaf', models.BooleanField(verbose_name='Является листом дерева категорий')),
                ('old_category_id', models.CharField(blank=True, max_length=15, null=True, verbose_name='ID старой версии категории')),
                ('category_tree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etsy_product_categories', to='etsy_category.EtsyCategoryTree', verbose_name='Дерево категорий товаров Etsy')),
            ],
            options={
                'verbose_name': 'Категория товара Etsy',
                'verbose_name_plural': 'Категории товара Etsy',
            },
        ),
        migrations.AddConstraint(
            model_name='etsycategory',
            constraint=models.UniqueConstraint(fields=('category_id', 'category_tree'), name='unique_etsy_category_id_for_tree'),
        ),
    ]
