#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['pytest_cleanup']

package_data = \
{'': ['*']}

install_requires = \
['jsonpickle <2', 'loguru <1']

setup(name='pytest_cleanup',
      version='0.1',
      description='A simple cli-based recorder for Python',
      author='Jeshan G. BABOOA',
      author_email='j@jeshan.co',
      url='https://github.com/jeshan/pytest-cleanup',
      packages=packages,
      package_data=package_data,
      install_requires=install_requires,
     )
