image: python:3.5

definitions:
  steps:
    - step: &run-tests
        caches:
          - pip
          - docker
        services:
          - docker
        script:
          - ./scripts/prepare.sh
          - tox -e py$((34+${BITBUCKET_PARALLEL_STEP}))
          - python setup.py bdist_wheel sdist
    - parallel: &build
      - step:
          image: python:2.7
          caches:
            - pip
            - docker
          services:
            - docker
          script:
            - ./scripts/prepare.sh
            - tox -e py27
            - python setup.py bdist_wheel sdist
          artifacts:
            - dist/*
      - step:
          <<: *run-tests
          image: python:3.5
      - step:
          <<: *run-tests
          image: python:3.6
      - step:
          <<: *run-tests
          image: python:3.7
          artifacts:
            - dist/*

pipelines:
  default:
    - parallel: *build
    - step:
        name: Deploy to PyPI
        deployment: production
        caches:
          - pip
          - docker
        services:
          - docker
        script:
          - ./scripts/prepare.sh
          - ./scripts/deploy.sh
