
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-01-23T09:55:52+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "00ec65352f2bd71cce607274a64c334c40b51142",
 "version": "0.10.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
