# Generated by Django 2.2.5 on 2020-01-17 11:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EtsyUserAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('access_token', models.CharField(max_length=50, verbose_name='Токен доступа')),
                ('access_token_secret', models.CharField(max_length=50, verbose_name='Секрет токена доступа')),
                ('sandbox', models.BooleanField(verbose_name='Аккаунт для Etsy Sandbox')),
            ],
            options={
                'verbose_name': 'Пользовательский аккаунт Etsy',
                'verbose_name_plural': 'Пользовательские аккаунт Etsy',
            },
        ),
        migrations.CreateModel(
            name='EtsyUserAccountInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('user_id', models.CharField(max_length=30, unique=True, verbose_name='ID пользователя')),
                ('login_name', models.CharField(max_length=50, unique=True, verbose_name='Логин пользователя')),
                ('primary_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail пользователя')),
                ('feedback_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество оценок')),
                ('feedback_score', models.PositiveIntegerField(blank=True, null=True, verbose_name='Процент положительных оценок')),
                ('creation_tsz', models.FloatField(blank=True, null=True, verbose_name='Дата и время регистрации (unix-время)')),
                ('etsy_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_info', to='etsy_account.EtsyUserAccount', verbose_name='Пользовательский аккаунт Etsy')),
            ],
            options={
                'verbose_name': 'Информация об аккаунте',
                'verbose_name_plural': 'Информация об аккаунте',
            },
        ),
    ]
