
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-02-06T12:26:43-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "17f68f99612b2d577c90de3933e6ff068f6ba5c4",
 "version": "0.1.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
