etsy_receipt_sample_data = [
    {
        "receipt_id": 1578501733,
        "receipt_type": 0,
        "order_id": 879192576,
        "seller_user_id": 266587158,
        "buyer_user_id": 273657473,
        "creation_tsz": 1580213410,
        "can_refund": False,
        "last_modified_tsz": 1580213410,
        "name": "Alexandr Stefanitsky-Mozdor",
        "first_line": "Улица Красного Маяка",
        "second_line": "дом 11, корпус 1, квартира 88",
        "city": "Москва",
        "state": "",
        "zip": "117570",
        "formatted_address": "Alexandr Stefanitsky-Mozdor\nУЛИЦА КРАСНОГО МАЯКА\nДОМ 11, КОРПУС 1, КВАРТИРА 88\nМОСКВА\n117570\nRussia",
        "country_id": 181,
        "payment_method": "other",
        "payment_email": "",
        "message_from_seller": None,
        "message_from_buyer": "Note for a seller, hello. Test note btw.",
        "was_paid": False,
        "total_tax_cost": "0.00",
        "total_vat_cost": "0.00",
        "total_price": "0.20",
        "total_shipping_cost": "0.00",
        "currency_code": "USD",
        "message_from_payment": None,
        "was_shipped": False,
        "buyer_email": "zs-dev-etsy-buyer@yandex.ru",
        "seller_email": "dev@zonesmart.ru",
        "is_gift": True,
        "needs_gift_wrap": False,
        "gift_message": "Hello, dear friend!",
        "discount_amt": "0.00",
        "subtotal": "0.20",
        "grandtotal": "0.20",
        "adjusted_grandtotal": "0.20",
        "buyer_adjusted_grandtotal": "0.20",
        "shipments": [],
        "shipped_date": None,
        "is_overdue": False,
        "days_from_due_date": 18290,
        "shipping_details": {
            "can_mark_as_shipped": False,
            "was_shipped": False,
            "is_future_shipment": True,
            "has_free_shipping_discount": False,
            "not_shipped_state_display": "Not Shipped",
            "shipping_method": "Standard Shipping",
            "is_estimated_delivery_date_relevant": False,
        },
        "transparent_price_message": "Local taxes included (where applicable)",
        "show_channel_badge": False,
        "channel_badge_suffix_string": "",
        "is_dead": False,
    }
]


find_all_shop_transactions_sample = {
    "response": {
        "x-ratelimit-limit": "10000",
        "x-ratelimit-remaining": "9916",
        "date": "Wed, 29 Jan 2020 17:24:01 GMT",
        "status": "200",
    },
    "count": 1,
    "results": [
        {
            "transaction_id": 1790249868,
            "title": "Test listing title",
            "description": "Some description",
            "seller_user_id": 266587158,
            "buyer_user_id": 273657473,
            "creation_tsz": 1580213410,
            "paid_tsz": None,
            "shipped_tsz": None,
            "price": "0.20",
            "currency_code": "USD",
            "quantity": 1,
            "tags": ["Bath_And_Beauty", "Makeup", "Lip"],
            "materials": [],
            "image_listing_id": 2216455135,
            "receipt_id": 1578501733,
            "shipping_cost": "0.00",
            "is_digital": None,
            "file_data": "",
            "listing_id": 771024915,
            "is_quick_sale": None,
            "seller_feedback_id": None,
            "buyer_feedback_id": None,
            "transaction_type": "listing",
            "url": "https://www.etsy.com/transaction/1790249868",
            "variations": [
                {
                    "property_id": 200,
                    "value_id": 65268861519,
                    "formatted_name": "Color",
                    "formatted_value": "1",
                },
                {
                    "property_id": 52047899002,
                    "value_id": 722854117302,
                    "formatted_name": "Secondary color",
                    "formatted_value": "1213",
                },
            ],
            "product_data": {
                "product_id": 4192741074,
                "sku": "product_sku_2",
                "property_values": [
                    {
                        "property_id": 200,
                        "property_name": "Primary color",
                        "scale_id": None,
                        "scale_name": None,
                        "values": ["1"],
                        "value_ids": [65268861519],
                    },
                    {
                        "property_id": 52047899002,
                        "property_name": "Secondary color",
                        "scale_id": None,
                        "scale_name": None,
                        "values": ["1213"],
                        "value_ids": [722854117302],
                    },
                ],
                "offerings": [
                    {
                        "offering_id": 4174795296,
                        "price": {
                            "amount": 20,
                            "divisor": 100,
                            "currency_code": "USD",
                            "currency_formatted_short": "$0.20",
                            "currency_formatted_long": "$0.20 USD",
                            "currency_formatted_raw": "0.20",
                        },
                        "quantity": 9,
                        "is_enabled": 1,
                        "is_deleted": 0,
                    }
                ],
                "is_deleted": 0,
            },
        }
    ],
    "params": {"shop_id": "22108314", "limit": 25, "offset": 0, "page": None},
    "type": "Transaction",
    "pagination": {
        "effective_limit": 25,
        "effective_offset": 0,
        "next_offset": None,
        "effective_page": 1,
        "next_page": None,
    },
}
