[tool.poetry]
name = "dj-pony.tenant"
version = "0.10.1"
description = "A Shared Schema based Multi-Tenancy Library for Django."
license = "Prosperity Public License 2.0.0"
repository = "https://github.com/dj-pony-pro/dj-pony-tenant"
authors = ["Samuel Bishop <sam@techdragon.io>"]
include = [
    "licensezero.json"
]
packages = [
    { include = "dj_pony" },
]
classifiers = [
    "Development Status :: 3 - Alpha",
    #"Framework :: Django :: 1.11",
    "Framework :: Django :: 2.0",
    "Intended Audience :: Developers",
    "Natural Language :: English",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.6"
]

[tool.poetry.dependencies]
python = "^3.6"
django = "^2.2.6"
packaging = "^19.0"
"dj-pony.ulidfield" = "^0.3.1"
django-model-utils = "^3.2.0"
django-jsonfield = "^1.3.1"
sentinels = "^1.0.0"
django-polymorphic = {version = "^2.1.2", optional = true}
deprecated = "^1.2.7"


[tool.poetry.dev-dependencies]
hypothesis = { version = "^4.14", extras = [ "django" ] }
model_mommy = {git = "https://github.com/techdragon/model_mommy.git", branch = "development"}
django-test-without-migrations = "^0.6.0"
pytest = "^4.4"
coverage = "^4.5"
pytest-cov = "^2.7"
django-extensions = "^2.1"
psycopg2 = {version = "^2.8.4", platform = "linux"}
psycopg2-binary = {version = "^2.8.4", platform = "darwin"}
mock = "^2.0"
tox = "^3.12"
tox-battery = "^0.5.1"
tox-pip-version = "^0.0.5"
pytest-django = "^3.5"
django-environ = "^0.4.5"
docker = "^4.0"
"dj-pony.django-docker-test-dbs" = "^0.1.0"
pip-licenses = "^1.15.2"
djangorestframework = "^3.10.3"
django-test-plus = "^1.3.1"
django-polymorphic = "^2.1.2"

[tool.poetry.extras]
polymorphic = ["django-polymorphic", ]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
