[tool.poetry]
name = "ylib"
version = "0.1.0"
description = "My Library"
authors = ["yassu <mathyassu@gmail.com>"]
license = "Apache-2.0"

[tool.poetry.dependencies]
python = "^3.8"
isort = "^4.3.21"
ipython = "^7.11.1"
invoke = "^1.4.0"
tqdm = "^4.41.1"
py-term = "^0.6"
prettytable = "^0.7.2"
pytest-cov = "^2.8.1"
flake8 = "^3.7.9"
autopep8 = "^1.5"
toml = "^0.10.0"

[tool.poetry.dev-dependencies]

[tool.isort]
line_length = 99
include_trailing_comma = true
multi_line_output = 3
[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[flake8]
max-line-length = 99

