# Generated by Django 2.2.5 on 2020-01-17 11:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('etsy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EtsyShippingTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False)),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False)),
                ('status', model_utils.fields.StatusField(choices=[('draft', 'draft'), ('ready_to_publish', 'ready_to_publish'), ('published', 'published'), ('update_required', 'update_required')], default='draft', max_length=100, no_check_for_status=True)),
                ('published_at', model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', when={'published'})),
                ('shipping_template_id', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='ID политики доставки')),
                ('title', models.CharField(max_length=100, verbose_name='Название политики')),
                ('max_processing_days', models.PositiveIntegerField(blank=True, null=True, verbose_name='Максимальное число дней на обработку заказа')),
                ('min_processing_days', models.PositiveIntegerField(blank=True, null=True, verbose_name='Минимальное число дней на обработку заказа')),
                ('processing_days_display_label', models.CharField(blank=True, max_length=100, null=True, verbose_name='Отображаемое число дней на обработку заказа')),
            ],
            options={
                'verbose_name': 'Политика доставки Etsy',
                'verbose_name_plural': 'Политики доставки Etsy',
            },
        ),
        migrations.CreateModel(
            name='EtsyShippingTemplateEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('shipping_template_entry_id', models.CharField(blank=True, max_length=30, null=True, verbose_name='ID записи политики доставки')),
                ('currency_code', models.CharField(blank=True, choices=[('RUB', 'Российский рубль'), ('USD', 'Доллар США'), ('EUR', 'Евро'), ('GBP', 'Фунт стерлингов'), ('JPY', 'Японская иена'), ('CNY', 'Китайский юань'), ('AUD', 'Австралийский доллар'), ('CAD', 'Канадский доллар')], default='USD', max_length=3, verbose_name='Код валюты')),
                ('primary_cost', models.FloatField(verbose_name='Плата за одиночную доставку')),
                ('secondary_cost', models.FloatField(verbose_name='Плата за совместную доставку')),
                ('destination_country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dest_shipping_templates', to='etsy.EtsyCountry', verbose_name='Страна, в которую отравляется заказ')),
                ('destination_region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='etsy.EtsyRegion', verbose_name='Регион, в который отравляется заказ')),
                ('origin_country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='origin_shipping_templates', to='etsy.EtsyCountry', verbose_name='Страна, из которой отравляется заказ')),
                ('shipping_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', related_query_name='entry', to='etsy_policy.EtsyShippingTemplate', verbose_name='Политика доставки')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
