# Generated by Django 2.2.5 on 2020-01-17 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('marketplace', '0001_initial'),
        ('etsy_policy', '0001_initial'),
        ('etsy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='etsyshippingtemplate',
            name='marketplace_user_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_templates', related_query_name='shipping_template', to='marketplace.MarketplaceUserAccount'),
        ),
        migrations.AddField(
            model_name='etsyshippingtemplate',
            name='origin_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='etsy.EtsyCountry', verbose_name='Страна, из которой отравляется заказ'),
        ),
    ]
