
# This file was generated by PyScaffold from the git
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.0.8'
version_full = '0a0f18469d484aba6871fa7421bbb2c00ccefcb0'
def get_versions(default=dict(), verbose=False):
    return dict(version=version_version, full=version_full)
