import openseespy.opensees as opy
opy.wipe()
opy.model('basic', '-ndm', 2, '-ndf', 3)
opy.node(1, 0.0, 0.0, '-mass', 0.0, 0.0, 0.0)
opy.node(2, 2.0, 0.0, '-mass', 0.0, 0.0, 0.0)
opy.geomTransf('Linear', 1)
opy.element('elasticBeamColumn', 1, 1, 2, 1.0, 1.0, 1.0, 1, '-mass', 1.0, '-cMass')
opy.fix(1, 1, 1, 1)
opy.fix(2, 0, 1, 1)
opy.timeSeries('Linear', 1, '-factor', 1.0)
opy.pattern('Plain', 1, 1)
opy.eleLoad('-ele', 1, '-type', '-beamUniform', -10)
opy.constraints('Plain')
opy.numberer('RCM')
opy.system('BandGeneral')
opy.test('NormDispIncr', 0.0001, 6, 0, 2)
opy.algorithm('Newton', False, False, False)
opy.integrator('LoadControl', 1.0, 10)
opy.analysis('Static')
opy.analyze(1, 0.1)
opy.eleResponse(1, 'force')
opy.nodeReaction(1, 2)
opy.analyze(1, 0.1)
