# Generated by Django 2.2.5 on 2020-01-28 09:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('marketplace', '0002_auto_20200117_1440'),
    ]

    operations = [
        migrations.CreateModel(
            name='EtsyShop',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('shop_id', models.CharField(max_length=30, unique=True, verbose_name='ID магазина Etsy')),
                ('title', models.CharField(max_length=300, verbose_name='Заголовок на главной странице магазина')),
                ('is_vacation', models.BooleanField(blank=True, default=False, verbose_name='Магазин временно не работает')),
                ('listing_active_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество активных листингов')),
                ('url', models.URLField(blank=True, null=True, verbose_name='URL магазина')),
                ('channel', models.OneToOneField(limit_choices_to={'domain__marketplace__unique_name': 'etsy'}, on_delete=django.db.models.deletion.CASCADE, related_name='shop', to='marketplace.Channel', verbose_name='Пользовательский канал продаж')),
            ],
            options={
                'verbose_name': 'Магазин Etsy',
                'verbose_name_plural': 'Магазины Etsy',
            },
        ),
        migrations.CreateModel(
            name='EtsyUserAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('access_token', models.CharField(max_length=50, verbose_name='Токен доступа')),
                ('access_token_secret', models.CharField(max_length=50, verbose_name='Секрет токена доступа')),
                ('sandbox', models.BooleanField(verbose_name='Аккаунт для Etsy Sandbox')),
                ('marketplace_user_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='etsy_user_account', to='marketplace.MarketplaceUserAccount')),
            ],
            options={
                'verbose_name': 'Пользовательский аккаунт Etsy',
                'verbose_name_plural': 'Пользовательские аккаунт Etsy',
            },
        ),
        migrations.CreateModel(
            name='EtsyUserAccountInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('user_id', models.CharField(max_length=30, unique=True, verbose_name='ID пользователя')),
                ('login_name', models.CharField(max_length=50, unique=True, verbose_name='Логин пользователя')),
                ('primary_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail пользователя')),
                ('feedback_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество оценок')),
                ('feedback_score', models.PositiveIntegerField(blank=True, null=True, verbose_name='Процент положительных оценок')),
                ('creation_tsz', models.DateTimeField(verbose_name='Дата и время регистрации')),
                ('etsy_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_info', to='etsy_account.EtsyUserAccount', verbose_name='Пользовательский аккаунт Etsy')),
            ],
            options={
                'verbose_name': 'Информация об аккаунте',
                'verbose_name_plural': 'Информация об аккаунте',
            },
        ),
        migrations.CreateModel(
            name='EtsyShopSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('shop_section_id', models.CharField(max_length=30, unique=True, verbose_name='ID секции магазина Etsy')),
                ('title', models.CharField(max_length=300, verbose_name='Заголовок секции магазина')),
                ('active_listing_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество активных листингов в секции')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', related_query_name='section', to='etsy_account.EtsyShop', verbose_name='Магазин Etsy')),
            ],
            options={
                'verbose_name': 'Секция магазина Etsy',
                'verbose_name_plural': 'Секции магазина Etsy',
            },
        ),
    ]
