# Generated by Django 2.2.5 on 2020-01-29 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('etsy_account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EtsyUserBillingOverview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_overdue', models.BooleanField(verbose_name='Баланс просрочен')),
                ('currency_code', models.CharField(choices=[('USD', 'USD')], max_length=3, verbose_name='Код валюты')),
                ('overdue_balance', models.FloatField(verbose_name='Сумма просроченного баланса')),
                ('balance_due', models.FloatField(verbose_name='Общая сумма, подлежащая оплате в настоящее время (включая просроченный остаток)')),
                ('total_balance', models.FloatField(verbose_name='Общая сумма, причитающаяся пользователю (включая сборы, которые еще не подлежат оплате)')),
                ('date_due', models.DateTimeField(verbose_name='Дата, к которой баланс должен быть оплачен')),
                ('etsy_user_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billing_overview', to='etsy_account.EtsyUserAccount', verbose_name='Пользовательский аккаунт Etsy')),
            ],
            options={
                'verbose_name': 'Информация о балансе аккаунта Etsy',
                'verbose_name_plural': 'Информация о балансах аккаунтов Etsy',
            },
        ),
        migrations.CreateModel(
            name='EtsyBillCharge',
            fields=[
                ('bill_charge_id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_tsz', models.DateTimeField(verbose_name='Дата и время создания')),
                ('last_modified_tsz', models.DateTimeField(verbose_name='Дата и время обновления')),
                ('bill_type', models.CharField(choices=[('listing', 'Публикация листинга'), ('edit', 'Увеличение кол-ва продуктов в листинге'), ('renew', 'Продление активного листинга'), ('renew_sold', 'Продление проданного листинга'), ('renew_sold_auto', 'Автоматическое продление проданного листинга'), ('transaction_quantity', 'Продажа листинга со множеством товаров'), ('renew_expired', 'Продление истекшего листинга'), ('transaction', 'Продажа товара'), ('wholesale_contract', 'Создание оптового контракта'), ('wholesale_transaction', 'Оптовая продажа'), ('shipping_labels', 'Почтовые расходы и дополнительные сборы'), ('shipping_label_insurance', 'Страхование почтовых отправлений (только USPS)'), ('shipping_label_coverage', 'Почтовые расходы (только Canada Post)'), ('shipping_label_taxes', 'Почтовые налоги (только Canada Post)'), ('shipping_label_adjustment', 'Возврат товара (только Canada Post)'), ('shipping_label_adjustment_taxes', 'Налоги на возвращаемый товар (только Canada Post)'), ('etsy_asap', 'Доставка с помощью Etsy ASAP'), ('search_ads', 'Рекламные объявления в поиске'), ('listing_private', 'Публикация приватного листинга'), ('showcase_category', 'Резервирование места в ветрине товаров категории'), ('prolist', 'Продвижение листинга'), ('wholesale_setup_fee', 'Присоединение к системе оптовых продаж'), ('vat_tax', 'НДС за продажу цифрового товара'), ('vat_seller_services', 'НДС за сервисы для продавцов')], max_length=30, verbose_name='Тип списания')),
                ('bill_type_id', models.CharField(max_length=20, verbose_name='ID объекта связанного со списанием')),
                ('amount', models.FloatField(verbose_name='Сумма списания')),
                ('currency_code', models.CharField(choices=[('USD', 'USD')], max_length=3, verbose_name='Код валюты')),
                ('etsy_user_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_charges', related_query_name='bill_charge', to='etsy_account.EtsyUserAccount')),
            ],
            options={
                'verbose_name': 'Списание по аккаунту Etsy',
                'verbose_name_plural': 'Списания по аккаунтам Etsy',
            },
        ),
    ]
