# Generated by Django 2.2.5 on 2020-01-27 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ebay_negotiation', '0002_auto_20200117_1440'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ebaymessage',
            options={'ordering': ['-receive_date']},
        ),
    ]
