# Generated by Django 2.2.5 on 2020-01-17 11:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AmazonOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('MarketplaceId', models.CharField(blank=True, max_length=30, null=True)),
                ('SalesChannel', models.CharField(blank=True, max_length=30, null=True)),
                ('FulfillmentChannel', models.CharField(blank=True, max_length=30, null=True)),
                ('OrderChannel', models.CharField(blank=True, max_length=30, null=True)),
                ('AmazonOrderId', models.CharField(max_length=30)),
                ('SellerOrderId', models.CharField(blank=True, default='', max_length=30)),
                ('OrderStatus', models.CharField(max_length=30)),
                ('OrderType', models.CharField(blank=True, max_length=30, null=True)),
                ('PurchaseDate', models.DateTimeField()),
                ('LastUpdateDate', models.DateTimeField()),
                ('LatestShipDate', models.DateTimeField(blank=True, null=True)),
                ('LatestDeliveryDate', models.DateTimeField(blank=True, null=True)),
                ('EarliestDeliveryDate', models.DateTimeField(blank=True, null=True)),
                ('BuyerName', models.CharField(blank=True, max_length=50, null=True)),
                ('BuyerEmail', models.EmailField(blank=True, max_length=254, null=True)),
                ('IsReplacementOrder', models.BooleanField(blank=True, null=True)),
                ('IsBusinessOrder', models.BooleanField(blank=True, null=True)),
                ('IsPremiumOrder', models.BooleanField(blank=True, null=True)),
                ('IsPrime', models.BooleanField(blank=True, null=True)),
                ('NumberOfItemsShipped', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('NumberOfItemsUnshipped', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('ShipServiceLevel', models.CharField(blank=True, max_length=30, null=True)),
                ('ShipmentServiceLevelCategory', models.CharField(blank=True, max_length=30, null=True)),
                ('PaymentMethod', models.CharField(blank=True, max_length=30, null=True)),
                ('_payment_method_details', models.TextField(default='[]')),
                ('PurchaseOrderNumber', models.CharField(blank=True, max_length=50, null=True)),
                ('CompanyLegalName', models.CharField(blank=True, max_length=100, null=True)),
                ('TaxingRegion', models.CharField(blank=True, max_length=50, null=True)),
                ('OrderTotalCurrencyCode', models.CharField(blank=True, max_length=3, null=True)),
                ('OrderTotalAmount', models.FloatField(blank=True, null=True)),
                ('IsAddressSharingConfidential', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Заказ Amazon',
                'verbose_name_plural': 'Заказы Amazon',
            },
        ),
        migrations.CreateModel(
            name='AmazonOrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('ASIN', models.CharField(max_length=30)),
                ('OrderItemId', models.CharField(max_length=30)),
                ('SellerSKU', models.CharField(blank=True, max_length=100, null=True)),
                ('Title', models.CharField(blank=True, max_length=255, null=True)),
                ('QuantityOrdered', models.PositiveSmallIntegerField()),
                ('QuantityShipped', models.PositiveSmallIntegerField()),
                ('IsGift', models.BooleanField(blank=True, null=True)),
                ('GiftMessageText', models.CharField(blank=True, max_length=300, null=True)),
                ('GiftWrapLevel', models.CharField(blank=True, max_length=50, null=True)),
                ('ConditionNote', models.CharField(blank=True, max_length=300, null=True)),
                ('ConditionId', models.CharField(blank=True, max_length=30, null=True)),
                ('ConditionSubtypeId', models.CharField(blank=True, max_length=30, null=True)),
                ('IsTransparency', models.BooleanField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='amazon_order.AmazonOrder')),
            ],
            options={
                'verbose_name': 'Товар из заказа Amazon',
                'verbose_name_plural': 'Товары из заказа Amazon',
            },
        ),
        migrations.CreateModel(
            name='TaxClassification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=50)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_classifications', to='amazon_order.AmazonOrder')),
            ],
        ),
        migrations.CreateModel(
            name='ShippingTax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CurrencyCode', models.CharField(max_length=3)),
                ('Amount', models.FloatField()),
                ('order_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_tax', to='amazon_order.AmazonOrderItem')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ShippingPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CurrencyCode', models.CharField(max_length=3)),
                ('Amount', models.FloatField()),
                ('order_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_price', to='amazon_order.AmazonOrderItem')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ShippingDiscount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CurrencyCode', models.CharField(max_length=3)),
                ('Amount', models.FloatField()),
                ('order_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_discount', to='amazon_order.AmazonOrderItem')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PromotionDiscount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CurrencyCode', models.CharField(max_length=3)),
                ('Amount', models.FloatField()),
                ('order_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_discount', to='amazon_order.AmazonOrderItem')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ItemTax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CurrencyCode', models.CharField(max_length=3)),
                ('Amount', models.FloatField()),
                ('order_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='item_tax', to='amazon_order.AmazonOrderItem')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ItemPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CurrencyCode', models.CharField(max_length=3)),
                ('Amount', models.FloatField()),
                ('order_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='item_price', to='amazon_order.AmazonOrderItem')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GiftWrapTax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CurrencyCode', models.CharField(max_length=3)),
                ('Amount', models.FloatField()),
                ('order_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gift_wrap_tax', to='amazon_order.AmazonOrderItem')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GiftWrapPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CurrencyCode', models.CharField(max_length=3)),
                ('Amount', models.FloatField()),
                ('order_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gift_wrap_price', to='amazon_order.AmazonOrderItem')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AmazonShippingAddress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('Name', models.CharField(blank=True, max_length=50, verbose_name='Имя')),
                ('CountryCode', models.CharField(blank=True, default='', max_length=2)),
                ('StateOrRegion', models.CharField(blank=True, default='', max_length=50)),
                ('County', models.CharField(blank=True, default='', max_length=50)),
                ('City', models.CharField(blank=True, default='', max_length=50)),
                ('AddressLine1', models.CharField(blank=True, default='', max_length=100)),
                ('AddressLine2', models.CharField(blank=True, default='', max_length=100)),
                ('AddressLine3', models.CharField(blank=True, default='', max_length=100)),
                ('PostalCode', models.CharField(blank=True, default='', max_length=30)),
                ('Phone', models.CharField(blank=True, max_length=20, null=True)),
                ('AddressType', models.CharField(blank=True, max_length=20, null=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_address', to='amazon_order.AmazonOrder')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
