[tool.poetry]
name = "multi-dash"
version = "0.2.0"
description = "A light framework to make multi-page dash based apps."
authors = ["James Saunders <james@businessoptics.biz>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]
flask = "^1.1"
dash = "^1.1"
pytest = "^5.2"
black = {version = "^18.3-alpha.0",allow-prereleases = true}

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"