# Generated by Django 2.2.5 on 2020-01-17 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ebay_location', '0001_initial'),
        ('ebay_policy', '0001_initial'),
        ('ebay_account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebayuseraccountdefaults',
            name='fulfillmentPolicy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ebay_policy.FulfillmentPolicy', verbose_name='Политика фулфилмента по умолчанию'),
        ),
        migrations.AddField(
            model_name='ebayuseraccountdefaults',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ebay_location.EbayLocation', verbose_name='Склад по умолчанию'),
        ),
        migrations.AddField(
            model_name='ebayuseraccountdefaults',
            name='paymentPolicy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ebay_policy.PaymentPolicy', verbose_name='Политика оплаты по умолчанию'),
        ),
        migrations.AddField(
            model_name='ebayuseraccountdefaults',
            name='returnPolicy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ebay_policy.ReturnPolicy', verbose_name='Политика возврата по умолчанию'),
        ),
    ]
