
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-01-23T16:03:49-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "d9b1c69080ca1e43545c243345f4a862c131b8e6",
 "version": "0.0.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
