language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"

# command to install dependencies
install:
  - pip install -qq pytest
  - pip install -qq "pytest-cov<2.6"
  - pip install -qq pycodestyle
  - pip install -qq python-coveralls
  - pip install -qq future
  - pip install --upgrade pip

# command to run tests
script:
  - py.test --cov=py_linq
  - pycodestyle --ignore=E501 --max-line-length=88 py_linq tests

after_success:
  - coveralls
