[tool.poetry]
name = "django-fahrenheit"
version = "0.1.3"
description = "A tool for easily restrict access to some project URLs or even objects for legal reasons."
authors = [
    "Mikhail Porokhovnichenko <marazmiki@gmail.com>"
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Environment :: Web Environment",
    "Framework :: Django",
    "Framework :: Django :: 2.1",
    "Framework :: Django :: 2.2",
    "Framework :: Django :: 3.0",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Topic :: Internet :: WWW/HTTP",
    "Topic :: Internet :: WWW/HTTP :: Dynamic Content",
    "Topic :: Software Development :: Libraries :: Python Modules",
]
license = "MIT"
readme = "README.rst"
homepage = "https://github.com/marazmiki/django-fahrenheit"
repository = "https://github.com/marazmiki/django-fahrenheit"
keywords = ["django", "fahrenheit", "451", "government", "censorship", "legal", "restriction", "deny"]


[tool.poetry.dependencies]
python = "^3.6"
geoip2 = "^2.9"
django-generic-helpers = "^1.0"

[tool.poetry.dev-dependencies]
pytest = "^5.0"
pytest-django = "^3.4"
pytest-env = "^0.6.2"
pytest-isort = "^0.3.1"
pytest-pythonpath = "^0.7.3"
pytest-flake8 = "^1.0"
pytest-cov = "^2.7"
pylint = "^2.4.4"
bump2version = "^0.5.11"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
