
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-01-23T19:05:52+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "9909e23a1e7b444627546a9e1b24d1e270c233b4",
 "version": "1.23.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
