# Generated by Django 2.2.5 on 2020-01-23 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etsy_policy', '0004_auto_20200123_1150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etsyshippingtemplate',
            name='origin_country',
        ),
        migrations.RemoveField(
            model_name='etsyshippingtemplateentry',
            name='destination_country',
        ),
        migrations.RemoveField(
            model_name='etsyshippingtemplateentry',
            name='destination_region',
        ),
    ]
