# Generated by Django 2.2.5 on 2020-01-23 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etsy_policy', '0006_auto_20200123_1207'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='etsyshippingtemplate',
            constraint=models.UniqueConstraint(fields=('marketplace_user_account', 'title'), name='unique_marketplace_user_account_and_name'),
        ),
    ]
