# Generated by Django 2.2.5 on 2020-01-27 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etsy_policy', '0010_auto_20200127_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etsyshippingtemplate',
            name='shipping_template_id',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='ID политики доставки'),
        ),
        migrations.AlterField(
            model_name='etsyshippingtemplateentry',
            name='shipping_template_entry_id',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='ID записи политики доставки'),
        ),
    ]
