
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-02-03T17:14:50-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "5c1cb4f1765f35a6675781138622a111edc9c3a3",
 "version": "0.6.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
