
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-01-22T12:56:16+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "e8268ed5c344ba0fd5ec2236a6343057ed4fe93d",
 "version": "0.4.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
