[tool.poetry]
name = "hadrosaur"
version = "0.0.1"
description = ""
authors = ["Jay R Bolton <jayrbolton@gmail.com>"]

[tool.poetry.dependencies]
python = ">=3.6"

[tool.poetry.dev-dependencies]
pytest = "5.3.5"
