# Generated by Django 2.2.5 on 2020-01-17 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ebay_listing', '0002_auto_20200117_1440'),
        ('ebay_negotiation', '0001_initial'),
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebaymessage',
            name='marketplace_user_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ebay_member_messages', related_query_name='ebay_member_message', to='marketplace.MarketplaceUserAccount', verbose_name='Пользовательский аккаунт маркетплейса'),
        ),
        migrations.AddField(
            model_name='ebayeligibleitem',
            name='ebay_product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='eligible_item', to='ebay_listing.EbayListing', verbose_name='Товар eBay'),
        ),
        migrations.AddField(
            model_name='ebaybuyerofferprice',
            name='offered_item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='price', to='ebay_negotiation.EbayBuyerOfferedItem', verbose_name='Предлагаемый товар'),
        ),
        migrations.AddField(
            model_name='ebaybuyeroffereditem',
            name='eligibleItem',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ebay_negotiation.EbayEligibleItem', verbose_name='Желаемый товар'),
        ),
        migrations.AddField(
            model_name='ebaybuyeroffereditem',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offered_items', related_query_name='offered_item', to='ebay_negotiation.EbayBuyerOffer', verbose_name='Предложение покупателю'),
        ),
        migrations.AddField(
            model_name='ebaybuyerofferduration',
            name='offer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='duration', to='ebay_negotiation.EbayBuyerOffer', verbose_name='Предложение покупателям'),
        ),
    ]
