- |
    __perc__!TEX TS-program = xelatex
    \documentclass[english,a4paper,11pt]{article}
    \usepackage[margin=3cm,a4paper]{geometry}
    \usepackage{graphicx}
    \usepackage{amssymb}
    \usepackage[utf8]{inputenc}
    \usepackage[norsk]{babel}
    \usepackage{color}
    \usepackage{xcolor}
    \usepackage{array}
    \usepackage{wrapfig}
    \usepackage{calc}
    \usepackage{hyperref}
    \usepackage{xspace}
    \usepackage{parskip}
    \usepackage{fancyhdr}
    \usepackage{longtable}
    \usepackage{needspace} \def\cvneedspaceconst{5}
    \fancyhf{}
    \renewcommand{\headrulewidth}{0pt}
    \cfoot[\fancyplain{}{\footnotesize\thepage}]{
    \includegraphics[width=5cm]{footer.pdf}
    }
    \definecolor{xalblue}{rgb}{0.1719,0.3516,0.6250}
    \definecolor{xaldark}{rgb}{0.1290,0.2566,0.4688}
    \definecolor{lightgray}{gray}{0.8}
    \renewcommand*{\familydefault}{\sfdefault}
    \newcolumntype{L}{>{\raggedright}p{0.16\textwidth}}
    \newcolumntype{R}{p{0.74\textwidth}}
    \newcommand\VRule{\color{lightgray}\vrule width 0.5pt}
    \usepackage{titlesec}
    \newcommand\secformat[1]{\normalfont\Large\bfseries\color{xalblue}#1}
    \titleformat{name=\section}[block]{}{}{}{\secformat}
    \begin{document}
    \pagestyle{fancy}
    \pagenumbering{gobble}
    \vspace*{%(logo_top)s}
    \hspace*{%(logo_left)s}\includegraphics[width=%(logo_width)s]{logo.pdf}
    \vspace*{%(logo_margin)s}

    \noindent
    {\LARGE \bfseries \color{xaldark}Curriculum Vitae for %(Name)s}

    %(Basic)s%(Summary)s%(Skills)s%(Education)s%(Courses)s%(Work)s%(Languages)s%(SelectedSkills)s%(Interests)s%(Projects)s%(Publications)s

    \end{document}
- logo_top: "%s"
  logo_left: "%s"
  logo_width: "%s"
  logo_margin: "%s"
  Name: "%s"
  Basic:
    - |
        \Needspace{\cvneedspaceconst\baselineskip}
        \section*{Personal information}
        \begin{minipage}[t]{0.4\textwidth}
        \begin{tabbing}Nationality---\=olaf\kill
        %(Address)s%(Post)s%(Birth)s\end{tabbing}
        \end{minipage}
        $\quad\quad$
        \begin{minipage}[t]{0.3\textwidth}
        \begin{tabbing}Nationality---\=olaf\kill
        %(Email)s%(Phone)s%(Nationality)s
        \end{tabbing}
        \end{minipage}
    - Name: |
        Name: \> %s \\

      Address: |
        Address: \> %s \\
      Post: |
        \> %s \\
      Birth: |
        Born: \>%s \\

      Email: |
        E-mail: \>%s \\

      Phone: |
        Phone: \>%s \\

      Nationality: |
        Nationality: \>%s \\

  Summary: "\n\n\\section*{Summary}\n\n%s\\\\\n"
  Skills:
    - - |
        \Needspace{\cvneedspaceconst\baselineskip}
        \section*{Technical skills}
        \begin{longtable}{LR}
      - ""
      - "\\end{longtable}\n\n"
    - - - ""
        - " & "
        - "\\\\ \n"
      - - ""
        - ", "
        - ""
  Languages:
    - - |
        \Needspace{\cvneedspaceconst\baselineskip}
        \section*{Languages}
        \begin{longtable}{LR}
      - ""
      - "\\end{longtable}\n\n"
    - - - ""
        - " & "
        - "\\\\ \n"
      - "%s"
  Courses:
    - - |
        \Needspace{\cvneedspaceconst\baselineskip}
        \section*{Courses}
        \begin{longtable}{LR}
      - ""
      - "\\end{longtable}\n\n"
    - - - ""
        - " & "
        - "\\\\ \n"
      - "%s"
  SelectedSkills:
    - - |
        \Needspace{\cvneedspaceconst\baselineskip}
        \section*{Personal skills}
        \begin{longtable}{LR}

      - ""
      - "\\end{longtable}\n\n"
    - - - ""
        - " & "
        - "\\\\ \n"
      - "%s"
  Interests:
    - - |
        \Needspace{\cvneedspaceconst\baselineskip}
        \section*{Some interests and hobbies}
        \begin{longtable}{LR}
      - ""
      - "\\end{longtable}\n\n"
    - - - ""
        - " & "
        - "\\\\ \n"
      - - ""
        - ", "
        - ""
  Education:
    - - |
        \Needspace{\cvneedspaceconst\baselineskip}
        \section*{Education}
        \begin{longtable}{LR}
      - ""
      - "\\end{longtable}\n\n"
    - - - ""
        - " -- "
        - " & "
        - "\\\\ \n"
      - "%s"
  Work:
    - - |
        \Needspace{\cvneedspaceconst\baselineskip}
        \section*{Professional experience}
        \begin{longtable}{LR}
      - ""
      - "\\end{longtable}\n\n"
    - - - ""
        - " -- "
        - " & "
        - "\\\\ \n"
      - "%s"
  Projects:
    - - |
        \Needspace{\cvneedspaceconst\baselineskip}
        \section*{Extended descriptions of selected projects}
        \begin{longtable}{@{}LR}
      - |
        \end{longtable}

        \begin{longtable}{@{}LR}
      - "\\end{longtable}\n"
    - A:
        - "%(Activity)s%(Period)s%(Role)s%(Staffing)s%(Volume)s%(Description)s%(Tools)s"
        - Activity: "Activity & %s \\\\ \n"
          Period: "Period & %s \\\\ \n"
          Role: "Role & %s \\\\ \n"
          Staffing: "Staffing & %s \\\\ \n"
          Volume: "Volume & %s \\\\ \n"
          Description: "Description & %s \\\\ \n"
          Tools: "Tools & %s \\\\ \n"
  Publications:
     - - |
         \Needspace{\cvneedspaceconst\baselineskip}
         \section*{Publications}
         \begin{longtable}{@{}LR}
       - |
         \end{longtable}

         \begin{longtable}{@{}LR}
       - "\\end{longtable}\n"
     - B:
         - "%(Journal)s%(Date)s%(Authors)s%(Title)s%(Summary)s%(DOI)s"
         - Journal: "Journal & %s \\\\ \n"
           Date: "Date & %s \\\\ \n"
           Authors: "Authors & %s \\\\ \n"
           Title: "Title & %s \\\\ \n"
           Summary: "Summary & %s \\\\ \n"
           DOI: "DOI & %s \\\\ \n"
