---

- name: Manage BoxBackup service
  collections: [ 'debops.debops' ]
  hosts: [ 'debops_service_boxbackup' ]
  become: True

  environment: '{{ inventory__environment | d({})
                   | combine(inventory__group_environment | d({}))
                   | combine(inventory__host_environment  | d({})) }}'

  roles:

    - role: boxbackup
      tags: [ 'role::boxbackup', 'skip::boxbackup' ]
