---

- name: Manage Monit service
  collections: [ 'debops.debops' ]
  hosts: [ 'debops_service_monit' ]
  become: True

  environment: '{{ inventory__environment | d({})
                   | combine(inventory__group_environment | d({}))
                   | combine(inventory__host_environment  | d({})) }}'

  roles:

    - role: monit
      tags: [ 'role::monit', 'skip::monit' ]
