---

- name: Manage custom resources
  collections: [ 'debops.debops' ]
  hosts: [ 'debops_all_hosts', 'debops_service_resources' ]
  become: True

  environment: '{{ inventory__environment | d({})
                   | combine(inventory__group_environment | d({}))
                   | combine(inventory__host_environment  | d({})) }}'

  roles:

    - role: resources
      tags: [ 'role::resources', 'skip::resources' ]
