---

- name: Configure secret storage space
  collections: [ 'debops.debops' ]
  hosts: [ 'debops_all_hosts' ]
  become: True

  environment: '{{ inventory__environment | d({})
                   | combine(inventory__group_environment | d({}))
                   | combine(inventory__host_environment  | d({})) }}'

  roles:

    - role: secret
      tags: [ 'role::secret' ]
