
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-01-28T15:14:52+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "adf747aae20d3467b1beceb6f54b2b3cf13716b5",
 "version": "0.1.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
