
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-02-01T17:17:53-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "ed30328af5da672919f227efb3d2a674deaee7ab",
 "version": "0.3.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
