language: python
cache: pip
dist: xenial

matrix:
  include:
    - name: Lint
      python: 3.7
      # env: TOXENV=black,flake8,isort
      env: TOXENV=black
    - name: Build docs
      python: 3.7
      env: TOXENV=build_docs
    - name: Run examples
      python: 3.7
      env: TOXENV=examples
    - os: osx
      language: shell
      osx_image: xcode11.2  # Python 3.7.4
      env: TOXENV=py37
    - os: linux
      python: 3.6
      env: TOXENV=py36
    - os: linux
      python: 3.7
      env: TOXENV=py37

install:
  - pip3 install tox

script:
  - tox
