[tool.poetry]
name = "ccautils"
version = "0.1.1"
description = "A set of useful utilities for python programs"
authors = ["ccdale <chris.charles.allison+ccautils@gmail.com>"]
license = "GPL-3.0-or-later"

[tool.poetry.dependencies]
python = "^3.6"
toml = "^0.10.0"

[tool.poetry.dev-dependencies]
pytest = "^5.3.5"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
