# Generated by Django 2.2.5 on 2020-01-30 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etsy_order', '0002_auto_20200130_1406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etsyreceipttransaction',
            name='id',
        ),
        migrations.AlterField(
            model_name='etsyreceipttransaction',
            name='buyer_user_id',
            field=models.PositiveIntegerField(verbose_name='ID покупателя'),
        ),
        migrations.AlterField(
            model_name='etsyreceipttransaction',
            name='seller_user_id',
            field=models.PositiveIntegerField(verbose_name='ID продавца'),
        ),
        migrations.AlterField(
            model_name='etsyreceipttransaction',
            name='transaction_id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
