
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-02-05T17:04:17-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "415b8aa255c766bd876e2b0efc643593e4352f28",
 "version": "0.0.60"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
