[tool.poetry]
name = "aeidon"
version = "1.7.0"
description = "aeidon is a Python package for reading, writing and manipulating text-based subtitle files. It is used by the gaupol package, which provides a subtitle editor with a GTK+ user interface."
authors = ["Jack Laxson <jackjrabbit+pypi@gmail.com>", "Osmo Salomaa <otsaloma@iki.fi>"]
packages = [{include = "aeidon"}]
license = "GPL-3.0+"
documentation = "https://otsaloma.io/gaupol/doc/api/aeidon.html"
repository =  "https://github.com/jrabbit/gaupol"
homepage = "https://otsaloma.io/gaupol/"

[tool.poetry.dependencies]
python = "^3.5"
chardet = "^3.0"

[tool.poetry.dev-dependencies]
pytest = "^5.0"
flake8 = "^3.7"


[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
