[tool.poetry]
name = "sudosearch"
version = "0.3.0"
description = "Google Crawler and Keyword Checker"
authors = ["John Aldrich Bernardo <4ldrich@protonmail.com>"]

[tool.poetry.dependencies]
python = "^3.6"
spacy = "2.2.3"

[tool.poetry.dev-dependencies]
pytest = "^4.6"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

