# Generated by Django 2.0.6 on 2018-10-05 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20171226_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_premium_checkout',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_replay_upload',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_site_activity',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
