
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-01-26T15:12:31-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "57d5f513c8b762bf9845b82507d7b2f17459694a",
 "version": "3.0a0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
