# Generated by Django 2.2.5 on 2020-01-17 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ebay_account', '0002_auto_20200117_1440'),
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebayuseraccount',
            name='marketplace_user_account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ebay_user_account', to='marketplace.MarketplaceUserAccount'),
        ),
        migrations.AddField(
            model_name='ebayratelimitsresourcerate',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='ebay_account.EbayRateLimitsResource'),
        ),
        migrations.AddField(
            model_name='ebayratelimitsresource',
            name='rate_limits',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='ebay_account.EbayUserRateLimits'),
        ),
        migrations.AddField(
            model_name='businessaddress',
            name='business_account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='ebay_account.BusinessAccount'),
        ),
        migrations.AddField(
            model_name='businessaccount',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='businessAccount', to='ebay_account.EbayUserAccountProfile'),
        ),
        migrations.AddField(
            model_name='individualsecondaryphone',
            name='individual_account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='secondaryPhone', to='ebay_account.IndividualAccount'),
        ),
        migrations.AddField(
            model_name='individualregistrationaddress',
            name='individual_account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='registrationAddress', to='ebay_account.IndividualAccount'),
        ),
        migrations.AddField(
            model_name='individualprimaryphone',
            name='individual_account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='primaryPhone', to='ebay_account.IndividualAccount'),
        ),
        migrations.AddField(
            model_name='individualaccount',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='individualAccount', to='ebay_account.EbayUserAccountProfile'),
        ),
        migrations.AddField(
            model_name='businesssecondaryphone',
            name='business_account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='secondaryPhone', to='ebay_account.BusinessAccount'),
        ),
        migrations.AddField(
            model_name='businessprimaryphone',
            name='business_account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='primaryPhone', to='ebay_account.BusinessAccount'),
        ),
        migrations.AddField(
            model_name='businessprimarycontact',
            name='business_account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='primaryContact', to='ebay_account.BusinessAccount'),
        ),
    ]
