# Generated by Django 2.2.4 on 2019-12-01 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_magnificent_messages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'default_permissions': (), 'ordering': ('-created',), 'permissions': (('send_message', 'Send message'), ('view_all_message', 'View all messages'), ('delete_any_message', 'Delete any messages'))},
        ),
    ]
