# Generated by Django 3.0.2 on 2020-01-19 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_magnificent_messages', '0002_auto_20191201_1245'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='raw_text',
            new_name='text',
        ),
    ]
