[tool.poetry]
name = "carte"
version = "0.2.2"
description = "Carte is a flexible, extensible reverse-geocode library."
authors = ["Payson Wallach <payson@fourpeaksstudios.com>"]
license = "LGPL-2.1-or-later"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.7"
appdirs = "^1.4.3"
initable = "^0.2.0"
scipy = "^1.4.1"

[tool.poetry.dev-dependencies]
black = "^19.10b0"
pytest = "^5.3.2"

[tool.black]
line-length = 79
include = '\.pyi?$'
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
