
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-01-28T10:41:26-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "d75bfcbbc0fa88001f7bcfd9de4a865b63057f58",
 "version": "3.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
