
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-01-31T14:30:23-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "19bddf23de820822567e9df9a395482d888ac897",
 "version": "0.3.0.a3.post1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
