# Generated by Django 2.2.5 on 2020-01-24 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ebay_account', '0004_auto_20200124_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebayappratelimits',
            name='ebay_app_account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rate_limits', to='ebay_account.EbayAppAccount'),
            preserve_default=False,
        ),
    ]
