
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-02-05T16:25:49-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "051957f7606d8d829bc681c7449a2120b09fcc91",
 "version": "0.0.59"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
