variables:
- group: pypi-info

trigger:
  branches:
    include:
      - master
  tags:
    include:
      - v*

stages:
- stage: Test
  jobs:
  - job: Test
    strategy:
      matrix:
        Python27-windows:
          python-version: '2.7'
          platform: windows-latest
        Python35-windows:
          python-version: '3.5'
          platform: windows-latest
        Python36-windows:
          python-version: '3.6'
          platform: windows-latest
        Python37-windows:
          python-version: '3.7'
          platform: windows-latest
        Python38-windows:
          python-version: '3.8'
          platform: windows-latest
        Python27:
          python-version: '2.7'
          platform: ubuntu-latest
        Python35:
          python-version: '3.5'
          platform: ubuntu-latest
        Python36:
          python-version: '3.6'
          platform: ubuntu-latest
        Python37:
          python-version: '3.7'
          platform: ubuntu-latest
        Python38:
          python-version: '3.8'
          platform: ubuntu-latest
        PyPy:
          python-version: 'pypy2'
          platform: ubuntu-latest
        PyPy3:
          python-version: 'pypy3'
          platform: ubuntu-latest
    pool:
      vmImage: $(platform)

    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(python-version)'
      displayName: 'Use Python $(python-version)'
    - script: |
        python -m pip install --upgrade --user pip setuptools tox
      displayName: 'Install dependencies'
    - script: |
        python -m tox -vv -epy
      displayName: 'Test'
    - script: |
        python -m tox -elint
      displayName: 'Lint'
      condition: and(succeeded(), eq(variables['python-version'], '3.8'), eq(variables['platform'], 'ubuntu-latest'))

- ${{ if startsWith(variables['Build.SourceBranch'], 'refs/tags/') }}:
  - stage: Deploy
    dependsOn: [Test]
    condition: succeeded()
    variables:
      python-version: '3.8'
    jobs:
    - job: deploy
      pool:
        vmImage: ubuntu-latest
      steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '$(python-version)'
        displayName: 'Use Python $(python-version)'

      - script: |
          python -m pip install --user --upgrade pip setuptools wheel tox twine
        displayName: 'Install dependencies'

      - script: |
          python setup.py sdist bdist_wheel
          python -m twine upload dist/*
        env:
          TWINE_USERNAME: $(TWINE_USERNAME)
          TWINE_PASSWORD: $(TWINE_PASSWORD)
          TWINE_REPOSITORY_URL: $(TWINE_REPOSITORY_URL)
        displayName: 'Push to Python Package Index'

      - task: InstallSSHKey@0
        inputs:
          hostName: 'github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ=='
          sshPublicKey: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDFJni31fgrXUYAq1bwM7XD8oCc5nCpv83IP52/GMaimakRv5mUUoTGJA4N/3WjNyB5rGrbvcB7T2bFpvsznibQpMuKYCf+Z0ziY1hMdaV3BcjD8hLuEUUSQ1KtIcZqONcvFEbATd2kyhWB2P8ixQrHEeaZ7REr/ftCsn9vGcso0RPz5G3PebkEBZusmeH9lZPzi3CFJdqgl/+U88GuIDze3wDU9vAFOx/vLGVAd7SiM+TlrJ2LlIAtXxFmRkGn2yQhHv6by0Mjt87EyK9Fx/LY/JTtrd2mAiZoxuIDLb0tQZHTMqnPuoHYh0C2PL9yvxMUMSlcDFg1M/EnVgO/2i9N'
          sshKeySecureFile: 'newrelic-telemetry-sdk-python#deploy_key'

      - script: |
          git config --local user.name "Azure Pipelines"
          git config --local user.email "bot@bot.localhost"
          git remote add upstream git@github.com:newrelic/newrelic-telemetry-sdk-python.git
          git fetch upstream gh-pages && git worktree add -B gh-pages docs/_build upstream/gh-pages
        displayName: 'Prepare git directory for docs'

      - script: |
          python -m tox -edocs
        displayName: 'Generate docs'

      - script: |
          cd docs/_build && git add --all && git commit -m "Publishing docs to gh-pages" && git push
        displayName: 'Publish Docs'
