[tool.poetry]
name = "autosys"
version = "1.3.0"
description = "System utilities for Python on macOS"
authors = ["skeptycal <skeptycal@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
pytest = "^5.3.5"
pylint = "^2.4.4"
requests = "^2.22.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
