# Generated by Django 2.2.5 on 2020-01-17 11:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AmazonUserAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('access_token', models.CharField(max_length=2500, verbose_name='Токен доступа')),
            ],
            options={
                'verbose_name': 'Пользовательский токен для Amazon',
                'verbose_name_plural': 'Пользовательские токены для Amazon',
            },
        ),
    ]
