
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-01-28T14:25:56+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "00411de4ed290dd05efe9a2cef2054fcdba027b9",
 "version": "v1.0.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
