
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-02-06T14:12:09-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "aec423327a5ab9907a26302471d41452e867231a",
 "version": "2.0a1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
