[tool.poetry]
name = "django-component"
version = "0.1.0"
description = "Django template tags to create composable components"
authors = ["Jérôme Bon <bon.jerome@protonmail.com>"]

[tool.poetry.dependencies]
python = "^3.6"
django = ">=1.11"


[tool.poetry.dev-dependencies]
pytest = "^4.1"
tox = "^3.0"
mypy = "^0.761"
black = "^19.10b0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
