[tool.pdm]
name = "pdm"
version = "0.0.6"
description = "Python Development Master"
author = "frostming <mianghong@gmail.com>"
license = "MIT"
python_requires = ">=3.7"
readme = "README.md"

homepage = "https://github.com/pdm-project/pdm"
repository = "https://github.com/pdm-project/pdm"

keywords = ["packaging", "dependency", "workflow"]

classifiers = [
    "Topic :: Software Development :: Build Tools",
    "Topic :: Software Development :: Libraries :: Python Modules"
]

[tool.pdm.dependencies]
# TODO: update pip and pip_shims version
appdirs = "*"
click = "*"
distlib = "*"
pip = "<20.0.0,>=19.3.1"
pip_shims = "~=0.4.0"
pythonfinder = "*"
tomlkit = "*"
halo = "<1.0.0,>=0.0.28"

[tool.pdm.dev-dependencies]
pytest = "*"
pytest-cov = "*"
pytest-mock = "*"

[tool.pdm.cli]
pdm = "pdm.cli.commands:cli"

[tool.intreehooks]
build-backend = "pdm.builders.api"

[tool.coverage.run]
branch = true
omit = ["pdm/__main__.py"]

[tool.coverage.report]
# Regexes for lines to exclude from consideration
exclude_lines = [
    "pragma: no cover",
    # Don't complain about missing debug-only code:
    "def __repr__",
    "if self.debug",
    # Don't complain if tests don't hit defensive assertion code:
    "raise AssertionError",
    "raise NotImplementedError",
    # Don't complain if non-runnable code isn't run:
    "if __name__ == .__main__.:"
]
ignore_errors = true

[tool.isort]
line_length = 88
multi_line_output = 3
include_trailing_comma = true
use_parentheses = true
force_grid_wrap = 0
atomic = true
not_skip = "__init__.py"
skip_glob = ["*/setup.py"]
filter_files = true
known_first_party = "pdm"
known_third_party = "pip_shims"

[tool.black]
line-length = 88
[build-system]
requires = ["intreehooks"]
build-backend = "intreehooks:loader"

