[tool.poetry]
name = "equium"
version = "0.0.1"
description = "Experimenting with Equality"
authors = ["John Paulett <john@paulett.org>"]
license = "BSD-3-Clause"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.7"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
