# Generated by Django 2.2.5 on 2020-01-17 11:40

from django.db import migrations, models
import django.db.models.deletion
import uuid
import zonesmart.utils.upload


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=80, verbose_name='Название канала продаж')),
            ],
            options={
                'verbose_name': 'Канал продаж пользователя',
                'verbose_name_plural': 'Каналы продаж пользователей',
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название домена')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='Описание домена')),
                ('url', models.URLField(blank=True, null=True, verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Домен',
                'verbose_name_plural': 'Домены',
            },
        ),
        migrations.CreateModel(
            name='Marketplace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название маркетплейса')),
                ('unique_name', models.CharField(max_length=50, unique=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to=zonesmart.utils.upload.get_marketplace_icon_upload_path, verbose_name='Иконка маркетплейса')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='Описание маркетплейса')),
            ],
            options={
                'verbose_name': 'Маркетплейс',
                'verbose_name_plural': 'Маркетплейсы',
            },
        ),
        migrations.CreateModel(
            name='MarketplaceUserAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('marketplace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_user_accounts', related_query_name='marketplace_user_account', to='marketplace.Marketplace', verbose_name='Маркетплейс')),
            ],
            options={
                'verbose_name': 'Аккаунт маркетплейса',
                'verbose_name_plural': 'Аккаунты маркетплейсов',
            },
        ),
    ]
