# Generated by Django 2.2.5 on 2020-01-17 11:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('text', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name': 'Анонс',
                'verbose_name_plural': 'Анонсы',
                'ordering': ['published'],
            },
        ),
    ]
