# Generated by Django 2.2.5 on 2020-01-17 11:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid
import zonesmart.utils.upload


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SupportRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', model_utils.fields.StatusField(choices=[('NEW', 'Ожидает рассмотрения'), ('WAITING_FOR_HELPER', 'Ожидает ответа оператора'), ('WAITING_FOR_USER', 'Ожидает ответа пользователя'), ('CLOSED_BY_USER', 'Закрыта пользователем'), ('CLOSED_BY_TIMEOUT', 'Закрыта по истечению времени')], default='NEW', max_length=100, no_check_for_status=True, verbose_name='status')),
                ('status_changed', model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', verbose_name='status changed')),
                ('title', models.CharField(max_length=100, verbose_name='Тема заявки')),
            ],
            options={
                'verbose_name': 'Заявка в службу поддержки',
                'verbose_name_plural': 'Заявки в службу поддержки',
            },
        ),
        migrations.CreateModel(
            name='SupportRequestMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('message', models.TextField(max_length=1500, verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
                'ordering': ['modified'],
            },
        ),
        migrations.CreateModel(
            name='SupportRequestMessageFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('file', models.FileField(upload_to=zonesmart.utils.upload.get_support_file_upload_path, verbose_name='Приложенный файл')),
                ('support_request_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', related_query_name='file', to='support.SupportRequestMessage', verbose_name='Заявка')),
            ],
            options={
                'verbose_name': 'Приложенный к сообщению файл',
                'verbose_name_plural': 'Приложенные к сообщению файлы',
            },
        ),
    ]
