# Generated by Django 3.0.2 on 2020-01-31 11:52

import aligo_sms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_at', models.DateTimeField(auto_now_add=True, verbose_name='요청일시')),
                ('sender', models.CharField(max_length=16, verbose_name='발신자 전화번호')),
                ('receiver', models.CharField(max_length=16, verbose_name='수신자 전화번호')),
                ('msg', models.TextField(verbose_name='메시지 내용')),
                ('title', models.CharField(blank=True, max_length=44, null=True, verbose_name='메시지 제목')),
                ('debug', models.BooleanField(blank=True, default=aligo_sms.models.is_debug, null=True, verbose_name='테스트모드')),
                ('msg_type', models.CharField(blank=True, choices=[('SMS', 'SMS'), ('LMS', 'LMS'), ('MMS', 'MMS')], max_length=3, null=True, verbose_name='메시지 구분')),
                ('result', models.NullBooleanField(default=None, verbose_name='발송결과')),
                ('result_code', models.IntegerField(blank=True, null=True, verbose_name='결과코드')),
                ('result_message', models.TextField(blank=True, null=True, verbose_name='결과 메세지')),
                ('result_message_id', models.IntegerField(blank=True, null=True, verbose_name='메시지 고유 아이디')),
            ],
            options={
                'verbose_name': '발송기록',
                'verbose_name_plural': '발송기록',
                'ordering': ('-registered_at',),
            },
        ),
    ]
