[tool.poetry]
name = "openstates_metadata"
version = "2020.01.31"
description = "metadata for the openstates project"
authors = ["James Turk <james@openstates.org>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/openstates/metadata"
repository = "https://github.com/openstates/metadata"
include = [
    "LICENSE",
]

[tool.poetry.dependencies]
python = "^3.7"
pyyaml = "^5.3"
attrs = "^19.3"
us = "^1.0"

[tool.poetry.dev-dependencies]
flake8 = "^3.7"
pytest = "^5.3"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
