
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "d20a3c469e2152407a5b0796a15bfbbbc9c54afe",
 "version": "0.0.22"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
