
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-01-31T14:35:26-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "c85cf7b6adba336a6db3f7cd9a9d0eb9a0e1063f",
 "version": "1.46.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
