
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-01-27T12:54:59-0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "665755cfb8a45217c93b7188a641d83e7474c909",
 "version": "v0.2.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
