[tool.poetry]
name = "py-terminal-notifier"
version = "0.1.1"
description = "A python wrapper for terminal-notifier"
authors = ["flomk <sudogitrekt@gmail.com>"]
keywords=['py-terminal-notifier', 'terminal-notifier', 'terminal', 'notifier']

[tool.poetry.dependencies]
python = "^3.7"


[tool.poetry.dev-dependencies]
pytest = "^5.2"



[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
