[tool.poetry]
name = "aimapper"
version = "0.1.0"
description = "Python package for the adaptively-integrated intensity map (AIMAP) method"
authors = ["Akio Taniguchi <taniguchi@a.phys.nagoya-u.ac.jp>"]

[tool.poetry.dependencies]
python = "^3.6"
astropy = "^4.0"
numpy = "^1.18.1"
scipy = "^1.4.1"

[tool.poetry.dev-dependencies]
black = "^19.10b0"
flake8 = "^3.7.9"
ipython = "^7.11.1"
jupyter = "^1.0.0"
jupyterlab = "^1.2.6"
jupyter-io = "^0.1.1"
matplotlib = "^3.1.2"
pytest = "^5.3.4"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
