stages:
- ingest

.image:
  image:
    name: $IMAGE
    entrypoint: ["start.sh"]
  stage: ingest
  tags: [data, docker]

fullscan:
  extends: .image
  script:
  - datafaucet run --timeout=-1 --profile=prod src/fullscan.ipynb
  only:
  - triggers

daily:
  extends: .image
  script:
  - datafaucet run --timeout=-1 --profile=prod src/daily.ipynb
  only:
  - schedules
  - web
