
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-01-28T14:53:52-0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "af53c908ae4e54160dc628f546e9aeed5f5c701a",
 "version": "0.8.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
