[tool.poetry]
name = "pytest-chdir"
version = "0.1.1"
description = "A pytest fixture for changing current working directory"
authors = ["Masahiro Wada <argon.argon.argon@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.6"
pytest = "^5.0.0"

[tool.poetry.dev-dependencies]
pytest-datadir = "^1.3.1"
pre-commit = "^1.21.0"
pytest-mypy = "^0.4.2"
pytest-black = "^0.3.7"
pytest-cov = "^2.8.1"
bandit = "^1.6.2"

[tool.black]
multi_line_output=3
include_trailing_comma=true
force_grid_wrap=0
use_parentheses=true
line_length=88
target-version = ['py36']
include = '\.pyi?$'
exclude = '''

(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
  )/
  | foo.py           # also separately exclude a file named foo.py in
                     # the root of the project
)
'''

[tool.poetry.plugins.pytest11]
pytest-chdir = "pytest_chdir.plugin"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
