# This file is automatically generated, DO NOT EDIT
# fmt: off

from os.path import abspath, join, dirname
_root = abspath(dirname(__file__))

# runtime dependencies
import wpilib._init_wpilib
import wpiutil._init_wpiutil
from ctypes import cdll

_lib = cdll.LoadLibrary(join(_root, "lib", "SparkMaxDriver.dll"))
