# Generated by Django 2.2.5 on 2020-01-17 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('amazon_category', '0001_initial'),
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazoncategorytree',
            name='domain',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='marketplace.Domain', verbose_name='Домен маркетплейса'),
        ),
        migrations.AddField(
            model_name='amazoncategoryaspect',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aspects', to='amazon_category.AmazonCategory', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='amazoncategory',
            name='category_tree',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amazon_product_categories', to='amazon_category.AmazonCategoryTree', verbose_name='Дерево категорий товаров Amazon'),
        ),
        migrations.AddConstraint(
            model_name='amazoncategory',
            constraint=models.UniqueConstraint(fields=('id_path', 'category_tree'), name='unique_amazon_category_id_for_tree'),
        ),
    ]
