FM_DICT = {'AgricultureFishingForestry': ['agriculture_fishing_and_forestry',
                                          'food_feed_and_tobacco_wholesale_and_distribution',
                                          'support_services_for_crop_production',
                                          'agriculture_and_fishing_equipment', 'forestry_and_industrial_crops',
                                          'fishing_and_aquaculture', 'fish_and_seafood_distribution_and_retail',
                                          'livestock_and_livestock_products', 'livestock_for_food', 'fishing',
                                          'livestock_food_products', 'support_services_for_livestock_production',
                                          'livestock_fur_and_goods', 'tobacco_and_alcohol_crops',
                                          'livestock_and_livestock_products_wholesale_and_distribution',
                                          'animal_feed_production', 'fertilizer', 'floriculture',
                                          'timber_and_logging', 'food_feed_and_tobacco_crops',
                                          'pesticides_and_herbicides',
                                          'agricultural_fishing_and_forestry_equipment', 'industrial_crops'],
           'BusinessServices': ['market_research', 'commercial_loans', 'waste_and_recycling', 'telecom', 'research',
                                'equipment_services', 'facility_management', 'maintenance_and_repair',
                                'sales_and_crm_software', 'ground_shipping', 'hiring_and_training', 'marine_shipping',
                                'land_surveying', 'call_centers', 'general_research',
                                'business_directories_and_databases', 'it_services', 'printing_and_document_services',
                                'hr_and_employee_services', 'accounting_and_taxes', 'diversified_shipping',
                                'air_shipping', 'consulting', 'hazardous_waste_collection_and_disposal',
                                'hr_management', 'business_events_and_associations', 'equipment_rental',
                                'graphic_design', 'transportation_and_infrastructure', 'software_development',
                                'printing_and_support_services', 'engineering_and_design', 'facility_cleaning',
                                'marketing', 'shipping', 'facility_lessor', 'advertising', 'consulting_and_management',
                                'payroll_and_benefits', 'finance_accounting_and_notaries',
                                'advertising_distribution_services', 'uniform_and_linen_rental', 'cloud_storage',
                                'patents_and_legal_services', 'business_services', 'shipping_and_temporary_storage',
                                'inspection_services', 'telecom_and_technology', 'temporary_storage',
                                'temporary_staffing', 'support_services', 'facility_services',
                                'operational_management'],
           'ConsumerServices': ['healthcare_services', 'legal_services', 'education', 'maintenance_and_repair',
                                'organizations', 'government', 'contractors_and_installers', 'employment_services',
                                'moving_and_delivery', 'personal_care', 'waste_services',
                                'real_estate_transaction_services', 'entertainment', 'real_estate_services',
                                'transportation', 'consumer_services', 'financial_services',
                                'recording_documentation_and_translation_services', 'security_and_investigations',
                                'caretaking', 'telecommunications'],
           'Energy': ['energy', 'energy_transmission', 'power_plant_fuel', 'site_preparation_services',
                      'crude_oil_producer_coal_miner_&_uranium_ore_miner', 'energy_retails_and_wholesales',
                      'refinement_of_energy_resources', 'energy_resource_brokers_wholesalers_and_merchants',
                      'electric_utilities', 'gas_utilities', 'power_plant', 'oil_&_gas_pipelines',
                      'extraction_equipment', 'utilities', 'energy_storage_and_transportation', 'refinery',
                      'extraction_of_natural_resources_for_energy', 'fuel_retails_and_wholesales',
                      'exploration_services', 'construction', 'equipment', 'electrical_power_grid'],
           'FinanceBanking': ['services_for_banks_and_lenders', 'accounting_and_taxes', 'finance_and_banking',
                              'asset_management', 'financial_advisory_and_other_financial_services',
                              'financial_information', 'payroll', 'asset_management_services',
                              'consumer_banks_and_lenders', 'commercial_banks_and_lenders', 'grants',
                              'government_banks_and_lenders', 'insurance', 'dealers_and_brokers',
                              'banks_and_lending', 'financial_vehicles'],
           'Food': ['diversified_processed_foods', 'sauces_spreads_and_condiments', 'wholesale_and_distribution',
                    'snacks_and_candy', 'crop_maintenance', 'catering_and_foodservices',
                    'frozen_food_mixes_and_concentrates', 'farming', 'fertilizers', 'food_processing_and_manufacturing',
                    'storage', 'food_trucks', 'food', 'livestock_feed', 'farming_support_services',
                    'meat_poultry_and_seafood', 'breweries', 'beverages', 'restaurants', 'agriculture',
                    'prepared_food_manufacturing', 'food_equipment', 'refined_grains_oils_and_spices', 'alcohol',
                    'dairy_products', 'wineries', 'restaurants_and_food_trucks', 'distribution',
                    'diversified_agriculture', 'processing', 'restaurants_and_grocery',
                    'fertilizers_feed_and_farming_supplies', 'vending_machines', 'packaging', 'production',
                    'grocery_stores', 'restaurants_and_restaurant_services', 'transportation',
                    'distribution_storage_and_logistics', 'animal_maintenance', 'farming_supplies', 'equipment',
                    'crop_and_animal_maintenance', 'distilleries'],
           'Healthcare': ['healthcare_providers', 'equipment_for_pharmaceutical_and_biotech_research',
                          'pharmaceutical_and_biotech_research', 'health_insurance', 'implants_and_medical_devices',
                          'healthcare', 'pharmaceuticals_and_biotech', 'pharmaceutical_retail',
                          'residential_healthcare_services', 'pharmaceutical_and_biotech_manufacturing'],
           'Infrastructure': ['pipelines', 'railways', 'water_and_sewage_systems', 'electricity',
                              'maintenance_and_repair', 'support_equipment_and_infrastructure',
                              'diversified_hydrocarbon_pipeline', 'infrastructure', 'gas_utilities',
                              'highways_roads_and_bridges', 'refined_fuels_pipeline', 'meters',
                              'equipment_and_infrastructure', 'distribution', 'transmission', 'transportation',
                              'water_utility', 'utility_equipment_and_services', 'operations', 'crude_oil_pipeline',
                              'natural_gas_pipeline', 'construction', 'telecommunications',
                              'road_materials_supply_services'],
           'Manufacturing': ['industrial_machines', 'electronics', 'manufacturing', 'maintenance_and_repair',
                             'manufacturing_industry_services', 'furniture_and_home_goods', 'leasing_and_rental',
                             'apparel', 'material_manufacturing', 'household_appliances', 'food_equipment',
                             'manufacturing_for_energy', 'finished_goods_manufacturing', 'packaging', 'vehicles',
                             'medical_devices', 'construction', 'components_manufacturing',
                             'entertainment_devices_&_toys'],
           'Media': ['music', 'tv_and_movies', 'print', 'photography', 'art', 'amusement_parks_and_arcades',
                     'video_games', 'news', 'media', 'radio'],
           'MiningExtraction': ['chemical_ores', 'mining', 'equipment_and_infrastructure', 'rocks_and_minerals',
                                'mined_materials', 'metals', 'wholesale_and_distribution', 'mining_equipment',
                                'extraction_infrastructure', 'natural_gas', 'extraction', 'mining_and_extraction',
                                'extraction_equipment', 'extracted_materials'],
           'PublicServices': ['public_services', 'social_services', 'social_&_advocacy_organizations'],
           'RealEstate': ['real_estate_security_services', 'real_estate_construction', 'real_estate_operators',
                          'real_estate_financial_products', 'real_estate_construction_materials',
                          'real_estate_architecture_and_design', 'real_estate_structural_components',
                          'real_estate_lighting_hvac_and_heating', 'real_estate_mortgage_&_mortgage_products',
                          'real_estate_for_agriculture_forestry_and_mining', 'real_estate',
                          'real_estate_components_and_materials', 'real_estate_construction_and_subcontractors',
                          'real_estate_components_and_materials_sales',
                          'real_estate_cleaning_and_maintenance_services', 'real_estate_lessor',
                          'real_estate_survey_services', 'real_estate_brokerage_services', 'residential_lessor',
                          'real_estate_services', 'office_lessor', 'real_estate_construction_equipment',
                          'real_estate_developers', 'real_estate_management_services', 'real_estate_insurance'],
           'RetailWholesaleDistribution': ['retail_wholesale_distribution', 'wholesale_and_distribution',
                                           'consumer_product_rentals', 'diversified_equipment_retail',
                                           'vehicle_and_vehicle_parts_wholesalers',
                                           'alcohol_and_tobacco_wholesale_and_distribution',
                                           'raw_materials_and_chemicals_wholesalers',
                                           'electronics_and_components_wholesalers', 'diversified_product_rentals',
                                           'apparel_and_jewelry_wholesalers', 'retail',
                                           'equipment_wholesale_and_distribution',
                                           'commercial_and_industrial_products_wholesalers',
                                           'food_wholesale_and_distribution',
                                           'building_material_wholesale_and_distribution', 'food_and_drink_retail',
                                           'vehicle_parts_stores', 'home_improvement_retail',
                                           'wholesale_and_distribution_to_manufacturers',
                                           'fuel_wholesale_and_distribution',
                                           'office_and_home_products_wholesalers', 'grocery_stores',
                                           'food_product_wholesale_and_distribution', 'bars_and_restaurants',
                                           'medicine_and_medical_devices_wholesalers',
                                           'vehicle_vehicle_parts_and_fuel_retail', 'gas_stations',
                                           'consumer_media_retail', 'consumer_products_wholesalers',
                                           'apparel_and_jewelry_retail', 'door_to_door_sales', 'on_site_rentals',
                                           'vehicle_dealerships', 'alcohol_and_tobacco_stores',
                                           'consumer_media_wholesalers'],
           'Technology': ['it_services', 'software', 'electronic_displays', 'medical_technology',
                          'semiconductor_manufacturing_equipment_and_services', 'electronic_components',
                          'enterprise_software', 'social_and_search_networks', 'integrated_circuits',
                          'automation_robotics_and_industrial_hardware', 'hardware',
                          'electronic_systems_for_transportation', 'databases', 'network_equipment_&_servers',
                          'technology', 'computers_phones_and_entertainment_equipment', 'search_networks',
                          'web_based_retailing_and_distribution_platforms'],
           'TourismLeisure': ['entertainment_establishments', 'food_services', 'campgrounds', 'accommodation',
                              'casinos', 'sightseeing_travel', 'bars', 'motor_vehicle_travel',
                              'travel_agents_and_insurance', 'restaurants', 'leisure_activities', 'air_travel',
                              'sports_and_recreation', 'tourism_based_transportation', 'hotels', 'tourism',
                              'tourism_and_leisure', 'alcohol_production', 'amusement_parks_and_arcades',
                              'live_entertainment', 'amusement_parks'],
           'Transportation': ['maintenance_and_repair', 'public_transit', 'transportation_of_people', 'trains',
                              'fueling', 'rental_and_leasing', 'motor_vehicle_travel', 'moving_and_delivery',
                              'infrastructure', 'roads_rails_waterways', 'manufacture', 'boats', 'train_travel',
                              'shipping', 'air_travel', 'airplanes', 'transportation_of_goods', 'waste_collection',
                              'water_travel', 'sale', 'vehicles', 'transportation', 'operations',
                              'automobiles_and_motorcyles']}

OUTCOME_DICT = {'MedianIncome': 'median_income', 'UnemploymentRate': 'unemployment_rate',
                'AdjustedMedianIncome': 'median_income_ppp_adj',
                'EmploymentPopulationRatio': 'employment_population_ratio',
                'GiniIndex': 'gini_index', 'TotalPopulation': 'total_population',
                'PercentageHSDiploma': 'pct_pop_high_school_diploma',
                'PercentageBachelorDegree': 'pct_pop_bachelor_degree',
                'HealthInsuranceCoverage': 'pct_pop_health_insurance_coverage',
                'HousingCost': 'median_monthly_housing_cost'}

# List of all metrics
METRIC_NAMES = ['PC_EMPL', 'PC_ESTAB', 'LQ_EMPL_ESTAB',
                'LQ_EMPL_ESTAB_RANK', 'WM_ESTAB', 'PRES_ESTAB']
