#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['l5_shoppinglist']

package_data = \
{'': ['*'], 'l5_shoppinglist': ['db/*']}

install_requires = \
['tinydb>=3.15.2', 'PyGObject']

setup(name='l5_shoppinglist',
      version='20.2.1',
      description='gtk l5_shoppinglist',
      author='fphemeral',
      author_email='fphemeral@i2pmail.org',
      url='https://source.puri.sm/fphemeral/l5_shoppinglist',
      packages=packages,
      package_data=package_data,
      install_requires=install_requires,
      python_requires='>=3.7',
     )
