- name: Example of merging lists without deduplication
  hosts: localhost
  gather_facts: false  # Speed up the example
  vars: # Note that these could be definied anywhere in inventory
    group1_ports__to_merge:
      - 22
      - 80
      - 443
    group2_ports__to_merge:
      - 22
      - 1111
    group3_ports__to_merge:
      - 443
      - 2222
    group4_some_other_var:
      - 3333
      - 4444
  tasks:
    - name: Merge port vars
      merge_vars:
        suffix_to_merge: ports__to_merge
        merged_var_name: merged_ports
        dedup: false
        expected_type: list

    - debug:
        var: merged_ports
