#AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"fix_annotations_format": "00_core.ipynb",
         "dataset_stats": "00_core.ipynb",
         "ents_by_label": "00_core.ipynb",
         "get_label_disparities": "00_core.ipynb",
         "top_prediction_errors": "00_core.ipynb",
         "convert_labels": "00_core.ipynb",
         "Pipeline": "01_pipeline.ipynb",
         "select_subset_of_overlapping_chain": "99_util.ipynb",
         "remove_overlapping_entities": "99_util.ipynb",
         "filter_overlaps": "99_util.ipynb"}

modules = ["core.py",
           "pipeline.py",
           "util.py"]

git_url = "https://github.com/kabirkhan/spacy_data_debug/tree/master/"

def custom_doc_links(name): return None