name: ci

on:
  push:
    branches:
      - master
  pull_request:
    branches_ignore: []

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Setup black linter
        run: conda create --quiet --name black black

      - name: Lint python code
        run: |
          export PATH="/usr/share/miniconda/bin:$PATH"
          source activate black
          black --check griznog

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Setup conda environment
        run: conda create --quiet --name griznog

      - name: Install griznog
        run: |
          export PATH="/usr/share/miniconda/bin:$PATH"
          source activate griznog
          python setup.py install

      - name: Test griznog
        run: |
          export PATH="/usr/share/miniconda/bin:$PATH"
          source activate griznog
          pip install pytest
          pytest .github/test_wisdom.py
