# Generated by Django 2.2.5 on 2020-01-28 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('etsy_policy', '0001_initial'),
        ('etsy_listing', '0001_initial'),
        ('etsy_account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='etsylisting',
            name='shipping_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etsy_products', related_query_name='etsy_product', to='etsy_policy.EtsyShippingTemplate', verbose_name='Политика доставки'),
        ),
        migrations.AddField(
            model_name='etsylisting',
            name='shop_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listings', related_query_name='listing', to='etsy_account.EtsyShopSection', verbose_name='Секция магазина Etsy'),
        ),
    ]
