# Generated by Django 2.2.4 on 2019-11-23 21:38

from django.db import migrations, models
import django_magnificent_messages.fields
import tests.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JSONFieldCustomModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', django_magnificent_messages.fields.JSONField(decode=tests.models.custom_decode, encode=tests.models.custom_encode)),
            ],
            options={
                'db_table': 'custom',
            },
        ),
        migrations.CreateModel(
            name='JSONFieldDefaultModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', django_magnificent_messages.fields.JSONField(null=True)),
            ],
            options={
                'db_table': 'default',
            },
        ),
    ]
