# Generated by Django 2.2.2 on 2019-07-04 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_tasker_geobase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='geobase',
            name='openweathermap',
            field=models.IntegerField(blank=True, null=True, verbose_name='Open Weather Map'),
        ),
    ]
