# Generated by Django 2.2.2 on 2019-07-09 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_tasker_geobase', '0002_geobase_openweathermap'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('temperature', models.FloatField(blank=True, null=True, verbose_name='Temperature celsius')),
                ('temperature_min', models.FloatField(blank=True, null=True, verbose_name='Temperature celsius min')),
                ('temperature_max', models.FloatField(blank=True, null=True, verbose_name='Temperature celsius max')),
                ('pressure', models.FloatField(blank=True, null=True, verbose_name='Atmospheric pressure (hPa)')),
                ('humidity', models.FloatField(blank=True, null=True, verbose_name='Humidity (%)')),
                ('visibility', models.FloatField(blank=True, null=True, verbose_name='Visibility (meter)')),
                ('wind_speed', models.FloatField(blank=True, null=True, verbose_name='Wind speed (mps)')),
                ('wind_degrees', models.FloatField(blank=True, null=True, verbose_name='Wind degrees (meter/sec)')),
                ('clouds', models.FloatField(blank=True, null=True, verbose_name='Cloudiness (%)')),
                (
                    'geobase',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to='django_tasker_geobase.Geobase'
                    )
                ),
            ],
        ),
    ]
