
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-01-22T23:43:50+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "0dfc97b708c4dd3abc39001f1078b22ecbc4b4cb",
 "version": "v0.3.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
