"""Tabler."""

__title__ = "tabler"
__description__ = "Simple interface for tabulated data and .csv files"
__url__ = "http://github.com/lukeshiner/tabler.git"
__version__ = "2.4.0"
__author__ = "Luke Shiner"
__author_email__ = "luke@lukeshiner.com"
__license__ = "MIT"
__copyright__ = "Copyright 2018 Luke Shiner"
