arangodb:
  DB_end_point: apmdb
  DB_service_host: localhost
  DB_service_name: createDB
  DB_service_port: 8529
  arangodb_replication_factor: null
  conn_protocol: http
  dbName: arangopipe
  password: MLhsm6hofxidw56b2tc4j1
  root_user: root
  root_user_password: open sesame
  username: arangopipe
mlgraph:
  graphname: enterprise_ml_graph
