# Generated by Django 2.2.5 on 2020-01-22 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etsy_policy', '0002_auto_20200117_1440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etsyshippingtemplateentry',
            name='origin_country',
        ),
    ]
