# Generated by Django 2.2.5 on 2020-01-23 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('etsy', '0003_etsycountry_etsyregion'),
        ('etsy_policy', '0005_auto_20200123_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='etsyshippingtemplate',
            name='origin_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='etsy.EtsyCountry', verbose_name='Страна, из которой отравляется заказ'),
        ),
        migrations.AddField(
            model_name='etsyshippingtemplateentry',
            name='destination_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dest_shipping_templates', to='etsy.EtsyCountry', verbose_name='Страна, в которую отравляется заказ'),
        ),
        migrations.AddField(
            model_name='etsyshippingtemplateentry',
            name='destination_region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='etsy.EtsyRegion', verbose_name='Регион, в который отравляется заказ'),
        ),
    ]
