# Generated by Django 2.2.5 on 2020-01-27 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etsy_policy', '0009_auto_20200124_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etsyshippingtemplate',
            name='shipping_template_id',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='ID политики доставки'),
        ),
        migrations.AlterField(
            model_name='etsyshippingtemplateentry',
            name='shipping_template_entry_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID записи политики доставки'),
        ),
    ]
