# Generated by Django 2.2.5 on 2020-01-30 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etsy_order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etsyreceipt',
            name='payment_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail покупателя для получения информации о платеже'),
        ),
        migrations.AlterField(
            model_name='etsyreceipt',
            name='state',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Область'),
        ),
        migrations.AlterField(
            model_name='etsyreceipttransaction',
            name='paid_tsz',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время оплаты'),
        ),
        migrations.AlterField(
            model_name='etsyreceipttransaction',
            name='shipped_tsz',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время отправки'),
        ),
    ]
