
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "f9c0c17369d813ee314975f69ec6a7dcbedac126",
 "version": "1.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
