---
fixes:
  - |
    Fixes templating of Prometheus configuration when Alertmanager is disabled.
    In a deployment where Prometheus is enabled and Alertmanager is disabled the
    configuration for the Prometheus will fail when templating as the variable
    `prometheus_alert_rules` does not contain the key `files`. For details
    please see <https://bugs.launchpad.net/kolla-ansible/+bug/1854540>`__.
