# Generated by Django 2.2.5 on 2020-01-17 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('etsy_category', '0002_auto_20200117_1440'),
        ('etsy_listing', '0001_initial'),
        ('etsy_policy', '0001_initial'),
        ('base_product', '0001_initial'),
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='etsyshop',
            name='channel',
            field=models.OneToOneField(limit_choices_to={'domain__marketplace__unique_name': 'etsy'}, on_delete=django.db.models.deletion.CASCADE, related_name='shop', to='marketplace.Channel', verbose_name='Пользовательский канал продаж'),
        ),
        migrations.AddField(
            model_name='etsyproductproperty',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', related_query_name='property', to='etsy_listing.EtsyProduct'),
        ),
        migrations.AddField(
            model_name='etsyproduct',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', related_query_name='product', to='etsy_listing.EtsyListing'),
        ),
        migrations.AddField(
            model_name='etsylistingattribute',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', related_query_name='attribute', to='etsy_listing.EtsyListing'),
        ),
        migrations.AddField(
            model_name='etsylisting',
            name='base_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etsy_products', related_query_name='etsy_product', to='base_product.BaseProduct', verbose_name='Базовый листинг'),
        ),
        migrations.AddField(
            model_name='etsylisting',
            name='category',
            field=models.ForeignKey(limit_choices_to={'is_leaf': True}, on_delete=django.db.models.deletion.CASCADE, related_name='etsy_products', related_query_name='etsy_product', to='etsy_category.EtsyCategory', verbose_name='Категория листинга Etsy'),
        ),
        migrations.AddField(
            model_name='etsylisting',
            name='channel',
            field=models.ForeignKey(limit_choices_to={'domain__marketplace__unique_name': 'etsy'}, on_delete=django.db.models.deletion.CASCADE, related_name='etsy_products', related_query_name='etsy_product', to='marketplace.Channel', verbose_name='Пользовательский канал продаж'),
        ),
        migrations.AddField(
            model_name='etsylisting',
            name='shipping_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etsy_products', related_query_name='etsy_product', to='etsy_policy.EtsyShippingTemplate', verbose_name='Политика доставки'),
        ),
        migrations.AddField(
            model_name='etsylisting',
            name='shop_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listings', related_query_name='listing', to='etsy_listing.EtsyShopSection', verbose_name='Секция магазина Etsy'),
        ),
    ]
