# Generated by Django 2.2.5 on 2020-01-20 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etsy_listing', '0002_auto_20200117_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etsylisting',
            name='num_favorers',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество лайков листинга'),
        ),
        migrations.AlterField(
            model_name='etsylisting',
            name='views',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество просмотров листинга'),
        ),
        migrations.AlterField(
            model_name='etsylistingattribute',
            name='property_id',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='ID атрибута'),
        ),
        migrations.AlterField(
            model_name='etsylistingattribute',
            name='property_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Название атрибута'),
        ),
        migrations.AlterField(
            model_name='etsylistingattribute',
            name='values',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Список значений'),
        ),
        migrations.AlterField(
            model_name='etsyproduct',
            name='offering_id',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='ID оффера'),
        ),
        migrations.AlterField(
            model_name='etsyproduct',
            name='product_id',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='ID продукта'),
        ),
        migrations.AlterField(
            model_name='etsyproductproperty',
            name='property_id',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='ID атрибута'),
        ),
        migrations.AlterField(
            model_name='etsyproductproperty',
            name='property_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Название атрибута'),
        ),
        migrations.AlterField(
            model_name='etsyproductproperty',
            name='values',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Список значений'),
        ),
    ]
