# Generated by Django 2.2.5 on 2020-01-22 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etsy_listing', '0003_auto_20200120_1340'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='etsyshop',
            options={'verbose_name': 'Магазин Etsy', 'verbose_name_plural': 'Магазины Etsy'},
        ),
        migrations.AlterModelOptions(
            name='etsyshopsection',
            options={'verbose_name': 'Секция магазина Etsy', 'verbose_name_plural': 'Секции магазина Etsy'},
        ),
        migrations.AlterField(
            model_name='etsyshopsection',
            name='shop_section_id',
            field=models.CharField(default=1, max_length=30, unique=True, verbose_name='ID секции магазина Etsy'),
            preserve_default=False,
        ),
    ]
