# Generated by Django 2.2.5 on 2020-01-24 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('etsy_listing', '0005_auto_20200123_1858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etsyshopsection',
            name='shop',
        ),
        migrations.AlterField(
            model_name='etsylisting',
            name='shop_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listings', related_query_name='listing', to='etsy_account.EtsyShopSection', verbose_name='Секция магазина Etsy'),
        ),
        migrations.DeleteModel(
            name='EtsyShop',
        ),
        migrations.DeleteModel(
            name='EtsyShopSection',
        ),
    ]
