[tool.poetry]
name = "daculous"
version = "0.0.1"
description = "Python library for DACulous"
authors = ["Fabian Schuh <fabian@chainsquad.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.6"
graphenelib = "^1.2.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
