# Generated by Django 2.2.5 on 2020-01-17 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ebay_order', '0001_initial'),
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebayorder',
            name='marketplace_user_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ebay_orders', related_query_name='ebay_order', to='marketplace.MarketplaceUserAccount'),
        ),
        migrations.AddField(
            model_name='discountedlineitemcost',
            name='line_item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='discounted_line_item_cost', to='ebay_order.EbayOrderLineItem'),
        ),
        migrations.AddField(
            model_name='discountamount',
            name='applied_promotion',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='discount_amount', to='ebay_order.AppliedPromotion'),
        ),
        migrations.AddField(
            model_name='deliverydiscount',
            name='pricing_summary',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_discount', to='ebay_order.PricingSummary'),
        ),
        migrations.AddField(
            model_name='deliverycost',
            name='pricing_summary',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_cost', to='ebay_order.PricingSummary'),
        ),
        migrations.AddField(
            model_name='contactaddress',
            name='ship_to',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contact_address', to='ebay_order.ShipTo'),
        ),
        migrations.AddField(
            model_name='cancelstatus',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cancel_status', to='ebay_order.EbayOrder'),
        ),
        migrations.AddField(
            model_name='cancelrequest',
            name='cancel_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancel_requests', related_query_name='cancel_request', to='ebay_order.CancelStatus'),
        ),
        migrations.AddField(
            model_name='appliedpromotion',
            name='line_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applied_promotions', related_query_name='applied_promotion', to='ebay_order.EbayOrderLineItem'),
        ),
        migrations.AddField(
            model_name='adjustment',
            name='pricing_summary',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='adjustment', to='ebay_order.PricingSummary'),
        ),
        migrations.AddConstraint(
            model_name='ebayorder',
            constraint=models.UniqueConstraint(fields=('orderId', 'legacyOrderId'), name='unique_order_id_and_legacy_order_id'),
        ),
    ]
