# This file exists within 'human-friendly_pedantic-timedelta' aka 'pedantic_timedelta':
#
#   https://github.com/hotoffthehamster/human-friendly_pedantic-timedelta

# (lb): Including this file just to be pedantic.

[build-system]
requires = ["setuptools", "wheel"]

