
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-01-28T22:11:33-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "232f5544800a8c2746855b796487ee587516a3e1",
 "version": "0.16.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
