
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-02-04T12:38:53-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "4e2cd06f73ac2a61b9e4a2acee326cda535ea0dd",
 "version": "0.1.1.post.dev11"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
