# AUTOGENERATED! DO NOT EDIT! File to edit: 00_core.ipynb (unless otherwise specified).

__all__ = ['abc2', 'abc3', 'abc4']

# Cell
# def abc(x):
#     return x+1


# Cell
def abc2(x):
    return x+2

# Cell
def abc3(x):
    return x+3

# Cell
def abc4(x):
    return x+4