
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-02-05T13:02:16-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "16a4489b405663d71ea7270a752e84d967b2e0d6",
 "version": "0.3.1.alpha0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
