# Generated by Django 2.2.9 on 2020-01-30 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inte_subject', '0002_auto_20200130_1053'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generalassessment',
            old_name='diabetes_screening',
            new_name='diabetes_screen',
        ),
        migrations.RenameField(
            model_name='generalassessment',
            old_name='hiv_screening',
            new_name='hiv_screen',
        ),
        migrations.RenameField(
            model_name='generalassessment',
            old_name='hypertension_screening',
            new_name='hypertension_screen',
        ),
        migrations.RenameField(
            model_name='historicalgeneralassessment',
            old_name='diabetes_screening',
            new_name='diabetes_screen',
        ),
        migrations.RenameField(
            model_name='historicalgeneralassessment',
            old_name='hiv_screening',
            new_name='hiv_screen',
        ),
        migrations.RenameField(
            model_name='historicalgeneralassessment',
            old_name='hypertension_screening',
            new_name='hypertension_screen',
        ),
        migrations.RemoveField(
            model_name='generalassessment',
            name='diabetes_screening_ago',
        ),
        migrations.RemoveField(
            model_name='generalassessment',
            name='hiv_screening_ago',
        ),
        migrations.RemoveField(
            model_name='generalassessment',
            name='hypertension_screening_ago',
        ),
        migrations.RemoveField(
            model_name='historicalgeneralassessment',
            name='diabetes_screening_ago',
        ),
        migrations.RemoveField(
            model_name='historicalgeneralassessment',
            name='hiv_screening_ago',
        ),
        migrations.RemoveField(
            model_name='historicalgeneralassessment',
            name='hypertension_screening_ago',
        ),
        migrations.AddField(
            model_name='generalassessment',
            name='diabetes_screen_date',
            field=models.DateField(blank=True, help_text='Diabetes. If estimated, see protocol for instructions on how to estimate dates', null=True, verbose_name='How long ago was this?'),
        ),
        migrations.AddField(
            model_name='generalassessment',
            name='hiv_screen_date',
            field=models.DateField(blank=True, help_text='HIV. If estimated, see protocol for instructions on how to estimate dates', null=True, verbose_name='How long ago was this'),
        ),
        migrations.AddField(
            model_name='generalassessment',
            name='hypertension_screen_date',
            field=models.DateField(blank=True, help_text='Hypertension. If estimated, see protocol for instructions on how to estimate dates', null=True, verbose_name='How long ago was this?'),
        ),
        migrations.AddField(
            model_name='historicalgeneralassessment',
            name='diabetes_screen_date',
            field=models.DateField(blank=True, help_text='Diabetes. If estimated, see protocol for instructions on how to estimate dates', null=True, verbose_name='How long ago was this?'),
        ),
        migrations.AddField(
            model_name='historicalgeneralassessment',
            name='hiv_screen_date',
            field=models.DateField(blank=True, help_text='HIV. If estimated, see protocol for instructions on how to estimate dates', null=True, verbose_name='How long ago was this'),
        ),
        migrations.AddField(
            model_name='historicalgeneralassessment',
            name='hypertension_screen_date',
            field=models.DateField(blank=True, help_text='Hypertension. If estimated, see protocol for instructions on how to estimate dates', null=True, verbose_name='How long ago was this?'),
        ),
    ]
