language: python
sudo: false
env:
  - REDIS_PY=3.4.1
python:
  - 3.7
jobs:
  include:
    - python: 2.7
    - python: 3.5
    - python: 3.6
    - python: pypy
    - env: REDIS_PY=2.10.6
    - env: REDIS_PY=3.0.1
    - env: REDIS_PY=3.1.0
    - env: REDIS_PY=3.2.1
    - env: REDIS_PY=3.3.11
    - env: REDIS_PY=3.4.1
cache:
  - pip
services:
  - redis-server
install:
  - pip install -r requirements.txt
  - pip install redis==$REDIS_PY
  - pip install coverage python-coveralls
before_script:
  - flake8
script:
  - coverage erase
  - pytest --cov=fakeredis test_fakeredis.py
notifications:
  email:
    - js@jamesls.com
    - bmerry@ska.ac.za
after_success: coveralls
