
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-01-31T16:07:09-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "2499ec25fd5513d7bb299a231baab9a178f7704a",
 "version": "1.1.17rc1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
