# see https://pyup.io/docs/configuration/ for all available options

branch: develop
schedule: every day

requirements:
  - requirements.txt:
      update: True
      pin: True
  - requirements-dev.txt:
      update: False
      pin: False
