
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-01-29T21:44:37+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "38bc8974fde1f616ad9a732bbdec9287e0694a99",
 "version": "0.4.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
