[tool.poetry]
name = "hycli"
version = "0.2.0"
description = "Interface package to convert invoice to xml by requesting different Hypatos services."
authors = ["Dylan Bartels <dylan.bartels@hypatos.ai>"]

[tool.poetry.dependencies]
python = "^3.7"
requests = "^2.22.0"
xmltodict = "^0.12.0"
click = "^7.0"
halo = "^0.0.28"
bump2version = "^0.5.11"
filetype = "^1.0.5"
click-log = "^0.3.2"
Redis = "^3.3.11"
rq = "^1.2.0"
rq-scheduler = "^0.9.1"
XlsxWriter = "^1.2.7"

[tool.poetry.dev-dependencies]
rope = "^0.16.0"
flake8 = "^3.7.9"
pytest = "^5.3.5"
black = "^19.10b0"

[tool.poetry.scripts]
hycli = "hycli.cli:main"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.black]
line-length = 88
target-version = ['py38']
include = '\.pyi?$'
exclude = '''
(
  /(
      \.eggs
    | \.git
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
  )/
)
'''