
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-01-31T16:35:57-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "d7ed82ef8c7747b74eac511ac1b8b1631d5a7dd2",
 "version": "1.1.17rc3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
