language: "de"

pipeline:
- name: "SpacyNLP"
  model: de_core_news_sm
- name: "SpacyTokenizer"
- name: "SpacyEntityExtractor"
- name: "CRFEntityExtractor"
- name: "EntitySynonymMapper"
- name: "CountVectorsFeaturizer"
- name: "EmbeddingIntentClassifier"
- name: "DucklingHTTPExtractor"
  locale: "de_Nothing"
  url: "http://samlet:8000"
