# Generated by Django 2.2.5 on 2020-01-17 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('amazon_category', '0001_initial'),
        ('amazon_product', '0001_initial'),
        ('base_product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazonproduct',
            name='base_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amazon_products', related_query_name='amazon_product', to='base_product.BaseProduct', verbose_name='Базовый товар'),
        ),
        migrations.AddField(
            model_name='amazonproduct',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='amazon_category.AmazonCategory', verbose_name='Категория товара Amazon'),
        ),
    ]
