
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-02-06T22:41:03-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "02493c3b9b2b4e286ef6fa32b755791c5d2c7ce8",
 "version": "v0.1.9"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
