[tool.poetry]
name = "git-gone"
version = "2.2.2"
description = "A simple tool to track visited Git repositories, and check them for unpushed/committed changes"
authors = ["Angus Hollands <goosey15@gmail.com>"]
license = "MIT"
repository = "https://github.com/agoose77/git-gone"
homepage = "https://github.com/agoose77/git-gone"

[tool.poetry.dependencies]
python = "^3.7.0"
plumbum = "^1.6.8"

[tool.poetry.dev-dependencies]

[tool.poetry.scripts]
git-gone = 'git_gone.__main__:main'

[build-system]
requires = ["poetry>=1.0"]
build-backend = "poetry.masonry.api"
