name: Tests

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-2019
          - ubuntu-18.04
          - macos-latest
        python:
          - 3.6
          - 3.7

    steps:
    - name: Set up environment
      uses: actions/checkout@v1
      with:  # no need for the history
        fetch-depth: 1
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ".[test]"
    - name: ${{ matrix.module }} tests
      run: |
        python -m pytest -s -v --cov=dandi dandi
