
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-02-05T21:35:52+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "ae2ca07329ac5c4d53e933e97c8c18eb90f2f3c2",
 "version": "1.0.0.post.dev66"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
