
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-01-27T10:50:32-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "9f687674818a080ce50667c16dcf0c277f138dc7",
 "version": "0.0.54"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
