# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer/desktop_ui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(941, 871)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QtCore.QSize(820, 0))
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setTitle("")
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_16.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_16.setSpacing(0)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.butSaveProjectAs = QtWidgets.QPushButton(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.butSaveProjectAs.sizePolicy().hasHeightForWidth())
        self.butSaveProjectAs.setSizePolicy(sizePolicy)
        self.butSaveProjectAs.setObjectName("butSaveProjectAs")
        self.gridLayout_16.addWidget(self.butSaveProjectAs, 0, 3, 1, 1)
        self.butSaveProject = QtWidgets.QPushButton(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.butSaveProject.sizePolicy().hasHeightForWidth())
        self.butSaveProject.setSizePolicy(sizePolicy)
        self.butSaveProject.setObjectName("butSaveProject")
        self.gridLayout_16.addWidget(self.butSaveProject, 0, 2, 1, 1)
        self.butOpenProject = QtWidgets.QPushButton(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.butOpenProject.sizePolicy().hasHeightForWidth())
        self.butOpenProject.setSizePolicy(sizePolicy)
        self.butOpenProject.setObjectName("butOpenProject")
        self.gridLayout_16.addWidget(self.butOpenProject, 0, 1, 1, 1)
        self.butNewProject = QtWidgets.QPushButton(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.butNewProject.sizePolicy().hasHeightForWidth())
        self.butNewProject.setSizePolicy(sizePolicy)
        self.butNewProject.setObjectName("butNewProject")
        self.gridLayout_16.addWidget(self.butNewProject, 0, 0, 1, 1)
        self.gridLayout_15.addWidget(self.groupBox_4, 4, 0, 1, 1)
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.tabWidget = QtWidgets.QTabWidget(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(True)
        self.tabWidget.setObjectName("tabWidget")
        self.tabScript = QtWidgets.QWidget()
        self.tabScript.setObjectName("tabScript")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.tabScript)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.lblCharacters = QtWidgets.QLabel(self.tabScript)
        self.lblCharacters.setObjectName("lblCharacters")
        self.gridLayout_6.addWidget(self.lblCharacters, 9, 1, 1, 2)
        self.butAddCharacters = QtWidgets.QPushButton(self.tabScript)
        self.butAddCharacters.setObjectName("butAddCharacters")
        self.gridLayout_6.addWidget(self.butAddCharacters, 11, 1, 1, 4)
        self.spinStartLine = QtWidgets.QSpinBox(self.tabScript)
        self.spinStartLine.setMinimum(1)
        self.spinStartLine.setMaximum(9999)
        self.spinStartLine.setObjectName("spinStartLine")
        self.gridLayout_6.addWidget(self.spinStartLine, 1, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.tabScript)
        self.label_3.setObjectName("label_3")
        self.gridLayout_6.addWidget(self.label_3, 1, 3, 1, 1)
        self.spinEndLine = QtWidgets.QSpinBox(self.tabScript)
        self.spinEndLine.setMaximum(9999)
        self.spinEndLine.setObjectName("spinEndLine")
        self.gridLayout_6.addWidget(self.spinEndLine, 1, 4, 1, 1)
        self.butImportScript = QtWidgets.QPushButton(self.tabScript)
        self.butImportScript.setObjectName("butImportScript")
        self.gridLayout_6.addWidget(self.butImportScript, 1, 0, 1, 1)
        self.tblCharacters = QtWidgets.QTableWidget(self.tabScript)
        self.tblCharacters.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tblCharacters.setColumnCount(2)
        self.tblCharacters.setObjectName("tblCharacters")
        self.tblCharacters.setRowCount(0)
        self.tblCharacters.horizontalHeader().setStretchLastSection(True)
        self.gridLayout_6.addWidget(self.tblCharacters, 10, 1, 1, 4)
        self.tblLineProps = QtWidgets.QTableWidget(self.tabScript)
        self.tblLineProps.setColumnCount(2)
        self.tblLineProps.setObjectName("tblLineProps")
        self.tblLineProps.setRowCount(0)
        self.tblLineProps.horizontalHeader().setStretchLastSection(True)
        self.gridLayout_6.addWidget(self.tblLineProps, 7, 1, 1, 4)
        self.label_2 = QtWidgets.QLabel(self.tabScript)
        self.label_2.setObjectName("label_2")
        self.gridLayout_6.addWidget(self.label_2, 1, 1, 1, 1)
        self.lblLineProps = QtWidgets.QLabel(self.tabScript)
        self.lblLineProps.setObjectName("lblLineProps")
        self.gridLayout_6.addWidget(self.lblLineProps, 6, 1, 1, 2)
        self.lblLineView = QtWidgets.QLabel(self.tabScript)
        self.lblLineView.setObjectName("lblLineView")
        self.gridLayout_6.addWidget(self.lblLineView, 6, 0, 1, 1)
        self.butUpdateLineProps = QtWidgets.QPushButton(self.tabScript)
        self.butUpdateLineProps.setObjectName("butUpdateLineProps")
        self.gridLayout_6.addWidget(self.butUpdateLineProps, 8, 1, 1, 4)
        self.butImportParsed = QtWidgets.QPushButton(self.tabScript)
        self.butImportParsed.setObjectName("butImportParsed")
        self.gridLayout_6.addWidget(self.butImportParsed, 2, 0, 1, 1)
        self.butExportParsedLines = QtWidgets.QPushButton(self.tabScript)
        self.butExportParsedLines.setObjectName("butExportParsedLines")
        self.gridLayout_6.addWidget(self.butExportParsedLines, 3, 0, 1, 1)
        self.grboxTextVis = QtWidgets.QGroupBox(self.tabScript)
        self.grboxTextVis.setObjectName("grboxTextVis")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.grboxTextVis)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.rbutPlain = QtWidgets.QRadioButton(self.grboxTextVis)
        self.rbutPlain.setChecked(True)
        self.rbutPlain.setObjectName("rbutPlain")
        self.horizontalLayout.addWidget(self.rbutPlain)
        self.rbutParsed = QtWidgets.QRadioButton(self.grboxTextVis)
        self.rbutParsed.setObjectName("rbutParsed")
        self.horizontalLayout.addWidget(self.rbutParsed)
        self.gridLayout_6.addWidget(self.grboxTextVis, 2, 1, 2, 4)
        self.listScriptLines = QtWidgets.QListWidget(self.tabScript)
        self.listScriptLines.setWordWrap(True)
        self.listScriptLines.setObjectName("listScriptLines")
        self.gridLayout_6.addWidget(self.listScriptLines, 7, 0, 5, 1)
        self.tabWidget.addTab(self.tabScript, "")
        self.tabSubstitutions = QtWidgets.QWidget()
        self.tabSubstitutions.setObjectName("tabSubstitutions")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.tabSubstitutions)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.butImportSubst = QtWidgets.QPushButton(self.tabSubstitutions)
        self.butImportSubst.setObjectName("butImportSubst")
        self.gridLayout_8.addWidget(self.butImportSubst, 0, 2, 1, 1)
        self.butRemoveSubst = QtWidgets.QPushButton(self.tabSubstitutions)
        self.butRemoveSubst.setObjectName("butRemoveSubst")
        self.gridLayout_8.addWidget(self.butRemoveSubst, 5, 2, 1, 1)
        self.butUpdateSubst = QtWidgets.QPushButton(self.tabSubstitutions)
        self.butUpdateSubst.setObjectName("butUpdateSubst")
        self.gridLayout_8.addWidget(self.butUpdateSubst, 6, 2, 1, 1)
        self.butAddSubst = QtWidgets.QPushButton(self.tabSubstitutions)
        self.butAddSubst.setObjectName("butAddSubst")
        self.gridLayout_8.addWidget(self.butAddSubst, 4, 2, 1, 1)
        self.tblSubst = QtWidgets.QTableWidget(self.tabSubstitutions)
        self.tblSubst.setMinimumSize(QtCore.QSize(0, 300))
        self.tblSubst.setColumnCount(4)
        self.tblSubst.setObjectName("tblSubst")
        self.tblSubst.setRowCount(0)
        self.tblSubst.horizontalHeader().setCascadingSectionResizes(False)
        self.tblSubst.horizontalHeader().setMinimumSectionSize(27)
        self.tblSubst.horizontalHeader().setStretchLastSection(True)
        self.gridLayout_8.addWidget(self.tblSubst, 4, 0, 3, 1)
        self.butExportSubst = QtWidgets.QPushButton(self.tabSubstitutions)
        self.butExportSubst.setObjectName("butExportSubst")
        self.gridLayout_8.addWidget(self.butExportSubst, 1, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.tabSubstitutions)
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 100))
        self.label_4.setWordWrap(True)
        self.label_4.setObjectName("label_4")
        self.gridLayout_8.addWidget(self.label_4, 0, 0, 2, 1)
        self.tabWidget.addTab(self.tabSubstitutions, "")
        self.tabSpeakers = QtWidgets.QWidget()
        self.tabSpeakers.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabSpeakers.sizePolicy().hasHeightForWidth())
        self.tabSpeakers.setSizePolicy(sizePolicy)
        self.tabSpeakers.setObjectName("tabSpeakers")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tabSpeakers)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tabSpeakers)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.gridLayout_2.addWidget(self.groupBox_3, 2, 2, 1, 1)
        self.tblSpeakerParameters = QtWidgets.QTableWidget(self.tabSpeakers)
        self.tblSpeakerParameters.setColumnCount(2)
        self.tblSpeakerParameters.setObjectName("tblSpeakerParameters")
        self.tblSpeakerParameters.setRowCount(0)
        self.tblSpeakerParameters.horizontalHeader().setStretchLastSection(True)
        self.gridLayout_2.addWidget(self.tblSpeakerParameters, 3, 2, 1, 1)
        self.lblTestPhrase = QtWidgets.QLabel(self.tabSpeakers)
        self.lblTestPhrase.setObjectName("lblTestPhrase")
        self.gridLayout_2.addWidget(self.lblTestPhrase, 5, 2, 1, 1)
        self.butPlayTest = QtWidgets.QPushButton(self.tabSpeakers)
        self.butPlayTest.setObjectName("butPlayTest")
        self.gridLayout_2.addWidget(self.butPlayTest, 7, 2, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.tabSpeakers)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.lvSpeakers = QtWidgets.QListWidget(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lvSpeakers.sizePolicy().hasHeightForWidth())
        self.lvSpeakers.setSizePolicy(sizePolicy)
        self.lvSpeakers.setMaximumSize(QtCore.QSize(300, 16777215))
        self.lvSpeakers.setObjectName("lvSpeakers")
        self.verticalLayout_5.addWidget(self.lvSpeakers)
        self.gridGroupBox = QtWidgets.QGroupBox(self.groupBox_2)
        self.gridGroupBox.setObjectName("gridGroupBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridGroupBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.butRemoveSpeaker = QtWidgets.QPushButton(self.gridGroupBox)
        self.butRemoveSpeaker.setObjectName("butRemoveSpeaker")
        self.gridLayout_3.addWidget(self.butRemoveSpeaker, 0, 1, 1, 1)
        self.butAddSpeaker = QtWidgets.QPushButton(self.gridGroupBox)
        self.butAddSpeaker.setObjectName("butAddSpeaker")
        self.gridLayout_3.addWidget(self.butAddSpeaker, 0, 0, 1, 1)
        self.butImportSpeakers = QtWidgets.QPushButton(self.gridGroupBox)
        self.butImportSpeakers.setObjectName("butImportSpeakers")
        self.gridLayout_3.addWidget(self.butImportSpeakers, 1, 0, 1, 1)
        self.butExportSpeakers = QtWidgets.QPushButton(self.gridGroupBox)
        self.butExportSpeakers.setObjectName("butExportSpeakers")
        self.gridLayout_3.addWidget(self.butExportSpeakers, 1, 1, 1, 1)
        self.verticalLayout_5.addWidget(self.gridGroupBox)
        self.gridLayout_2.addWidget(self.groupBox_2, 2, 0, 6, 1)
        self.txtTestPhrase = QtWidgets.QPlainTextEdit(self.tabSpeakers)
        self.txtTestPhrase.setObjectName("txtTestPhrase")
        self.gridLayout_2.addWidget(self.txtTestPhrase, 6, 2, 1, 1)
        self.butUpdateSpeaker = QtWidgets.QPushButton(self.tabSpeakers)
        self.butUpdateSpeaker.setObjectName("butUpdateSpeaker")
        self.gridLayout_2.addWidget(self.butUpdateSpeaker, 4, 2, 1, 1)
        self.tabWidget.addTab(self.tabSpeakers, "")
        self.tabRender = QtWidgets.QWidget()
        self.tabRender.setObjectName("tabRender")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.tabRender)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.leFestivalVersion = QtWidgets.QLineEdit(self.tabRender)
        self.leFestivalVersion.setEnabled(False)
        self.leFestivalVersion.setReadOnly(True)
        self.leFestivalVersion.setObjectName("leFestivalVersion")
        self.gridLayout_7.addWidget(self.leFestivalVersion, 1, 1, 1, 1)
        self.grRenderOptions = QtWidgets.QGroupBox(self.tabRender)
        self.grRenderOptions.setObjectName("grRenderOptions")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.grRenderOptions)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.spindBLevel = QtWidgets.QSpinBox(self.grRenderOptions)
        self.spindBLevel.setMinimum(-99)
        self.spindBLevel.setMaximum(0)
        self.spindBLevel.setProperty("value", -3)
        self.spindBLevel.setObjectName("spindBLevel")
        self.gridLayout_13.addWidget(self.spindBLevel, 7, 2, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.grRenderOptions)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_13.addWidget(self.label_7, 7, 1, 1, 1)
        self.cmbSpeakerSelect = QtWidgets.QComboBox(self.grRenderOptions)
        self.cmbSpeakerSelect.setEnabled(False)
        self.cmbSpeakerSelect.setObjectName("cmbSpeakerSelect")
        self.gridLayout_13.addWidget(self.cmbSpeakerSelect, 5, 1, 1, 3)
        self.lblThreads = QtWidgets.QLabel(self.grRenderOptions)
        self.lblThreads.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblThreads.setObjectName("lblThreads")
        self.gridLayout_13.addWidget(self.lblThreads, 7, 3, 1, 1)
        self.butSetOutputFolder = QtWidgets.QPushButton(self.grRenderOptions)
        self.butSetOutputFolder.setObjectName("butSetOutputFolder")
        self.gridLayout_13.addWidget(self.butSetOutputFolder, 2, 4, 1, 1)
        self.spinCPUthreads = QtWidgets.QSpinBox(self.grRenderOptions)
        self.spinCPUthreads.setProperty("value", 1)
        self.spinCPUthreads.setObjectName("spinCPUthreads")
        self.gridLayout_13.addWidget(self.spinCPUthreads, 7, 4, 1, 1)
        self.spinSceneOffset = QtWidgets.QSpinBox(self.grRenderOptions)
        self.spinSceneOffset.setMinimum(0)
        self.spinSceneOffset.setMaximum(9999)
        self.spinSceneOffset.setObjectName("spinSceneOffset")
        self.gridLayout_13.addWidget(self.spinSceneOffset, 4, 1, 1, 1)
        self.chbNormalizeAudio = QtWidgets.QCheckBox(self.grRenderOptions)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chbNormalizeAudio.sizePolicy().hasHeightForWidth())
        self.chbNormalizeAudio.setSizePolicy(sizePolicy)
        self.chbNormalizeAudio.setChecked(True)
        self.chbNormalizeAudio.setObjectName("chbNormalizeAudio")
        self.gridLayout_13.addWidget(self.chbNormalizeAudio, 7, 0, 1, 1)
        self.chbLimitSpeaker = QtWidgets.QCheckBox(self.grRenderOptions)
        self.chbLimitSpeaker.setObjectName("chbLimitSpeaker")
        self.gridLayout_13.addWidget(self.chbLimitSpeaker, 5, 0, 1, 1)
        self.lblOutputFolder = QtWidgets.QLabel(self.grRenderOptions)
        self.lblOutputFolder.setObjectName("lblOutputFolder")
        self.gridLayout_13.addWidget(self.lblOutputFolder, 2, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.grRenderOptions)
        self.label_5.setObjectName("label_5")
        self.gridLayout_13.addWidget(self.label_5, 4, 0, 1, 1)
        self.leOutputFolder = QtWidgets.QLineEdit(self.grRenderOptions)
        self.leOutputFolder.setEnabled(False)
        self.leOutputFolder.setObjectName("leOutputFolder")
        self.gridLayout_13.addWidget(self.leOutputFolder, 2, 1, 1, 3)
        self.spinLastScene = QtWidgets.QSpinBox(self.grRenderOptions)
        self.spinLastScene.setMaximum(9999)
        self.spinLastScene.setObjectName("spinLastScene")
        self.gridLayout_13.addWidget(self.spinLastScene, 4, 2, 1, 1)
        self.chbCombine = QtWidgets.QCheckBox(self.grRenderOptions)
        self.chbCombine.setObjectName("chbCombine")
        self.gridLayout_13.addWidget(self.chbCombine, 2, 5, 1, 1)
        self.chbUseServer = QtWidgets.QCheckBox(self.grRenderOptions)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chbUseServer.sizePolicy().hasHeightForWidth())
        self.chbUseServer.setSizePolicy(sizePolicy)
        self.chbUseServer.setObjectName("chbUseServer")
        self.gridLayout_13.addWidget(self.chbUseServer, 8, 0, 1, 1)
        self.leFestivalServerName = QtWidgets.QLineEdit(self.grRenderOptions)
        self.leFestivalServerName.setObjectName("leFestivalServerName")
        self.gridLayout_13.addWidget(self.leFestivalServerName, 8, 2, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.grRenderOptions)
        self.label_25.setObjectName("label_25")
        self.gridLayout_13.addWidget(self.label_25, 8, 1, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.grRenderOptions)
        self.label_26.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_26.setObjectName("label_26")
        self.gridLayout_13.addWidget(self.label_26, 8, 3, 1, 1)
        self.leFestivalServerPort = QtWidgets.QLineEdit(self.grRenderOptions)
        self.leFestivalServerPort.setObjectName("leFestivalServerPort")
        self.gridLayout_13.addWidget(self.leFestivalServerPort, 8, 4, 1, 1)
        self.gridLayout_7.addWidget(self.grRenderOptions, 3, 0, 1, 2)
        self.label_9 = QtWidgets.QLabel(self.tabRender)
        self.label_9.setObjectName("label_9")
        self.gridLayout_7.addWidget(self.label_9, 1, 0, 1, 1)
        self.leSoXversion = QtWidgets.QLineEdit(self.tabRender)
        self.leSoXversion.setEnabled(False)
        self.leSoXversion.setReadOnly(True)
        self.leSoXversion.setObjectName("leSoXversion")
        self.gridLayout_7.addWidget(self.leSoXversion, 2, 1, 1, 1)
        self.grPostProcessing = QtWidgets.QGroupBox(self.tabRender)
        self.grPostProcessing.setObjectName("grPostProcessing")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.grPostProcessing)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.butNormailzeAudio = QtWidgets.QPushButton(self.grPostProcessing)
        self.butNormailzeAudio.setObjectName("butNormailzeAudio")
        self.gridLayout_12.addWidget(self.butNormailzeAudio, 1, 0, 1, 1)
        self.butRemoveFiles = QtWidgets.QPushButton(self.grPostProcessing)
        self.butRemoveFiles.setObjectName("butRemoveFiles")
        self.gridLayout_12.addWidget(self.butRemoveFiles, 1, 2, 1, 1)
        self.butCombineAudio = QtWidgets.QPushButton(self.grPostProcessing)
        self.butCombineAudio.setObjectName("butCombineAudio")
        self.gridLayout_12.addWidget(self.butCombineAudio, 1, 1, 1, 1)
        self.gridLayout_7.addWidget(self.grPostProcessing, 8, 0, 1, 2)
        self.label_10 = QtWidgets.QLabel(self.tabRender)
        self.label_10.setObjectName("label_10")
        self.gridLayout_7.addWidget(self.label_10, 2, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_7.addItem(spacerItem, 9, 1, 1, 1)
        self.butRender = QtWidgets.QPushButton(self.tabRender)
        self.butRender.setEnabled(True)
        self.butRender.setObjectName("butRender")
        self.gridLayout_7.addWidget(self.butRender, 4, 0, 1, 2)
        self.tabWidget.addTab(self.tabRender, "")
        self.tabPreferences = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabPreferences.sizePolicy().hasHeightForWidth())
        self.tabPreferences.setSizePolicy(sizePolicy)
        self.tabPreferences.setObjectName("tabPreferences")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.tabPreferences)
        self.gridLayout_9.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.grRenderOptionsDefault = QtWidgets.QGroupBox(self.tabPreferences)
        self.grRenderOptionsDefault.setObjectName("grRenderOptionsDefault")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.grRenderOptionsDefault)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_17 = QtWidgets.QLabel(self.grRenderOptionsDefault)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_17.sizePolicy().hasHeightForWidth())
        self.label_17.setSizePolicy(sizePolicy)
        self.label_17.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_17.setObjectName("label_17")
        self.gridLayout_4.addWidget(self.label_17, 0, 1, 1, 1)
        self.chbNormalizeAudioDefault = QtWidgets.QCheckBox(self.grRenderOptionsDefault)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chbNormalizeAudioDefault.sizePolicy().hasHeightForWidth())
        self.chbNormalizeAudioDefault.setSizePolicy(sizePolicy)
        self.chbNormalizeAudioDefault.setObjectName("chbNormalizeAudioDefault")
        self.gridLayout_4.addWidget(self.chbNormalizeAudioDefault, 0, 0, 1, 1)
        self.chbCombineAudioDefault = QtWidgets.QCheckBox(self.grRenderOptionsDefault)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chbCombineAudioDefault.sizePolicy().hasHeightForWidth())
        self.chbCombineAudioDefault.setSizePolicy(sizePolicy)
        self.chbCombineAudioDefault.setObjectName("chbCombineAudioDefault")
        self.gridLayout_4.addWidget(self.chbCombineAudioDefault, 0, 8, 1, 1)
        self.spinDBlevelDefault = QtWidgets.QSpinBox(self.grRenderOptionsDefault)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinDBlevelDefault.sizePolicy().hasHeightForWidth())
        self.spinDBlevelDefault.setSizePolicy(sizePolicy)
        self.spinDBlevelDefault.setMinimumSize(QtCore.QSize(70, 0))
        self.spinDBlevelDefault.setMinimum(-99)
        self.spinDBlevelDefault.setMaximum(0)
        self.spinDBlevelDefault.setProperty("value", -3)
        self.spinDBlevelDefault.setObjectName("spinDBlevelDefault")
        self.gridLayout_4.addWidget(self.spinDBlevelDefault, 0, 2, 1, 1)
        self.spinCPUThreadsDefault = QtWidgets.QSpinBox(self.grRenderOptionsDefault)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinCPUThreadsDefault.sizePolicy().hasHeightForWidth())
        self.spinCPUThreadsDefault.setSizePolicy(sizePolicy)
        self.spinCPUThreadsDefault.setMinimumSize(QtCore.QSize(70, 0))
        self.spinCPUThreadsDefault.setMinimum(1)
        self.spinCPUThreadsDefault.setObjectName("spinCPUThreadsDefault")
        self.gridLayout_4.addWidget(self.spinCPUThreadsDefault, 0, 6, 1, 1)
        self.chbUseFesitvalServerDefault = QtWidgets.QCheckBox(self.grRenderOptionsDefault)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chbUseFesitvalServerDefault.sizePolicy().hasHeightForWidth())
        self.chbUseFesitvalServerDefault.setSizePolicy(sizePolicy)
        self.chbUseFesitvalServerDefault.setObjectName("chbUseFesitvalServerDefault")
        self.gridLayout_4.addWidget(self.chbUseFesitvalServerDefault, 0, 7, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.grRenderOptionsDefault)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_16.sizePolicy().hasHeightForWidth())
        self.label_16.setSizePolicy(sizePolicy)
        self.label_16.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_16.setObjectName("label_16")
        self.gridLayout_4.addWidget(self.label_16, 0, 3, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem1, 0, 9, 1, 1)
        self.gridLayout_9.addWidget(self.grRenderOptionsDefault, 1, 0, 1, 3)
        self.grDefaultSpeaker = QtWidgets.QGroupBox(self.tabPreferences)
        self.grDefaultSpeaker.setObjectName("grDefaultSpeaker")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.grDefaultSpeaker)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.grNarrator = QtWidgets.QGroupBox(self.grDefaultSpeaker)
        self.grNarrator.setObjectName("grNarrator")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.grNarrator)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.label_18 = QtWidgets.QLabel(self.grNarrator)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_18.sizePolicy().hasHeightForWidth())
        self.label_18.setSizePolicy(sizePolicy)
        self.label_18.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_18.setObjectName("label_18")
        self.gridLayout_10.addWidget(self.label_18, 0, 0, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.grNarrator)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_19.sizePolicy().hasHeightForWidth())
        self.label_19.setSizePolicy(sizePolicy)
        self.label_19.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_19.setObjectName("label_19")
        self.gridLayout_10.addWidget(self.label_19, 0, 2, 1, 1)
        self.spinDefaultNarratorPitch = QtWidgets.QSpinBox(self.grNarrator)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinDefaultNarratorPitch.sizePolicy().hasHeightForWidth())
        self.spinDefaultNarratorPitch.setSizePolicy(sizePolicy)
        self.spinDefaultNarratorPitch.setMinimumSize(QtCore.QSize(100, 0))
        self.spinDefaultNarratorPitch.setMinimum(-1000)
        self.spinDefaultNarratorPitch.setMaximum(1000)
        self.spinDefaultNarratorPitch.setSingleStep(50)
        self.spinDefaultNarratorPitch.setObjectName("spinDefaultNarratorPitch")
        self.gridLayout_10.addWidget(self.spinDefaultNarratorPitch, 0, 3, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.grNarrator)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_21.sizePolicy().hasHeightForWidth())
        self.label_21.setSizePolicy(sizePolicy)
        self.label_21.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_21.setObjectName("label_21")
        self.gridLayout_10.addWidget(self.label_21, 0, 6, 1, 1)
        self.cmbDefaultNarratorVoice = QtWidgets.QComboBox(self.grNarrator)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbDefaultNarratorVoice.sizePolicy().hasHeightForWidth())
        self.cmbDefaultNarratorVoice.setSizePolicy(sizePolicy)
        self.cmbDefaultNarratorVoice.setObjectName("cmbDefaultNarratorVoice")
        self.gridLayout_10.addWidget(self.cmbDefaultNarratorVoice, 0, 1, 1, 1)
        self.spinDefaultNarratorTempo = QtWidgets.QDoubleSpinBox(self.grNarrator)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinDefaultNarratorTempo.sizePolicy().hasHeightForWidth())
        self.spinDefaultNarratorTempo.setSizePolicy(sizePolicy)
        self.spinDefaultNarratorTempo.setSingleStep(0.1)
        self.spinDefaultNarratorTempo.setObjectName("spinDefaultNarratorTempo")
        self.gridLayout_10.addWidget(self.spinDefaultNarratorTempo, 0, 5, 1, 1)
        self.spinDefaultNarratorVolume = QtWidgets.QDoubleSpinBox(self.grNarrator)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinDefaultNarratorVolume.sizePolicy().hasHeightForWidth())
        self.spinDefaultNarratorVolume.setSizePolicy(sizePolicy)
        self.spinDefaultNarratorVolume.setSingleStep(0.1)
        self.spinDefaultNarratorVolume.setObjectName("spinDefaultNarratorVolume")
        self.gridLayout_10.addWidget(self.spinDefaultNarratorVolume, 0, 7, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.grNarrator)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_20.sizePolicy().hasHeightForWidth())
        self.label_20.setSizePolicy(sizePolicy)
        self.label_20.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_20.setObjectName("label_20")
        self.gridLayout_10.addWidget(self.label_20, 0, 4, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem2, 0, 8, 1, 1)
        self.gridLayout_5.addWidget(self.grNarrator, 1, 0, 1, 3)
        self.chbImportDefaultSpeakers = QtWidgets.QCheckBox(self.grDefaultSpeaker)
        self.chbImportDefaultSpeakers.setObjectName("chbImportDefaultSpeakers")
        self.gridLayout_5.addWidget(self.chbImportDefaultSpeakers, 0, 0, 1, 1)
        self.leDefaultSpeakerFile = QtWidgets.QLineEdit(self.grDefaultSpeaker)
        self.leDefaultSpeakerFile.setEnabled(False)
        self.leDefaultSpeakerFile.setObjectName("leDefaultSpeakerFile")
        self.gridLayout_5.addWidget(self.leDefaultSpeakerFile, 0, 1, 1, 1)
        self.butSetDefaultSpeakersPath = QtWidgets.QPushButton(self.grDefaultSpeaker)
        self.butSetDefaultSpeakersPath.setObjectName("butSetDefaultSpeakersPath")
        self.gridLayout_5.addWidget(self.butSetDefaultSpeakersPath, 0, 2, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.grDefaultSpeaker)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.label_22 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_22.sizePolicy().hasHeightForWidth())
        self.label_22.setSizePolicy(sizePolicy)
        self.label_22.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_22.setObjectName("label_22")
        self.gridLayout_11.addWidget(self.label_22, 0, 0, 1, 1)
        self.spinPitchDefaultSpeaker = QtWidgets.QSpinBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinPitchDefaultSpeaker.sizePolicy().hasHeightForWidth())
        self.spinPitchDefaultSpeaker.setSizePolicy(sizePolicy)
        self.spinPitchDefaultSpeaker.setMinimumSize(QtCore.QSize(100, 0))
        self.spinPitchDefaultSpeaker.setMinimum(-1000)
        self.spinPitchDefaultSpeaker.setMaximum(1000)
        self.spinPitchDefaultSpeaker.setSingleStep(50)
        self.spinPitchDefaultSpeaker.setProperty("value", 0)
        self.spinPitchDefaultSpeaker.setObjectName("spinPitchDefaultSpeaker")
        self.gridLayout_11.addWidget(self.spinPitchDefaultSpeaker, 0, 3, 1, 1)
        self.spinVolumeDefaultSpeaker = QtWidgets.QDoubleSpinBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinVolumeDefaultSpeaker.sizePolicy().hasHeightForWidth())
        self.spinVolumeDefaultSpeaker.setSizePolicy(sizePolicy)
        self.spinVolumeDefaultSpeaker.setSingleStep(0.1)
        self.spinVolumeDefaultSpeaker.setObjectName("spinVolumeDefaultSpeaker")
        self.gridLayout_11.addWidget(self.spinVolumeDefaultSpeaker, 0, 7, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout_11.addWidget(self.label_8, 0, 4, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_23.sizePolicy().hasHeightForWidth())
        self.label_23.setSizePolicy(sizePolicy)
        self.label_23.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_23.setObjectName("label_23")
        self.gridLayout_11.addWidget(self.label_23, 0, 6, 1, 1)
        self.cmbDefaultSpeakerVoice = QtWidgets.QComboBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbDefaultSpeakerVoice.sizePolicy().hasHeightForWidth())
        self.cmbDefaultSpeakerVoice.setSizePolicy(sizePolicy)
        self.cmbDefaultSpeakerVoice.setObjectName("cmbDefaultSpeakerVoice")
        self.gridLayout_11.addWidget(self.cmbDefaultSpeakerVoice, 0, 1, 1, 1)
        self.spinTempoDefaultSpeaker = QtWidgets.QDoubleSpinBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinTempoDefaultSpeaker.sizePolicy().hasHeightForWidth())
        self.spinTempoDefaultSpeaker.setSizePolicy(sizePolicy)
        self.spinTempoDefaultSpeaker.setSingleStep(0.1)
        self.spinTempoDefaultSpeaker.setObjectName("spinTempoDefaultSpeaker")
        self.gridLayout_11.addWidget(self.spinTempoDefaultSpeaker, 0, 5, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_11.addWidget(self.label_6, 0, 2, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem3, 0, 8, 1, 1)
        self.gridLayout_5.addWidget(self.groupBox, 2, 0, 1, 3)
        self.gridLayout_9.addWidget(self.grDefaultSpeaker, 2, 0, 1, 3)
        self.grExecPaths = QtWidgets.QGroupBox(self.tabPreferences)
        self.grExecPaths.setObjectName("grExecPaths")
        self.gridLayout = QtWidgets.QGridLayout(self.grExecPaths)
        self.gridLayout.setObjectName("gridLayout")
        self.label_12 = QtWidgets.QLabel(self.grExecPaths)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 3, 0, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.grExecPaths)
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 1, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.grExecPaths)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 2, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.grExecPaths)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 0, 0, 1, 1)
        self.butSetText2wavePath = QtWidgets.QPushButton(self.grExecPaths)
        self.butSetText2wavePath.setObjectName("butSetText2wavePath")
        self.gridLayout.addWidget(self.butSetText2wavePath, 1, 2, 1, 1)
        self.butSelectFestivalPath = QtWidgets.QPushButton(self.grExecPaths)
        self.butSelectFestivalPath.setObjectName("butSelectFestivalPath")
        self.gridLayout.addWidget(self.butSelectFestivalPath, 0, 2, 1, 1)
        self.leFestivalPath = QtWidgets.QLineEdit(self.grExecPaths)
        self.leFestivalPath.setEnabled(False)
        self.leFestivalPath.setObjectName("leFestivalPath")
        self.gridLayout.addWidget(self.leFestivalPath, 0, 1, 1, 1)
        self.leSoxPath = QtWidgets.QLineEdit(self.grExecPaths)
        self.leSoxPath.setEnabled(False)
        self.leSoxPath.setObjectName("leSoxPath")
        self.gridLayout.addWidget(self.leSoxPath, 3, 1, 1, 1)
        self.butSetSoXPath = QtWidgets.QPushButton(self.grExecPaths)
        self.butSetSoXPath.setObjectName("butSetSoXPath")
        self.gridLayout.addWidget(self.butSetSoXPath, 3, 2, 1, 1)
        self.leText2WavePath = QtWidgets.QLineEdit(self.grExecPaths)
        self.leText2WavePath.setEnabled(False)
        self.leText2WavePath.setObjectName("leText2WavePath")
        self.gridLayout.addWidget(self.leText2WavePath, 1, 1, 1, 1)
        self.butSetFestivalClientPath = QtWidgets.QPushButton(self.grExecPaths)
        self.butSetFestivalClientPath.setObjectName("butSetFestivalClientPath")
        self.gridLayout.addWidget(self.butSetFestivalClientPath, 2, 2, 1, 1)
        self.leFestivalClientPath = QtWidgets.QLineEdit(self.grExecPaths)
        self.leFestivalClientPath.setEnabled(False)
        self.leFestivalClientPath.setObjectName("leFestivalClientPath")
        self.gridLayout.addWidget(self.leFestivalClientPath, 2, 1, 1, 1)
        self.gridLayout_9.addWidget(self.grExecPaths, 0, 0, 1, 3)
        self.butExportPrefs = QtWidgets.QPushButton(self.tabPreferences)
        self.butExportPrefs.setObjectName("butExportPrefs")
        self.gridLayout_9.addWidget(self.butExportPrefs, 6, 2, 1, 1)
        self.butSavePrefs = QtWidgets.QPushButton(self.tabPreferences)
        self.butSavePrefs.setObjectName("butSavePrefs")
        self.gridLayout_9.addWidget(self.butSavePrefs, 6, 0, 1, 1)
        self.butImportPrefs = QtWidgets.QPushButton(self.tabPreferences)
        self.butImportPrefs.setObjectName("butImportPrefs")
        self.gridLayout_9.addWidget(self.butImportPrefs, 6, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_9.addItem(spacerItem4, 5, 0, 1, 1)
        self.grSubstitutions = QtWidgets.QGroupBox(self.tabPreferences)
        self.grSubstitutions.setObjectName("grSubstitutions")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.grSubstitutions)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.chbImportDefaultSubst = QtWidgets.QCheckBox(self.grSubstitutions)
        self.chbImportDefaultSubst.setObjectName("chbImportDefaultSubst")
        self.gridLayout_14.addWidget(self.chbImportDefaultSubst, 0, 0, 1, 1)
        self.leDefaultSubstFile = QtWidgets.QLineEdit(self.grSubstitutions)
        self.leDefaultSubstFile.setEnabled(False)
        self.leDefaultSubstFile.setObjectName("leDefaultSubstFile")
        self.gridLayout_14.addWidget(self.leDefaultSubstFile, 0, 1, 1, 1)
        self.butSetDefaultSubstPath = QtWidgets.QPushButton(self.grSubstitutions)
        self.butSetDefaultSubstPath.setObjectName("butSetDefaultSubstPath")
        self.gridLayout_14.addWidget(self.butSetDefaultSubstPath, 0, 2, 1, 1)
        self.gridLayout_9.addWidget(self.grSubstitutions, 4, 0, 1, 3)
        self.tabWidget.addTab(self.tabPreferences, "")
        self.tabAbout = QtWidgets.QWidget()
        self.tabAbout.setObjectName("tabAbout")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tabAbout)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lblLicense = QtWidgets.QLabel(self.tabAbout)
        self.lblLicense.setAlignment(QtCore.Qt.AlignCenter)
        self.lblLicense.setOpenExternalLinks(True)
        self.lblLicense.setTextInteractionFlags(QtCore.Qt.TextBrowserInteraction)
        self.lblLicense.setObjectName("lblLicense")
        self.verticalLayout.addWidget(self.lblLicense)
        self.tabWidget.addTab(self.tabAbout, "")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.splitter)
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.ConsoleLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.ConsoleLayout.setContentsMargins(0, 0, 0, 0)
        self.ConsoleLayout.setObjectName("ConsoleLayout")
        self.label_13 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_13.setObjectName("label_13")
        self.ConsoleLayout.addWidget(self.label_13)
        self.txtLog = QtWidgets.QTextEdit(self.verticalLayoutWidget)
        self.txtLog.setObjectName("txtLog")
        self.ConsoleLayout.addWidget(self.txtLog)
        self.gridLayout_15.addWidget(self.splitter, 6, 0, 1, 3)
        self.lblLogo = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.lblLogo.setFont(font)
        self.lblLogo.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblLogo.setObjectName("lblLogo")
        self.gridLayout_15.addWidget(self.lblLogo, 4, 2, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 941, 22))
        self.menubar.setDefaultUp(False)
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "dramaTTS"))
        self.butSaveProjectAs.setText(_translate("MainWindow", "Save as..."))
        self.butSaveProject.setText(_translate("MainWindow", "Save"))
        self.butOpenProject.setText(_translate("MainWindow", "Open "))
        self.butNewProject.setText(_translate("MainWindow", "New"))
        self.lblCharacters.setText(_translate("MainWindow", "Characters"))
        self.butAddCharacters.setText(_translate("MainWindow", "Add speakers for characters"))
        self.label_3.setText(_translate("MainWindow", "End line"))
        self.butImportScript.setText(_translate("MainWindow", "Import script from .txt"))
        self.tblLineProps.setSortingEnabled(True)
        self.label_2.setText(_translate("MainWindow", "Start line"))
        self.lblLineProps.setText(_translate("MainWindow", "Line properties"))
        self.lblLineView.setText(_translate("MainWindow", "Script lines"))
        self.butUpdateLineProps.setText(_translate("MainWindow", "Update Line properties"))
        self.butImportParsed.setText(_translate("MainWindow", "Import parsed lines from .json"))
        self.butExportParsedLines.setText(_translate("MainWindow", "Export parsed lines to .json"))
        self.grboxTextVis.setTitle(_translate("MainWindow", "Text rendering"))
        self.rbutPlain.setText(_translate("MainWindow", "Original text"))
        self.rbutParsed.setText(_translate("MainWindow", "Parsed lines"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabScript), _translate("MainWindow", "Script"))
        self.butImportSubst.setText(_translate("MainWindow", "Import Substitutions"))
        self.butRemoveSubst.setText(_translate("MainWindow", "Remove entry"))
        self.butUpdateSubst.setText(_translate("MainWindow", "Update entries"))
        self.butAddSubst.setText(_translate("MainWindow", "Add entry"))
        self.tblSubst.setSortingEnabled(False)
        self.butExportSubst.setText(_translate("MainWindow", "Export Substitutions"))
        self.label_4.setText(_translate("MainWindow", "Define substitutions of strings in the text here.\n"
"The substitutions will be performed as the first step, when a text file is imported.\n"
"Regular expressions based on the python re module are supported."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabSubstitutions), _translate("MainWindow", "Substitutions"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Speaker parameters"))
        self.lblTestPhrase.setText(_translate("MainWindow", "Enter test phrase below"))
        self.butPlayTest.setText(_translate("MainWindow", "Play test phrase"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Available speakers"))
        self.butRemoveSpeaker.setText(_translate("MainWindow", "Remove Speaker"))
        self.butAddSpeaker.setText(_translate("MainWindow", "Add Speaker"))
        self.butImportSpeakers.setText(_translate("MainWindow", "Import Speakers"))
        self.butExportSpeakers.setText(_translate("MainWindow", "Export Speakers"))
        self.txtTestPhrase.setPlainText(_translate("MainWindow", "May the force be with you."))
        self.txtTestPhrase.setPlaceholderText(_translate("MainWindow", "Enter test phrase here..."))
        self.butUpdateSpeaker.setText(_translate("MainWindow", "Update speaker parameters"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabSpeakers), _translate("MainWindow", "Speakers"))
        self.grRenderOptions.setTitle(_translate("MainWindow", "Render Options"))
        self.label_7.setText(_translate("MainWindow", "dB level"))
        self.lblThreads.setText(_translate("MainWindow", "CPU threads:"))
        self.butSetOutputFolder.setText(_translate("MainWindow", "Set Output folder"))
        self.chbNormalizeAudio.setText(_translate("MainWindow", "Normalize audio"))
        self.chbLimitSpeaker.setText(_translate("MainWindow", "Render only one speaker"))
        self.lblOutputFolder.setText(_translate("MainWindow", "Output folder: "))
        self.label_5.setText(_translate("MainWindow", "First scene/Last scene"))
        self.chbCombine.setText(_translate("MainWindow", "Combine output to one file"))
        self.chbUseServer.setText(_translate("MainWindow", "Use festival Server"))
        self.label_25.setText(_translate("MainWindow", "Sever name"))
        self.label_26.setText(_translate("MainWindow", "port:"))
        self.label_9.setText(_translate("MainWindow", "festival version:"))
        self.grPostProcessing.setTitle(_translate("MainWindow", "Post processing"))
        self.butNormailzeAudio.setText(_translate("MainWindow", "Normalize audio"))
        self.butRemoveFiles.setText(_translate("MainWindow", "Remove temp. files"))
        self.butCombineAudio.setText(_translate("MainWindow", "Combine to one file"))
        self.label_10.setText(_translate("MainWindow", "SoX version:"))
        self.butRender.setText(_translate("MainWindow", "Start Render"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabRender), _translate("MainWindow", "Render"))
        self.grRenderOptionsDefault.setTitle(_translate("MainWindow", "Default Render Options"))
        self.label_17.setText(_translate("MainWindow", "dB level:"))
        self.chbNormalizeAudioDefault.setText(_translate("MainWindow", "Normalize audio"))
        self.chbCombineAudioDefault.setText(_translate("MainWindow", "Combine audio to one file"))
        self.chbUseFesitvalServerDefault.setText(_translate("MainWindow", "Use festival server"))
        self.label_16.setText(_translate("MainWindow", "no. of CPU threads:"))
        self.grDefaultSpeaker.setTitle(_translate("MainWindow", "Speakers options"))
        self.grNarrator.setTitle(_translate("MainWindow", "Narrator settings"))
        self.label_18.setText(_translate("MainWindow", "Voice"))
        self.label_19.setText(_translate("MainWindow", "Pitch shift"))
        self.label_21.setText(_translate("MainWindow", "Volume"))
        self.label_20.setText(_translate("MainWindow", "Tempo"))
        self.chbImportDefaultSpeakers.setText(_translate("MainWindow", "Import speakers"))
        self.butSetDefaultSpeakersPath.setText(_translate("MainWindow", "Select file"))
        self.groupBox.setTitle(_translate("MainWindow", "Default speaker settings"))
        self.label_22.setText(_translate("MainWindow", "Voice"))
        self.label_8.setText(_translate("MainWindow", "Tempo"))
        self.label_23.setText(_translate("MainWindow", "Volume"))
        self.label_6.setText(_translate("MainWindow", "Pitch shift"))
        self.grExecPaths.setTitle(_translate("MainWindow", "Executable paths"))
        self.label_12.setText(_translate("MainWindow", "SoX path"))
        self.label_15.setText(_translate("MainWindow", "text2wave path:"))
        self.label_14.setText(_translate("MainWindow", "festival_client path:"))
        self.label_11.setText(_translate("MainWindow", "festvial path:"))
        self.butSetText2wavePath.setText(_translate("MainWindow", "Select file"))
        self.butSelectFestivalPath.setText(_translate("MainWindow", "Select file"))
        self.butSetSoXPath.setText(_translate("MainWindow", "Select file"))
        self.butSetFestivalClientPath.setText(_translate("MainWindow", "Select file"))
        self.butExportPrefs.setText(_translate("MainWindow", "Export preferences"))
        self.butSavePrefs.setText(_translate("MainWindow", "Save preferences"))
        self.butImportPrefs.setText(_translate("MainWindow", "Import preferences"))
        self.grSubstitutions.setTitle(_translate("MainWindow", "Substitutions"))
        self.chbImportDefaultSubst.setText(_translate("MainWindow", "Import substitutions"))
        self.butSetDefaultSubstPath.setText(_translate("MainWindow", "Select file"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabPreferences), _translate("MainWindow", "Preferences"))
        self.lblLicense.setText(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Cantarell\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Cantarell\';\">dramaTTS</span></p>\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Cantarell\';\">Free screen play / drama text to multi-voice audio play converter </span></p>\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Bitstream Vera Sans Mono\'; font-size:9pt; color:#000000;\">Copyright (C) 2020 Thies Hecker</span><span style=\" font-family:\'Cantarell\';\"><br /></span></p>\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Cantarell\';\">You can obtain the source code from </span><a href=\"https://gitlab.com/thecker/dramatts\"><span style=\" font-family:\'Cantarell\'; text-decoration: underline; color:#0000ff;\">https://gitlab.com/thecker/dramatts</span></a><span style=\" font-family:\'Cantarell\';\"><br /></span></p>\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Bitstream Vera Sans Mono\'; font-size:9pt; font-style:italic; color:#000000;\">dramaTTS is free software: you can redistribute it and/or modify<br />it under the terms of the GNU General Public License as published by<br />the Free Software Foundation, either version 3 of the License, or<br />(at your option) any later version.<br /><br />This program is distributed in the hope that it will be useful,<br />but WITHOUT ANY WARRANTY; without even the implied warranty of<br />MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the<br />GNU General Public License for more details.<br /><br />You should have received a copy of the GNU General Public License<br />along with this program. If not, see &lt;</span><a href=\"https://www.gnu.org/licenses/\"><span style=\" font-family:\'Cantarell\'; text-decoration: underline; color:#0000ff;\">https://www.gnu.org/licenses/</span></a><span style=\" font-family:\'Bitstream Vera Sans Mono\'; font-size:9pt; font-style:italic; color:#000000;\">&gt;.</span></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Bitstream Vera Sans Mono\'; font-size:9pt; font-style:italic; color:#000000;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Cantarell\';\">dramaTTS relies on the </span><a href=\"http://festvox.org/festival/\"><span style=\" font-family:\'Cantarell\'; text-decoration: underline; color:#0000ff;\">Festival Speech Synthesis System</span></a><span style=\" font-family:\'Cantarell\';\"> for text-to-speech synthesis and </span><a href=\"http://sox.sourceforge.net/\"><span style=\" font-family:\'Cantarell\'; text-decoration: underline; color:#0000ff;\">Sound eXchange (SoX)</span></a><span style=\" font-family:\'Cantarell\';\"> for audio post-processing. </span></p>\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Cantarell\';\">The GUI is made using the </span><a href=\"https://www.riverbankcomputing.com/software/pyqt/intro\"><span style=\" font-family:\'Cantarell\'; text-decoration: underline; color:#0000ff;\">PyQt</span></a><span style=\" font-family:\'Cantarell\';\"> framework and </span><a href=\"https://github.com/pypa/setuptools_scm/\"><span style=\" text-decoration: underline; color:#0000ff;\">setuptools_scm</span></a><span style=\" font-family:\'Cantarell\';\"> is used to align version tags with git.</span></p>\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Cantarell\';\">Please see the </span><a href=\"https://gitlab.com/thecker/dramatts/blob/master/COPYING\"><span style=\" text-decoration: underline; color:#0000ff;\">COPYING</span></a><span style=\" font-family:\'Cantarell\';\"> file for details on the copyrights/licenses of the components listed above.</span></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabAbout), _translate("MainWindow", "About"))
        self.label_13.setText(_translate("MainWindow", "Log:"))
        self.lblLogo.setText(_translate("MainWindow", "dramaTTS"))

