
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-01-25T12:38:41-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "9ab1905f99d5d36547666a4332ae6813290e95ad",
 "version": "0.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
