# coding: utf-8

"""
    Red Rover API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Contact: contact@edustaff.org
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import redrover_api
from redrover_api.models.replacement_criteria_dto import ReplacementCriteriaDto  # noqa: E501
from redrover_api.rest import ApiException


class TestReplacementCriteriaDto(unittest.TestCase):
    """ReplacementCriteriaDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testReplacementCriteriaDto(self):
        """Test ReplacementCriteriaDto"""
        # FIXME: construct object with mandatory attributes with example values
        # model = redrover_api.models.replacement_criteria_dto.ReplacementCriteriaDto()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
