# coding: utf-8

"""
    Red Rover API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Contact: contact@edustaff.org
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import redrover_api
from redrover_api.models.simple_person import SimplePerson  # noqa: E501
from redrover_api.rest import ApiException


class TestSimplePerson(unittest.TestCase):
    """SimplePerson unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSimplePerson(self):
        """Test SimplePerson"""
        # FIXME: construct object with mandatory attributes with example values
        # model = redrover_api.models.simple_person.SimplePerson()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
