#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['winpath']

package_data = \
{'': ['*']}

extras_require = \
{'dev': ['tox', 'pycalver', 'flake8', 'black', 'twine', 'wheel', 'pre-commit'],
 'doc': ['mkdocs', 'mkdocs-material', 'markdown-include'],
 'test': ['pytest >=4.0.0', 'pytest-cov', 'mypy', 'codecov', 'black']}

setup(name='winpath',
      version='202002.1b0',
      description='Retrieves common Windows folders as Unicode strings',
      author='Alberto J. Marin',
      author_email='alberto@ajmar.in',
      url='https://github.com/git-albertomarin/winpath',
      packages=packages,
      package_data=package_data,
      extras_require=extras_require,
      python_requires='>=3.0',
     )
