[tool.poetry]
name = "memfault-cli"
version = "0.0.3"
description = "Memfault CLI tool"
authors = ["Memfault Inc <hello@memfault.com>"]
readme = "README.md"

[tool.poetry.scripts]
memfault = 'memfault_cli.cli:main'

[tool.poetry.dependencies]
python = "^3.6"
Click = "^7.0"
requests = "^2.22.0"
pyelftools = "^0.26.0"
more_itertools = "^7.0"

[tool.poetry.dev-dependencies]
pytest = "^3.0"
requests-mock = "^1.7.0"
snapshottest = "^0.5.1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
