# Generated by Django 2.2.5 on 2020-01-23 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etsy_listing', '0004_auto_20200122_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etsyshop',
            name='shop_id',
            field=models.CharField(default=1, max_length=30, unique=True, verbose_name='ID магазина Etsy'),
            preserve_default=False,
        ),
    ]
