sudo: false
language: python
python:
   - "3.6"
install:
   - pip install -U setuptools
   - pip install -U setuptools-scm
   - pip install -U packaging
   - pip install -r requirements.txt
   - pip install -e .
before_script:
   - coverage run -m aakbar
   - export COVERAGE_PROCESS_START="${PWD}/.coveragerc"
script:
   - cd aakbar/test
   - aakbar --version
   - aakbar --help
   - aakbar test-logging
   - aakbar show-context-object
   - aakbar install-demo-scripts --force
   - aakbar init-config-file .
   - aakbar define-set S.mutans Streptococcus_mutans
   - aakbar label-set S.mutans "Streptococcus mutans"
   - aakbar define-set S.pneu "Streptococcus_pneumoniae"
   - aakbar label-set S.pneu "Streptococcus pneumoniae"
   - aakbar define-set S.infant Streptococcus_infantis
   - aakbar label-set S.infant "Streptococcus infantis"
   - aakbar define-summary strep3 "S.pneu S.mutans S.infant"
   - aakbar set-simplicity-type
   - aakbar set-simplicity-type null
   - aakbar demo-simplicity
   - aakbar set-simplicity-type runlength
   - aakbar demo-simplicity
   - aakbar set-simplicity-type generis10
   - aakbar demo-simplicity
   - aakbar set-simplicity-window 12
   - aakbar set-simplicity-window 10
   - aakbar set-simplicity-type letterfreq10
   - aakbar show-config
   - aakbar set-plot-type png
   - aakbar demo-simplicity
   - aakbar -e peptide-simplicity-mask --cutoff 3 protein.faa protein_letterfreq10-3 all
   - aakbar -e calculate-peptide-terms -k 10 protein_letterfreq12-5.faa protein_letterfreq12-5_k-10 all
   - aakbar -e intersect-peptide-terms protein_letterfreq12-5_k-10 all
   - aakbar -e filter-peptide-terms --cutoff 0.1 protein_letterfreq12-5_k-10 strep3
   - aakbar -e search-peptide-occurrances protein.faa strep3 all
   - aakbar define-set S.pig Streptococcus_porcinus
   - aakbar label-set S.pig "Streptococcus porcinus"
   - aakbar -e search-peptide-occurrances --nucleotides genome-200-bp_reads-first2000.fna strep3 S.pig
   - aakbar conserved-signature-stats genome-200-bp_reads-first2000 strep3 S.pig
after_success:
   - coverage combine
   - cp /tmp/.coverage .
   - bash <(curl -s https://codecov.io/bash) -X gcov
