[tool.poetry]
name = "ilinq"
version = "0.3.2"
description = "linq library"
authors = ["yassu <mathyassu@gmail.com>"]
license = "Apache-2.0"
readme = "Readme.rst"
repository = "https://gitlab.com/yassu/ilinq/"
# documentation = "https://yassu.gitlab.io/ilinq"
classifiers = [
    "Development Status :: 4 - Beta",
    "License :: OSI Approved :: Apache Software License",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Utilities",
]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
sphinx = "^2.3.1"
invoke = "^1.4.0"
flake8 = "^3.7.9"
twine = "^3.1.1"
nose = "^1.3.7"
coverage = "^5.0.3"
sphinx_rtd_theme = "^0.4.3"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
