
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-01-30T14:22:41-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "03b74dd71b331179ec96aed628abfdb3b9b72fad",
 "version": "0.9.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
