---

- name: Manage local device and bind mounts
  collections: [ 'debops.debops' ]
  hosts: [ 'debops_all_hosts', 'debops_service_mount' ]
  become: True

  environment: '{{ inventory__environment | d({})
                   | combine(inventory__group_environment | d({}))
                   | combine(inventory__host_environment  | d({})) }}'

  roles:

    - role: mount
      tags: [ 'role::mount', 'skip::mount' ]
