#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['simple_test_generator']

package_data = \
{'': ['*'],
 'simple_test_generator': ['.pytest_cache/*',
                           '.pytest_cache/v/*',
                           '.pytest_cache/v/cache/*']}

install_requires = \
['jsonpickle <2', 'loguru <1']

setup(name='simple_test_generator',
      version='0.27',
      description='A simple cli-based recorder for Python',
      author='Jeshan G. BABOOA',
      author_email='j@jeshan.co',
      url='https://github.com/jeshan/simple-test-generator',
      packages=packages,
      package_data=package_data,
      install_requires=install_requires,
     )
