# Generated by Django 2.2.5 on 2020-01-17 11:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EbayCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('category_id', models.CharField(max_length=15, verbose_name='ID категории')),
                ('parent_id', models.CharField(max_length=15, verbose_name='ID родительской категории или 0')),
                ('level', models.PositiveSmallIntegerField(verbose_name='Уровень вложенности категории')),
                ('name', models.CharField(max_length=100, verbose_name='Название категории')),
                ('name_path', models.CharField(blank=True, default='', max_length=500, verbose_name='Путь к категории')),
                ('id_path', models.CharField(blank=True, default='', max_length=300, verbose_name='ID пути к категории')),
                ('is_leaf', models.BooleanField(verbose_name='Является листом дерева категорий')),
                ('variationsSupported', models.BooleanField(blank=True, default=False, verbose_name='Доступно для групп товаров')),
                ('transportSupported', models.BooleanField(blank=True, default=False, verbose_name='Транспортная категория')),
            ],
            options={
                'verbose_name': 'Категория товара eBay',
                'verbose_name_plural': 'Категории товара eBay',
            },
        ),
        migrations.CreateModel(
            name='EbayCategoryTree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_tree_id', models.CharField(max_length=10, unique=True, verbose_name='ID дерева категорий')),
                ('category_tree_version', models.CharField(blank=True, max_length=4, null=True, verbose_name='Версия дерева категорий')),
            ],
            options={
                'verbose_name': 'Дерево категорий для eBay',
                'verbose_name_plural': 'Деревья категорий для eBay',
            },
        ),
    ]
