
version: "{branch}-{build}"

branches:
  only:
    - master
    - develop

environment:
  matrix:
    - PYTHON: "C:\\Python35-x64"
      TOXENV: "py35"
    - PYTHON: "C:\\Python36-x64"
      TOXENV: "py36"
    - PYTHON: "C:\\Python37-x64"
      TOXENV: "py37"
    - PYTHON: "C:\\Python38-x64"
      TOXENV: "py38"

install:
  - "%PYTHON%\\python.exe -m pip install --upgrade pip setuptools wheel"
  - "%PYTHON%\\python.exe -m pip install tox"

build: off

test_script:
  - "%PYTHON%\\python.exe -m tox"
