
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-02-03T14:36:09-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "4187cc604efdc2ca5b66481f1b4ab9a67330270b",
 "version": "0.0.58"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
