
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-02-05T16:22:22-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "a47be4ae373ef4cb5e57838da5cfd6a8dad6c3e3",
 "version": "v0.13.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
