language: python
python:
  - "3.6"
  - "3.6-dev"  # 3.6 development branch
  - "3.7"
  - "3.7-dev"  # 3.7 development branch
  - "3.8"
  - "3.8-dev"  # 3.8 development branch
dist: xenial
sudo: true
# command to install dependencies
install:
  - sudo apt-get install libc6
  - pip install -U numpy
  - pip install -U scipy
  - pip install Cython
  - pip install -U .
# command to run tests
script:
  - python setup.py test
