
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-02-04T10:57:29-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "b615994a4c08f93134de1b3dd1d8f422abb3f961",
 "version": "0.1.1.post.dev10"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
