[build-system]
requires = ["flit"]
build-backend = "flit.buildapi"

[tool.flit.metadata]
module = "enboard"
author = "Thomas Kluyver"
author-email = "thomas@kluyver.me.uk"
home-page = "https://gitlab.com/takluyver/enboard"
description-file = "README.rst"
requires-python = ">=3.5"
requires = ["prompt_toolkit>=2", "pygments"]
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Environment :: Console",
    "Programming Language :: Python :: 3"
]

[tool.flit.scripts]
enboard = "enboard:main"
