#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['enboard']

package_data = \
{'': ['*']}

install_requires = \
['prompt_toolkit>=2', 'pygments']

entry_points = \
{'console_scripts': ['enboard = enboard:main']}

setup(name='enboard',
      version='0.6',
      description='Manage Python environments easily.',
      author='Thomas Kluyver',
      author_email='thomas@kluyver.me.uk',
      url='https://gitlab.com/takluyver/enboard',
      packages=packages,
      package_data=package_data,
      install_requires=install_requires,
      entry_points=entry_points,
      python_requires='>=3.5',
     )
