[tool.poetry]
name = "aftool"
version = "0.1.0"
description = "Asdil Fibrizo's tool"
authors = ["Asdil Fibrizo <jpl4job@126.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/Asdil/aftool"
repository = "https://github.com/Asdil/aftool"

[tool.poetry.dependencies]
python = "^3.6"
tqdm = "^4.41"
psutil = "^5.6"
pandas = "^0.25.3"
numpy = "^1.18.0"

[tool.poetry.dev-dependencies]

[[tool.poetry.source]]
name = "ali"
url = "https://mirrors.aliyun.com/pypi/simple/"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
