# Generated by Django 2.2.5 on 2020-01-17 11:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EtsyCountry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('country_id', models.CharField(max_length=10, verbose_name='ID страны')),
                ('iso_country_code', models.CharField(max_length=2, verbose_name='Код страны (ISO)')),
                ('world_bank_country_code', models.CharField(blank=True, max_length=3, null=True, verbose_name='Код страны (мировой банк)')),
                ('name', models.CharField(max_length=50, verbose_name='Название страны')),
                ('slug', models.CharField(blank=True, max_length=50, null=True, verbose_name='Slug страны')),
                ('lat', models.FloatField(blank=True, null=True, verbose_name='Широта')),
                ('lon', models.FloatField(blank=True, null=True, verbose_name='Долгота')),
            ],
            options={
                'verbose_name': 'Страна',
                'verbose_name_plural': 'Страны',
            },
        ),
        migrations.CreateModel(
            name='EtsyRegion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('region_id', models.CharField(max_length=10, verbose_name='ID региона')),
                ('region_name', models.CharField(max_length=50, verbose_name='Название страны')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
