[build-system]
requires = [
  "setuptools>=42",
  "wheel",
  "setuptools-scm[toml]>=3.4.1,<4"
]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]


[tool.coverage.run]
source = ["instawow"]
omit = [
  "instawow/migrations/env.py",
  "instawow/migrations/versions/*.py"
]


[tool.isort]
line_length = 99
combine_as_imports = true
force_sort_within_sections = true
default_section = "THIRDPARTY"
known_first_party = ["instawow"]
