base_enrichr_url: http://amp.pharm.mssm.edu/Enrichr/
gene_set_libraries:
  enrichr:
    - "GO_Biological_Process_2015"
    - "ChEA_2015"
    - "KEGG_2016"
    # - "ESCAPE"
    # - "Epigenomics_Roadmap_HM_ChIP-seq"
    - "ENCODE_TF_ChIP-seq_2015"
    - "ENCODE_and_ChEA_Consensus_TFs_from_ChIP-X"
    # - "ENCODE_Histone_Modifications_2015"
    # - "OMIM_Expanded"
    # - "TF-LOF_Expression_from_GEO"
    # - "Gene_Perturbations_from_GEO_down"
    # - "Gene_Perturbations_from_GEO_up"
    # - "Disease_Perturbations_from_GEO_down"
    # - "Disease_Perturbations_from_GEO_up"
    # - "Drug_Perturbations_from_GEO_down"
    # - "Drug_Perturbations_from_GEO_up"
    - "WikiPathways_2016"
    - "Reactome_2016"
    - "BioCarta_2016"
    - "NCI-Nature_2016"
    # - "BioPlanet_2019"
