# Generated by Django 2.2.5 on 2020-01-17 11:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid
import zonesmart.utils.upload


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCodeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='Наименование')),
                ('description', models.CharField(max_length=100, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Тип кода товара',
                'verbose_name_plural': 'Типы кодов товара',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('image_file', models.ImageField(null=True, upload_to=zonesmart.utils.upload.get_product_image_upload_path, verbose_name='Файл изображения')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='URL изображения')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание изображения')),
            ],
            options={
                'verbose_name': 'Фото товара',
                'verbose_name_plural': 'Фото товара',
            },
        ),
        migrations.CreateModel(
            name='BaseProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('value', models.FloatField(verbose_name='Цена')),
                ('currency', models.CharField(choices=[('RUB', 'Российский рубль'), ('USD', 'Доллар США'), ('EUR', 'Евро'), ('GBP', 'Фунт стерлингов'), ('JPY', 'Японская иена'), ('CNY', 'Китайский юань'), ('AUD', 'Австралийский доллар'), ('CAD', 'Канадский доллар')], max_length=20, verbose_name='Валюта')),
                ('converted_from_value', models.FloatField(blank=True, null=True, verbose_name='Исходная цена')),
                ('converted_from_currency', models.CharField(blank=True, choices=[('RUB', 'Российский рубль'), ('USD', 'Доллар США'), ('EUR', 'Евро'), ('GBP', 'Фунт стерлингов'), ('JPY', 'Японская иена'), ('CNY', 'Китайский юань'), ('AUD', 'Австралийский доллар'), ('CAD', 'Канадский доллар')], max_length=20, null=True, verbose_name='Исходная валюта')),
                ('sku', models.CharField(max_length=50, verbose_name='SKU')),
                ('description', models.TextField(max_length=500000, verbose_name='Описание продукта')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Количество')),
                ('product_id_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Код товара')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('extra_images', models.ManyToManyField(blank=True, related_name='baseproduct_extras', related_query_name='baseproduct_extra', to='base_product.ProductImage', verbose_name='Дополнительные изображения')),
                ('main_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='baseproduct_main_images', related_query_name='baseproduct_main_image', to='base_product.ProductImage', verbose_name='Главное изображение')),
                ('product_id_code_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base_product.ProductCodeType', verbose_name='Тип кода товара')),
            ],
            options={
                'verbose_name': 'Базовый товар',
                'verbose_name_plural': 'Базовые товары',
            },
        ),
    ]
