language: python
python:
  - "3.5"
  - "3.6"
  - "3.7-dev"  # 3.7 development branch
# command to install dependencies
install:
  - pip install numpy scipy matplotlib
  - pip install .
# command to run tests
script:
  - pytest
deploy:
  provider: pypi
  user: colehurwitz
  on:
    tags: true
  password:
    secure: Q+QmnJj7yBtVzu37smXjAxPYHPkaoXGT9wkFUuWaUYP0EtwDCrRQruTNagXz4kOctx9VFNA9Gc4FzWhOBlk2f7F7JvT+whsbGGUI4LsI0hD5H4UqCTGkwnS5deaUMYESNMrdTrq0YSY2yavmTZDT3LupXHYb7sxbTzP2WperTPWSM1do7yFwzhZCFNB1S7Kz+D51m3xdwwLCn3EM3GdwM5Dp8hg0AD+vPBMqgDc5un93sJBxUNHe4Ql7xWzaYcl99ie8oEsshpkR1y4HyqJP7YwDYCrnNdxQS098k76RO2EwXCMtVYR9XQJ0lzMC+fgC0x5DHDOCQ2WSSV9Fy5aKhZV3p/aSaaEyPaTPyaz3lKIAeBxdP2yR5H3wvIxEFjEdEr+yQAqdNlydk7jbpz5sYom3eO9dDEESnuKZR7CnnCtdgJeheFO/SXBXderBHpEA8tNh5pakEYvOgCNUV3fQiQX1H3rwIq7uTtgcQFnSqtrO2OGUOaRutlLY+7lC1jyeC2G9tS+qoRyBGGFu4Pd4Sla4/ccZFk+zsrBma7jdrmPjH9pDNvPhAo6dNgjK5ElZhiqf/WBB1prnRbgGq3D4YvkJ8lHK6oNMzqBv3ily463LbxDcAjF6er3EAxAMyAtwhk39xtQVnIQIbI77GcbtciXbvpHllcBuceNvrSmEBlY=
notifications:
  webhooks:
    urls:
      - YOUR_WEBHOOK_URL
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
