[tool.poetry]
name = "kalc"
version = "0.1.5"
description = "Kalc - the Kubernetes Calculator core"
authors = ["CriticalHop Team <info@criticalhop.com>"]
license = "Apache-2.0"
readme = "README.md"

packages = [
    { include = "kalc" },
]

[tool.poetry.dependencies]
python = ">=3.7"
PyYAML = "^5.1.2"
# yaspin = "^0.15.0"
# Click = "^7.0"
logzero = "^1.5.0"
# pyupdater = "^3.1"
poodle = "^0.2.9"
pandas = "^0.25.3"
libkubeselector = "^0.0.2"
Pygments = "^2.5"
jsonpatch = "^1.24"
setuptools = "^45.0.0"
pytest = "^5.3.5"

[tool.poetry.scripts]
kalc-optimize = "kalc.misc.cli_optimize:tryrun"
kalc-dump = "kalc.misc.cluster_dump:run"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

