
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-01-31T08:29:07+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "1060cd744c5e50df55b6959ece3189c99d72aa66",
 "version": "0.14.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
