

// This file is autogenerated. DO NOT EDIT

#pragma once
#include <robotpy_build.h>

#include <..\..\build\temp.win-amd64-3.6\dlstatic\ctre_api\include\ctre\phoenix\tasking\IProcessable.h>



namespace rpygen {

using namespace ctre::phoenix::tasking;

template <typename CxxBase>
struct Pyctre__phoenix__tasking__IProcessable : CxxBase {
    using CxxBase::CxxBase;



#ifndef RPYGEN_DISABLE_Process_v
    void Process() override {
RPYBUILD_OVERLOAD_PURE_NAME(IProcessable,void, CxxBase, "process", Process,);
    }
#endif



};

}; // namespace rpygen