
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "1541be25665c23593098033582dfb0bc15d7cc1e",
 "version": "3.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
