# Generated by Django 2.2.5 on 2020-01-28 09:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('etsy_category', '0001_initial'),
        ('marketplace', '0002_auto_20200117_1440'),
        ('base_product', '0002_baseproduct_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='EtsyListing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False)),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False)),
                ('status', model_utils.fields.StatusField(choices=[('draft', 'draft'), ('ready_to_publish', 'ready_to_publish'), ('published', 'published'), ('update_required', 'update_required')], default='draft', max_length=100, no_check_for_status=True)),
                ('published_at', model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', when={'published'})),
                ('listing_id', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='ID листинга')),
                ('creation_tsz', models.DateTimeField(blank=True, null=True, verbose_name='Дата и время создания листинга в системе Etsy')),
                ('ending_tsz', models.DateTimeField(blank=True, null=True, verbose_name='Дата и время завершения листинга в системе Etsy')),
                ('original_creation_tsz', models.DateTimeField(blank=True, null=True, verbose_name='Дата и время публикации листинга в системе Etsy')),
                ('last_modified_tsz', models.DateTimeField(blank=True, null=True, verbose_name='Дата и время последнего обновления листинга в системе Etsy')),
                ('state_tsz', models.DateTimeField(blank=True, null=True, verbose_name='Дата и время последнего обновления статуса листинга в системе Etsy')),
                ('title', models.CharField(max_length=300, verbose_name='Заголовок')),
                ('description', models.TextField(max_length=4000, verbose_name='Описание листинга')),
                ('price', models.FloatField(verbose_name='Минимальная цена (USD)')),
                ('currency_code', models.CharField(choices=[('USD', 'USD')], max_length=3, verbose_name='Валюта')),
                ('total_quantity', models.PositiveIntegerField(default=0, verbose_name='Общее количество')),
                ('state', models.CharField(blank=True, choices=[('active', 'active'), ('removed', 'removed'), ('sold_out', 'sold_out'), ('expired', 'expired'), ('edit', 'edit'), ('draft', 'draft'), ('private', 'private'), ('unavailable', 'unavailable')], max_length=30, null=True, verbose_name='Статус листинга')),
                ('who_made', models.CharField(blank=True, choices=[('i_did', 'i_did'), ('collective', 'collective'), ('someone_else', 'someone_else')], default='someone_else', max_length=30, verbose_name='Создатель листинга')),
                ('when_made', models.CharField(blank=True, choices=[('made_to_order', 'made_to_order'), ('2010_2019', '2010_2019'), ('2000_2009', '2000_2009'), ('before_2000', 'before_2000'), ('1990s', '1990s'), ('1980s', '1980s'), ('1970s', '1970s'), ('1960s', '1960s'), ('1950s', '1950s'), ('1940s', '1940s'), ('1930s', '1930s'), ('1920s', '1920s'), ('1910s', '1910s'), ('1900s', '1900s'), ('1800s', '1800s'), ('1700s', '1700s'), ('before_1700', 'before_1700')], default='made_to_order', max_length=30, verbose_name='Период создания листинга')),
                ('is_supply', models.BooleanField(blank=True, default=False, verbose_name='Is supply')),
                ('has_variations', models.BooleanField(blank=True, default=False, verbose_name='Листинг имеет вариации')),
                ('language', models.CharField(default='en-US', max_length=5, verbose_name='Код языка локализации')),
                ('is_digital', models.BooleanField(blank=True, default=False, verbose_name='Листинг предназначен для скачивания')),
                ('url', models.CharField(blank=True, max_length=255, null=True, verbose_name='URL листинга на сайте Etsy')),
                ('views', models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество просмотров листинга')),
                ('num_favorers', models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество лайков листинга')),
                ('_style', models.TextField(default='[]', verbose_name='Стиль')),
                ('file_data', models.TextField(blank=True, max_length=500, null=True, verbose_name='Описание цифровых файлов')),
                ('is_customizable', models.BooleanField(blank=True, default=False, verbose_name='Товар кастомизируем')),
                ('base_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etsy_products', related_query_name='etsy_product', to='base_product.BaseProduct', verbose_name='Базовый листинг')),
                ('category', models.ForeignKey(limit_choices_to={'is_leaf': True}, on_delete=django.db.models.deletion.CASCADE, related_name='etsy_products', related_query_name='etsy_product', to='etsy_category.EtsyCategory', verbose_name='Категория листинга Etsy')),
                ('channel', models.ForeignKey(limit_choices_to={'domain__marketplace__unique_name': 'etsy'}, on_delete=django.db.models.deletion.CASCADE, related_name='etsy_products', related_query_name='etsy_product', to='marketplace.Channel', verbose_name='Пользовательский канал продаж')),
            ],
            options={
                'verbose_name': 'Листинг Etsy',
                'verbose_name_plural': 'Листинги Etsy',
            },
        ),
        migrations.CreateModel(
            name='EtsyProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('is_removed', models.BooleanField(default=False)),
                ('product_id', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='ID продукта')),
                ('offering_id', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='ID оффера')),
                ('sku', models.CharField(max_length=50, verbose_name='SKU')),
                ('price', models.FloatField(verbose_name='Цена (USD)')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Количество')),
                ('is_enabled', models.BooleanField(blank=True, default=False, verbose_name='Товар доступен')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', related_query_name='product', to='etsy_listing.EtsyListing')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EtsyProductProperty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('property_id', models.CharField(blank=True, max_length=30, null=True, verbose_name='ID атрибута')),
                ('property_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Название атрибута')),
                ('scale_id', models.CharField(blank=True, max_length=30, null=True, verbose_name='Scale ID')),
                ('scale_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Scale name')),
                ('value_ids', models.CharField(max_length=500, verbose_name='Список ID значений')),
                ('values', models.CharField(blank=True, max_length=500, null=True, verbose_name='Список значений')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', related_query_name='property', to='etsy_listing.EtsyProduct')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EtsyListingAttribute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('property_id', models.CharField(blank=True, max_length=30, null=True, verbose_name='ID атрибута')),
                ('property_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Название атрибута')),
                ('scale_id', models.CharField(blank=True, max_length=30, null=True, verbose_name='Scale ID')),
                ('scale_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Scale name')),
                ('value_ids', models.CharField(max_length=500, verbose_name='Список ID значений')),
                ('values', models.CharField(blank=True, max_length=500, null=True, verbose_name='Список значений')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', related_query_name='attribute', to='etsy_listing.EtsyListing')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
