
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "2cee26e647d7997934ad5c327afcb90eee417b84",
 "version": "2.4.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
