# Generated by Django 2.2.5 on 2020-01-17 11:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AmazonCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('category_id', models.CharField(max_length=15, verbose_name='ID категории')),
                ('parent_id', models.CharField(max_length=15, verbose_name='ID родительской категории или 0')),
                ('level', models.PositiveSmallIntegerField(verbose_name='Уровень вложенности категории')),
                ('name', models.CharField(max_length=100, verbose_name='Название категории')),
                ('name_path', models.CharField(blank=True, default='', max_length=500, verbose_name='Путь к категории')),
                ('id_path', models.CharField(blank=True, default='', max_length=300, verbose_name='ID пути к категории')),
                ('is_leaf', models.BooleanField(verbose_name='Является листом дерева категорий')),
            ],
            options={
                'verbose_name': 'Категория товара Amazon',
                'verbose_name_plural': 'Категории товара Amazon',
            },
        ),
        migrations.CreateModel(
            name='AmazonCategoryAspect',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AmazonCategoryTree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Дерево категорий для Amazon',
                'verbose_name_plural': 'Деревья категорий для Amazon',
            },
        ),
    ]
