[tool.poetry]
name = "srusp"
version = "0.1.0"
description = "Python package for the SRUSP method"
authors = ["Akio Taniguchi <taniguchi@a.phys.nagoya-u.ac.jp>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.6"
astropy = "^4.0"
numpy = "^1.18.1"
pandas = "^0.25.3"
scikit-learn = "^0.22.1"
scipy = "^1.4.1"
xarray = "^0.14.1"

[tool.poetry.dev-dependencies]
black = "^19.10b0"
decode = "^0.5.5"
defunc = "^2019.7.8"
flake8 = "^3.7.9"
ipython = "^7.11.1"
jupyter = "^1.0.0"
jupyterlab = "^1.2.6"
jupyter-io = "^0.1.1"
matplotlib = "^3.1.2"
pytest = "^5.3.4"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
