[tool.poetry]
name = "extends"
version = "0.3.0"
description = "A simple Python library that adds a decorator which helps extend functionality of classes by new methods without inheriting them"
authors = ["Arthur Hakimov <verybigfolder@yandex.ru>"]
license = "BSD-3-Clause"
readme = "README.md"
repository = "https://github.com/mefolder/extends"

[tool.poetry.dependencies]
python = "^3.5"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
