# coding: utf-8

"""
    Allegro REST API

    https://developer.allegro.pl/about  # noqa: E501

    The version of the OpenAPI document: 2020.01.28
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import allegro_api
from allegro_api.models.offer_event_ended_offer_all_of_publication import OfferEventEndedOfferAllOfPublication  # noqa: E501
from allegro_api.rest import ApiException


class TestOfferEventEndedOfferAllOfPublication(unittest.TestCase):
    """OfferEventEndedOfferAllOfPublication unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOfferEventEndedOfferAllOfPublication(self):
        """Test OfferEventEndedOfferAllOfPublication"""
        # FIXME: construct object with mandatory attributes with example values
        # model = allegro_api.models.offer_event_ended_offer_all_of_publication.OfferEventEndedOfferAllOfPublication()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
