# coding: utf-8

"""
    Allegro REST API

    https://developer.allegro.pl/about  # noqa: E501

    The version of the OpenAPI document: 2020.01.28
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import allegro_api
from allegro_api.models.initialize_refund import InitializeRefund  # noqa: E501
from allegro_api.rest import ApiException


class TestInitializeRefund(unittest.TestCase):
    """InitializeRefund unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInitializeRefund(self):
        """Test InitializeRefund"""
        # FIXME: construct object with mandatory attributes with example values
        # model = allegro_api.models.initialize_refund.InitializeRefund()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
