# coding: utf-8

"""
    Allegro REST API

    https://developer.allegro.pl/about  # noqa: E501

    The version of the OpenAPI document: 2020.01.28
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import allegro_api
from allegro_api.models.constraint_criteria import ConstraintCriteria  # noqa: E501
from allegro_api.rest import ApiException


class TestConstraintCriteria(unittest.TestCase):
    """ConstraintCriteria unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testConstraintCriteria(self):
        """Test ConstraintCriteria"""
        # FIXME: construct object with mandatory attributes with example values
        # model = allegro_api.models.constraint_criteria.ConstraintCriteria()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
