[tool.poetry]
name = "tasklib"
version = "1.3.0"
description = "Python Task Warrior library"
authors = ["Rob Golding-Day <rob@golding-day.com>"]
license = "BSD-3-Clause"

[tool.poetry.dependencies]
# python = "2.6, 2.7, 3.2, 3.3"
six = "1.14.0"
pytz = "2019.3"
tzlocal = "2.0.0"

[tool.poetry.dev-dependencies]
pytest = "^4.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
