[build-system]
requires = ["flit_core >=2,<3"]
build-backend = "flit_core.buildapi"

[tool.flit.metadata]
module = "py2sfn_task_tools"
author = "Jonathan Drake"
author-email = "jdrake@narrativescience.com"
home-page = "https://github.com/NarrativeScience/py2sfn-task-tools"
license = "BSD-3-Clause"
description-file = "README.md"
requires = [
    "backoff>=1.8.0,<2",
    "boto3",
    "sfn-workflow-client",
]
classifiers = [
    "Intended Audience :: Developers",
    "License :: OSI Approved :: BSD License",
    "Programming Language :: Python :: 3",
    "Topic :: Software Development :: Libraries :: Python Modules",
]
requires-python = ">=3.6,<4"
keywords = "py2sfn,aws step functions,workflow"

[tool.flit.sdist]
include = ["LICENSE.md"]
exclude = ["tests/"]
