__version__      = '1.3.0'
__url__          = 'https://github.com/innodatalabs/ilabs.client'
__author__       = 'Mike Kroutikov'
__author_email__ = 'mkroutikov@innodata.com'
__description__  = 'Python client to connect to api.innodatalabs.com'
__keywords__     = 'innodatalabs api rest'