# Generated by Django 2.2.5 on 2020-01-17 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('etsy_category', '0001_initial'),
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='etsycategorytree',
            name='domain',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='marketplace.Domain', verbose_name='Домен маркетплейса'),
        ),
        migrations.AddField(
            model_name='etsycategory',
            name='category_tree',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etsy_product_categories', to='etsy_category.EtsyCategoryTree', verbose_name='Дерево категорий товаров Etsy'),
        ),
        migrations.AddConstraint(
            model_name='etsycategory',
            constraint=models.UniqueConstraint(fields=('category_id', 'category_tree'), name='unique_etsy_category_id_for_tree'),
        ),
    ]
