[build-system]
requires = ["setuptools",
            "wheel",
            "cython",
            "numpy==1.14.1; python_version<'3.7'",
            "numpy==1.15.0; python_version=='3.7'",
            "numpy==1.17.3; python_version=='3.8'",
            "numpy; python_version>'3.8'"]
