
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

from __future__ import absolute_import
import json

version_json = '''
{
 "date": "2020-01-27T20:17:50+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "58f5e95c05fa41df9f471772664839226610d5af",
 "version": "2020.1.27"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
