
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-01-22T11:35:43+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "7c4315d2b6d23348a1f5a37970475b7463644f63",
 "version": "v1.3.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
