

// This file is autogenerated. DO NOT EDIT

#pragma once
#include <robotpy_build.h>

#include <..\..\build\temp.win-amd64-3.8\dlstatic\ctre_wpiapi\include\ctre\phoenix\motorcontrol\WPI_MotorSafetyImplem.h>


#include <rpygen/frc__MotorSafety.hpp>

namespace rpygen {

using namespace ctre::phoenix::motorcontrol;

template <typename CxxBase>
using PyBasectre__phoenix__motorcontrol__WPI_MotorSafetyImplem = 
    Pyfrc__MotorSafety<
        CxxBase
    >
;

template <typename CxxBase>
struct Pyctre__phoenix__motorcontrol__WPI_MotorSafetyImplem : PyBasectre__phoenix__motorcontrol__WPI_MotorSafetyImplem<CxxBase> {
    using PyBasectre__phoenix__motorcontrol__WPI_MotorSafetyImplem<CxxBase>::PyBasectre__phoenix__motorcontrol__WPI_MotorSafetyImplem;



#ifndef RPYGEN_DISABLE_StopMotor_v
    void StopMotor() override {
PYBIND11_OVERLOAD_NAME(void, CxxBase, "stopMotor", StopMotor,);
    }
#endif

#ifndef RPYGEN_DISABLE_KGetDescription_RTwpi__raw_ostream
    void GetDescription(wpi::raw_ostream& desc) const override {
PYBIND11_OVERLOAD_NAME(void, CxxBase, "getDescription", GetDescription,desc);
    }
#endif



};

}; // namespace rpygen