
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-01-23T01:14:36-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "282cc1f6a2502cbde08d1bb1f45c09f8395c1b3b",
 "version": "0.6.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
