version: '{branch}-{build}'
build: off

environment:
  matrix:
  - TOXENV: 'py36,codecov'
  - TOXENV: 'py37,codecov'
  - TOXENV: 'py38,codecov'

install:
- pip install tox

test_script:
- tox
