# Generated by Django 2.2.5 on 2020-01-17 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ebay_location', '0001_initial'),
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebaylocation',
            name='marketplace_user_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ebay_locations', related_query_name='ebay_location', to='marketplace.MarketplaceUserAccount', verbose_name='Пользовательский аккаунт маркетплейса'),
        ),
        migrations.AddConstraint(
            model_name='ebaylocation',
            constraint=models.UniqueConstraint(fields=('marketplace_user_account', 'merchantLocationKey'), name='unique_marketplace_user_account'),
        ),
    ]
