# Generated by Django 2.2.5 on 2020-01-17 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ebay_category', '0001_initial'),
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebaycategorytree',
            name='domain',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='marketplace.Domain', verbose_name='Домен маркетплейса'),
        ),
        migrations.AddField(
            model_name='ebaycategory',
            name='category_tree',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ebay_product_categories', to='ebay_category.EbayCategoryTree', verbose_name='Дерево категорий товаров eBay'),
        ),
        migrations.AddConstraint(
            model_name='ebaycategorytree',
            constraint=models.UniqueConstraint(fields=('domain', 'category_tree_id', 'category_tree_version'), name='unique_ebay_category_tree'),
        ),
        migrations.AddConstraint(
            model_name='ebaycategory',
            constraint=models.UniqueConstraint(fields=('category_id', 'category_tree'), name='unique_ebay_category_id_for_tree'),
        ),
    ]
