# coding: utf-8

"""
    Fiddle Options Platform

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest


class TestOptionContract(unittest.TestCase):
    """OptionContract unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOptionContract(self):
        """Test OptionContract"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.option_contract.OptionContract()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
