[tool.poetry]
name = "huntinghorn"
version = "0.1.2"
description = "Command-Line tool for Hunting Horn users."
authors = ["Jeremiah Boby <mail@jeremiahboby.me>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
docopt = "^0.6.2"
colorama = "^0.4.3"

[tool.poetry.scripts]
horn = "huntinghorn:main"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
