dist: xenial
language: node_js
node_js: 11
install:
 - make js_build
script:
 - python3 -m tests.server &
 - ./runtests.sh
addons:
  apt:
    packages:
      - python3-setuptools
before_deploy:
 - ./set_dev_version.sh
 - cd packages/$PACKAGE
 - "curl -u $BINTRAY_USER:$BINTRAY_KEY https://api.bintray.com/npm/wq/npm/auth/scope/wq > .npmrc"
deploy:
  provider: script
  script: npm publish
  skip_cleanup: true
  on:
    all_branches: true
git:
  depth: false
matrix:
  include:
    - name: "@wq/app"
      env: PACKAGE=app
    - name: "@wq/jquery-mobile"
      env: PACKAGE=jquery-mobile
    - name: "@wq/map"
      env: PACKAGE=map
    - name: "@wq/model"
      env: PACKAGE=model
    - name: "@wq/outbox"
      env: PACKAGE=outbox
    - name: "@wq/router"
      env: PACKAGE=router
    - name: "@wq/store"
      env: PACKAGE=store
    - name: "@wq/template"
      env: PACKAGE=template
    - name: "wq.app PyPI Package"
      language: python
      python: 3.7
      install:
        - pip install --upgrade pip
        - python setup.py bdist_wheel
        - pip install dist/*.whl
      script:
        - cd tests
        - mkdir css && wq init && wq scss --indir scss --outdir css
        - cd commands
        - ./test_commands.sh
      before_deploy:
        - pip install setuptools_scm
        - cd ../..
        - git checkout .
        - python3 -m tests.bintray > dist/bintray.json
      deploy:
        provider: bintray
        file: dist/bintray.json
        skip_cleanup: true
        user: "$BINTRAY_USER"
        key: "$BINTRAY_KEY"
      after_deploy:
        - sleep 20
        - WHEEL=`cd dist && ls *.whl | tail -n 1 && cd ..`
        - "curl -X PUT -H 'Content-Type: application/json' -u $BINTRAY_USER:$BINTRAY_KEY https://api.bintray.com/file_metadata/wq/wq.app/$WHEEL -d '{\"list_in_downloads\": true}'"
    - name: "JavaScript Lint"
      install: npm install
      script: npm run lint
      before_deploy:
      deploy:
    - name: "Python Lint"
      language: python
      python: 3.7
      install: pip install flake8
      script: flake8 build/*.py tests/*.py
      before_deploy:
      deploy:
