group: travis_latest
language: python
cache: pip

matrix:
  include:
    - python: '3.8'
      dist: xenial
      env: COVERAGE=--cov
    - python: '3.7'
    - python: '3.6'
    - python: '3.5'
    - python: '3.4'
    - python: 'pypy3'
    - python: '2.7'
      env: COVERAGE=--cov
    - python: 'pypy'
  allow_failures:
    - python: 'nightly'

install:
  - pip install --upgrade -r requirements.txt
  - if [ -n "$COVERAGE" ]; then pip install coveralls; fi
  - pip install -e .

script:
  - py.test --flake8 $COVERAGE

after_success:
  - if [ -n "$COVERAGE" ]; then coveralls; fi
