[tool.poetry]
name = "servicectl"
version = "0.0.0"
description = "Docker stack deployment manager"
authors = ["Pavle Portic <pavle.portic@tilda.center>"]

repository = "https://github.com/TheEdgeOfRage/servicectl"
license = "BSD-3-Clause"
readme = "README.rst"
keywords = ["docker", "service", "deployment"]

[tool.poetry.dependencies]
python = "^3.6"
docker = "^4.1.0"

[tool.dephell.main]
from = {format = "poetry", path = "pyproject.toml"}
to = {format = "setuppy", path = "setup.py"}

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
