# Generated by Django 2.2.5 on 2020-01-23 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etsy_policy', '0005_auto_20200123_1201'),
        ('etsy', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EtsyCountry',
        ),
        migrations.DeleteModel(
            name='EtsyRegion',
        ),
    ]
