# Generated by Django 2.2.5 on 2020-01-23 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etsy', '0003_etsycountry_etsyregion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etsycountry',
            name='country_id',
            field=models.PositiveSmallIntegerField(primary_key=True, serialize=False, verbose_name='ID страны'),
        ),
        migrations.AlterField(
            model_name='etsyregion',
            name='region_id',
            field=models.PositiveSmallIntegerField(primary_key=True, serialize=False, verbose_name='ID региона'),
        ),
    ]
