[tool.poetry]
name = "django-athm"
version = "0.3.0"
description = "Django + ATH Móvil"
authors = ["Raúl Negrón <raul.esteban.negron@gmail.com>"]
maintainers = ["Raúl Negrón <raul.esteban.negron@gmail.com>"]
license = "MIT"
readme = "README.md"
homepage = ""
repository = "https://github.com/django-athm/django-athm"
documentation = "https://django-athm.github.io/django-athm/"
keywords = ["Django",
            "ATH Móvil",
            "Payments",
            "athm"]

[tool.poetry.dependencies]
python = "^3.7"
django = "<3"
httpx = "^0.11.1"

[tool.poetry.dev-dependencies]
black = "^19.10b0"
isort = "^4.3.21"
flake8 = "^3.7.9"
pre-commit = "^1.21.0"
pytest-django = "^3.8.0"
tox = "^3.14.3"
codecov = "^2.0.15"
django-debug-toolbar = "^2.1"
pytest-cov = "^2.8.1"
mkdocs = "1.0.4"


[tool.poetry.urls]
issues = "https://github.com/django-athm/django-athm/issues"

[tool.tox]
legacy_tox_ini = """
[tox]
envlist =
    py{36,37,38}-django{111,22,30}

[travis]
python =
    3.6: py36
    3.7: py37
    3.8: py38

[travis:env]
DJANGO =
    1.11: django111
    2.2: django22
    3.0: django30

[testenv]
passenv = DJANGO_ATHM_*
setenv =
    PYTHONWARNINGS = all
    PYTEST_ADDOPTS = --cov --cov-report=html  --cov-report=term
commands = pytest {posargs}
deps =
    django111: django>=1.11,<2.0
    django22: Django>=2.2,<2.3
    django30: Django>=3.0,<3.1
    pytest-django
    pytest-cov

[pytest]
DJANGO_SETTINGS_MODULE = tests.settings
"""

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

