image: Visual Studio 2019
cache:
  - .env
  - &omwcmd-ver c:\python38\Scripts\omwcmd-0.2.0.exe
  - &omwcmd c:\python38\Scripts\omwcmd.exe
environment:
  PATH: '%PATH%;c:\python38\Scripts'
  OMWCMD_VER: *omwcmd-ver
  OMWCMD: *omwcmd
build_script:
- ps: >-
    pip3 install virtualenv

    virtualenv .venv

    .venv\Scripts\activate

    pip3 install .

    if (!(Test-Path $env:OMWCMD_VER)) {

        iwr https://gitlab.com/portmod/omwcmd/uploads/7c4ee7879b2e129152021c43c9fae16d/omwcmd.exe -OutFile $env:OMWCMD_VER

        Copy-Item -Path $env:OMWCMD_VER -Destination $env:OMWCMD

    }

test_script:
- cmd: >-
    pip3 install pytest pytest-cov

    pytest --cov=portmod || exit /b 0
