# Generated by Django 2.2.5 on 2020-01-17 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ebay_location', '0001_initial'),
        ('ebay_policy', '0001_initial'),
        ('ebay_listing', '0001_initial'),
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebaylisting',
            name='channel',
            field=models.ForeignKey(limit_choices_to={'domain__marketplace__unique_name': 'ebay'}, on_delete=django.db.models.deletion.CASCADE, related_name='ebay_products', related_query_name='ebay_product', to='marketplace.Channel', verbose_name='Пользовательский канал продаж'),
        ),
        migrations.AddField(
            model_name='ebaylisting',
            name='fulfillmentPolicy',
            field=models.ForeignKey(limit_choices_to={'channel__domain__marketplace__unique_name': 'ebay'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', related_query_name='product', to='ebay_policy.FulfillmentPolicy', verbose_name='ID политики фулфилмента'),
        ),
        migrations.AddField(
            model_name='ebaylisting',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ebay_location.EbayLocation', verbose_name='Идентификатор склада для eBay'),
        ),
        migrations.AddField(
            model_name='ebaylisting',
            name='paymentPolicy',
            field=models.ForeignKey(limit_choices_to={'channel__domain__marketplace__unique_name': 'ebay'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', related_query_name='product', to='ebay_policy.PaymentPolicy', verbose_name='ID политики оплаты'),
        ),
        migrations.AddField(
            model_name='ebaylisting',
            name='returnPolicy',
            field=models.ForeignKey(limit_choices_to={'channel__domain__marketplace__unique_name': 'ebay'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', related_query_name='product', to='ebay_policy.ReturnPolicy', verbose_name='ID политики возврата'),
        ),
        migrations.AddConstraint(
            model_name='ebaylistingaspect',
            constraint=models.UniqueConstraint(fields=('listing', 'name', 'value'), name='unique_listing_aspect_name_and_value'),
        ),
    ]
