[tool.poetry]
name = "dbx-deploy"
version = "0.7.0"
description = "Databrics Deployment Tool"
readme = "README.md"
repository = "https://github.com/DataSentics/dbx-deploy"

license = "MIT"

authors = [
    "Jiri Koutny <jiri.koutny@datasentics.com>"
]

classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

include = ["*.yaml", "*.tpl"]

packages = [
    { include = "dbxdeploy", from = "src" },
]

[tool.poetry.dependencies]
colorlog = "4.0.*"
databricks-api = "0.3.*"
dbx-notebook-exporter = "0.2.*"
injecta = "0.5.*"
nbconvert = "5.6.*"
pygit2 = "0.28.*"
python = "~3.7.3"
python-box = "3.4.*"
PyYAML = "5.1.*"
tomlkit = "0.5.*"
console-bundle = "0.1*"

[tool.poetry.dev-dependencies]
pylint = "2.4.*"
pytest = "5.2.*"
