[tool.poetry]
name = "tabler"
version = "2.4.0"
description = "Simple interface for tabulated data and .csv files"
authors = ["Luke Shiner <luke@lukeshiner.com>"]
license = "MIT"
readme = "README.rst"
homepage = "https://github.com/lukeshiner/tabler"
repository = "https://github.com/lukeshiner/tabler"
documentation = "https://tabler.readthedocs.io/en/latest/"
keywords = ["table", "csv", "simple"]

classifiers = [
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Development Status :: 4 - Beta",
    "Natural Language :: English",
    "Topic :: Utilities",
    "Topic :: Other/Nonlisted Topic",
]

[tool.poetry.dependencies]
python = "^3.6"
requests = "^2.22.0"
openpyxl = "^3.0.3"
jinja2 = "^2.11.0"
pyexcel-ods = "^0.5.6"
urllib3 = "^1.25.8"

[tool.poetry.dev-dependencies]
pytest = "^5.3.4"
pytest-cov = "^2.8.1"
flake8 = "^3.7.9"
pydocstyle = "^5.0.2"
black = {version = "^19.10b0", allow-prereleases = true}
sphinx = "^2.3.1"
sphinx-rtd-theme = "^0.4.3"
tox = "^3.14.3"
changelog-cli = "^0.6.2"
bump2version = "^1.0.0"
coveralls = "^1.10.0"
requests-mock = "^1.7.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.coverage.run]
branch = true
omit = ["tests/*"]