# Generated by Django 2.2.5 on 2020-01-17 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ebay_policy', '0001_initial'),
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnpolicy',
            name='channel',
            field=models.ForeignKey(limit_choices_to={'domain__marketplace__unique_name': 'ebay'}, on_delete=django.db.models.deletion.CASCADE, related_name='return_policies', related_query_name='return_policy', to='marketplace.Channel', verbose_name='Аккаунт пользователя eBay'),
        ),
        migrations.AddField(
            model_name='paymentpolicycategorytype',
            name='payment_policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categoryTypes', to='ebay_policy.PaymentPolicy', verbose_name='Payment policy'),
        ),
        migrations.AddField(
            model_name='paymentpolicy',
            name='channel',
            field=models.ForeignKey(limit_choices_to={'domain__marketplace__unique_name': 'ebay'}, on_delete=django.db.models.deletion.CASCADE, related_name='payment_policies', related_query_name='payment_policy', to='marketplace.Channel', verbose_name='Channel'),
        ),
        migrations.AddField(
            model_name='packagehandlingcost',
            name='shipping_option',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='packageHandlingCost', to='ebay_policy.ShippingOption'),
        ),
        migrations.AddField(
            model_name='internationaloverridereturnperiod',
            name='international_override',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='returnPeriod', to='ebay_policy.InternationalOverride', verbose_name='International return override type'),
        ),
        migrations.AddField(
            model_name='internationaloverride',
            name='return_policy',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='internationalOverride', to='ebay_policy.ReturnPolicy', verbose_name='Return policy'),
        ),
        migrations.AddField(
            model_name='insurancefee',
            name='shipping_option',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='insuranceFee', to='ebay_policy.ShippingOption'),
        ),
        migrations.AddField(
            model_name='handlingtime',
            name='fulfillment_policy',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='handlingTime', to='ebay_policy.FulfillmentPolicy'),
        ),
        migrations.AddField(
            model_name='fullpaymentduein',
            name='payment_policy',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fullPaymentDueIn', to='ebay_policy.PaymentPolicy', verbose_name='Payment policy'),
        ),
        migrations.AddField(
            model_name='fulfillmentpolicyshiptolocations',
            name='fulfillment_policy',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shipToLocations', to='ebay_policy.FulfillmentPolicy', verbose_name='Fulfillment policy'),
        ),
        migrations.AddField(
            model_name='fulfillmentpolicyregionincluded',
            name='ship_to_locations',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regionIncluded', to='ebay_policy.FulfillmentPolicyShipToLocations'),
        ),
        migrations.AddField(
            model_name='fulfillmentpolicyregionexcluded',
            name='ship_to_locations',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regionExcluded', to='ebay_policy.FulfillmentPolicyShipToLocations'),
        ),
        migrations.AddField(
            model_name='fulfillmentpolicycategorytype',
            name='fulfillment_policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categoryTypes', to='ebay_policy.FulfillmentPolicy'),
        ),
        migrations.AddField(
            model_name='fulfillmentpolicy',
            name='channel',
            field=models.ForeignKey(limit_choices_to={'domain__marketplace__unique_name': 'ebay'}, on_delete=django.db.models.deletion.CASCADE, related_name='fulfillment_policies', related_query_name='fulfillment_policy', to='marketplace.Channel', verbose_name='Аккаунт пользователя eBay'),
        ),
        migrations.AddField(
            model_name='depositduein',
            name='deposit',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dueIn', to='ebay_policy.Deposit', verbose_name='Deposit'),
        ),
        migrations.AddField(
            model_name='depositamount',
            name='deposit',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='amount', to='ebay_policy.Deposit', verbose_name='Deposit'),
        ),
        migrations.AddField(
            model_name='deposit',
            name='payment_policy',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deposit', to='ebay_policy.PaymentPolicy', verbose_name='Payment policy'),
        ),
        migrations.AddField(
            model_name='cashondeliveryfee',
            name='shipping_service',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cashOnDeliveryFee', to='ebay_policy.ShippingService'),
        ),
        migrations.AddField(
            model_name='additionalshippingcost',
            name='shipping_service',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='additionalShippingCost', to='ebay_policy.ShippingService'),
        ),
        migrations.AddField(
            model_name='recipientaccountreference',
            name='payment_method',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recipientAccountReference', to='ebay_policy.PaymentMethod'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='payment_policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paymentMethods', to='ebay_policy.PaymentPolicy', verbose_name='Payment policy'),
        ),
        migrations.AddField(
            model_name='depositrecipientaccountreference',
            name='deposit_payment_method',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recipientAccountReference', to='ebay_policy.DepositPaymentMethod', verbose_name='Deposit payment method'),
        ),
        migrations.AddField(
            model_name='depositpaymentmethod',
            name='deposit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paymentMethods', to='ebay_policy.Deposit', verbose_name='Deposit'),
        ),
    ]
