[tool.poetry]
name = "predatools"
version = "0.1.1"
description = ""
authors = ["Kawin Liaowongphuthorn <liaokangtai@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
s3fs = "^0.4.0"
fastavro = "^0.22.9"
boto3 = "^1.11.9"
pandas = "^1.0.0"
pyarrow = "^0.15.1"
tqdm = "^4.42.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
