
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-01-31T11:54:22-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "5aed07ee5a2f7a0ae6f3e51f9a989ddb387f8871",
 "version": "v0.1.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
