# Generated by Django 2.2.5 on 2020-01-28 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EtsyCountry',
            fields=[
                ('country_id', models.PositiveSmallIntegerField(primary_key=True, serialize=False, verbose_name='ID страны')),
                ('iso_country_code', models.CharField(max_length=2, verbose_name='Код страны (ISO)')),
                ('world_bank_country_code', models.CharField(blank=True, max_length=3, null=True, verbose_name='Код страны (мировой банк)')),
                ('name', models.CharField(max_length=50, verbose_name='Название страны')),
                ('slug', models.CharField(blank=True, max_length=50, null=True, verbose_name='Slug страны')),
                ('lat', models.FloatField(blank=True, null=True, verbose_name='Широта')),
                ('lon', models.FloatField(blank=True, null=True, verbose_name='Долгота')),
            ],
            options={
                'verbose_name': 'Страна',
                'verbose_name_plural': 'Страны',
            },
        ),
        migrations.CreateModel(
            name='EtsyRegion',
            fields=[
                ('region_id', models.PositiveSmallIntegerField(primary_key=True, serialize=False, verbose_name='ID региона')),
                ('region_name', models.CharField(max_length=50, verbose_name='Название страны')),
            ],
        ),
    ]
