name: hashit
version: 3.5.3
summary: hashit is an replacement for (md5sum, sha1sum, and so on)
icon: img/icon.png
description: |
  Hashit, is an hashing application used as an verification tool, intendet to replace the "standard" linux hashing utilities such as
  md5sum, sha1sum and so on. One of the main reasons why this program was develop was to create an easy-to-use command line tool for 
  newcomers and professionals alike to hash/verify files and other data. For more see our homepage at https://cjavad.github.io/hashit 


grade: stable
confinement: strict

apps:
  hashit:
    command: bin/hashit
    plugs: [home, removable-media]

parts:
  hashit:
    plugin: python
    python-version: python3
    source: .
