# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-10 18:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playcricketlink', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pc_club_link', to='core.Club'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pc_competition_link', to='core.Competition'),
        ),
        migrations.AlterField(
            model_name='ground',
            name='ground',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pc_ground_link', to='core.Ground'),
        ),
        migrations.AlterField(
            model_name='league',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pc_league_link', to='core.Competition'),
        ),
        migrations.AlterField(
            model_name='match',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pc_match_link', to='core.Match'),
        ),
        migrations.AlterField(
            model_name='player',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pc_player_link', to='core.Player'),
        ),
        migrations.AlterField(
            model_name='scorer',
            name='scorer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pc_scorer_link', to='core.Scorer'),
        ),
        migrations.AlterField(
            model_name='team',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pc_team_link', to='core.Team'),
        ),
        migrations.AlterField(
            model_name='umpire',
            name='umpire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pc_umpire_link', to='core.Umpire'),
        ),
    ]
