# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-27 17:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playcricketlink', '0002_auto_20190110_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pc_league_link', to='core.League'),
        ),
    ]
