# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-27 17:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playcricketlink', '0003_auto_20190127_1747'),
    ]

    operations = [
        migrations.RenameField(
            model_name='club',
            old_name='club',
            new_name='link',
        ),
        migrations.RenameField(
            model_name='competition',
            old_name='competition',
            new_name='link',
        ),
        migrations.RenameField(
            model_name='ground',
            old_name='ground',
            new_name='link',
        ),
        migrations.RenameField(
            model_name='league',
            old_name='league',
            new_name='link',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='match',
            new_name='link',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='player',
            new_name='link',
        ),
        migrations.RenameField(
            model_name='scorer',
            old_name='scorer',
            new_name='link',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='team',
            new_name='link',
        ),
        migrations.RenameField(
            model_name='umpire',
            old_name='umpire',
            new_name='link',
        ),
    ]
