# Generated by Django 2.2.5 on 2020-01-23 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('etsy_policy', '0003_remove_etsyshippingtemplateentry_origin_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etsyshippingtemplate',
            name='marketplace_user_account',
            field=models.ForeignKey(limit_choices_to={'marketplace__unique_name': 'etsy'}, on_delete=django.db.models.deletion.CASCADE, related_name='shipping_templates', related_query_name='shipping_template', to='marketplace.MarketplaceUserAccount'),
        ),
    ]
