# Generated by Django 2.2.5 on 2020-01-23 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etsy_policy', '0007_auto_20200123_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='etsyshippingtemplateentry',
            name='is_removed',
            field=models.BooleanField(default=False),
        ),
    ]
