# Generated by Django 2.2.5 on 2020-01-24 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etsy_policy', '0008_etsyshippingtemplateentry_is_removed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etsyshippingtemplate',
            name='shipping_template_id',
            field=models.IntegerField(blank=True, max_length=30, null=True, unique=True, verbose_name='ID политики доставки'),
        ),
        migrations.AlterField(
            model_name='etsyshippingtemplateentry',
            name='shipping_template_entry_id',
            field=models.IntegerField(blank=True, max_length=30, null=True, verbose_name='ID записи политики доставки'),
        ),
    ]
