# Generated by Django 2.2.5 on 2020-01-17 11:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AbstractContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя')),
                ('lastName', models.CharField(blank=True, max_length=255, null=True, verbose_name='Фамилия')),
            ],
        ),
        migrations.CreateModel(
            name='AbstractPhone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countryCode', models.CharField(blank=True, choices=[('AD', 'Andorra'), ('AE', 'United Arab Emirates'), ('AF', 'Afghanistan'), ('AG', 'Antigua and Barbuda'), ('AI', 'Anguilla'), ('AL', 'Albania'), ('AM', 'Armenia'), ('AN', 'Netherlands Antilles'), ('AO', 'Angola'), ('AQ', 'Antarctica'), ('AR', 'Argentina'), ('AS', 'American Samoa'), ('AT', 'Austria'), ('AU', 'Australia'), ('AW', 'Aruba'), ('AX', 'Aland Islands'), ('AZ', 'Azerbaijan'), ('BA', 'Bosnia and Herzegovina'), ('BB', 'Barbados'), ('BD', 'Bangladesh'), ('BE', 'Belgium'), ('BF', 'Burkina Faso'), ('BG', 'Bulgaria'), ('BH', 'Bahrain'), ('BI', 'Burundi'), ('BJ', 'Benin'), ('BL', 'Saint Barthelemy'), ('BM', 'Bermuda'), ('BN', 'Brunei Darussalam'), ('BO', 'Bolivia'), ('BQ', 'Bonaire, Sint Eustatius, and Saba'), ('BR', 'Brazil'), ('BS', 'Bahamas'), ('BT', 'Bhutan'), ('BV', 'Bouvet Island'), ('BW', 'Botswana'), ('BY', 'Belarus'), ('BZ', 'Belize'), ('CA', 'Canada'), ('CC', 'Cocos (Keeling) Islands'), ('CD', 'The Democratic Republic of the Congo'), ('CF', 'Central African Republic'), ('CG', 'Congo'), ('CH', 'Switzerland'), ('CI', "Cote d'Ivoire"), ('CK', 'Cook Islands'), ('CL', 'Chile'), ('CM', 'Cameroon'), ('CN', 'China'), ('CO', 'Colombia'), ('CR', 'Costa Rica'), ('CU', 'Cuba'), ('CV', 'Cape Verde'), ('CW', 'Curacao'), ('CX', 'Christmas Island'), ('CY', 'Cyprus'), ('CZ', 'Czech Republic'), ('DE', 'Germany'), ('DJ', 'Djibouti'), ('DK', 'Denmark'), ('DM', 'Dominica'), ('DO', 'Dominican Republic'), ('DZ', 'Algeria'), ('EC', 'Ecuador'), ('EE', 'Estonia'), ('EG', 'Egypt'), ('EH', 'Western Sahara'), ('ER', 'Eritrea'), ('ES', 'Spain'), ('ET', 'Ethiopia'), ('FI', 'Finland'), ('FJ', 'Fiji'), ('FK', 'Falkland Islands (Malvinas)'), ('FM', 'Federated States of Micronesia'), ('FO', 'Faroe Islands'), ('FR', 'France'), ('GA', 'Gabon'), ('GB', 'United Kingdom'), ('GD', 'Grenada'), ('GE', 'Georgia'), ('GF', 'French Guiana'), ('GG', 'Guernsey'), ('GH', 'Ghana'), ('GI', 'Gibraltar'), ('GL', 'Greenland'), ('GM', 'Gambia'), ('GN', 'Guinea'), ('GP', 'Guadeloupe'), ('GQ', 'Equatorial Guinea'), ('GR', 'Greece'), ('GS', 'South Georgia and the South Sandwich Islands'), ('GT', 'Guatemala'), ('GU', 'Guam'), ('GW', 'Guinea-Bissau'), ('GY', 'Guyana'), ('HK', 'Hong Kong'), ('HM', 'Heard Island and McDonald Islands'), ('HN', 'Honduras'), ('HR', 'Croatia'), ('HT', 'Haiti'), ('HU', 'Hungary'), ('ID', 'Indonesia'), ('IE', 'Ireland'), ('IL', 'Israel'), ('IM', 'Isle of Man'), ('IN', 'India'), ('IO', 'British Indian Ocean Territory'), ('IQ', 'Iraq'), ('IR', 'Islamic Republic of Iran'), ('IS', 'Iceland'), ('IT', 'Italy'), ('JE', 'Jersey'), ('JM', 'Jamaica'), ('JO', 'Jordan'), ('JP', 'Japan'), ('KE', 'Kenya'), ('KG', 'Kyrgyzstan'), ('KH', 'Cambodia'), ('KI', 'Kiribati'), ('KM', 'Comoros'), ('KN', 'Saint Kitts and Nevis'), ('KP', "Democratic People's Republic of Korea"), ('KR', 'Republic of Korea'), ('KW', 'Kuwait'), ('KY', 'Cayman Islands'), ('KZ', 'Kazakhstan'), ('LA', "Lao People's Democratic Republic"), ('LB', 'Lebanon'), ('LC', 'Saint Lucia'), ('LI', 'Liechtenstein'), ('LK', 'Sri Lanka'), ('LR', 'Liberia'), ('LS', 'Lesotho'), ('LT', 'Lithuania'), ('LU', 'Luxembourg'), ('LV', 'atvia'), ('LY', 'Libyan Arab Jamahiriya'), ('MA', 'Morocco'), ('MC', 'Monaco'), ('MD', 'Republic of Moldova'), ('ME', 'Montenegro'), ('MF', 'Saint Martin (French part)'), ('MG', 'Madagascar'), ('MH', 'Marshall Islands'), ('MK', 'The Former Yugoslav Republic of Macedonia'), ('ML', 'Mali'), ('MM', 'Myanmar'), ('MN', 'Mongolia'), ('MO', 'Macao'), ('MP', 'Northern Mariana Islands'), ('MQ', 'Martinique'), ('MR', 'Mauritania'), ('MS', 'Montserrat'), ('MT', 'Malta'), ('MU', 'Mauritius'), ('MV', 'Maldives'), ('MW', 'Malawi'), ('MX', 'Mexico'), ('MY', 'Malaysia'), ('MZ', 'Mozambique'), ('NA', 'Namibia'), ('NC', 'New Caledonia'), ('NE', 'Niger'), ('NF', 'Norfolk Island'), ('NG', 'Nigeria'), ('NI', 'Nicaragua'), ('NL', 'Netherlands'), ('NO', 'Norway'), ('NP', 'Nepal'), ('NR', 'Nauru'), ('NU', 'Niue'), ('NZ', 'New Zealand'), ('OM', 'Oman'), ('PA', 'Panama'), ('PE', 'Peru'), ('PF', 'French Polynesia, Includes Tahiti'), ('PG', 'Papua New Guinea'), ('PH', 'Philippines'), ('PK', 'Pakistan'), ('PL', 'Poland'), ('PM', 'Saint Pierre and Miquelon'), ('PN', 'Pitcairn'), ('PR', 'Puerto Rico'), ('PS', 'Palestinian territory Occupied'), ('PT', 'Portugal'), ('PW', 'Palau'), ('PY', 'Paraguay'), ('QA', 'Qatar'), ('RE', 'Reunion'), ('RO', 'Romania'), ('RS', 'Serbia'), ('RU', 'Russian Federation'), ('RW', 'Rwanda'), ('SA', 'Saudi Arabia'), ('SB', 'Solomon Islands'), ('SC', 'Seychelles'), ('SD', 'Sudan'), ('SE', 'Sweden'), ('SG', 'Singapore'), ('SH', 'Saint Helena'), ('SI', 'Slovenia'), ('SJ', 'Svalbard and Jan Mayen'), ('SK', 'Slovakia'), ('SL', 'Sierra Leone'), ('SM', 'San Marino'), ('SN', 'Senegal'), ('SO', 'Somalia'), ('SR', 'Suriname'), ('ST', 'Sao Tome and Principe'), ('SV', 'El Salvador'), ('SX', 'Sint Maarten (Dutch part)'), ('SY', 'Syrian Arab Republic'), ('SZ', 'Swaziland'), ('TC', 'Turks and Caicos Islands'), ('TD', 'Chad'), ('TF', 'French Southern Territories'), ('TG', 'Togo'), ('TH', 'Thailand'), ('TJ', 'Tajikistan'), ('TK', 'Tokelau'), ('TL', 'Timor-Leste'), ('TM', 'Turkmenistan'), ('TN', 'Tunisia'), ('TO', 'Tonga'), ('TR', 'Turkey'), ('TT', 'Trinidad and Tobago'), ('TV', 'Tuvalu'), ('TW', 'Taiwan'), ('TZ', 'Tanzania'), ('UA', 'Ukraine'), ('UG', 'Uganda'), ('UM', 'United States Minor Outlying Islands'), ('US', 'United States'), ('UY', 'Uruguay'), ('UZ', 'Uzbekistan'), ('VA', 'Holy See (Vatican City state)'), ('VC', 'Saint Vincent and the Grenadines'), ('VE', 'Venezuela'), ('VG', 'British Virgin Islands'), ('VI', 'The US Virgin Islands'), ('VN', 'Vietnam'), ('VU', 'Vanuatu'), ('WF', 'Wallis and Futuna'), ('WS', 'Samoa'), ('YE', 'Yemen'), ('YT', 'Mayotte'), ('ZA', 'South Africa'), ('ZM', 'Zambia'), ('ZW', 'Zimbabwe')], max_length=2, null=True, verbose_name='Страна')),
                ('number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефона')),
                ('phoneType', models.CharField(blank=True, choices=[('MOBILE', 'Мобильный'), ('LAND_LINE', 'Стационарный')], max_length=10, null=True, verbose_name='Тип телефона')),
            ],
        ),
        migrations.CreateModel(
            name='BusinessAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doingBusinessAs', models.CharField(blank=True, max_length=255, null=True, verbose_name='Дополнительное имя, используемое для названия бизнесс аккаунта в системе eBay')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя, используемое для названия бизнесс аккаунта в системе eBay')),
                ('website', models.CharField(blank=True, max_length=255, null=True, verbose_name='Веб-сайт')),
            ],
            options={
                'verbose_name': 'Информация о бизнесс аккаунте',
                'verbose_name_plural': 'Информация о бизнесс аккаунтах',
            },
        ),
        migrations.CreateModel(
            name='BusinessAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addressLine1', models.CharField(blank=True, max_length=128, null=True, verbose_name='Первая строка адреса')),
                ('addressLine2', models.CharField(blank=True, max_length=128, null=True, verbose_name='Вторая строка адреса')),
                ('city', models.CharField(blank=True, max_length=128, null=True, verbose_name='Населённый пункт')),
                ('county', models.CharField(blank=True, max_length=50, null=True, verbose_name='Округ')),
                ('postalCode', models.CharField(blank=True, max_length=16, null=True, verbose_name='Почтовый индекс')),
                ('stateOrProvince', models.CharField(blank=True, max_length=128, null=True, verbose_name='Штат или провинция')),
                ('countryCode', models.CharField(blank=True, choices=[('AD', 'Andorra'), ('AE', 'United Arab Emirates'), ('AF', 'Afghanistan'), ('AG', 'Antigua and Barbuda'), ('AI', 'Anguilla'), ('AL', 'Albania'), ('AM', 'Armenia'), ('AN', 'Netherlands Antilles'), ('AO', 'Angola'), ('AQ', 'Antarctica'), ('AR', 'Argentina'), ('AS', 'American Samoa'), ('AT', 'Austria'), ('AU', 'Australia'), ('AW', 'Aruba'), ('AX', 'Aland Islands'), ('AZ', 'Azerbaijan'), ('BA', 'Bosnia and Herzegovina'), ('BB', 'Barbados'), ('BD', 'Bangladesh'), ('BE', 'Belgium'), ('BF', 'Burkina Faso'), ('BG', 'Bulgaria'), ('BH', 'Bahrain'), ('BI', 'Burundi'), ('BJ', 'Benin'), ('BL', 'Saint Barthelemy'), ('BM', 'Bermuda'), ('BN', 'Brunei Darussalam'), ('BO', 'Bolivia'), ('BQ', 'Bonaire, Sint Eustatius, and Saba'), ('BR', 'Brazil'), ('BS', 'Bahamas'), ('BT', 'Bhutan'), ('BV', 'Bouvet Island'), ('BW', 'Botswana'), ('BY', 'Belarus'), ('BZ', 'Belize'), ('CA', 'Canada'), ('CC', 'Cocos (Keeling) Islands'), ('CD', 'The Democratic Republic of the Congo'), ('CF', 'Central African Republic'), ('CG', 'Congo'), ('CH', 'Switzerland'), ('CI', "Cote d'Ivoire"), ('CK', 'Cook Islands'), ('CL', 'Chile'), ('CM', 'Cameroon'), ('CN', 'China'), ('CO', 'Colombia'), ('CR', 'Costa Rica'), ('CU', 'Cuba'), ('CV', 'Cape Verde'), ('CW', 'Curacao'), ('CX', 'Christmas Island'), ('CY', 'Cyprus'), ('CZ', 'Czech Republic'), ('DE', 'Germany'), ('DJ', 'Djibouti'), ('DK', 'Denmark'), ('DM', 'Dominica'), ('DO', 'Dominican Republic'), ('DZ', 'Algeria'), ('EC', 'Ecuador'), ('EE', 'Estonia'), ('EG', 'Egypt'), ('EH', 'Western Sahara'), ('ER', 'Eritrea'), ('ES', 'Spain'), ('ET', 'Ethiopia'), ('FI', 'Finland'), ('FJ', 'Fiji'), ('FK', 'Falkland Islands (Malvinas)'), ('FM', 'Federated States of Micronesia'), ('FO', 'Faroe Islands'), ('FR', 'France'), ('GA', 'Gabon'), ('GB', 'United Kingdom'), ('GD', 'Grenada'), ('GE', 'Georgia'), ('GF', 'French Guiana'), ('GG', 'Guernsey'), ('GH', 'Ghana'), ('GI', 'Gibraltar'), ('GL', 'Greenland'), ('GM', 'Gambia'), ('GN', 'Guinea'), ('GP', 'Guadeloupe'), ('GQ', 'Equatorial Guinea'), ('GR', 'Greece'), ('GS', 'South Georgia and the South Sandwich Islands'), ('GT', 'Guatemala'), ('GU', 'Guam'), ('GW', 'Guinea-Bissau'), ('GY', 'Guyana'), ('HK', 'Hong Kong'), ('HM', 'Heard Island and McDonald Islands'), ('HN', 'Honduras'), ('HR', 'Croatia'), ('HT', 'Haiti'), ('HU', 'Hungary'), ('ID', 'Indonesia'), ('IE', 'Ireland'), ('IL', 'Israel'), ('IM', 'Isle of Man'), ('IN', 'India'), ('IO', 'British Indian Ocean Territory'), ('IQ', 'Iraq'), ('IR', 'Islamic Republic of Iran'), ('IS', 'Iceland'), ('IT', 'Italy'), ('JE', 'Jersey'), ('JM', 'Jamaica'), ('JO', 'Jordan'), ('JP', 'Japan'), ('KE', 'Kenya'), ('KG', 'Kyrgyzstan'), ('KH', 'Cambodia'), ('KI', 'Kiribati'), ('KM', 'Comoros'), ('KN', 'Saint Kitts and Nevis'), ('KP', "Democratic People's Republic of Korea"), ('KR', 'Republic of Korea'), ('KW', 'Kuwait'), ('KY', 'Cayman Islands'), ('KZ', 'Kazakhstan'), ('LA', "Lao People's Democratic Republic"), ('LB', 'Lebanon'), ('LC', 'Saint Lucia'), ('LI', 'Liechtenstein'), ('LK', 'Sri Lanka'), ('LR', 'Liberia'), ('LS', 'Lesotho'), ('LT', 'Lithuania'), ('LU', 'Luxembourg'), ('LV', 'atvia'), ('LY', 'Libyan Arab Jamahiriya'), ('MA', 'Morocco'), ('MC', 'Monaco'), ('MD', 'Republic of Moldova'), ('ME', 'Montenegro'), ('MF', 'Saint Martin (French part)'), ('MG', 'Madagascar'), ('MH', 'Marshall Islands'), ('MK', 'The Former Yugoslav Republic of Macedonia'), ('ML', 'Mali'), ('MM', 'Myanmar'), ('MN', 'Mongolia'), ('MO', 'Macao'), ('MP', 'Northern Mariana Islands'), ('MQ', 'Martinique'), ('MR', 'Mauritania'), ('MS', 'Montserrat'), ('MT', 'Malta'), ('MU', 'Mauritius'), ('MV', 'Maldives'), ('MW', 'Malawi'), ('MX', 'Mexico'), ('MY', 'Malaysia'), ('MZ', 'Mozambique'), ('NA', 'Namibia'), ('NC', 'New Caledonia'), ('NE', 'Niger'), ('NF', 'Norfolk Island'), ('NG', 'Nigeria'), ('NI', 'Nicaragua'), ('NL', 'Netherlands'), ('NO', 'Norway'), ('NP', 'Nepal'), ('NR', 'Nauru'), ('NU', 'Niue'), ('NZ', 'New Zealand'), ('OM', 'Oman'), ('PA', 'Panama'), ('PE', 'Peru'), ('PF', 'French Polynesia, Includes Tahiti'), ('PG', 'Papua New Guinea'), ('PH', 'Philippines'), ('PK', 'Pakistan'), ('PL', 'Poland'), ('PM', 'Saint Pierre and Miquelon'), ('PN', 'Pitcairn'), ('PR', 'Puerto Rico'), ('PS', 'Palestinian territory Occupied'), ('PT', 'Portugal'), ('PW', 'Palau'), ('PY', 'Paraguay'), ('QA', 'Qatar'), ('RE', 'Reunion'), ('RO', 'Romania'), ('RS', 'Serbia'), ('RU', 'Russian Federation'), ('RW', 'Rwanda'), ('SA', 'Saudi Arabia'), ('SB', 'Solomon Islands'), ('SC', 'Seychelles'), ('SD', 'Sudan'), ('SE', 'Sweden'), ('SG', 'Singapore'), ('SH', 'Saint Helena'), ('SI', 'Slovenia'), ('SJ', 'Svalbard and Jan Mayen'), ('SK', 'Slovakia'), ('SL', 'Sierra Leone'), ('SM', 'San Marino'), ('SN', 'Senegal'), ('SO', 'Somalia'), ('SR', 'Suriname'), ('ST', 'Sao Tome and Principe'), ('SV', 'El Salvador'), ('SX', 'Sint Maarten (Dutch part)'), ('SY', 'Syrian Arab Republic'), ('SZ', 'Swaziland'), ('TC', 'Turks and Caicos Islands'), ('TD', 'Chad'), ('TF', 'French Southern Territories'), ('TG', 'Togo'), ('TH', 'Thailand'), ('TJ', 'Tajikistan'), ('TK', 'Tokelau'), ('TL', 'Timor-Leste'), ('TM', 'Turkmenistan'), ('TN', 'Tunisia'), ('TO', 'Tonga'), ('TR', 'Turkey'), ('TT', 'Trinidad and Tobago'), ('TV', 'Tuvalu'), ('TW', 'Taiwan'), ('TZ', 'Tanzania'), ('UA', 'Ukraine'), ('UG', 'Uganda'), ('UM', 'United States Minor Outlying Islands'), ('US', 'United States'), ('UY', 'Uruguay'), ('UZ', 'Uzbekistan'), ('VA', 'Holy See (Vatican City state)'), ('VC', 'Saint Vincent and the Grenadines'), ('VE', 'Venezuela'), ('VG', 'British Virgin Islands'), ('VI', 'The US Virgin Islands'), ('VN', 'Vietnam'), ('VU', 'Vanuatu'), ('WF', 'Wallis and Futuna'), ('WS', 'Samoa'), ('YE', 'Yemen'), ('YT', 'Mayotte'), ('ZA', 'South Africa'), ('ZM', 'Zambia'), ('ZW', 'Zimbabwe')], max_length=2, null=True, verbose_name='Страна')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EbayAppAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('access_token', models.CharField(blank=True, default='', max_length=2500, verbose_name='Токен доступа')),
                ('access_token_expiry', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Токен доступа годен до')),
                ('refresh_token', models.CharField(blank=True, default='', max_length=2500, verbose_name='Токен обновления')),
                ('refresh_token_expiry', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Токен обновления годен до')),
                ('sandbox', models.BooleanField(verbose_name='Аккаунт eBay Sandbox')),
            ],
            options={
                'verbose_name': 'Аккаунт eBay уровня приложения',
                'verbose_name_plural': 'Аккаунты eBay уровня приложения',
            },
        ),
        migrations.CreateModel(
            name='EbayRateLimitsResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название ресурса')),
            ],
            options={
                'verbose_name': 'Ограничение на число запросов для ресурса',
                'verbose_name_plural': 'Ограничение на число запросов для ресурса',
            },
        ),
        migrations.CreateModel(
            name='EbayRateLimitsResourceRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limit', models.IntegerField(verbose_name='Лимит')),
                ('remaining', models.IntegerField(verbose_name='Остаток')),
                ('reset', models.DateTimeField(verbose_name='Дата и время обновления лимита')),
                ('timeWindow', models.IntegerField(verbose_name='Временное окно')),
            ],
        ),
        migrations.CreateModel(
            name='EbayUserAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('access_token', models.CharField(blank=True, default='', max_length=2500, verbose_name='Токен доступа')),
                ('access_token_expiry', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Токен доступа годен до')),
                ('refresh_token', models.CharField(blank=True, default='', max_length=2500, verbose_name='Токен обновления')),
                ('refresh_token_expiry', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Токен обновления годен до')),
                ('sandbox', models.BooleanField(verbose_name='Аккаунт eBay Sandbox')),
            ],
            options={
                'verbose_name': 'Аккаунт для eBay уровня пользователя',
                'verbose_name_plural': 'Аккаунты для eBay уровня пользователя',
            },
        ),
        migrations.CreateModel(
            name='IndividualRegistrationAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addressLine1', models.CharField(blank=True, max_length=128, null=True, verbose_name='Первая строка адреса')),
                ('addressLine2', models.CharField(blank=True, max_length=128, null=True, verbose_name='Вторая строка адреса')),
                ('city', models.CharField(blank=True, max_length=128, null=True, verbose_name='Населённый пункт')),
                ('county', models.CharField(blank=True, max_length=50, null=True, verbose_name='Округ')),
                ('postalCode', models.CharField(blank=True, max_length=16, null=True, verbose_name='Почтовый индекс')),
                ('stateOrProvince', models.CharField(blank=True, max_length=128, null=True, verbose_name='Штат или провинция')),
                ('countryCode', models.CharField(blank=True, choices=[('AD', 'Andorra'), ('AE', 'United Arab Emirates'), ('AF', 'Afghanistan'), ('AG', 'Antigua and Barbuda'), ('AI', 'Anguilla'), ('AL', 'Albania'), ('AM', 'Armenia'), ('AN', 'Netherlands Antilles'), ('AO', 'Angola'), ('AQ', 'Antarctica'), ('AR', 'Argentina'), ('AS', 'American Samoa'), ('AT', 'Austria'), ('AU', 'Australia'), ('AW', 'Aruba'), ('AX', 'Aland Islands'), ('AZ', 'Azerbaijan'), ('BA', 'Bosnia and Herzegovina'), ('BB', 'Barbados'), ('BD', 'Bangladesh'), ('BE', 'Belgium'), ('BF', 'Burkina Faso'), ('BG', 'Bulgaria'), ('BH', 'Bahrain'), ('BI', 'Burundi'), ('BJ', 'Benin'), ('BL', 'Saint Barthelemy'), ('BM', 'Bermuda'), ('BN', 'Brunei Darussalam'), ('BO', 'Bolivia'), ('BQ', 'Bonaire, Sint Eustatius, and Saba'), ('BR', 'Brazil'), ('BS', 'Bahamas'), ('BT', 'Bhutan'), ('BV', 'Bouvet Island'), ('BW', 'Botswana'), ('BY', 'Belarus'), ('BZ', 'Belize'), ('CA', 'Canada'), ('CC', 'Cocos (Keeling) Islands'), ('CD', 'The Democratic Republic of the Congo'), ('CF', 'Central African Republic'), ('CG', 'Congo'), ('CH', 'Switzerland'), ('CI', "Cote d'Ivoire"), ('CK', 'Cook Islands'), ('CL', 'Chile'), ('CM', 'Cameroon'), ('CN', 'China'), ('CO', 'Colombia'), ('CR', 'Costa Rica'), ('CU', 'Cuba'), ('CV', 'Cape Verde'), ('CW', 'Curacao'), ('CX', 'Christmas Island'), ('CY', 'Cyprus'), ('CZ', 'Czech Republic'), ('DE', 'Germany'), ('DJ', 'Djibouti'), ('DK', 'Denmark'), ('DM', 'Dominica'), ('DO', 'Dominican Republic'), ('DZ', 'Algeria'), ('EC', 'Ecuador'), ('EE', 'Estonia'), ('EG', 'Egypt'), ('EH', 'Western Sahara'), ('ER', 'Eritrea'), ('ES', 'Spain'), ('ET', 'Ethiopia'), ('FI', 'Finland'), ('FJ', 'Fiji'), ('FK', 'Falkland Islands (Malvinas)'), ('FM', 'Federated States of Micronesia'), ('FO', 'Faroe Islands'), ('FR', 'France'), ('GA', 'Gabon'), ('GB', 'United Kingdom'), ('GD', 'Grenada'), ('GE', 'Georgia'), ('GF', 'French Guiana'), ('GG', 'Guernsey'), ('GH', 'Ghana'), ('GI', 'Gibraltar'), ('GL', 'Greenland'), ('GM', 'Gambia'), ('GN', 'Guinea'), ('GP', 'Guadeloupe'), ('GQ', 'Equatorial Guinea'), ('GR', 'Greece'), ('GS', 'South Georgia and the South Sandwich Islands'), ('GT', 'Guatemala'), ('GU', 'Guam'), ('GW', 'Guinea-Bissau'), ('GY', 'Guyana'), ('HK', 'Hong Kong'), ('HM', 'Heard Island and McDonald Islands'), ('HN', 'Honduras'), ('HR', 'Croatia'), ('HT', 'Haiti'), ('HU', 'Hungary'), ('ID', 'Indonesia'), ('IE', 'Ireland'), ('IL', 'Israel'), ('IM', 'Isle of Man'), ('IN', 'India'), ('IO', 'British Indian Ocean Territory'), ('IQ', 'Iraq'), ('IR', 'Islamic Republic of Iran'), ('IS', 'Iceland'), ('IT', 'Italy'), ('JE', 'Jersey'), ('JM', 'Jamaica'), ('JO', 'Jordan'), ('JP', 'Japan'), ('KE', 'Kenya'), ('KG', 'Kyrgyzstan'), ('KH', 'Cambodia'), ('KI', 'Kiribati'), ('KM', 'Comoros'), ('KN', 'Saint Kitts and Nevis'), ('KP', "Democratic People's Republic of Korea"), ('KR', 'Republic of Korea'), ('KW', 'Kuwait'), ('KY', 'Cayman Islands'), ('KZ', 'Kazakhstan'), ('LA', "Lao People's Democratic Republic"), ('LB', 'Lebanon'), ('LC', 'Saint Lucia'), ('LI', 'Liechtenstein'), ('LK', 'Sri Lanka'), ('LR', 'Liberia'), ('LS', 'Lesotho'), ('LT', 'Lithuania'), ('LU', 'Luxembourg'), ('LV', 'atvia'), ('LY', 'Libyan Arab Jamahiriya'), ('MA', 'Morocco'), ('MC', 'Monaco'), ('MD', 'Republic of Moldova'), ('ME', 'Montenegro'), ('MF', 'Saint Martin (French part)'), ('MG', 'Madagascar'), ('MH', 'Marshall Islands'), ('MK', 'The Former Yugoslav Republic of Macedonia'), ('ML', 'Mali'), ('MM', 'Myanmar'), ('MN', 'Mongolia'), ('MO', 'Macao'), ('MP', 'Northern Mariana Islands'), ('MQ', 'Martinique'), ('MR', 'Mauritania'), ('MS', 'Montserrat'), ('MT', 'Malta'), ('MU', 'Mauritius'), ('MV', 'Maldives'), ('MW', 'Malawi'), ('MX', 'Mexico'), ('MY', 'Malaysia'), ('MZ', 'Mozambique'), ('NA', 'Namibia'), ('NC', 'New Caledonia'), ('NE', 'Niger'), ('NF', 'Norfolk Island'), ('NG', 'Nigeria'), ('NI', 'Nicaragua'), ('NL', 'Netherlands'), ('NO', 'Norway'), ('NP', 'Nepal'), ('NR', 'Nauru'), ('NU', 'Niue'), ('NZ', 'New Zealand'), ('OM', 'Oman'), ('PA', 'Panama'), ('PE', 'Peru'), ('PF', 'French Polynesia, Includes Tahiti'), ('PG', 'Papua New Guinea'), ('PH', 'Philippines'), ('PK', 'Pakistan'), ('PL', 'Poland'), ('PM', 'Saint Pierre and Miquelon'), ('PN', 'Pitcairn'), ('PR', 'Puerto Rico'), ('PS', 'Palestinian territory Occupied'), ('PT', 'Portugal'), ('PW', 'Palau'), ('PY', 'Paraguay'), ('QA', 'Qatar'), ('RE', 'Reunion'), ('RO', 'Romania'), ('RS', 'Serbia'), ('RU', 'Russian Federation'), ('RW', 'Rwanda'), ('SA', 'Saudi Arabia'), ('SB', 'Solomon Islands'), ('SC', 'Seychelles'), ('SD', 'Sudan'), ('SE', 'Sweden'), ('SG', 'Singapore'), ('SH', 'Saint Helena'), ('SI', 'Slovenia'), ('SJ', 'Svalbard and Jan Mayen'), ('SK', 'Slovakia'), ('SL', 'Sierra Leone'), ('SM', 'San Marino'), ('SN', 'Senegal'), ('SO', 'Somalia'), ('SR', 'Suriname'), ('ST', 'Sao Tome and Principe'), ('SV', 'El Salvador'), ('SX', 'Sint Maarten (Dutch part)'), ('SY', 'Syrian Arab Republic'), ('SZ', 'Swaziland'), ('TC', 'Turks and Caicos Islands'), ('TD', 'Chad'), ('TF', 'French Southern Territories'), ('TG', 'Togo'), ('TH', 'Thailand'), ('TJ', 'Tajikistan'), ('TK', 'Tokelau'), ('TL', 'Timor-Leste'), ('TM', 'Turkmenistan'), ('TN', 'Tunisia'), ('TO', 'Tonga'), ('TR', 'Turkey'), ('TT', 'Trinidad and Tobago'), ('TV', 'Tuvalu'), ('TW', 'Taiwan'), ('TZ', 'Tanzania'), ('UA', 'Ukraine'), ('UG', 'Uganda'), ('UM', 'United States Minor Outlying Islands'), ('US', 'United States'), ('UY', 'Uruguay'), ('UZ', 'Uzbekistan'), ('VA', 'Holy See (Vatican City state)'), ('VC', 'Saint Vincent and the Grenadines'), ('VE', 'Venezuela'), ('VG', 'British Virgin Islands'), ('VI', 'The US Virgin Islands'), ('VN', 'Vietnam'), ('VU', 'Vanuatu'), ('WF', 'Wallis and Futuna'), ('WS', 'Samoa'), ('YE', 'Yemen'), ('YT', 'Mayotte'), ('ZA', 'South Africa'), ('ZM', 'Zambia'), ('ZW', 'Zimbabwe')], max_length=2, null=True, verbose_name='Страна')),
            ],
            options={
                'verbose_name': 'Адресс регистрации',
                'verbose_name_plural': 'Адреса регистрации',
            },
        ),
        migrations.CreateModel(
            name='BusinessPrimaryContact',
            fields=[
                ('abstractcontact_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ebay_account.AbstractContact')),
            ],
            options={
                'verbose_name': 'Основное контактное лицо',
                'verbose_name_plural': 'Основные контактные лица',
            },
            bases=('ebay_account.abstractcontact',),
        ),
        migrations.CreateModel(
            name='BusinessPrimaryPhone',
            fields=[
                ('abstractphone_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ebay_account.AbstractPhone')),
            ],
            options={
                'verbose_name': 'Основной телефон',
                'verbose_name_plural': 'Основные телефоны',
            },
            bases=('ebay_account.abstractphone',),
        ),
        migrations.CreateModel(
            name='BusinessSecondaryPhone',
            fields=[
                ('abstractphone_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ebay_account.AbstractPhone')),
            ],
            options={
                'verbose_name': 'Дополнительный телефон',
                'verbose_name_plural': 'Дополнительные телефоны',
            },
            bases=('ebay_account.abstractphone',),
        ),
        migrations.CreateModel(
            name='IndividualAccount',
            fields=[
                ('abstractcontact_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ebay_account.AbstractContact')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
            ],
            options={
                'verbose_name': 'Индивидуальный аккаунт',
                'verbose_name_plural': 'Индивидуальные аккаунты',
            },
            bases=('ebay_account.abstractcontact',),
        ),
        migrations.CreateModel(
            name='IndividualPrimaryPhone',
            fields=[
                ('abstractphone_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ebay_account.AbstractPhone')),
            ],
            options={
                'verbose_name': 'Основной телефон',
                'verbose_name_plural': 'Основные телефоны',
            },
            bases=('ebay_account.abstractphone',),
        ),
        migrations.CreateModel(
            name='IndividualSecondaryPhone',
            fields=[
                ('abstractphone_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ebay_account.AbstractPhone')),
            ],
            options={
                'verbose_name': 'Дополнительный телефон',
                'verbose_name_plural': 'Дополнительные телефоны',
            },
            bases=('ebay_account.abstractphone',),
        ),
        migrations.CreateModel(
            name='EbayUserRateLimits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apiContext', models.CharField(max_length=50, verbose_name='Тип API')),
                ('apiName', models.CharField(max_length=50, verbose_name='Название API')),
                ('apiVersion', models.CharField(blank=True, default='', max_length=10, verbose_name='Версия API')),
                ('ebay_user_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_limits', to='ebay_account.EbayUserAccount', verbose_name='Пользовательский аккаунт eBay')),
            ],
            options={
                'verbose_name': 'Ограничение на число запросов',
                'verbose_name_plural': 'Ограничение на число запросов',
            },
        ),
        migrations.CreateModel(
            name='EbayUserAccountProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('account_type', models.CharField(blank=True, choices=[('BUSINESS', 'BUSINESS'), ('INDIVIDUAL', 'INDIVIDUAL')], max_length=10, null=True, verbose_name='Тип аккаунта')),
                ('registrationMarketplaceId', models.CharField(choices=[('EBAY_US', 'US site (ebay.com)'), ('EBAY_MOTORS_US', 'US eBay Motors site (ebay.com/motors)'), ('EBAY_CA', 'Canada (English) site (ebay.ca)'), ('EBAY_GB', 'UK site (ebay.co.uk)'), ('EBAY_AU', 'Australia site (ebay.com.au)'), ('EBAY_AT', 'Austria site (ebay.at)'), ('EBAY_BE_FR', 'French version of the Belgium site (befr.ebay.be)'), ('EBAY_FR', 'France site (ebay.fr)'), ('EBAY_DE', 'Germany site (ebay.de)'), ('EBAY_IT', 'Italy site (ebay.it)'), ('EBAY_BE_NL', 'Dutch version of the Belgium site (https://www.benl.ebay.be/)'), ('EBAY_NL', 'Netherlands site (ebay.nl)'), ('EBAY_ES', 'Spain site (ebay.es)'), ('EBAY_CH', 'Switzerland site (ebay.ch)'), ('EBAY_TW', 'Taiwan site (ebay.com/tw)'), ('EBAY_CZ', 'Czech Republic site (ebay.com/sch/Czech-Republic)'), ('EBAY_DK', 'Denmark site (ebay.com/sch/Denmark)'), ('EBAY_FI', 'Finland site (ebay.com/sch/Finland)'), ('EBAY_GR', 'Greece site (ebay.com/sch/Greece)'), ('EBAY_HK', 'Hong Kong site (ebay.com.hk)'), ('EBAY_HU', 'Hungary site (ebay.com/sch/Hungary)'), ('EBAY_IN', 'India site (ebay.in)'), ('EBAY_ID', 'Indonesia site (id.ebay.com)'), ('EBAY_IE', 'Ireland site (ebay.ie)'), ('EBAY_IL', 'Israel site (ebay.com/sch/Israel)'), ('EBAY_MY', 'Malaysia site (ebay.com/my)'), ('EBAY_NZ', 'New Zealand site (ebay.com/sch/New-Zealand)'), ('EBAY_NO', 'Norway site (ebay.com/sch/Norway)'), ('EBAY_PH', 'Philippines site (ebay.ph)'), ('EBAY_PL', 'Poland site (ebay.pl)'), ('EBAY_PT', 'Portugal site (ebay.com/sch/Portugal)'), ('EBAY_PR', 'Puerto Rico site (ebay.com/sch/Puerto-Rico)'), ('EBAY_RU', 'Russia site (ebay.com/sch/Russia)'), ('EBAY_SG', 'Singapore site (ebay.com/sg)'), ('EBAY_ZA', 'South Africa site (ebay.com/sch/South-Africa)'), ('EBAY_SE', 'Sweden site (ebay.com/sch/Sweden)'), ('EBAY_TH', 'Thailand site (export.ebay.co.th)'), ('EBAY_VN', 'Vietnam site (ebay.vn)'), ('EBAY_CN', 'China site (ebay.com/sch/China)'), ('EBAY_PE', 'Peru site (ebay.com/sch/Peru)'), ('EBAY_CA_FR', 'Canada (English) site (https://www.cafr.ebay.ca/)'), ('EBAY_JP', 'Japan site (ebay.co.jp)')], max_length=14, verbose_name='Домен регистрации')),
                ('status', models.CharField(blank=True, choices=[('CONFIRMED', 'Верифицирован'), ('UNCONFIRMED', 'Неверифицирован'), ('ACCOUNTONHOLD', 'Ожидает верификации'), ('UNDETERMINED', 'Другое')], max_length=13, null=True, verbose_name='Статус аккаунта')),
                ('userId', models.CharField(max_length=50, verbose_name='ID пользователя')),
                ('username', models.CharField(max_length=100, verbose_name='Имя пользователя')),
                ('ebay_user_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='ebay_account.EbayUserAccount')),
            ],
            options={
                'verbose_name': 'Профиль пользователя в eBay',
                'verbose_name_plural': 'Профили пользователей в eBay',
            },
        ),
        migrations.CreateModel(
            name='EbayUserAccountPrivileges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('RUB', 'Российский рубль'), ('USD', 'Доллар США'), ('EUR', 'Евро'), ('GBP', 'Фунт стерлингов'), ('JPY', 'Японская иена'), ('CNY', 'Китайский юань'), ('AUD', 'Австралийский доллар'), ('CAD', 'Канадский доллар')], max_length=20, verbose_name='Валюта')),
                ('value', models.FloatField(verbose_name='Значение цены')),
                ('convertedFromCurrency', models.CharField(blank=True, choices=[('RUB', 'Российский рубль'), ('USD', 'Доллар США'), ('EUR', 'Евро'), ('GBP', 'Фунт стерлингов'), ('JPY', 'Японская иена'), ('CNY', 'Китайский юань'), ('AUD', 'Австралийский доллар'), ('CAD', 'Канадский доллар')], max_length=20, null=True, verbose_name='Валюта исходной цены')),
                ('convertedFromValue', models.FloatField(blank=True, null=True, verbose_name='Значение исходной цены')),
                ('sellerRegistrationCompleted', models.BooleanField(blank=True, null=True, verbose_name='Регистрация аккаунта eBay завершена')),
                ('quantity', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Ограничение на количество товаров в месяц')),
                ('ebay_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='privileges', to='ebay_account.EbayUserAccount', verbose_name='Пользовательский аккаунт eBay')),
            ],
            options={
                'verbose_name': 'Ограничения аккаунта eBay',
                'verbose_name_plural': 'Ограничения аккаунта eBay',
            },
        ),
        migrations.CreateModel(
            name='EbayUserAccountDefaults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ebay_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='defaults', to='ebay_account.EbayUserAccount', verbose_name='Пользовательский аккаунт eBay')),
            ],
            options={
                'verbose_name': 'Значения по умолчанию для пользователя eBay',
                'verbose_name_plural': 'Значения по умолчанию для пользователей eBay',
            },
        ),
    ]
