# Generated by Django 2.2.5 on 2020-01-17 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('amazon_order', '0001_initial'),
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazonorder',
            name='channel',
            field=models.ForeignKey(limit_choices_to={'domain__marketplace__unique_name__in': ['amazon_north_america', 'amazon_europe', 'amazon_far_east']}, on_delete=django.db.models.deletion.CASCADE, related_name='amazon_orders', related_query_name='amazon_order', to='marketplace.Channel'),
        ),
    ]
