# Generated by Django 2.2.5 on 2020-01-17 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('amazon_account', '0001_initial'),
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazonuseraccount',
            name='marketplace_user_account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='amazon_user_account', to='marketplace.MarketplaceUserAccount'),
        ),
    ]
