
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-01-28T19:07:32-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "0421e6f809ee271ae7cf755ee1838b0fdefeb74d",
 "version": "1.1.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
