[tool.poetry]
name = "jupyter-io"
version = "0.1.1"
description = "Python pacakge of some I/O utilities for Jupyter notebook"
authors = ["Akio Taniguchi <taniguchi@a.phys.nagoya-u.ac.jp>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.6"
matplotlib = "^3.1.2"
ipython = "^7.11.1"
pandas = "^0.25.3"

[tool.poetry.dev-dependencies]
flake8 = "^3.7.9"
black = "^19.10b0"
pytest = "^5.3.4"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
