# Generated by Django 2.2.5 on 2020-01-29 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etsy_listing', '0002_auto_20200128_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='etsylisting',
            name='_materials',
            field=models.TextField(default='[]', verbose_name='Материалы'),
        ),
        migrations.AddField(
            model_name='etsylisting',
            name='_tags',
            field=models.TextField(default='[]', verbose_name='Теги'),
        ),
    ]
