
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-01-23T22:50:20-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "0ea1eba65fb693afb238df0fa2f6114acc3afa85",
 "version": "0.4.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
