
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-01-17T11:04:13+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "add93d56ba1ac2f7d00576bd3f2d1be0db3e1757",
 "version": "0.10.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
