---
engines:
  duplication:
    enabled: true
    config:
      languages:
        python:
          mass_threshold: 40
    checks:
      Similar code:
        enabled: false
  radon:
    enabled: true
    config:
      threshold: "D"
  fixme:
    enabled: true
    config:
      strings:
      - FIXME
ratings:
  paths:
  - "**.py"
# Including paths "**.py" also includes the ".pylintrc" file, so
# we are excluding it again via ".*".
exclude_paths:
- ".*"
- "design/"
- "dist/"
- "docs/"
- "examples/"
- "tests/"
